# Syllabus {-}

## GEO5165C: Quantitative Geography {-}

## Contact information {-}

* Instructor Name: Professor James B. Elsner
* Instructor Location: Bellamy Building, Room 323a
* Lesson Hours: TR 3:05-4:20 p.m.
* Student Hours: TR 9-10 a.m., 2-3 p.m.

Email: <jelsner@fsu.edu>

## Course description {-}

This course is an introduction to the quantitative analysis of geographic data (data analysis for geographers). Most of the course content will be available through Canvas and through RStudio Cloud. Please open an account with RStudio Cloud at (https://rstudio.cloud). 

Please use this link https://rstudio.cloud/spaces/12733/join?access_code=NuhGFcK71GlGuzoKzAUIe1lqgcMDyOIC7UnnFtNG to join the Spatial Data Analysis workspace on RStudio Cloud.

## Expected learning outcomes {-}

You will describe and demonstrate the principles of data science. You will do this with a grammar for manipulating data and a grammar for making graphs. The grammars are implemented in R using the syntax of tidyverse.

## Materials {-}

* You will need access to the internet and either an iPad, laptop, or desktop computer. 
* All course materials are available through RStudio Cloud (https://rstudio.cloud/spaces/12733/projects) and archived on Canvas.
* There is no required textbook. 
* Much of the material for the course comes from the online book: R for Data Science https://r4ds.had.co.nz/
* Additional help is available online (e.g., https://tinystats.github.io/teacups-giraffes-and-statistics/index.html)

## Class meetings {-}

- Online: synchronous, interactive, asynchronous recordings available on Canvas
- Some lectures, lots of learn-by-doing

## Grades {-}

* Grades are determined solely by how well you do on the regularly scheduled homework/classwork assignments. 
* There are NO quizzes, tests, or exams. 
* Synchronous attendance is expected but not required. 
* Late classwork or homework assignments will not be accepted.
* Cumulative numerical averages of 90 - 100 (outstanding) are guaranteed at least an A-, 80 - 89 (good) at least a B-, and 70 - 79 (satisfactory) at least a C-, however the exact ranges for letter grades will be determined after all work is complete.

## Academic honor code {-}

http://www.eng.fsu.edu/~peterson/fsuhc.html

## Students With Disabilities Act {-}

Students needing academic accommodation should: (1) register with and provide documentation to the Student Disability Resource Center (https://dos.fsu.edu/sdrc/); (2) bring a letter to me indicating the need for accommodation and what type. This should be done sometime during the first week of classes.

## Inclusiveness {-}

It is my intent to present materials and activities that are respectful of diversity: gender identity, sexuality, disability, age, socioeconomic status, ethnicity, race, nationality, religion, and culture. Let me know ways to improve the effectiveness of the course for you personally, or for other students or student groups.

- If you have a name and/or set of pronouns that differ from those that appear in your official FSU records, please let me know.
- If you feel your performance is being impacted by your experiences outside of class, please don't hesitate to come and talk with me. If you prefer to speak with someone outside of the course, your academic dean is an excellent resource. 
- If something was said in class (by anyone) that made you feel uncomfortable, please talk to me about it.

## More about your instructor {-}

* [Canvas](https://cas.fsu.edu/cas/login)
* [GitHub](https://github.com/jelsner/)
* [Twitter](https://twitter.com/JBElsner)
* [Research Website](http://myweb.fsu.edu/jelsner/_site/)

## Syllabus change policy {-}

This syllabus is a guide for the course and is subject to change with advanced notice.

## Schedule (subject to change with notice) {-}

Week | Dates                       | Topic
-----|-----------------------------|-------
1    | August 23, 25               | RStudio Cloud and R
2    | August 30, September 1      | Working with R
3    | September 6, 8              | Data and data frames
4    | September 13, 15            | Data analysis
5    | September 20, 22            | Graphical analysis
6    | September 27, 29            | Mapping data
7    | October 4, 6                | Bayesian data analysis
8    | October 11, 13              | Regression
9    | October 18, 20              | Multiple regression
10   | October 25, 27              | Regression trees
11   | November 1, 3               | Spatial data
12   | November 8, 10              | Spatial autocorrelation
13   | November 15, 17             | Geographic regression
14   | November 29, December 1     | Finish assignments

28 dates 26 lessons

Assignment | Due Date (5 pm)
-----------|---------------
1          | August 30
2          | September 6
3          | September 13
4          | September 27
5          | October 4
6          | October 18
7          | October 25
8          | November 1
9          | November 8
10         | November 15
11         | November 29

## Other materials to check out {-}

* [Best practices for working with R](https://twitter.com/DanOvand0/status/1309223236740083712)
Develop a project-oriented work flow and don't use `setwd()`. Don't hard-coded file path names. Use version control (github). Manage package dependencies. Pick a style of writing code and stick with it. Do as much as you can in RMarkdown (notes, lectures, slides, etc). Check out [Openscapes](https://www.openscapes.org/).

* [Reading R](https://kieranhealy.org/blog/archives/2020/09/24/us-excess-mortality/)

* Towards a more open and reproducible approach to geographic and spatial data science [Opening practice: supporting reproducibility and critical spatial data science](https://link.springer.com/article/10.1007/s10109-020-00334-2)

* [Transportation Network Analysis Tools](https://www.eventbrite.com/e/new-rstats-transportation-network-analysis-tools-tickets-121594443253) A workshop with Kyle Walker on the {Mapboxapi} package that makes a host of complex transportation network and routing tools accessible to beginners.


## Julia programming language {-}

Julia programming language https://julialang.org/
Download > Open

Jupyter Notebook
(1) Anaconda > Individual > Download > Install
(2) In the Julia REPL type:
using Pkg
Pkg.add("IJulia")
(3) Then click on the Anaconda-Navigator icon and Launch Jupyter Notebook
(4) Click on the New button and select Julia.
Problems? watch https://www.youtube.com/watch?v=oyx8M1yoboY

Pluto Notebook
In the Julia REPL type:
import Pkg; Pkg.add("Pluto")
import Pluto
Pluto.run()

md"""
# This Pluto notebook is a test.
"""
begin
a = [1, 4, 7, 22]
	a * 10
end

