---
title: "GEO5156: Quantitative Geography"
subtitle: "Fall 2022"
author: "James B. Elsner"
date: "Date compiled: `r Sys.Date()`"
bibliography: ["References.bib"]
biblio-style: apalike
link-citations: yes
github-repo: jelsner/QG-2022
site: "bookdown::bookdown_site"
documentclass: book
editor_options: 
  chunk_output_type: console
---

# {-}

tidycensus::get_acs(geography = "county", variables = "B01003_001") will get you the latest 2016-2020 ACS estimates

https://walker-data.com/census-r/wrangling-census-data-with-tidyverse-tools.html

```{r, eval=FALSE}
install.packages("bookdown")
install.packages("DiagrammeR")
install.packages("UsingR")
install.packages("nycflights13")
install.packages("ggmap")
install.packages("nullabor")
install.packages("bayesAB")
install.packages("palmerpenguins")
```


```{r, echo=FALSE}
DiagrammeR::grViz("digraph rmarkdown {

D [shape = square]
A [shape = square]
L [shape = circle]
H [shape = circle]
W [shape = circle, color = orange]

{D A L H} -> W

}
", height = 250)
```