<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Thursday, September 29, 2022 | GEO5156: Quantitative Geography</title>
  <meta name="description" content="Thursday, September 29, 2022 | GEO5156: Quantitative Geography" />
  <meta name="generator" content="bookdown 0.27 and GitBook 2.6.7" />

  <meta property="og:title" content="Thursday, September 29, 2022 | GEO5156: Quantitative Geography" />
  <meta property="og:type" content="book" />
  
  
  <meta name="github-repo" content="jelsner/QG-2022" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Thursday, September 29, 2022 | GEO5156: Quantitative Geography" />
  
  
  

<meta name="author" content="James B. Elsner" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="tuesday-october-4-2022.html"/>
<link rel="next" href="tuesday-october-4-2022-1.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Quantitative Geography</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html"><i class="fa fa-check"></i>Syllabus</a>
<ul>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#geo5165c-quantitative-geography"><i class="fa fa-check"></i>GEO5165C: Quantitative Geography</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#contact-information"><i class="fa fa-check"></i>Contact information</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#course-description-and-expected-learning-outcomes"><i class="fa fa-check"></i>Course description and expected learning outcomes</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#grades-and-ethics"><i class="fa fa-check"></i>Grades and ethics</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#schedule-subject-to-change-with-notice"><i class="fa fa-check"></i>Schedule (subject to change with notice)</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#deeper-dives"><i class="fa fa-check"></i>Deeper dives</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html"><i class="fa fa-check"></i>Tuesday, August 23, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#what-is-this-course"><i class="fa fa-check"></i>What is this course?</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#where-are-the-materials-for-this-course"><i class="fa fa-check"></i>Where are the materials for this course?</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#get-the-syllabus"><i class="fa fa-check"></i>Get the syllabus</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#getting-setup"><i class="fa fa-check"></i>Getting setup</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#getting-to-know-rstudios-integrated-development-environment-ide"><i class="fa fa-check"></i>Getting to know RStudio’s integrated development environment (IDE)</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html"><i class="fa fa-check"></i>Thursday, August 25, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#data-science"><i class="fa fa-check"></i>Data science</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#structure-of-markdown-files"><i class="fa fa-check"></i>Structure of markdown files</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#how-to-make-a-plot"><i class="fa fa-check"></i>How to make a plot</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#getting-started-using-r"><i class="fa fa-check"></i>Getting started using R</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html"><i class="fa fa-check"></i>Tuesday, August 30, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html#graphing-examples"><i class="fa fa-check"></i>Graphing examples</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html#introduction-to-working-with-base-r"><i class="fa fa-check"></i>Introduction to working with base R</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html#data-as-vectors"><i class="fa fa-check"></i>Data as vectors</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-september-1-2022.html"><a href="thursday-september-1-2022.html"><i class="fa fa-check"></i>Thursday, September 1, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-september-1-2022.html"><a href="thursday-september-1-2022.html#statistical-summaries-of-data"><i class="fa fa-check"></i>Statistical summaries of data</a></li>
<li class="chapter" data-level="" data-path="thursday-september-1-2022.html"><a href="thursday-september-1-2022.html#structured-data"><i class="fa fa-check"></i>Structured data</a></li>
<li class="chapter" data-level="" data-path="thursday-september-1-2022.html"><a href="thursday-september-1-2022.html#tables"><i class="fa fa-check"></i>Tables</a></li>
<li class="chapter" data-level="" data-path="thursday-september-1-2022.html"><a href="thursday-september-1-2022.html#assignment-1"><i class="fa fa-check"></i>Assignment #1</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-september-6-2022.html"><a href="tuesday-september-6-2022.html"><i class="fa fa-check"></i>Tuesday, September 6, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-september-6-2022.html"><a href="tuesday-september-6-2022.html#getting-data-into-r"><i class="fa fa-check"></i>Getting data into R</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-6-2022.html"><a href="tuesday-september-6-2022.html#data-frames"><i class="fa fa-check"></i>Data frames</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-6-2022.html"><a href="tuesday-september-6-2022.html#piping-your-commands"><i class="fa fa-check"></i>Piping your commands</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-september-8-2022.html"><a href="thursday-september-8-2022.html"><i class="fa fa-check"></i>Thursday, September 8, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-september-8-2022.html"><a href="thursday-september-8-2022.html#data-transformation-with-dplyr"><i class="fa fa-check"></i>Data transformation with {dplyr}</a></li>
<li class="chapter" data-level="" data-path="thursday-september-8-2022.html"><a href="thursday-september-8-2022.html#from-data-import-to-final-plot"><i class="fa fa-check"></i>From data import to final plot</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-september-13-2022.html"><a href="tuesday-september-13-2022.html"><i class="fa fa-check"></i>Tuesday, September 13, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-september-13-2022.html"><a href="tuesday-september-13-2022.html#data-visualization"><i class="fa fa-check"></i>Data visualization</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-september-20-2022.html"><a href="tuesday-september-20-2022.html"><i class="fa fa-check"></i>Tuesday, September 20, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-september-20-2022.html"><a href="tuesday-september-20-2022.html#comparing-distributions"><i class="fa fa-check"></i>Comparing distributions</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-20-2022.html"><a href="tuesday-september-20-2022.html#visualizing-uncertainty"><i class="fa fa-check"></i>Visualizing uncertainty</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-20-2022.html"><a href="tuesday-september-20-2022.html#simple-feature-data-frames"><i class="fa fa-check"></i>Simple feature data frames</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-20-2022.html"><a href="tuesday-september-20-2022.html#making-a-boundary-map"><i class="fa fa-check"></i>Making a boundary map</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-september-22-2022.html"><a href="thursday-september-22-2022.html"><i class="fa fa-check"></i>Thursday, September 22, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-september-22-2022.html"><a href="thursday-september-22-2022.html#adding-data-to-boundary-maps"><i class="fa fa-check"></i>Adding data to boundary maps</a></li>
<li class="chapter" data-level="" data-path="thursday-september-22-2022.html"><a href="thursday-september-22-2022.html#changing-projections"><i class="fa fa-check"></i>Changing projections</a></li>
<li class="chapter" data-level="" data-path="thursday-september-22-2022.html"><a href="thursday-september-22-2022.html#mapping-using-functions-from-tmap"><i class="fa fa-check"></i>Mapping using functions from tmap</a></li>
<li class="chapter" data-level="" data-path="thursday-september-22-2022.html"><a href="thursday-september-22-2022.html#making-an-interactive-map"><i class="fa fa-check"></i>Making an interactive map</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-october-4-2022.html"><a href="tuesday-october-4-2022.html"><i class="fa fa-check"></i>Tuesday, October 4, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-october-4-2022.html"><a href="tuesday-october-4-2022.html#extended-mapping-example-tornado-frequency"><i class="fa fa-check"></i>Extended mapping example: tornado frequency</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-4-2022.html"><a href="tuesday-october-4-2022.html#geo-computation-on-simple-feature-data-frames"><i class="fa fa-check"></i>Geo-computation on simple feature data frames</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-4-2022.html"><a href="tuesday-october-4-2022.html#making-raster-maps"><i class="fa fa-check"></i>Making raster maps</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-4-2022.html"><a href="tuesday-october-4-2022.html#spatial-density-maps"><i class="fa fa-check"></i>Spatial density maps</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-4-2022.html"><a href="tuesday-october-4-2022.html#assignment-3"><i class="fa fa-check"></i>Assignment #3</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-september-29-2022.html"><a href="thursday-september-29-2022.html"><i class="fa fa-check"></i>Thursday, September 29, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-september-29-2022.html"><a href="thursday-september-29-2022.html#one-sample-test-for-the-value-of-the-population-mean"><i class="fa fa-check"></i>One-sample test for the value of the population mean</a></li>
<li class="chapter" data-level="" data-path="thursday-september-29-2022.html"><a href="thursday-september-29-2022.html#graphical-inference"><i class="fa fa-check"></i>Graphical inference</a></li>
<li class="chapter" data-level="" data-path="thursday-september-29-2022.html"><a href="thursday-september-29-2022.html#two-sample-test-for-a-difference-in-population-means"><i class="fa fa-check"></i>Two-sample test for a difference in population means</a></li>
<li class="chapter" data-level="" data-path="thursday-september-29-2022.html"><a href="thursday-september-29-2022.html#a-non-parameteric-test-for-difference-in-population-means"><i class="fa fa-check"></i>A non-parameteric test for difference in population means</a></li>
<li class="chapter" data-level="" data-path="thursday-september-29-2022.html"><a href="thursday-september-29-2022.html#paired-observations"><i class="fa fa-check"></i>Paired observations</a></li>
<li class="chapter" data-level="" data-path="thursday-september-29-2022.html"><a href="thursday-september-29-2022.html#chi-squared-test-for-independence"><i class="fa fa-check"></i>Chi-squared test for independence</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-october-4-2022-1.html"><a href="tuesday-october-4-2022-1.html"><i class="fa fa-check"></i>Tuesday, October 4, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-october-4-2022-1.html"><a href="tuesday-october-4-2022-1.html#paired-observations-1"><i class="fa fa-check"></i>Paired observations</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-4-2022-1.html"><a href="tuesday-october-4-2022-1.html#chi-squared-test-for-independence-1"><i class="fa fa-check"></i>Chi-squared test for independence</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-october-6-2022.html"><a href="thursday-october-6-2022.html"><i class="fa fa-check"></i>Thursday, October 6, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-october-6-2022.html"><a href="thursday-october-6-2022.html#bayesian-data-analysis"><i class="fa fa-check"></i>Bayesian data analysis</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-october-11-2022.html"><a href="tuesday-october-11-2022.html"><i class="fa fa-check"></i>Tuesday, October 11, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-october-11-2022.html"><a href="tuesday-october-11-2022.html#more-examples-of-bayesian-data-analyses"><i class="fa fa-check"></i>More examples of Bayesian data analyses</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-october-13-2022.html"><a href="thursday-october-13-2022.html"><i class="fa fa-check"></i>Thursday, October 13, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-october-13-2022.html"><a href="thursday-october-13-2022.html#linear-regression-a-t-test-by-another-name"><i class="fa fa-check"></i>Linear regression: A t test by another name</a></li>
<li class="chapter" data-level="" data-path="thursday-october-13-2022.html"><a href="thursday-october-13-2022.html#motivation-for-the-regression-model"><i class="fa fa-check"></i>Motivation for the regression model</a></li>
<li class="chapter" data-level="" data-path="thursday-october-13-2022.html"><a href="thursday-october-13-2022.html#making-predictions-with-the-regression-model"><i class="fa fa-check"></i>Making predictions with the regression model</a></li>
<li class="chapter" data-level="" data-path="thursday-october-13-2022.html"><a href="thursday-october-13-2022.html#uncertainty-about-the-regression-model-coefficients"><i class="fa fa-check"></i>Uncertainty about the regression model coefficients</a></li>
<li class="chapter" data-level="" data-path="thursday-october-13-2022.html"><a href="thursday-october-13-2022.html#bootstrapping-the-uncertainty"><i class="fa fa-check"></i>Bootstrapping the uncertainty</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-october-18-2022.html"><a href="tuesday-october-18-2022.html"><i class="fa fa-check"></i>Tuesday, October 18, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-october-18-2022.html"><a href="tuesday-october-18-2022.html#uncertainty-about-a-particular-predicted-value"><i class="fa fa-check"></i>Uncertainty about a particular predicted value</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-18-2022.html"><a href="tuesday-october-18-2022.html#model-adequacy"><i class="fa fa-check"></i>Model Adequacy</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-18-2022.html"><a href="tuesday-october-18-2022.html#transforming-the-response-variable"><i class="fa fa-check"></i>Transforming the response variable</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-october-20-2022.html"><a href="thursday-october-20-2022.html"><i class="fa fa-check"></i>Thursday, October 20, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-october-20-2022.html"><a href="thursday-october-20-2022.html#more-regression-examples"><i class="fa fa-check"></i>More regression examples</a></li>
<li class="chapter" data-level="" data-path="thursday-october-20-2022.html"><a href="thursday-october-20-2022.html#outliers"><i class="fa fa-check"></i>Outliers</a></li>
<li class="chapter" data-level="" data-path="thursday-october-20-2022.html"><a href="thursday-october-20-2022.html#simpsons-paradox"><i class="fa fa-check"></i>Simpson’s paradox</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-october-25-2022.html"><a href="tuesday-october-25-2022.html"><i class="fa fa-check"></i>Tuesday, October 25, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-october-25-2022.html"><a href="tuesday-october-25-2022.html#a-regression-plane"><i class="fa fa-check"></i>A regression plane</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-25-2022.html"><a href="tuesday-october-25-2022.html#fitting-a-multiple-variable-regression-model"><i class="fa fa-check"></i>Fitting a multiple variable regression model</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-25-2022.html"><a href="tuesday-october-25-2022.html#should-you-remove-a-variable-from-the-model"><i class="fa fa-check"></i>Should you remove a variable from the model?</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-25-2022.html"><a href="tuesday-october-25-2022.html#checking-on-the-model-assumptions"><i class="fa fa-check"></i>Checking on the model assumptions</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-25-2022.html"><a href="tuesday-october-25-2022.html#using-the-model-to-make-predictions"><i class="fa fa-check"></i>Using the model to make predictions</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-25-2022.html"><a href="tuesday-october-25-2022.html#collinearity"><i class="fa fa-check"></i>Collinearity</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-25-2022.html"><a href="tuesday-october-25-2022.html#interactions"><i class="fa fa-check"></i>Interactions</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-october-27-2022.html"><a href="thursday-october-27-2022.html"><i class="fa fa-check"></i>Thursday, October 27, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-october-27-2022.html"><a href="thursday-october-27-2022.html#removing-variables-from-a-regression-model"><i class="fa fa-check"></i>Removing variables from a regression model</a></li>
<li class="chapter" data-level="" data-path="thursday-october-27-2022.html"><a href="thursday-october-27-2022.html#the-stepwise-selection-procedure"><i class="fa fa-check"></i>The stepwise selection procedure</a></li>
<li class="chapter" data-level="" data-path="thursday-october-27-2022.html"><a href="thursday-october-27-2022.html#transforming-a-response-variable"><i class="fa fa-check"></i>Transforming a response variable</a></li>
<li class="chapter" data-level="" data-path="thursday-october-27-2022.html"><a href="thursday-october-27-2022.html#regression-trees"><i class="fa fa-check"></i>Regression trees</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-november-1-2022.html"><a href="tuesday-november-1-2022.html"><i class="fa fa-check"></i>Tuesday, November 1, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-november-1-2022.html"><a href="tuesday-november-1-2022.html#predictive-uncertainty-with-regression-trees"><i class="fa fa-check"></i>Predictive uncertainty with regression trees</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-1-2022.html"><a href="tuesday-november-1-2022.html#the-random-forest-algorithm"><i class="fa fa-check"></i>The random forest algorithm</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-1-2022.html"><a href="tuesday-november-1-2022.html#cross-validation"><i class="fa fa-check"></i>Cross validation</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-1-2022.html"><a href="tuesday-november-1-2022.html#classification-trees"><i class="fa fa-check"></i>Classification trees</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-november-3-2022.html"><a href="thursday-november-3-2022.html"><i class="fa fa-check"></i>Thursday, November 3, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-november-3-2022.html"><a href="thursday-november-3-2022.html#binary-outcomes-and-probabilities"><i class="fa fa-check"></i>Binary outcomes and probabilities</a></li>
<li class="chapter" data-level="" data-path="thursday-november-3-2022.html"><a href="thursday-november-3-2022.html#logistic-regression"><i class="fa fa-check"></i>Logistic regression</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-november-8-2022.html"><a href="tuesday-november-8-2022.html"><i class="fa fa-check"></i>Tuesday, November 8, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-november-8-2022.html"><a href="tuesday-november-8-2022.html#quantifying-autocorrelation-in-spatial-data"><i class="fa fa-check"></i>Quantifying autocorrelation in spatial data</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-8-2022.html"><a href="tuesday-november-8-2022.html#spatial-data-as-polygon-areas"><i class="fa fa-check"></i>Spatial data as polygon areas</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-8-2022.html"><a href="tuesday-november-8-2022.html#nearest-neighbors"><i class="fa fa-check"></i>Nearest neighbors</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-8-2022.html"><a href="tuesday-november-8-2022.html#spatial-weights"><i class="fa fa-check"></i>Spatial weights</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-8-2022.html"><a href="tuesday-november-8-2022.html#morans-i"><i class="fa fa-check"></i>Moran’s I</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-8-2022.html"><a href="tuesday-november-8-2022.html#spatial-lag-variable"><i class="fa fa-check"></i>Spatial lag variable</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-november-10-2022.html"><a href="thursday-november-10-2022.html"><i class="fa fa-check"></i>Thursday, November 10, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-november-10-2022.html"><a href="thursday-november-10-2022.html#statistical-significance-of-spatial-autocorrelation"><i class="fa fa-check"></i>Statistical significance of spatial autocorrelation</a></li>
<li class="chapter" data-level="" data-path="thursday-november-10-2022.html"><a href="thursday-november-10-2022.html#a-monte-carlo-approach-to-inference-about-spatial-autocorrelation"><i class="fa fa-check"></i>A Monte Carlo approach to inference about spatial autocorrelation</a></li>
<li class="chapter" data-level="" data-path="thursday-november-10-2022.html"><a href="thursday-november-10-2022.html#spatial-autocorrelation-in-model-residuals"><i class="fa fa-check"></i>Spatial autocorrelation in model residuals</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-november-15-2022.html"><a href="tuesday-november-15-2022.html"><i class="fa fa-check"></i>Tuesday, November 15, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-november-15-2022.html"><a href="tuesday-november-15-2022.html#bi-variate-spatial-autocorrelation"><i class="fa fa-check"></i>Bi-variate spatial autocorrelation</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-15-2022.html"><a href="tuesday-november-15-2022.html#local-autocorrelation"><i class="fa fa-check"></i>Local autocorrelation</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-15-2022.html"><a href="tuesday-november-15-2022.html#local-regression"><i class="fa fa-check"></i>Local regression</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-15-2022.html"><a href="tuesday-november-15-2022.html#spatial-weights-1"><i class="fa fa-check"></i>Spatial weights</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-november-17-2022.html"><a href="thursday-november-17-2022.html"><i class="fa fa-check"></i>Thursday, November 17, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-november-17-2022.html"><a href="thursday-november-17-2022.html#geographic-regression"><i class="fa fa-check"></i>Geographic regression</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">GEO5156: Quantitative Geography</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="thursday-september-29-2022" class="section level1 unnumbered hasAnchor">
<h1>Thursday, September 29, 2022<a href="thursday-september-29-2022.html#thursday-september-29-2022" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>Today</p>
<p>Inferential statistics: How to apply common statistical tests in R and how to understand their meaning using graphs.</p>
<ul>
<li>One-sample test for the value of the population mean</li>
<li>Graphical inference</li>
<li>Two-sample test for a difference in population means</li>
<li>A non-parametric test for difference in population means</li>
<li>Paired observations</li>
<li>Chi-squared test for independence</li>
</ul>
<p>This lesson marks a departure from the earlier lessons. You will continue to learn how to code in R, but you will do it in the context of statistical thinking, analysis, and modeling.</p>
<p>I find statistics to be a natural extension to how I think about the world, but I realize this comes with experience and may not come natural to you.</p>
<p>The process of drawing conclusions about a population from a sample of data is called <em>inference</em>. Formally referred to as <em>inferential statistics</em> and it is a foundation of data science.</p>
<p>Two approaches: frequentist (standard practice) and Bayesian. Standard practice relies on disproving a research claim that is NOT of interest.</p>
<p>The research claim you want to disprove is called the <em>null hypothesis</em>. For instance, to show that one medical treatment is better than another treatment, you first assume that the two treatments lead to equal survival rates. You then proceed to disprove this null hypothesis with data. Often the other treatment is a placebo (sugar pill).</p>
<p>To show that the climate is getting warmer, you first assume that it is not getting warmer. You then proceed trying to disprove this hypothesis.</p>
<p>Q: What is the difference between the medical treatment example and the climate change example?</p>
<div id="one-sample-test-for-the-value-of-the-population-mean" class="section level2 unnumbered hasAnchor">
<h2>One-sample test for the value of the population mean<a href="thursday-september-29-2022.html#one-sample-test-for-the-value-of-the-population-mean" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Oftentimes interest lies in the mean value (from a population of all values) being different than some prescribed value <span class="math inline">\(M\)</span>. So the null hypothesis (what you want to disprove) is that the population mean equals <span class="math inline">\(M\)</span>.</p>
<p>Using textbook notation the test is written as
<span class="math display">\[
\hbox{H}_0: \mu = M \\
\hbox{H}_A: \mu \neq M
\]</span>
where H sub naught (<span class="math inline">\(\hbox{H}_0\)</span>) is the null hypothesis stating that the unknown population mean (<span class="math inline">\(\mu\)</span>) equals a specific value <span class="math inline">\(M\)</span> and where H sub A (<span class="math inline">\(\hbox{H}_A\)</span>) is the alternative hypothesis stating that the unknown population mean does equal <span class="math inline">\(M\)</span>.</p>
<p>For example, given a sample of FSU students where heights are measured in centimeters, you test the hypothesis that the mean height of all students at FSU (the population) is 183 cm (6 feet).</p>
<p>You should start by plotting the data together with the hypothesis. Here first create a data frame using the vector of heights and number the students from 1 to n using the sequence operator <code>:</code>.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="thursday-september-29-2022.html#cb1-1" aria-hidden="true" tabindex="-1"></a>ht <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">177</span>, <span class="dv">180</span>, <span class="dv">179</span>, <span class="dv">174</span>, <span class="dv">192</span>, <span class="dv">186</span>, <span class="dv">165</span>, <span class="dv">183</span>)</span>
<span id="cb1-2"><a href="thursday-september-29-2022.html#cb1-2" aria-hidden="true" tabindex="-1"></a>ht.df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Student =</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(ht), </span>
<span id="cb1-3"><a href="thursday-september-29-2022.html#cb1-3" aria-hidden="true" tabindex="-1"></a>                    <span class="at">Height =</span> ht)</span></code></pre></div>
<p>Then use <code>ggplot()</code> to make a box plot and add the hypothesized mean as a layer with the <code>geom_hline()</code> function and the data values as layer with the <code>geom_point()</code> function.</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="thursday-september-29-2022.html#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb2-2"><a href="thursday-september-29-2022.html#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="thursday-september-29-2022.html#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> ht.df, </span>
<span id="cb2-4"><a href="thursday-september-29-2022.html#cb2-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> <span class="st">&quot;&quot;</span>, <span class="at">y =</span> ht)) <span class="sc">+</span> </span>
<span id="cb2-5"><a href="thursday-september-29-2022.html#cb2-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb2-6"><a href="thursday-september-29-2022.html#cb2-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">&quot;blue&quot;</span>) <span class="sc">+</span></span>
<span id="cb2-7"><a href="thursday-september-29-2022.html#cb2-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Height (cm)&quot;</span>) <span class="sc">+</span> <span class="fu">xlab</span>(<span class="st">&quot;&quot;</span>) <span class="sc">+</span></span>
<span id="cb2-8"><a href="thursday-september-29-2022.html#cb2-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="fu">aes</span>(<span class="at">yintercept =</span> <span class="dv">183</span>), <span class="at">color =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span></span>
<span id="cb2-9"><a href="thursday-september-29-2022.html#cb2-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">150</span>, <span class="dv">200</span>)) <span class="sc">+</span></span>
<span id="cb2-10"><a href="thursday-september-29-2022.html#cb2-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="QG-2022_files/figure-html/unnamed-chunk-2-1.png" width="672" /></p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="thursday-september-29-2022.html#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(ht)</span></code></pre></div>
<pre><code>## [1] 179.5</code></pre>
<p>The median height in our sample is less than 180 cm (thick black line) and the hypothesized mean (red line) is within the interquartile range.</p>
<p>You write the test as:
<span class="math display">\[
\hbox{H}_0: \mu = 183 \\
\hbox{H}_A: \mu \neq 183
\]</span></p>
<p>You test the hypothesis that the mean height in the population is 183 cm with the <code>t.test()</code> function. The first argument is the data vector (not a data frame) and the second argument is the hypothesized mean (<code>mu =</code>).</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="thursday-september-29-2022.html#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(ht, </span>
<span id="cb5-2"><a href="thursday-september-29-2022.html#cb5-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">mu =</span> <span class="dv">183</span>)</span></code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  ht
## t = -1.2239, df = 7, p-value = 0.2606
## alternative hypothesis: true mean is not equal to 183
## 95 percent confidence interval:
##  172.7376 186.2624
## sample estimates:
## mean of x 
##     179.5</code></pre>
<p>Where do these values come from and how do you interpret them?</p>
<p>The output includes the <span class="math inline">\(t\)</span> value (-1.2239). The <span class="math inline">\(t\)</span> value (or <span class="math inline">\(t\)</span> statistic) is computed as
<span class="math display">\[
t = \frac{\bar x - M}{s/\sqrt{n}}
\]</span>
where <span class="math inline">\(\bar x\)</span> is the sample mean, <span class="math inline">\(M\)</span> is the hypothesized value, <span class="math inline">\(s\)</span> is the standard deviation and <span class="math inline">\(n\)</span> is the sample size.</p>
<p>In code the <span class="math inline">\(t\)</span> value is</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="thursday-september-29-2022.html#cb7-1" aria-hidden="true" tabindex="-1"></a>(<span class="fu">mean</span>(ht) <span class="sc">-</span> <span class="dv">183</span>) <span class="sc">/</span> (<span class="fu">sd</span>(ht) <span class="sc">/</span> <span class="fu">sqrt</span>(<span class="fu">length</span>(ht)))</span></code></pre></div>
<pre><code>## [1] -1.223853</code></pre>
<p>The output also includes the degrees of freedom (7). The degrees of freedom on the <span class="math inline">\(t\)</span> value is the sample size minus one. There are eight student heights (sample size is 8) so <code>df = 7</code>.</p>
<p>The <em>degrees of freedom</em> (dof, df) is a term that indicates the number of values in the calculation of a statistic that are ‘free’ to vary. Suppose you know the mean value of a set of numbers (say the mean value is 24). Further, suppose you know how many numbers were used to calculate this mean (say there were five) but you don’t know what the five values were.</p>
<p>Now you ask, what values could the five numbers be so that the mean is 24? With a few moments thought you will conclude that four of them could be any value at all, but the fifth one is constrained so that the mean value equals 24.</p>
<p>Thus the mean is a statistic with n-1 degrees of freedom.</p>
<p>The output also includes the sample mean. The sample mean height of 179.5 cm is shorter than the hypothesized height of 183 cm. But, with only eight values, this amount of “shortness” does not provide you with enough evidence to reject the null hypothesis that the population height is 183 cm. So you conclude by stating that you fail to reject the null hypothesis.</p>
<p>The <span class="math inline">\(p\)</span>-value which quantifies the evidence in support of the null hypothesis. The smaller the <span class="math inline">\(p\)</span>-value the less support there is for the null hypothesis. The <span class="math inline">\(p\)</span>-value is the area under the <span class="math inline">\(t\)</span> distribution curve to left of the <span class="math inline">\(t\)</span> value (lower quantile value).</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="thursday-september-29-2022.html#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pt</span>(<span class="at">q =</span> <span class="sc">-</span><span class="fl">1.2239</span>, <span class="at">df =</span> <span class="dv">7</span>) <span class="sc">*</span> <span class="dv">2</span></span></code></pre></div>
<pre><code>## [1] 0.2605821</code></pre>
<p>The <code>pt()</code> function is the <em>cumulative distribution function</em> for the <span class="math inline">\(t\)</span> distribution. The degrees of freedom is the parameter so you need to include that as the <code>df =</code> argument.</p>
<p>You multiply this probability by 2 because your alternative hypothesis is two-sided (not equal to <span class="math inline">\(M\)</span>).</p>
<p>The output provides a 95% uncertainty interval about the sample mean. It includes the hypothesized mean height of 183 cm.</p>
<p>The uncertainty (confidence) interval is a statistic that tells you how much uncertainty there is in using the sample mean as an estimate for the population mean. You conclude that, based on the sample of eight students, your best estimate for the mean height of all students at FSU is 179.5 cm with a 95% uncertainty interval that ranges from 172.7 to 186.3 cm.</p>
<p>A <span class="math inline">\(p\)</span>-value is an estimate of the probability that your data, or data more extreme than observed, could occur by chance if the null hypothesis is true. A small <span class="math inline">\(p\)</span>-value tells you that the data is <em>unusual</em> with respect to the particular null hypothesis.</p>
<p>Interpretation of the <span class="math inline">\(p\)</span>-value is stated as evidence AGAINST the null hypothesis. This is because interest lies in the null hypothesis being untenable.</p>
<table>
<thead>
<tr class="header">
<th><span class="math inline">\(p\)</span>-value</th>
<th>Statement of evidence against the null</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>less than .01</td>
<td>convincing</td>
</tr>
<tr class="even">
<td>.01 - .05</td>
<td>moderate</td>
</tr>
<tr class="odd">
<td>.05 - .15</td>
<td>suggestive, but inconclusive</td>
</tr>
<tr class="even">
<td>greater than .15</td>
<td>no</td>
</tr>
</tbody>
</table>
<p>The <span class="math inline">\(p\)</span>-value comes from the <code>pt()</code> function, which determines the area under the <span class="math inline">\(t\)</span> distribution curve to the left of a particular value. The curve is obtained using the <code>dt()</code> function (density function).</p>
<p>For example, to plot the <span class="math inline">\(t\)</span> distribution curve and the <span class="math inline">\(t\)</span> value from our hypothesis above you type</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="thursday-september-29-2022.html#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">curve</span>(<span class="fu">dt</span>(x, <span class="dv">7</span>), <span class="at">from =</span> <span class="sc">-</span><span class="dv">3</span>, <span class="at">to =</span> <span class="dv">3</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb11-2"><a href="thursday-september-29-2022.html#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> <span class="sc">-</span><span class="fl">1.2239</span>, <span class="at">col =</span> <span class="st">&#39;red&#39;</span>)</span>
<span id="cb11-3"><a href="thursday-september-29-2022.html#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> <span class="fl">1.2239</span>, <span class="at">col =</span> <span class="st">&#39;red&#39;</span>)</span></code></pre></div>
<p><img src="QG-2022_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<p>The area under the curve to the left of -1.2239 is</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="thursday-september-29-2022.html#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pt</span>(<span class="at">q =</span> <span class="sc">-</span><span class="fl">1.2239</span>, </span>
<span id="cb12-2"><a href="thursday-september-29-2022.html#cb12-2" aria-hidden="true" tabindex="-1"></a>   <span class="at">df =</span> <span class="dv">7</span>)</span></code></pre></div>
<pre><code>## [1] 0.130291</code></pre>
<p>So 13% of the area lies to the left of the first red line. The distribution is symmetric so 13% of the area lies to the right of the second red line. With a two-sided test you add these two fractions to get the <span class="math inline">\(p\)</span>-value.</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="thursday-september-29-2022.html#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pt</span>(<span class="at">q =</span> <span class="sc">-</span><span class="fl">1.2239</span>, <span class="at">df =</span> <span class="dv">7</span>) <span class="sc">+</span> <span class="fu">pt</span>(<span class="at">q =</span> <span class="fl">1.2239</span>, <span class="at">df =</span> <span class="dv">7</span>, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## [1] 0.2605821</code></pre>
<p>Example: Strongest Atlantic hurricanes</p>
<p>Are hurricanes getting stronger? Let’s say you know that the strongest hurricanes in the past have an average minimum pressure of 915 mb. Lower central pressure means a stronger hurricane.</p>
<p>Suppose you collect data on the strength of hurricanes over the period 1980-2017.</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="thursday-september-29-2022.html#cb16-1" aria-hidden="true" tabindex="-1"></a>Names <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;Allen&quot;</span>, <span class="st">&quot;Gloria&quot;</span>, <span class="st">&quot;Gilbert&quot;</span>, <span class="st">&quot;Hugo&quot;</span>, <span class="st">&quot;Opal&quot;</span>, <span class="st">&quot;Mitch&quot;</span>, <span class="st">&quot;Isabel&quot;</span>, <span class="st">&quot;Ivan&quot;</span>, <span class="st">&quot;Katrina&quot;</span>, <span class="st">&quot;Rita&quot;</span>, <span class="st">&quot;Wilma&quot;</span>, <span class="st">&quot;Dean&quot;</span>, <span class="st">&quot;Irma&quot;</span>, <span class="st">&quot;Maria&quot;</span>)</span>
<span id="cb16-2"><a href="thursday-september-29-2022.html#cb16-2" aria-hidden="true" tabindex="-1"></a>Year <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1980</span>, <span class="dv">1985</span>, <span class="dv">1988</span>, <span class="dv">1989</span>, <span class="dv">1995</span>, <span class="dv">1998</span>, <span class="dv">2003</span>, <span class="dv">2004</span>, <span class="dv">2005</span>, <span class="dv">2005</span>, <span class="dv">2005</span>, <span class="dv">2007</span>, <span class="dv">2017</span>, <span class="dv">2017</span>)</span>
<span id="cb16-3"><a href="thursday-september-29-2022.html#cb16-3" aria-hidden="true" tabindex="-1"></a>minP <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">899</span>, <span class="dv">919</span>, <span class="dv">888</span>, <span class="dv">918</span>, <span class="dv">916</span>, <span class="dv">905</span>, <span class="dv">915</span>, <span class="dv">910</span>, <span class="dv">902</span>, <span class="dv">895</span>, <span class="dv">882</span>, <span class="dv">905</span>, <span class="dv">914</span>, <span class="dv">908</span>)</span>
<span id="cb16-4"><a href="thursday-september-29-2022.html#cb16-4" aria-hidden="true" tabindex="-1"></a>hur.df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(Year, Names, minP, <span class="at">Basin =</span> <span class="st">&quot;A&quot;</span>)</span></code></pre></div>
<p>You are interested in whether these recent Atlantic hurricanes since 1980 have an average minimum pressure less than 915 mb. So this is our alternative hypothesis.</p>
<p>Your null hypothesis is that the average minimum pressure (<span class="math inline">\(\mu\)</span>) is 915 mb or higher and the alternative hypothesis is that it is less than 915.</p>
<p>Formally, you write the statistical test as
<span class="math display">\[
\hbox{H}_0: \mu \ge 915 \\
\hbox{H}_A: \mu \lt 915
\]</span></p>
<p>Start with a plot.</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="thursday-september-29-2022.html#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(hur.df, </span>
<span id="cb17-2"><a href="thursday-september-29-2022.html#cb17-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> <span class="st">&quot;&quot;</span>, <span class="at">y =</span> minP)) <span class="sc">+</span> </span>
<span id="cb17-3"><a href="thursday-september-29-2022.html#cb17-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb17-4"><a href="thursday-september-29-2022.html#cb17-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">&quot;blue&quot;</span>) <span class="sc">+</span></span>
<span id="cb17-5"><a href="thursday-september-29-2022.html#cb17-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Minimum Pressure (mb)&quot;</span>) <span class="sc">+</span> <span class="fu">xlab</span>(<span class="st">&quot;&quot;</span>) <span class="sc">+</span></span>
<span id="cb17-6"><a href="thursday-september-29-2022.html#cb17-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="fu">aes</span>(<span class="at">yintercept =</span> <span class="dv">915</span>), <span class="at">color =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span></span>
<span id="cb17-7"><a href="thursday-september-29-2022.html#cb17-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>() <span class="sc">+</span></span>
<span id="cb17-8"><a href="thursday-september-29-2022.html#cb17-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="QG-2022_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="thursday-september-29-2022.html#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(hur.df<span class="sc">$</span>minP)</span></code></pre></div>
<pre><code>## [1] 905.4286</code></pre>
<p>You see that the data support your idea (hypothesis) that recent hurricanes have, on average, pressures below 915 mb.</p>
<p>You formally test the hypothesis with the <code>t.test()</code> function. The first argument is the data values as a vector (here <code>hur.df$minP</code>), the second argument is the hypothesized mean, and the <code>alternative =</code> argument is set to <code>"less"</code> because that is your alternative hypothesis.</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="thursday-september-29-2022.html#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(hur.df<span class="sc">$</span>minP, </span>
<span id="cb20-2"><a href="thursday-september-29-2022.html#cb20-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">mu =</span> <span class="dv">915</span>,</span>
<span id="cb20-3"><a href="thursday-september-29-2022.html#cb20-3" aria-hidden="true" tabindex="-1"></a>       <span class="at">alternative =</span> <span class="st">&quot;less&quot;</span>)</span></code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  hur.df$minP
## t = -3.1679, df = 13, p-value = 0.003706
## alternative hypothesis: true mean is less than 915
## 95 percent confidence interval:
##      -Inf 910.7792
## sample estimates:
## mean of x 
##  905.4286</code></pre>
<p>Here you summarize/conclude as follows: The sample mean intensity of the recent hurricanes is 905.4 mb, which is less than 915 mb by a difference of about 10 mb.</p>
<p>Given this amount of difference (the effect size) together with a sample size of 14, you conclude there is convincing evidence that, on average, the strongest hurricanes since 1980 are stronger than those in the past.</p>
</div>
<div id="graphical-inference" class="section level2 unnumbered hasAnchor">
<h2>Graphical inference<a href="thursday-september-29-2022.html#graphical-inference" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Applying a <span class="math inline">\(t\)</span> test is an example of statistical inference. You draw conclusions about the population from the sample of data. This is why statistics is useful: you don’t want your conclusions to apply only to a sample. You want them to apply to the population at large.</p>
<p>There are two parts: Testing (is there a difference?) and estimation (how big is the difference?). Is there a difference is visual. “Is what you see really there?” More precisely, is what you see in a plot of the sample an accurate reflection of the entire population?</p>
<p>For example, generate samples with the hypothesized mean value. Then see how these samples compare with our data.</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="thursday-september-29-2022.html#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rnorm</span>(<span class="at">n =</span> <span class="dv">8</span>, </span>
<span id="cb22-2"><a href="thursday-september-29-2022.html#cb22-2" aria-hidden="true" tabindex="-1"></a>      <span class="at">mean =</span> <span class="dv">183</span>, </span>
<span id="cb22-3"><a href="thursday-september-29-2022.html#cb22-3" aria-hidden="true" tabindex="-1"></a>      <span class="at">sd =</span> <span class="fu">sd</span>(ht))</span></code></pre></div>
<pre><code>## [1] 191.5521 185.9609 174.7002 191.6241 189.5957 182.1216 179.0626 183.0548</code></pre>
<p>Consider the situation where you try to ‘find’ your data from a lineup of plots generated from ‘fake’ data under the null hypothesis. By ‘find’ I mean determine which plot corresponds to your data.</p>
<p>The functions in the {nullabor} package generate data sets and plots under various null hypotheses through permutation or simulation.</p>
<p>The <code>nullabor::null_dist()</code> function is used to create another function with arguments <code>var =</code> that specifies the name of the column in our data frame containing the data values of interest, <code>dist =</code> that specifies what type of distribution you assume for your data (here ‘normal’) and <code>params =</code> as a list of the mean and standard deviation of your data.</p>
<p>The function <code>null_dist()</code> generates another function based on your null hypothesis. In this case a normal distribution for the variable <code>Height</code> (in the data frame <code>ht.df</code>) centered on 183 with a standard deviation equal to the standard deviation of the sample (<code>ht</code>).</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="thursday-september-29-2022.html#cb24-1" aria-hidden="true" tabindex="-1"></a>fun <span class="ot">&lt;-</span> nullabor<span class="sc">::</span><span class="fu">null_dist</span>(<span class="at">var =</span> <span class="st">&quot;Height&quot;</span>, </span>
<span id="cb24-2"><a href="thursday-september-29-2022.html#cb24-2" aria-hidden="true" tabindex="-1"></a>                           <span class="at">dist =</span> <span class="st">&#39;normal&#39;</span>, </span>
<span id="cb24-3"><a href="thursday-september-29-2022.html#cb24-3" aria-hidden="true" tabindex="-1"></a>                           <span class="at">params =</span> <span class="fu">list</span>(<span class="at">mean =</span> <span class="dv">183</span>, </span>
<span id="cb24-4"><a href="thursday-september-29-2022.html#cb24-4" aria-hidden="true" tabindex="-1"></a>                                         <span class="at">sd =</span> <span class="fu">sd</span>(ht)))</span></code></pre></div>
<p>The magic happens when you use the <code>lineup()</code> function that takes as it’s arguments the saved function (here <code>fun</code>) and the true data frame (here <code>ht.df</code>) and returns a data frame in long format (here assigned to the object <code>dfL</code>).</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="thursday-september-29-2022.html#cb25-1" aria-hidden="true" tabindex="-1"></a>dfL <span class="ot">&lt;-</span> nullabor<span class="sc">::</span><span class="fu">lineup</span>(<span class="at">method =</span> fun, </span>
<span id="cb25-2"><a href="thursday-september-29-2022.html#cb25-2" aria-hidden="true" tabindex="-1"></a>                        <span class="at">true =</span> ht.df)</span></code></pre></div>
<pre><code>## decrypt(&quot;CLg7 X161 sO bJws6sJO vH&quot;)</code></pre>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="thursday-september-29-2022.html#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(dfL)</span></code></pre></div>
<pre><code>##   Student   Height .sample
## 1       1 192.3907       1
## 2       2 177.1609       1
## 3       3 171.3312       1
## 4       4 169.5355       1
## 5       5 178.3207       1
## 6       6 189.9504       1</code></pre>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="thursday-september-29-2022.html#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tail</span>(dfL)</span></code></pre></div>
<pre><code>##     Student   Height .sample
## 147       3 168.6288      20
## 148       4 199.3645      20
## 149       5 184.3624      20
## 150       6 183.4669      20
## 151       7 185.5285      20
## 152       8 189.2463      20</code></pre>
<p>The data frame contains the random null heights and the observed heights. The heights are listed in the column name <code>Height</code> and by default there are 20 samples each indicated by a number in the column labeled <code>.sample</code>.</p>
<p>The output contains an encryption key that hides the sample number corresponding to the observed heights.</p>
<p>You know how to plot side-by-side using the <code>facet_wrap()</code> function so you can try to visually pick out the observed heights.</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="thursday-september-29-2022.html#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> dfL, </span>
<span id="cb31-2"><a href="thursday-september-29-2022.html#cb31-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> <span class="st">&quot;&quot;</span>, <span class="at">y =</span> Height)) <span class="sc">+</span> </span>
<span id="cb31-3"><a href="thursday-september-29-2022.html#cb31-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span> </span>
<span id="cb31-4"><a href="thursday-september-29-2022.html#cb31-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> .sample, <span class="at">nrow =</span> <span class="dv">1</span>, <span class="at">ncol =</span> <span class="dv">20</span>) <span class="sc">+</span></span>
<span id="cb31-5"><a href="thursday-september-29-2022.html#cb31-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="QG-2022_files/figure-html/unnamed-chunk-15-1.png" width="672" /></p>
<p>Can you pick out the actual data? A plot of the real data is hidden amount the 19 ‘fake’ data. The fakes are plots of data generated from the null hypothesis. If you can spot the real data, then there is evidence that your data is different from the null hypothesis.</p>
<p>With a null hypothesis stating that the mean height is 183 cm, the evidence is weak that the data is different. So you fail to reject the null.</p>
<p>Suppose the null hypothesis states that the mean height is 190 cm. Retest with the new null hypothesis.</p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="thursday-september-29-2022.html#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(ht, </span>
<span id="cb32-2"><a href="thursday-september-29-2022.html#cb32-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">mu =</span> <span class="dv">190</span>)</span></code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  ht
## t = -3.6716, df = 7, p-value = 0.007948
## alternative hypothesis: true mean is not equal to 190
## 95 percent confidence interval:
##  172.7376 186.2624
## sample estimates:
## mean of x 
##     179.5</code></pre>
<p>In this case, the sample of students looks unusual (they are too short) if the true height is 190 cm. The <span class="math inline">\(p\)</span>-value is reduced to .008.</p>
<p>The uncertainty interval does not change. The uncertainty interval is about the sample as an estimate of the unknown population mean regardless of what you think the mean is.</p>
<p>The value of 190 lies outside the uncertainty interval consistent with a small <span class="math inline">\(p\)</span> value.</p>
<p>Repeat the graphical lineup but this time with a hypothesized mean of 190 cm.</p>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="thursday-september-29-2022.html#cb34-1" aria-hidden="true" tabindex="-1"></a>fun <span class="ot">&lt;-</span> nullabor<span class="sc">::</span><span class="fu">null_dist</span>(<span class="at">var =</span> <span class="st">&quot;Height&quot;</span>, </span>
<span id="cb34-2"><a href="thursday-september-29-2022.html#cb34-2" aria-hidden="true" tabindex="-1"></a>                           <span class="at">dist =</span> <span class="st">&#39;normal&#39;</span>, </span>
<span id="cb34-3"><a href="thursday-september-29-2022.html#cb34-3" aria-hidden="true" tabindex="-1"></a>                           <span class="at">params =</span> <span class="fu">list</span>(<span class="at">mean =</span> <span class="dv">190</span>, <span class="at">sd =</span> <span class="fu">sd</span>(ht)))</span>
<span id="cb34-4"><a href="thursday-september-29-2022.html#cb34-4" aria-hidden="true" tabindex="-1"></a>inf <span class="ot">&lt;-</span> nullabor<span class="sc">::</span><span class="fu">lineup</span>(fun, ht.df)</span></code></pre></div>
<pre><code>## decrypt(&quot;CLg7 X161 sO bJws6sJO qZ&quot;)</code></pre>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="thursday-september-29-2022.html#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> inf, </span>
<span id="cb36-2"><a href="thursday-september-29-2022.html#cb36-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> <span class="st">&quot;&quot;</span>, <span class="at">y =</span> Height)) <span class="sc">+</span> </span>
<span id="cb36-3"><a href="thursday-september-29-2022.html#cb36-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span> </span>
<span id="cb36-4"><a href="thursday-september-29-2022.html#cb36-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> .sample, <span class="at">nrow =</span> <span class="dv">1</span>, <span class="at">ncol =</span> <span class="dv">20</span>) <span class="sc">+</span></span>
<span id="cb36-5"><a href="thursday-september-29-2022.html#cb36-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="QG-2022_files/figure-html/unnamed-chunk-17-1.png" width="672" /></p>
<p>In this case it is easier to pick out the actual data. And this ability to pick out the actual data corresponds with a lower <span class="math inline">\(p\)</span>-value.</p>
<p>The idea of comparing your actual data to a set of data generated under a null hypothesis is a fundamental idea of statistics.</p>
<p>Said another way: you have data and want to use it to say something about the world. You do this by comparing your data with data under other possible realities (hypotheticals–“what if?” or counterfactuals).</p>
<p>The possible realities are generated with computer code using statistical distributions or resampling methods.</p>
<p>Graphical inference can be used in a variety of applications. Here is an example from my tornado research. Here the innocent is a spatially random distribution of <a href="http://myweb.fsu.edu/jelsner/temp/TornadoLineup.png">genesis</a>. Can you pick out the actual data?</p>
<p>More information on the {nullabor} package <a href="https://cran.r-project.org/web/packages/nullabor/vignettes/nullabor.html">here</a></p>
</div>
<div id="two-sample-test-for-a-difference-in-population-means" class="section level2 unnumbered hasAnchor">
<h2>Two-sample test for a difference in population means<a href="thursday-september-29-2022.html#two-sample-test-for-a-difference-in-population-means" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>With two samples of data the null hypothesis is often that the two samples have the same population mean where you assume both samples can be adequately described with normal distributions.</p>
<p>You test the null hypothesis that the two samples have the same population mean by computing the <span class="math inline">\(t\)</span> value. In this case, the <span class="math inline">\(t\)</span> value is the difference in sample means divided by the standard error of the difference in means (SEDM).</p>
<p>There are two ways to calculate SEDM.</p>
<ol style="list-style-type: decimal">
<li><p>Assume equal variance: use the pooled standard deviation (<span class="math inline">\(s\)</span>). Under the null hypothesis, the <span class="math inline">\(t\)</span> value will follow a <span class="math inline">\(t\)</span> distribution with n1 + n2 - 2 degrees of freedom (df).</p></li>
<li><p>Don’t assume equal variances (this is the default assumption). Under the null hypothesis, the <span class="math inline">\(t\)</span> statistic approximates a <span class="math inline">\(t\)</span> distribution. In this case it is called the Welch procedure and the degrees of freedom is not an integer.</p></li>
</ol>
<p>Usually the methods give similar results unless group sizes and variances are widely different across the two samples.</p>
<p>Example: hurricanes occurring in the North Atlantic and the eastern North Pacific</p>
<p>Are hurricanes that occur over the eastern North Pacific weaker (or stronger) than those that occur over the Atlantic? Let’s look at the evidence.</p>
<p>You add the data from the Pacific to the data frame <code>hur.df</code> by making a similar data frame and then using the <code>rbind()</code> function to combine them.</p>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="thursday-september-29-2022.html#cb37-1" aria-hidden="true" tabindex="-1"></a>Names <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;Trudy&quot;</span>, <span class="st">&quot;Gilma&quot;</span>, <span class="st">&quot;Olivia&quot;</span>, <span class="st">&quot;Guillermo&quot;</span>, <span class="st">&quot;Linda&quot;</span>, <span class="st">&quot;Juliette&quot;</span>, <span class="st">&quot;Elida&quot;</span>, <span class="st">&quot;Hernan&quot;</span>, <span class="st">&quot;Kenna&quot;</span>, <span class="st">&quot;Ioke&quot;</span>, <span class="st">&quot;Rick&quot;</span>, <span class="st">&quot;Celia&quot;</span>, <span class="st">&quot;Marie&quot;</span>, <span class="st">&quot;Odile&quot;</span>, <span class="st">&quot;Patricia&quot;</span>, <span class="st">&quot;Lane&quot;</span>, <span class="st">&quot;Walaka&quot;</span>)</span>
<span id="cb37-2"><a href="thursday-september-29-2022.html#cb37-2" aria-hidden="true" tabindex="-1"></a>Year <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1990</span>, <span class="dv">1994</span>, <span class="dv">1994</span>, <span class="dv">1997</span>, <span class="dv">1997</span>, <span class="dv">2001</span>, <span class="dv">2002</span>, <span class="dv">2002</span>, <span class="dv">2002</span>, <span class="dv">2006</span>, <span class="dv">2009</span>, <span class="dv">2010</span>, <span class="dv">2014</span>, <span class="dv">2014</span>, <span class="dv">2015</span>, <span class="dv">2018</span>, <span class="dv">2018</span>)</span>
<span id="cb37-3"><a href="thursday-september-29-2022.html#cb37-3" aria-hidden="true" tabindex="-1"></a>minP <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">924</span>, <span class="dv">920</span>, <span class="dv">923</span>, <span class="dv">919</span>, <span class="dv">902</span>, <span class="dv">923</span>, <span class="dv">921</span>, <span class="dv">921</span>, <span class="dv">913</span>, <span class="dv">915</span>, <span class="dv">906</span>, <span class="dv">921</span>, <span class="dv">918</span>, <span class="dv">918</span>, <span class="dv">872</span>, <span class="dv">922</span>, <span class="dv">920</span>)</span>
<span id="cb37-4"><a href="thursday-september-29-2022.html#cb37-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-5"><a href="thursday-september-29-2022.html#cb37-5" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(Year, Names, minP, <span class="at">Basin =</span> <span class="st">&quot;P&quot;</span>)</span>
<span id="cb37-6"><a href="thursday-september-29-2022.html#cb37-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-7"><a href="thursday-september-29-2022.html#cb37-7" aria-hidden="true" tabindex="-1"></a>hur.df <span class="ot">&lt;-</span> <span class="fu">rbind</span>(hur.df, df)</span></code></pre></div>
<p>You start with a lineup of plots where you shuffle (permute) the minimum pressures between the basins multiple times. This is done with the <code>nullabor::null_permute()</code> function identifying what column to permute.</p>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="thursday-september-29-2022.html#cb38-1" aria-hidden="true" tabindex="-1"></a>fun <span class="ot">&lt;-</span> nullabor<span class="sc">::</span><span class="fu">null_permute</span>(<span class="st">&quot;Basin&quot;</span>)</span>
<span id="cb38-2"><a href="thursday-september-29-2022.html#cb38-2" aria-hidden="true" tabindex="-1"></a>inf <span class="ot">&lt;-</span> nullabor<span class="sc">::</span><span class="fu">lineup</span>(fun, hur.df, <span class="at">n =</span> <span class="dv">12</span>)</span></code></pre></div>
<pre><code>## decrypt(&quot;CLg7 X161 sO bJws6sJO vk&quot;)</code></pre>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="thursday-september-29-2022.html#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> inf, </span>
<span id="cb40-2"><a href="thursday-september-29-2022.html#cb40-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> Basin, <span class="at">y =</span> minP, <span class="at">color =</span> Basin)) <span class="sc">+</span> </span>
<span id="cb40-3"><a href="thursday-september-29-2022.html#cb40-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span> </span>
<span id="cb40-4"><a href="thursday-september-29-2022.html#cb40-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> .sample)</span></code></pre></div>
<p><img src="QG-2022_files/figure-html/unnamed-chunk-19-1.png" width="672" /></p>
<p>Based on these plots, what do you anticipate the conclusion will be when you formalize this with a <span class="math inline">\(t\)</span> test? Asking yourself what you expect the result will be before performing statistical tests is a good strategy to guard against interpreting non-sensical results.</p>
<p>Let <span class="math inline">\(\mu_{A}\)</span> be the population mean of Atlantic hurricanes and <span class="math inline">\(\mu_{P}\)</span> be the population mean of Pacific hurricanes, you formally write the statistical test as
<span class="math display">\[
\hbox{H}_0: \mu_{A} = \mu_{P} \\
\hbox{H}_A: \mu_{A} \neq \mu_{P}
\]</span>
You implement the test as follows</p>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="thursday-september-29-2022.html#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(minP <span class="sc">~</span> Basin, </span>
<span id="cb41-2"><a href="thursday-september-29-2022.html#cb41-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">data =</span> hur.df, </span>
<span id="cb41-3"><a href="thursday-september-29-2022.html#cb41-3" aria-hidden="true" tabindex="-1"></a>       <span class="at">var.equal =</span> <span class="cn">TRUE</span>,</span>
<span id="cb41-4"><a href="thursday-september-29-2022.html#cb41-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">alternative =</span> <span class="st">&quot;two.sided&quot;</span>)</span></code></pre></div>
<pre><code>## 
##  Two Sample t-test
## 
## data:  minP by Basin
## t = -2.2407, df = 29, p-value = 0.03287
## alternative hypothesis: true difference in means between group A and group P is not equal to 0
## 95 percent confidence interval:
##  -18.6455942  -0.8502041
## sample estimates:
## mean in group A mean in group P 
##        905.4286        915.1765</code></pre>
<p>You write a summary and conclusion as follows: “The sample mean intensity of Atlantic hurricanes is 905.4 mb and the sample mean intensity of the Pacific hurricanes is 915.2 mb. Given this amount of difference (the effect size) together with a sample size of 29, you conclude there is moderate evidence that the mean hurricane intensity in the Atlantic is different than the mean hurricane intensity of the Pacific with the difference in the direction of stronger (lower pressures) hurricanes in the Atlantic on average.”</p>
<p>Example: Palmer penguins</p>
<p>Let <span class="math inline">\(A\)</span> be the length of Adelie penguin flippers and <span class="math inline">\(C\)</span> be the length of Chinstrap penguin flippers. Then you formally write the statistical test as</p>
<p><span class="math display">\[
\hbox{H}_0: \mu_{A} = \mu_{C} \\
\hbox{H}_A: \mu_{A} \lt \mu_{C}
\]</span></p>
<p>The data set to test this one-sided hypothesis is available as part of the {palmerpenguins} package.</p>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="thursday-september-29-2022.html#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(palmerpenguins)</span>
<span id="cb43-2"><a href="thursday-september-29-2022.html#cb43-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(penguins)</span></code></pre></div>
<pre><code>## # A tibble: 6 × 8
##   species island    bill_length_mm bill_depth_mm flipper_l…¹ body_…² sex    year
##   &lt;fct&gt;   &lt;fct&gt;              &lt;dbl&gt;         &lt;dbl&gt;       &lt;int&gt;   &lt;int&gt; &lt;fct&gt; &lt;int&gt;
## 1 Adelie  Torgersen           39.1          18.7         181    3750 male   2007
## 2 Adelie  Torgersen           39.5          17.4         186    3800 fema…  2007
## 3 Adelie  Torgersen           40.3          18           195    3250 fema…  2007
## 4 Adelie  Torgersen           NA            NA            NA      NA &lt;NA&gt;   2007
## 5 Adelie  Torgersen           36.7          19.3         193    3450 fema…  2007
## 6 Adelie  Torgersen           39.3          20.6         190    3650 male   2007
## # … with abbreviated variable names ¹​flipper_length_mm, ²​body_mass_g</code></pre>
<p>Remove the rows corresponding to the larger Gentoo penguins.</p>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="thursday-september-29-2022.html#cb45-1" aria-hidden="true" tabindex="-1"></a>penguins <span class="ot">&lt;-</span> penguins <span class="sc">|&gt;</span></span>
<span id="cb45-2"><a href="thursday-september-29-2022.html#cb45-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">filter</span>(species <span class="sc">!=</span> <span class="st">&quot;Gentoo&quot;</span>)</span></code></pre></div>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="thursday-september-29-2022.html#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> penguins, </span>
<span id="cb46-2"><a href="thursday-september-29-2022.html#cb46-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> species, <span class="at">y =</span> flipper_length_mm)) <span class="sc">+</span></span>
<span id="cb46-3"><a href="thursday-september-29-2022.html#cb46-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">color =</span> species), </span>
<span id="cb46-4"><a href="thursday-september-29-2022.html#cb46-4" aria-hidden="true" tabindex="-1"></a>               <span class="at">width =</span> .<span class="dv">3</span>, <span class="at">show.legend =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb46-5"><a href="thursday-september-29-2022.html#cb46-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">color =</span> species), </span>
<span id="cb46-6"><a href="thursday-september-29-2022.html#cb46-6" aria-hidden="true" tabindex="-1"></a>              <span class="at">alpha =</span> .<span class="dv">5</span>, <span class="at">show.legend =</span> <span class="cn">FALSE</span>, </span>
<span id="cb46-7"><a href="thursday-september-29-2022.html#cb46-7" aria-hidden="true" tabindex="-1"></a>              <span class="at">position =</span> <span class="fu">position_jitter</span>(<span class="at">width =</span> <span class="fl">0.2</span>, <span class="at">seed =</span> <span class="dv">0</span>)) <span class="sc">+</span></span>
<span id="cb46-8"><a href="thursday-september-29-2022.html#cb46-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">&quot;darkorange&quot;</span>,<span class="st">&quot;purple&quot;</span>)) <span class="sc">+</span></span>
<span id="cb46-9"><a href="thursday-september-29-2022.html#cb46-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Species&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Flipper length (mm)&quot;</span>) <span class="sc">+</span></span>
<span id="cb46-10"><a href="thursday-september-29-2022.html#cb46-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<pre><code>## Warning: Removed 1 rows containing non-finite values (stat_boxplot).</code></pre>
<pre><code>## Warning: Removed 1 rows containing missing values (geom_point).</code></pre>
<p><img src="QG-2022_files/figure-html/unnamed-chunk-23-1.png" width="672" /></p>
<p>You see that Adelie penguins have shorter flippers than Chinstrap penguins on average, but there is substantial variability from one individual penguin to another.</p>
<p>Again you start with a lineup of plots where you permute flipper length between the species.</p>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb49-1"><a href="thursday-september-29-2022.html#cb49-1" aria-hidden="true" tabindex="-1"></a>fun <span class="ot">&lt;-</span> nullabor<span class="sc">::</span><span class="fu">null_permute</span>(<span class="st">&quot;species&quot;</span>)</span>
<span id="cb49-2"><a href="thursday-september-29-2022.html#cb49-2" aria-hidden="true" tabindex="-1"></a>inf <span class="ot">&lt;-</span> nullabor<span class="sc">::</span><span class="fu">lineup</span>(fun, penguins, <span class="at">n =</span> <span class="dv">12</span>)</span></code></pre></div>
<pre><code>## decrypt(&quot;CLg7 X161 sO bJws6sJO v5&quot;)</code></pre>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb51-1"><a href="thursday-september-29-2022.html#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> inf, </span>
<span id="cb51-2"><a href="thursday-september-29-2022.html#cb51-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> species, </span>
<span id="cb51-3"><a href="thursday-september-29-2022.html#cb51-3" aria-hidden="true" tabindex="-1"></a>                     <span class="at">color =</span> species, </span>
<span id="cb51-4"><a href="thursday-september-29-2022.html#cb51-4" aria-hidden="true" tabindex="-1"></a>                     <span class="at">y =</span> flipper_length_mm)) <span class="sc">+</span> </span>
<span id="cb51-5"><a href="thursday-september-29-2022.html#cb51-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span> </span>
<span id="cb51-6"><a href="thursday-september-29-2022.html#cb51-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">&quot;darkorange&quot;</span>,<span class="st">&quot;purple&quot;</span>)) <span class="sc">+</span></span>
<span id="cb51-7"><a href="thursday-september-29-2022.html#cb51-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> .sample)</span></code></pre></div>
<pre><code>## Warning: Removed 12 rows containing non-finite values (stat_boxplot).</code></pre>
<p><img src="QG-2022_files/figure-html/unnamed-chunk-24-1.png" width="672" /></p>
<p>What do you anticipate you will conclude when you formalize this with a <span class="math inline">\(t\)</span> test?</p>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="thursday-september-29-2022.html#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(flipper_length_mm <span class="sc">~</span> species, </span>
<span id="cb53-2"><a href="thursday-september-29-2022.html#cb53-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">data =</span> penguins,</span>
<span id="cb53-3"><a href="thursday-september-29-2022.html#cb53-3" aria-hidden="true" tabindex="-1"></a>       <span class="at">var.equal =</span> <span class="cn">TRUE</span>,</span>
<span id="cb53-4"><a href="thursday-september-29-2022.html#cb53-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">alternative =</span> <span class="st">&quot;less&quot;</span>)</span></code></pre></div>
<pre><code>## 
##  Two Sample t-test
## 
## data:  flipper_length_mm by species
## t = -5.974, df = 217, p-value = 4.689e-09
## alternative hypothesis: true difference in means between group Adelie and group Chinstrap is less than 0
## 95 percent confidence interval:
##       -Inf -4.246781
## sample estimates:
##    mean in group Adelie mean in group Chinstrap 
##                189.9536                195.8235</code></pre>
<p>What do you write in your summary and conclusions?</p>
<p>Adelie penguins in the sample have a mean flipper length of 190 mm, which is shorter than the mean flipper length of the Chinstrap penguins by about 6 mm. Given a sample size of 218 penguins this difference provides convincing evidence against the null hypothesis that population mean flipper length is the same (or longer) for the Chinstrap penguins.</p>
<p>In the test above you assumed that the variability among penguins is the same regardless of species (<code>var.equal = TRUE</code>).</p>
<p>You check this assumption by computing the variance by species.</p>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb55-1"><a href="thursday-september-29-2022.html#cb55-1" aria-hidden="true" tabindex="-1"></a>penguins <span class="sc">|&gt;</span></span>
<span id="cb55-2"><a href="thursday-september-29-2022.html#cb55-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">group_by</span>(species) <span class="sc">|&gt;</span></span>
<span id="cb55-3"><a href="thursday-september-29-2022.html#cb55-3" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">summarize</span>(<span class="at">varFL =</span> <span class="fu">var</span>(flipper_length_mm, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span></code></pre></div>
<pre><code>## # A tibble: 2 × 2
##   species   varFL
##   &lt;fct&gt;     &lt;dbl&gt;
## 1 Adelie     42.8
## 2 Chinstrap  50.9</code></pre>
<p>There is less variance in flipper length for the sample of Adelie penguins compared with the variance in flipper length for the sample of Chinstrap penguins. But is this difference significant?</p>
<p>The ratio of the two variances is about .84.</p>
<p>You formally test with the <code>var.test()</code> function under the null hypothesis that the ratio of the two variances is equal to 1.</p>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb57-1"><a href="thursday-september-29-2022.html#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">var.test</span>(flipper_length_mm <span class="sc">~</span> species, </span>
<span id="cb57-2"><a href="thursday-september-29-2022.html#cb57-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">data =</span> penguins)</span></code></pre></div>
<pre><code>## 
##  F test to compare two variances
## 
## data:  flipper_length_mm by species
## F = 0.84076, num df = 150, denom df = 67, p-value = 0.3854
## alternative hypothesis: true ratio of variances is not equal to 1
## 95 percent confidence interval:
##  0.5489336 1.2465576
## sample estimates:
## ratio of variances 
##          0.8407631</code></pre>
<p>The output shows that the ratio of the variances is .8407. Under the null hypothesis that the true ratio is 1 the ratio follows an F distribution with 150 and 67 degrees of freedom which gives a two-sided <span class="math inline">\(p\)</span>-value of .3854. This is why it is sometimes called the ‘F-test’.</p>
<p>Thus you conclude there is no statistical evidence of a difference in the variability in flipper length between the two species.</p>
<p>The uncertainty interval includes the value of 1 and is quite wide.</p>
<p>This variance test is sensitive to small departures from a normal distribution and it is based on the assumption that the groups are independent. It should not be applied in the setting where the data are paired.</p>
<p>The <code>t.test()</code> and <code>var.test()</code> functions are in the {stats} package as part of the base install of R.</p>
<p>The {ctest} package contains all the “classical tests,” and has several alternative tests for variance homogeneity, each with its own assumptions, benefits, and drawbacks.</p>
</div>
<div id="a-non-parameteric-test-for-difference-in-population-means" class="section level2 unnumbered hasAnchor">
<h2>A non-parameteric test for difference in population means<a href="thursday-september-29-2022.html#a-non-parameteric-test-for-difference-in-population-means" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>You can avoid the distributional assumption (assume data have a normal distribution) by using a non-parametric test. The non-parametric alternative is the Wilcoxon test (aka Mann-Whitney U test).</p>
<p>The test statistic ‘W’ is the sum of the ranks in the first group minus the sum of the ranks in the second. It is obtained with the <code>wilcox.test()</code> function.</p>
<p>For example, is there evidence of more or fewer U.S. hurricanes recently? One way to examine this question is to divide the time period into two samples and compare the means from both samples.</p>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb59-1"><a href="thursday-september-29-2022.html#cb59-1" aria-hidden="true" tabindex="-1"></a>loc <span class="ot">&lt;-</span> <span class="st">&quot;http://myweb.fsu.edu/jelsner/temp/data/US.txt&quot;</span></span>
<span id="cb59-2"><a href="thursday-september-29-2022.html#cb59-2" aria-hidden="true" tabindex="-1"></a>LH.df <span class="ot">&lt;-</span> <span class="fu">read.table</span>(loc, </span>
<span id="cb59-3"><a href="thursday-september-29-2022.html#cb59-3" aria-hidden="true" tabindex="-1"></a>                    <span class="at">header =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<p>You consider the first half of the record as separate from the second half and ask is there a difference in hurricane counts between the two halves. The null hypothesis is that the sample means are the same.</p>
<p>First create a vector that divides the record length in two equal parts.</p>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb60-1"><a href="thursday-september-29-2022.html#cb60-1" aria-hidden="true" tabindex="-1"></a>early <span class="ot">&lt;-</span> LH.df<span class="sc">$</span>Year <span class="sc">&lt;=</span> <span class="fu">median</span>(LH.df<span class="sc">$</span>Year)</span>
<span id="cb60-2"><a href="thursday-september-29-2022.html#cb60-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(early); <span class="fu">tail</span>(early)</span></code></pre></div>
<pre><code>## [1] TRUE TRUE TRUE TRUE TRUE TRUE</code></pre>
<pre><code>## [1] FALSE FALSE FALSE FALSE FALSE FALSE</code></pre>
<p>Then use the test on the U.S. hurricane counts where the explanatory variable is the vector early.</p>
<div class="sourceCode" id="cb63"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb63-1"><a href="thursday-september-29-2022.html#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(LH.df<span class="sc">$</span>All <span class="sc">~</span> early)</span></code></pre></div>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  LH.df$All by early
## t = -0.59291, df = 162.53, p-value = 0.5541
## alternative hypothesis: true difference in means between group FALSE and group TRUE is not equal to 0
## 95 percent confidence interval:
##  -0.5739157  0.3088554
## sample estimates:
## mean in group FALSE  mean in group TRUE 
##             1.60241             1.73494</code></pre>
<p>The <span class="math inline">\(p\)</span>-value is large (&gt; .15) so you fail to reject the null hypothesis of no difference in mean number of hurricanes between the earlier and the later periods.</p>
<p>The 95% uncertainty interval is centered the difference in means. Since the interval contains zero, there is no evidence against the null hypothesis.</p>
<p>Since there are 160 years in the record (<code>length(LH.df$All)</code>) you take the first 80 years for the first sample (<code>s1</code>) and the next 80 years for the second sample (<code>s2</code>) and then perform the test. Try it now.</p>
<div class="sourceCode" id="cb65"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb65-1"><a href="thursday-september-29-2022.html#cb65-1" aria-hidden="true" tabindex="-1"></a>s1 <span class="ot">&lt;-</span> LH.df<span class="sc">$</span>All[early]</span>
<span id="cb65-2"><a href="thursday-september-29-2022.html#cb65-2" aria-hidden="true" tabindex="-1"></a>s2 <span class="ot">&lt;-</span> LH.df<span class="sc">$</span>All[<span class="sc">!</span>early]</span></code></pre></div>
<p>Small counts are not described very well by a normal distribution.</p>
<div class="sourceCode" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb66-1"><a href="thursday-september-29-2022.html#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> LH.df, </span>
<span id="cb66-2"><a href="thursday-september-29-2022.html#cb66-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="fu">factor</span>(All))) <span class="sc">+</span> </span>
<span id="cb66-3"><a href="thursday-september-29-2022.html#cb66-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>() <span class="sc">+</span> </span>
<span id="cb66-4"><a href="thursday-september-29-2022.html#cb66-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Number of Years&quot;</span>) <span class="sc">+</span> </span>
<span id="cb66-5"><a href="thursday-september-29-2022.html#cb66-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Number of Hurricanes&quot;</span>)</span></code></pre></div>
<p><img src="QG-2022_files/figure-html/unnamed-chunk-32-1.png" width="672" /></p>
<p>So you use the non-parametric Wilcoxon test instead.</p>
<div class="sourceCode" id="cb67"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb67-1"><a href="thursday-september-29-2022.html#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="fu">wilcox.test</span>(s1, s2)</span></code></pre></div>
<pre><code>## 
##  Wilcoxon rank sum test with continuity correction
## 
## data:  s1 and s2
## W = 3592.5, p-value = 0.6239
## alternative hypothesis: true location shift is not equal to 0</code></pre>
<p>The <span class="math inline">\(p\)</span> value again exceeds .15 so your conclusion is the same. The average number of hurricanes during the second half of the record is statistically indistinguishable from the average number of hurricanes during the first half of the record.</p>
</div>
<div id="paired-observations" class="section level2 unnumbered hasAnchor">
<h2>Paired observations<a href="thursday-september-29-2022.html#paired-observations" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In cases where the observations come in pairs you can ‘control’ for individual variation by doing a paired <span class="math inline">\(t\)</span> test.</p>
<p>Example: A shoe manufacturer makes two different materials (A and B). A sample of 10 kids try <em>both</em> materials. Wear times (in months) are recorded for each material. You want to know if one material is more resistant to wear.</p>
<p>So you test if there is a difference in shoe material wear times. You start by creating a long data frame from the recorded wear times.</p>
<div class="sourceCode" id="cb69"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb69-1"><a href="thursday-september-29-2022.html#cb69-1" aria-hidden="true" tabindex="-1"></a>matA <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">14</span>, <span class="fl">8.8</span>, <span class="fl">11.2</span>, <span class="fl">14.2</span>, <span class="fl">11.8</span>, <span class="fl">6.4</span>, <span class="fl">9.8</span>, <span class="fl">11.3</span>, <span class="fl">9.3</span>, <span class="fl">13.6</span>)</span>
<span id="cb69-2"><a href="thursday-september-29-2022.html#cb69-2" aria-hidden="true" tabindex="-1"></a>matB <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">13.2</span>, <span class="fl">8.2</span>, <span class="fl">10.9</span>, <span class="fl">14.3</span>, <span class="fl">10.7</span>, <span class="fl">6.6</span>, <span class="fl">9.5</span>, <span class="fl">10.8</span>, <span class="fl">8.8</span>, <span class="fl">13.3</span>)</span>
<span id="cb69-3"><a href="thursday-september-29-2022.html#cb69-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-4"><a href="thursday-september-29-2022.html#cb69-4" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Kid =</span> <span class="fu">rep</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>, <span class="dv">2</span>), </span>
<span id="cb69-5"><a href="thursday-september-29-2022.html#cb69-5" aria-hidden="true" tabindex="-1"></a>                 <span class="at">Material =</span> <span class="fu">c</span>(<span class="fu">rep</span>(<span class="st">&quot;A&quot;</span>, <span class="dv">10</span>), <span class="fu">rep</span>(<span class="st">&quot;B&quot;</span>, <span class="dv">10</span>)), </span>
<span id="cb69-6"><a href="thursday-september-29-2022.html#cb69-6" aria-hidden="true" tabindex="-1"></a>                 <span class="at">Wear =</span> <span class="fu">c</span>(matA, matB))</span></code></pre></div>
<p>You then plot the wear times.</p>
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb70-1"><a href="thursday-september-29-2022.html#cb70-1" aria-hidden="true" tabindex="-1"></a>( p <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(df, <span class="fu">aes</span>(<span class="at">x =</span> Material, <span class="at">y =</span> Wear, <span class="at">color =</span> Material)) <span class="sc">+</span></span>
<span id="cb70-2"><a href="thursday-september-29-2022.html#cb70-2" aria-hidden="true" tabindex="-1"></a>         <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb70-3"><a href="thursday-september-29-2022.html#cb70-3" aria-hidden="true" tabindex="-1"></a>         <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb70-4"><a href="thursday-september-29-2022.html#cb70-4" aria-hidden="true" tabindex="-1"></a>         <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">&quot;#1F78B4&quot;</span>, <span class="st">&quot;#A6CEE3&quot;</span>)) )</span></code></pre></div>
<p><img src="QG-2022_files/figure-html/unnamed-chunk-35-1.png" width="672" /></p>
<p>Wear times range from less than 7 months to more than 14 months. But there does not appear to be a significant difference in wear times between material A and B.</p>
<p>On average, material A wears longer than material B (11 months versus 10.6 months) but the difference is small relative to the individual wear times. Thus, as expected when you run a <span class="math inline">\(t\)</span> test on these two samples you find a large <span class="math inline">\(p\)</span>-value.</p>
<div class="sourceCode" id="cb71"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb71-1"><a href="thursday-september-29-2022.html#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(matA, matB,</span>
<span id="cb71-2"><a href="thursday-september-29-2022.html#cb71-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">alternative =</span> <span class="st">&quot;two.sided&quot;</span>)</span></code></pre></div>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  matA and matB
## t = 0.36891, df = 17.987, p-value = 0.7165
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -1.925046  2.745046
## sample estimates:
## mean of x mean of y 
##     11.04     10.63</code></pre>
<p>You add a line layer to the plot where you group the points on the graph by <code>Kid</code>.</p>
<div class="sourceCode" id="cb73"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb73-1"><a href="thursday-september-29-2022.html#cb73-1" aria-hidden="true" tabindex="-1"></a>p <span class="sc">+</span> <span class="fu">geom_line</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">group =</span> Kid), <span class="at">color =</span> <span class="st">&quot;black&quot;</span>)</span></code></pre></div>
<p><img src="QG-2022_files/figure-html/unnamed-chunk-37-1.png" width="672" /></p>
<p>This shows material A wears longer in 8 of the 10 kids (most of the connecting lines slope downward toward material B).</p>
<p>In this case since there is a grouping variable you use the <code>paired = TRUE</code> argument in the <span class="math inline">\(t\)</span> test.</p>
<div class="sourceCode" id="cb74"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb74-1"><a href="thursday-september-29-2022.html#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(matA, matB, </span>
<span id="cb74-2"><a href="thursday-september-29-2022.html#cb74-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">paired =</span> <span class="cn">TRUE</span>,</span>
<span id="cb74-3"><a href="thursday-september-29-2022.html#cb74-3" aria-hidden="true" tabindex="-1"></a>       <span class="at">alternative =</span> <span class="st">&quot;two.sided&quot;</span>)</span></code></pre></div>
<pre><code>## 
##  Paired t-test
## 
## data:  matA and matB
## t = 3.3489, df = 9, p-value = 0.008539
## alternative hypothesis: true mean difference is not equal to 0
## 95 percent confidence interval:
##  0.1330461 0.6869539
## sample estimates:
## mean difference 
##            0.41</code></pre>
<p>Now you find a <span class="math inline">\(p\)</span>-value less than .01 so you conclude there is a significant difference in wear times between the two materials. More precisely you state that there is compelling evidence against the hypothesis of no difference in wear times.</p>
<p>Effectively the paired test is a one-sample test where the hypothesized mean difference is zero. To see this create a new vector as the difference in wear times.</p>
<div class="sourceCode" id="cb76"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb76-1"><a href="thursday-september-29-2022.html#cb76-1" aria-hidden="true" tabindex="-1"></a>( df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(matA, matB) <span class="sc">|&gt;</span></span>
<span id="cb76-2"><a href="thursday-september-29-2022.html#cb76-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">Diff =</span> matA <span class="sc">-</span> matB,</span>
<span id="cb76-3"><a href="thursday-september-29-2022.html#cb76-3" aria-hidden="true" tabindex="-1"></a>                <span class="at">Kid =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>) )</span></code></pre></div>
<pre><code>##    matA matB Diff Kid
## 1  14.0 13.2  0.8   1
## 2   8.8  8.2  0.6   2
## 3  11.2 10.9  0.3   3
## 4  14.2 14.3 -0.1   4
## 5  11.8 10.7  1.1   5
## 6   6.4  6.6 -0.2   6
## 7   9.8  9.5  0.3   7
## 8  11.3 10.8  0.5   8
## 9   9.3  8.8  0.5   9
## 10 13.6 13.3  0.3  10</code></pre>
<p>Then use the one-sample version of the <span class="math inline">\(t\)</span> test with <code>mu = 0</code>.</p>
<div class="sourceCode" id="cb78"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb78-1"><a href="thursday-september-29-2022.html#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(df<span class="sc">$</span>Diff, </span>
<span id="cb78-2"><a href="thursday-september-29-2022.html#cb78-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">mu =</span> <span class="dv">0</span>,</span>
<span id="cb78-3"><a href="thursday-september-29-2022.html#cb78-3" aria-hidden="true" tabindex="-1"></a>       <span class="at">alternative =</span> <span class="st">&quot;two.sided&quot;</span>)</span></code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  df$Diff
## t = 3.3489, df = 9, p-value = 0.008539
## alternative hypothesis: true mean is not equal to 0
## 95 percent confidence interval:
##  0.1330461 0.6869539
## sample estimates:
## mean of x 
##      0.41</code></pre>
<p>Example of how I would proceed in practice: Reaction time while driving.</p>
<p>Cell phone use while driving is believed to increase the chance of an accident due to slowed reaction time. The data set <code>reaction.time</code> in the package {UsingR} gives the time it takes to react to an external event while driving by various groups.</p>
<div class="sourceCode" id="cb80"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb80-1"><a href="thursday-september-29-2022.html#cb80-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> UsingR<span class="sc">::</span>reaction.time</span>
<span id="cb80-2"><a href="thursday-september-29-2022.html#cb80-2" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(df)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    60 obs. of  4 variables:
##  $ age    : Factor w/ 2 levels &quot;16-24&quot;,&quot;25+&quot;: 1 1 1 1 1 1 1 1 1 1 ...
##  $ gender : Factor w/ 2 levels &quot;F&quot;,&quot;M&quot;: 1 2 2 1 2 2 2 1 1 2 ...
##  $ control: Factor w/ 2 levels &quot;C&quot;,&quot;T&quot;: 2 2 2 2 2 1 2 2 2 1 ...
##  $ time   : num  1.36 1.47 1.51 1.39 1.38 ...</code></pre>
<p>The variable <code>time</code> is the reaction time in seconds. This is the response variable (the variable you are interested in). The factor variable <code>control</code> has two groups ‘C’ control (not using cell phone) and ‘T’ (using cell). The observations are not paired. The data set is in the long format.</p>
<p>Suppose I was asked to test the hypothesis that, on average, reaction time is <em>shorter</em> for those not using a cell phone.</p>
<p>Here is my workflow:</p>
<p>I would start by computing the mean for each group (C: control and T: phone user) from the sample of data I have.</p>
<div class="sourceCode" id="cb82"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb82-1"><a href="thursday-september-29-2022.html#cb82-1" aria-hidden="true" tabindex="-1"></a>df <span class="sc">|&gt;</span></span>
<span id="cb82-2"><a href="thursday-september-29-2022.html#cb82-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">group_by</span>(control) <span class="sc">|&gt;</span></span>
<span id="cb82-3"><a href="thursday-september-29-2022.html#cb82-3" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">summarize</span>(<span class="fu">mean</span>(time),</span>
<span id="cb82-4"><a href="thursday-september-29-2022.html#cb82-4" aria-hidden="true" tabindex="-1"></a>                   <span class="fu">sd</span>(time))</span></code></pre></div>
<pre><code>## # A tibble: 2 × 3
##   control `mean(time)` `sd(time)`
##   &lt;fct&gt;          &lt;dbl&gt;      &lt;dbl&gt;
## 1 C               1.39     0.100 
## 2 T               1.45     0.0747</code></pre>
<p>I note that the control group has a shorter reaction time than the phone-user group, on average. If this was not the case I would be finished concluding that the sample of data provides no evidence in support of the hypothesis.</p>
<p>Second I note that the difference in means is 6 hundredths of a second. And the standard deviations are of nearly the same magnitude as the difference in means.</p>
<p>Third I plot the response variable (<code>time</code>) conditional on the control variable.</p>
<div class="sourceCode" id="cb84"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb84-1"><a href="thursday-september-29-2022.html#cb84-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> df, </span>
<span id="cb84-2"><a href="thursday-september-29-2022.html#cb84-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> control, <span class="at">y =</span> time)) <span class="sc">+</span></span>
<span id="cb84-3"><a href="thursday-september-29-2022.html#cb84-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb84-4"><a href="thursday-september-29-2022.html#cb84-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb84-5"><a href="thursday-september-29-2022.html#cb84-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_discrete</span>(<span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;No Cell Phone Use&quot;</span>, <span class="st">&quot;Cell Phone Use&quot;</span>)) <span class="sc">+</span></span>
<span id="cb84-6"><a href="thursday-september-29-2022.html#cb84-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;Reaction Time (s)&quot;</span>)</span></code></pre></div>
<p><img src="QG-2022_files/figure-html/unnamed-chunk-43-1.png" width="672" /></p>
<p>Fourth I note the median reaction time for the control group (no cell phone use) is shorter and the interquartile ranges overlap. This tells me a statistical test is needed.</p>
<p>Fifth I note both distributions are approximately symmetric about the median so I am safe to use a <span class="math inline">\(t\)</span> test.</p>
<p>Sixth I note the variability in reaction times for the two groups is about the same.</p>
<p>The null hypothesis is that there is no difference in reaction times. Here the alternative is that the reaction time is <em>shorter</em> for those not using a phone.</p>
<p>I use the model syntax: response ~ explanatory as the first argument in the <code>t.test()</code> function. I include an argument that names the data frame where the columns <code>time</code> and <code>control</code> are located. Here the argument <code>alternative = 'less'</code> is used.</p>
<div class="sourceCode" id="cb85"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb85-1"><a href="thursday-september-29-2022.html#cb85-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(time <span class="sc">~</span> control, </span>
<span id="cb85-2"><a href="thursday-september-29-2022.html#cb85-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">data =</span> df, </span>
<span id="cb85-3"><a href="thursday-september-29-2022.html#cb85-3" aria-hidden="true" tabindex="-1"></a>       <span class="at">var.equal =</span> <span class="cn">TRUE</span>,</span>
<span id="cb85-4"><a href="thursday-september-29-2022.html#cb85-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">alternative =</span> <span class="st">&#39;less&#39;</span>)</span></code></pre></div>
<pre><code>## 
##  Two Sample t-test
## 
## data:  time by control
## t = -2.4329, df = 58, p-value = 0.009041
## alternative hypothesis: true difference in means between group C and group T is less than 0
## 95 percent confidence interval:
##         -Inf -0.01751153
## sample estimates:
## mean in group C mean in group T 
##        1.389613        1.445571</code></pre>
<p>The evidence in support of the null hypothesis that the reaction times are the same in the population is summarized by the <span class="math inline">\(p\)</span>-value. The <span class="math inline">\(p\)</span>-value is .009, so I conclude there is convincing evidence indicating cell phone use slows reaction times.</p>
<p>The adjective ‘convincing’ comes from the following table: <span class="math inline">\(p\)</span>-value as evidence against the null hypothesis.</p>
<pre><code>   less than 0.01: convincing
        0.01-0.05: moderate 
        0.05-0.15: suggestive, but inconclusive
greater than 0.15: no</code></pre>
</div>
<div id="chi-squared-test-for-independence" class="section level2 unnumbered hasAnchor">
<h2>Chi-squared test for independence<a href="thursday-september-29-2022.html#chi-squared-test-for-independence" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>This test is used when you have two categorical variables from a single population. It determines whether there is a significant association between the two variables.</p>
<p>For example, in an election survey, voters might be classified by male or female and voting preference (Democrat, Republican, or Independent). You use a chi-squared test for independence to determine whether sex is related to voting preference.</p>
<p>The test is appropriate when the sampling method is random, the variables under study are each categorical, and the expected frequency count for each cell of the table is at least five.</p>
<p>The hypothesis is:
<span class="math display">\[
\hbox{H}_0: \hbox{Variable A and Variable B are independent}\\
\hbox{H}_A: \hbox{Variable A and Variable B are not independent}
\]</span></p>
<p>The alternative hypothesis is that knowing the level of A can help us predict the level of B. Support for the alternative hypothesis does not imply causality.</p>
<p>The test statistic is a chi-squared random variable defined by <span class="math display">\[
\chi^2 = \sum_{r = 1}^{n_r} \sum_{c = 1}^{n_c} \frac{(O_{r,c} - E_{r,c})^2}{E_{r,c}}
\]</span>
where <span class="math inline">\(O_{r,c}\)</span> is the observed frequency count at level <span class="math inline">\(r\)</span> of variable A and level <span class="math inline">\(c\)</span> of variable B, and <span class="math inline">\(E_{r,c}\)</span> is the corresponding expected frequency count, where <span class="math display">\[
E_{r,c} = \frac{n_r \times n_c}{n}
\]</span> where <span class="math inline">\(n_r\)</span> is the total number of sample observations of variable A and <span class="math inline">\(n_c\)</span> is the total number of sample observations of variable B, and <span class="math inline">\(n\)</span> is the total sample size.</p>
<p>Example: Smoking and exercise</p>
<p>In the data set <code>survey</code> ({MASS} package), the <code>Smoke</code> column records the students smoking habit, while the <code>Exer</code> column records their exercise level. The allowed values in <code>Smoke</code> are “Heavy”, “Regul” (regularly), “Occas” (occasionally) and “Never”. As for <code>Exer</code>, they are “Freq” (frequently), “Some” and “None”.</p>
<p>You tally the students smoking habits against their exercise levels with the <code>table()</code> function.</p>
<div class="sourceCode" id="cb88"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb88-1"><a href="thursday-september-29-2022.html#cb88-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MASS)</span>
<span id="cb88-2"><a href="thursday-september-29-2022.html#cb88-2" aria-hidden="true" tabindex="-1"></a>( SH.tbl <span class="ot">&lt;-</span> <span class="fu">table</span>(survey<span class="sc">$</span>Smoke, survey<span class="sc">$</span>Exer) )</span></code></pre></div>
<pre><code>##        
##         Freq None Some
##   Heavy    7    1    3
##   Never   87   18   84
##   Occas   12    3    4
##   Regul    9    1    7</code></pre>
<p>The result is called a contingency table of the two variables. Values for the level of exercise are in the columns and values for the level of smoking are in the rows.</p>
<p>You test the hypothesis of whether student smoking levels are independent of their exercise level using</p>
<div class="sourceCode" id="cb90"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb90-1"><a href="thursday-september-29-2022.html#cb90-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(SH.tbl)</span></code></pre></div>
<pre><code>## Warning in chisq.test(SH.tbl): Chi-squared approximation may be incorrect</code></pre>
<pre><code>## 
##  Pearson&#39;s Chi-squared test
## 
## data:  SH.tbl
## X-squared = 5.4885, df = 6, p-value = 0.4828</code></pre>
<p>You find a large <span class="math inline">\(p\)</span>-value (greater than .15) and fail to reject the null hypothesis of independence.</p>
<p>The warning message tells us that some of counts are less than 5.</p>
<p>In the case where some of the counts have fewer than five cases it is better to use Fisher’s exact test.</p>
<div class="sourceCode" id="cb93"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb93-1"><a href="thursday-september-29-2022.html#cb93-1" aria-hidden="true" tabindex="-1"></a><span class="fu">fisher.test</span>(SH.tbl)</span></code></pre></div>
<pre><code>## 
##  Fisher&#39;s Exact Test for Count Data
## 
## data:  SH.tbl
## p-value = 0.4138
## alternative hypothesis: two.sided</code></pre>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="tuesday-october-4-2022.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="tuesday-october-4-2022-1.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
