<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Thursday December 1, 2022 | GEO5156: Quantitative Geography</title>
  <meta name="description" content="Thursday December 1, 2022 | GEO5156: Quantitative Geography" />
  <meta name="generator" content="bookdown 0.27 and GitBook 2.6.7" />

  <meta property="og:title" content="Thursday December 1, 2022 | GEO5156: Quantitative Geography" />
  <meta property="og:type" content="book" />
  
  
  <meta name="github-repo" content="jelsner/QG-2022" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Thursday December 1, 2022 | GEO5156: Quantitative Geography" />
  
  
  

<meta name="author" content="James B. Elsner" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="tuesday-november-29-2022.html"/>

<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Quantitative Geography</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html"><i class="fa fa-check"></i>Syllabus</a>
<ul>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#geo5165c-quantitative-geography"><i class="fa fa-check"></i>GEO5165C: Quantitative Geography</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#contact-information"><i class="fa fa-check"></i>Contact information</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#course-description-and-expected-learning-outcomes"><i class="fa fa-check"></i>Course description and expected learning outcomes</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#grades-and-ethics"><i class="fa fa-check"></i>Grades and ethics</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#schedule-subject-to-change-with-notice"><i class="fa fa-check"></i>Schedule (subject to change with notice)</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#deeper-dives"><i class="fa fa-check"></i>Deeper dives</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html"><i class="fa fa-check"></i>Tuesday, August 23, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#what-is-this-course"><i class="fa fa-check"></i>What is this course?</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#where-are-the-materials-for-this-course"><i class="fa fa-check"></i>Where are the materials for this course?</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#get-the-syllabus"><i class="fa fa-check"></i>Get the syllabus</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#getting-setup"><i class="fa fa-check"></i>Getting setup</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#getting-to-know-rstudios-integrated-development-environment-ide"><i class="fa fa-check"></i>Getting to know RStudio’s integrated development environment (IDE)</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html"><i class="fa fa-check"></i>Thursday, August 25, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#data-science"><i class="fa fa-check"></i>Data science</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#structure-of-markdown-files"><i class="fa fa-check"></i>Structure of markdown files</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#how-to-make-a-plot"><i class="fa fa-check"></i>How to make a plot</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#getting-started-using-r"><i class="fa fa-check"></i>Getting started using R</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html"><i class="fa fa-check"></i>Tuesday, August 30, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html#graphing-examples"><i class="fa fa-check"></i>Graphing examples</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html#introduction-to-working-with-base-r"><i class="fa fa-check"></i>Introduction to working with base R</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html#data-as-vectors"><i class="fa fa-check"></i>Data as vectors</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-september-1-2022.html"><a href="thursday-september-1-2022.html"><i class="fa fa-check"></i>Thursday, September 1, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-september-1-2022.html"><a href="thursday-september-1-2022.html#statistical-summaries-of-data"><i class="fa fa-check"></i>Statistical summaries of data</a></li>
<li class="chapter" data-level="" data-path="thursday-september-1-2022.html"><a href="thursday-september-1-2022.html#structured-data"><i class="fa fa-check"></i>Structured data</a></li>
<li class="chapter" data-level="" data-path="thursday-september-1-2022.html"><a href="thursday-september-1-2022.html#tables"><i class="fa fa-check"></i>Tables</a></li>
<li class="chapter" data-level="" data-path="thursday-september-1-2022.html"><a href="thursday-september-1-2022.html#assignment-1"><i class="fa fa-check"></i>Assignment #1</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-september-6-2022.html"><a href="tuesday-september-6-2022.html"><i class="fa fa-check"></i>Tuesday, September 6, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-september-6-2022.html"><a href="tuesday-september-6-2022.html#getting-data-into-r"><i class="fa fa-check"></i>Getting data into R</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-6-2022.html"><a href="tuesday-september-6-2022.html#data-frames"><i class="fa fa-check"></i>Data frames</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-6-2022.html"><a href="tuesday-september-6-2022.html#piping-your-commands"><i class="fa fa-check"></i>Piping your commands</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-september-8-2022.html"><a href="thursday-september-8-2022.html"><i class="fa fa-check"></i>Thursday, September 8, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-september-8-2022.html"><a href="thursday-september-8-2022.html#data-transformation-with-dplyr"><i class="fa fa-check"></i>Data transformation with {dplyr}</a></li>
<li class="chapter" data-level="" data-path="thursday-september-8-2022.html"><a href="thursday-september-8-2022.html#from-data-import-to-final-plot"><i class="fa fa-check"></i>From data import to final plot</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-september-13-2022.html"><a href="tuesday-september-13-2022.html"><i class="fa fa-check"></i>Tuesday, September 13, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-september-13-2022.html"><a href="tuesday-september-13-2022.html#data-visualization"><i class="fa fa-check"></i>Data visualization</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-september-20-2022.html"><a href="tuesday-september-20-2022.html"><i class="fa fa-check"></i>Tuesday, September 20, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-september-20-2022.html"><a href="tuesday-september-20-2022.html#comparing-distributions"><i class="fa fa-check"></i>Comparing distributions</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-20-2022.html"><a href="tuesday-september-20-2022.html#visualizing-uncertainty"><i class="fa fa-check"></i>Visualizing uncertainty</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-20-2022.html"><a href="tuesday-september-20-2022.html#simple-feature-data-frames"><i class="fa fa-check"></i>Simple feature data frames</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-20-2022.html"><a href="tuesday-september-20-2022.html#making-a-boundary-map"><i class="fa fa-check"></i>Making a boundary map</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-september-22-2022.html"><a href="thursday-september-22-2022.html"><i class="fa fa-check"></i>Thursday, September 22, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-september-22-2022.html"><a href="thursday-september-22-2022.html#adding-data-to-boundary-maps"><i class="fa fa-check"></i>Adding data to boundary maps</a></li>
<li class="chapter" data-level="" data-path="thursday-september-22-2022.html"><a href="thursday-september-22-2022.html#changing-projections"><i class="fa fa-check"></i>Changing projections</a></li>
<li class="chapter" data-level="" data-path="thursday-september-22-2022.html"><a href="thursday-september-22-2022.html#mapping-using-functions-from-tmap"><i class="fa fa-check"></i>Mapping using functions from tmap</a></li>
<li class="chapter" data-level="" data-path="thursday-september-22-2022.html"><a href="thursday-september-22-2022.html#making-an-interactive-map"><i class="fa fa-check"></i>Making an interactive map</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-october-4-2022.html"><a href="tuesday-october-4-2022.html"><i class="fa fa-check"></i>Tuesday, October 4, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-october-4-2022.html"><a href="tuesday-october-4-2022.html#extended-mapping-example-tornado-frequency"><i class="fa fa-check"></i>Extended mapping example: tornado frequency</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-4-2022.html"><a href="tuesday-october-4-2022.html#geo-computation-on-simple-feature-data-frames"><i class="fa fa-check"></i>Geo-computation on simple feature data frames</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-4-2022.html"><a href="tuesday-october-4-2022.html#making-raster-maps"><i class="fa fa-check"></i>Making raster maps</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-4-2022.html"><a href="tuesday-october-4-2022.html#spatial-density-maps"><i class="fa fa-check"></i>Spatial density maps</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-4-2022.html"><a href="tuesday-october-4-2022.html#assignment-3"><i class="fa fa-check"></i>Assignment #3</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-september-29-2022.html"><a href="thursday-september-29-2022.html"><i class="fa fa-check"></i>Thursday, September 29, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-september-29-2022.html"><a href="thursday-september-29-2022.html#one-sample-test-for-the-value-of-the-population-mean"><i class="fa fa-check"></i>One-sample test for the value of the population mean</a></li>
<li class="chapter" data-level="" data-path="thursday-september-29-2022.html"><a href="thursday-september-29-2022.html#graphical-inference"><i class="fa fa-check"></i>Graphical inference</a></li>
<li class="chapter" data-level="" data-path="thursday-september-29-2022.html"><a href="thursday-september-29-2022.html#two-sample-test-for-a-difference-in-population-means"><i class="fa fa-check"></i>Two-sample test for a difference in population means</a></li>
<li class="chapter" data-level="" data-path="thursday-september-29-2022.html"><a href="thursday-september-29-2022.html#a-non-parameteric-test-for-difference-in-population-means"><i class="fa fa-check"></i>A non-parameteric test for difference in population means</a></li>
<li class="chapter" data-level="" data-path="thursday-september-29-2022.html"><a href="thursday-september-29-2022.html#paired-observations"><i class="fa fa-check"></i>Paired observations</a></li>
<li class="chapter" data-level="" data-path="thursday-september-29-2022.html"><a href="thursday-september-29-2022.html#chi-squared-test-for-independence"><i class="fa fa-check"></i>Chi-squared test for independence</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-october-11-2022.html"><a href="tuesday-october-11-2022.html"><i class="fa fa-check"></i>Tuesday, October 11, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-october-11-2022.html"><a href="tuesday-october-11-2022.html#distributions-as-lego-bricks"><i class="fa fa-check"></i>Distributions as Lego bricks</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-11-2022.html"><a href="tuesday-october-11-2022.html#bayesian-computation"><i class="fa fa-check"></i>Bayesian computation</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-11-2022.html"><a href="tuesday-october-11-2022.html#real-world-example"><i class="fa fa-check"></i>Real world example</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-11-2022.html"><a href="tuesday-october-11-2022.html#why-use-bayesian-models"><i class="fa fa-check"></i>Why use Bayesian models?</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-october-13-2022.html"><a href="thursday-october-13-2022.html"><i class="fa fa-check"></i>Thursday, October 13, 2022</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-18-2022.html"><a href="tuesday-october-18-2022.html"><i class="fa fa-check"></i>Tuesday, October 18, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-october-18-2022.html"><a href="tuesday-october-18-2022.html#linear-regression-a-t-test-by-another-name"><i class="fa fa-check"></i>Linear regression: A t test by another name</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-18-2022.html"><a href="tuesday-october-18-2022.html#motivation-for-the-regression-model"><i class="fa fa-check"></i>Motivation for the regression model</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-18-2022.html"><a href="tuesday-october-18-2022.html#making-predictions-with-the-regression-model"><i class="fa fa-check"></i>Making predictions with the regression model</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-18-2022.html"><a href="tuesday-october-18-2022.html#uncertainty-about-the-regression-model-coefficients"><i class="fa fa-check"></i>Uncertainty about the regression model coefficients</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-18-2022.html"><a href="tuesday-october-18-2022.html#bootstrapping-the-uncertainty"><i class="fa fa-check"></i>Bootstrapping the uncertainty</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-october-20-2022.html"><a href="thursday-october-20-2022.html"><i class="fa fa-check"></i>Thursday, October 20, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-october-20-2022.html"><a href="thursday-october-20-2022.html#predictive-uncertainty"><i class="fa fa-check"></i>Predictive uncertainty</a></li>
<li class="chapter" data-level="" data-path="thursday-october-20-2022.html"><a href="thursday-october-20-2022.html#model-adequacy"><i class="fa fa-check"></i>Model adequacy</a></li>
<li class="chapter" data-level="" data-path="thursday-october-20-2022.html"><a href="thursday-october-20-2022.html#regression-examples"><i class="fa fa-check"></i>Regression examples</a></li>
<li class="chapter" data-level="" data-path="thursday-october-20-2022.html"><a href="thursday-october-20-2022.html#outliers"><i class="fa fa-check"></i>Outliers</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-october-25-2022.html"><a href="tuesday-october-25-2022.html"><i class="fa fa-check"></i>Tuesday, October 25, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-october-25-2022.html"><a href="tuesday-october-25-2022.html#simpsons-paradox"><i class="fa fa-check"></i>Simpson’s paradox</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-25-2022.html"><a href="tuesday-october-25-2022.html#multiple-variable-regression"><i class="fa fa-check"></i>Multiple variable regression</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-25-2022.html"><a href="tuesday-october-25-2022.html#fitting-a-multiple-variable-regression-model"><i class="fa fa-check"></i>Fitting a multiple variable regression model</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-25-2022.html"><a href="tuesday-october-25-2022.html#should-you-remove-a-variable-from-your-model"><i class="fa fa-check"></i>Should you remove a variable from your model?</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-25-2022.html"><a href="tuesday-october-25-2022.html#checking-the-model-assumptions"><i class="fa fa-check"></i>Checking the model assumptions</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-25-2022.html"><a href="tuesday-october-25-2022.html#using-the-model-to-make-predictions"><i class="fa fa-check"></i>Using the model to make predictions</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-25-2022.html"><a href="tuesday-october-25-2022.html#collinearity-and-what-to-do-about-it"><i class="fa fa-check"></i>Collinearity and what to do about it</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-25-2022.html"><a href="tuesday-october-25-2022.html#how-to-include-and-interpret-interactions-terms"><i class="fa fa-check"></i>How to include and interpret interactions terms</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-november-1-2022.html"><a href="tuesday-november-1-2022.html"><i class="fa fa-check"></i>Tuesday, November 1, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-november-1-2022.html"><a href="tuesday-november-1-2022.html#removing-variables-from-a-regression-model"><i class="fa fa-check"></i>Removing variables from a regression model</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-1-2022.html"><a href="tuesday-november-1-2022.html#automatic-selection-of-variables"><i class="fa fa-check"></i>Automatic selection of variables</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-1-2022.html"><a href="tuesday-november-1-2022.html#transforming-the-response-variable"><i class="fa fa-check"></i>Transforming the response variable</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-1-2022.html"><a href="tuesday-november-1-2022.html#fitting-a-regression-tree-model"><i class="fa fa-check"></i>Fitting a regression tree model</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-november-8-2022.html"><a href="tuesday-november-8-2022.html"><i class="fa fa-check"></i>Tuesday, November 8, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-november-8-2022.html"><a href="tuesday-november-8-2022.html#predictive-uncertainty-with-regression-trees"><i class="fa fa-check"></i>Predictive uncertainty with regression trees</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-8-2022.html"><a href="tuesday-november-8-2022.html#the-random-forest-algorithm"><i class="fa fa-check"></i>The random forest algorithm</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-8-2022.html"><a href="tuesday-november-8-2022.html#cross-validation"><i class="fa fa-check"></i>Cross validation</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-8-2022.html"><a href="tuesday-november-8-2022.html#classification-trees"><i class="fa fa-check"></i>Classification trees</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-november-15-2022.html"><a href="tuesday-november-15-2022.html"><i class="fa fa-check"></i>Tuesday, November 15, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-november-15-2022.html"><a href="tuesday-november-15-2022.html#binary-outcomes-and-probabilities"><i class="fa fa-check"></i>Binary outcomes and probabilities</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-15-2022.html"><a href="tuesday-november-15-2022.html#logistic-regression"><i class="fa fa-check"></i>Logistic regression</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-november-17-2022.html"><a href="thursday-november-17-2022.html"><i class="fa fa-check"></i>Thursday November 17, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-november-17-2022.html"><a href="thursday-november-17-2022.html#defining-spatial-neighborhoods-and-spatial-weights"><i class="fa fa-check"></i>Defining spatial neighborhoods and spatial weights</a></li>
<li class="chapter" data-level="" data-path="thursday-november-17-2022.html"><a href="thursday-november-17-2022.html#computing-autocorrelation"><i class="fa fa-check"></i>Computing autocorrelation</a></li>
<li class="chapter" data-level="" data-path="thursday-november-17-2022.html"><a href="thursday-november-17-2022.html#spatial-lag-and-its-relation-to-autocorrelation"><i class="fa fa-check"></i>Spatial lag and its relation to autocorrelation</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-november-22-2022.html"><a href="tuesday-november-22-2022.html"><i class="fa fa-check"></i>Tuesday November 22, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-november-22-2022.html"><a href="tuesday-november-22-2022.html#other-neighborhood-definitions"><i class="fa fa-check"></i>Other neighborhood definitions</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-22-2022.html"><a href="tuesday-november-22-2022.html#assessing-the-statistical-significance-of-autocorrelation"><i class="fa fa-check"></i>Assessing the statistical significance of autocorrelation</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-22-2022.html"><a href="tuesday-november-22-2022.html#bivariate-spatial-autocorrelation"><i class="fa fa-check"></i>Bivariate spatial autocorrelation</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-22-2022.html"><a href="tuesday-november-22-2022.html#local-indicators-of-spatial-autocorrelation"><i class="fa fa-check"></i>Local indicators of spatial autocorrelation</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-november-29-2022.html"><a href="tuesday-november-29-2022.html"><i class="fa fa-check"></i>Tuesday November 29, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-november-29-2022.html"><a href="tuesday-november-29-2022.html#estimating-spatial-autocorrelation-in-model-residuals"><i class="fa fa-check"></i>Estimating spatial autocorrelation in model residuals</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-29-2022.html"><a href="tuesday-november-29-2022.html#choosing-a-spatial-regression-model"><i class="fa fa-check"></i>Choosing a spatial regression model</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-29-2022.html"><a href="tuesday-november-29-2022.html#fitting-and-interpreting-spatial-regression-models"><i class="fa fa-check"></i>Fitting and interpreting spatial regression models</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-december-1-2022.html"><a href="thursday-december-1-2022.html"><i class="fa fa-check"></i>Thursday December 1, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-december-1-2022.html"><a href="thursday-december-1-2022.html#fitting-and-interpreting-geographic-regression"><i class="fa fa-check"></i>Fitting and interpreting geographic regression</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">GEO5156: Quantitative Geography</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="thursday-december-1-2022" class="section level1 unnumbered hasAnchor">
<h1>Thursday December 1, 2022<a href="thursday-december-1-2022.html#thursday-december-1-2022" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="fitting-and-interpreting-geographic-regression" class="section level2 unnumbered hasAnchor">
<h2>Fitting and interpreting geographic regression<a href="thursday-december-1-2022.html#fitting-and-interpreting-geographic-regression" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In the last lesson you learned that if the residuals from a linear regression model have significant spatial autocorrelation then inferences made with the model will be suspect.</p>
<p>A common approach to remedy this situation is to modify the linear regression by including a spatial term. The spatial term takes the form of a spatially lagged variable. The spatially lagged variable can be on the response variable or it can be on the residuals or both.</p>
<p>In the absence of domain specific knowledge of what is the best form of the spatial regression model, statistical tests can be used to help you determine the best model.</p>
<p>Another approach is to assume that the <em>relationships</em> between the response variable and the explanatory variables are modified by contextual factors that depend on location. In this case you fit <em>separate</em> regression models at each geographic location.</p>
<p>This approach is quite useful for exploratory analysis (e.g., to show where the explanatory variables are most strongly related to the response variable).</p>
<p>The analogy is local measures of spatial autocorrelation where you estimate an autocorrelation statistic (e.g., Moran’s I) at each location.</p>
<p>The approach is called geographically weighted regression (GWR) or simply geographic regression. GWR is used in epidemiology, particularly for research on infectious diseases and for evaluating health policies and programs.</p>
<p>Since GWR fits a regression model at every observation location, it is not a single model but a procedure for fitting a set of models. This is different from spatial regression. A spatially-lagged Y model, for example, is a single model with spatial terms.</p>
<p>Observations across the domain contribute to the model fit at a particular observation location with nearby observations given more weight than observations farther away.</p>
<p>Weighting is done with a Gaussian function (kernel) defined by a bandwidth. The bandwidth is defined as the distance across the kernel at the inflection points (2nd derivative goes through zero).</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="thursday-december-1-2022.html#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-2"><a href="thursday-december-1-2022.html#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="thursday-december-1-2022.html#cb1-3" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="at">from =</span> <span class="sc">-</span><span class="dv">1</span>, <span class="at">to =</span> <span class="dv">1</span>, <span class="at">by =</span> .<span class="dv">01</span> )</span>
<span id="cb1-4"><a href="thursday-december-1-2022.html#cb1-4" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> extremefit<span class="sc">::</span><span class="fu">Gaussian.kernel</span>(x)</span>
<span id="cb1-5"><a href="thursday-december-1-2022.html#cb1-5" aria-hidden="true" tabindex="-1"></a>dydx <span class="ot">&lt;-</span> DTWBI<span class="sc">::</span><span class="fu">local.derivative.ddtw</span>(y)</span>
<span id="cb1-6"><a href="thursday-december-1-2022.html#cb1-6" aria-hidden="true" tabindex="-1"></a>dy2dx2 <span class="ot">&lt;-</span> DTWBI<span class="sc">::</span><span class="fu">local.derivative.ddtw</span>(dydx)</span>
<span id="cb1-7"><a href="thursday-december-1-2022.html#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="thursday-december-1-2022.html#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>(x, y, dydx, dy2dx2) <span class="sc">|&gt;</span></span>
<span id="cb1-9"><a href="thursday-december-1-2022.html#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> x, <span class="at">y =</span> y)) <span class="sc">+</span></span>
<span id="cb1-10"><a href="thursday-december-1-2022.html#cb1-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb1-11"><a href="thursday-december-1-2022.html#cb1-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_segment</span>(<span class="at">x =</span> <span class="sc">-</span>.<span class="dv">33</span>, <span class="at">y =</span> .<span class="dv">73</span>, </span>
<span id="cb1-12"><a href="thursday-december-1-2022.html#cb1-12" aria-hidden="true" tabindex="-1"></a>               <span class="at">xend =</span> .<span class="dv">33</span>, <span class="at">yend =</span> .<span class="dv">73</span>, </span>
<span id="cb1-13"><a href="thursday-december-1-2022.html#cb1-13" aria-hidden="true" tabindex="-1"></a>               <span class="at">color =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span></span>
<span id="cb1-14"><a href="thursday-december-1-2022.html#cb1-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="QG-2022_files/figure-html/unnamed-chunk-1-1.png" width="672" /></p>
<p>The bandwidth distance is a given fixed value or it is determined through a cross-validation procedure based on the average distance between observation locations. It can also be a function of location.</p>
<p>Linear regression is a model for the conditional mean. The mean of the response variable depends on the explanatory variables. Geographic regressions show how this dependency varies by location.</p>
<p>GWR is used as an exploratory technique for determining where local regression coefficients are different from their corresponding global values.</p>
<p>Returning to the Columbus crime data.</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="thursday-december-1-2022.html#cb2-1" aria-hidden="true" tabindex="-1"></a>( CC.sf <span class="ot">&lt;-</span> sf<span class="sc">::</span><span class="fu">st_read</span>(<span class="at">dsn =</span> here<span class="sc">::</span><span class="fu">here</span>(<span class="st">&quot;data&quot;</span>, <span class="st">&quot;columbus&quot;</span>),</span>
<span id="cb2-2"><a href="thursday-december-1-2022.html#cb2-2" aria-hidden="true" tabindex="-1"></a>                       <span class="at">layer =</span> <span class="st">&quot;columbus&quot;</span>) )</span></code></pre></div>
<pre><code>## Reading layer `columbus&#39; from data source 
##   `/Users/jelsner/Desktop/ClassNotes/QG-2022/data/columbus&#39; using driver `ESRI Shapefile&#39;
## Simple feature collection with 49 features and 20 fields
## Geometry type: POLYGON
## Dimension:     XY
## Bounding box:  xmin: 5.874907 ymin: 10.78863 xmax: 11.28742 ymax: 14.74245
## CRS:           NA</code></pre>
<pre><code>## Simple feature collection with 49 features and 20 fields
## Geometry type: POLYGON
## Dimension:     XY
## Bounding box:  xmin: 5.874907 ymin: 10.78863 xmax: 11.28742 ymax: 14.74245
## CRS:           NA
## First 10 features:
##        AREA PERIMETER COLUMBUS_ COLUMBUS_I POLYID NEIG  HOVAL    INC     CRIME
## 1  0.309441  2.440629         2          5      1    5 80.467 19.531 15.725980
## 2  0.259329  2.236939         3          1      2    1 44.567 21.232 18.801754
## 3  0.192468  2.187547         4          6      3    6 26.350 15.956 30.626781
## 4  0.083841  1.427635         5          2      4    2 33.200  4.477 32.387760
## 5  0.488888  2.997133         6          7      5    7 23.225 11.252 50.731510
## 6  0.283079  2.335634         7          8      6    8 28.750 16.029 26.066658
## 7  0.257084  2.554577         8          4      7    4 75.000  8.438  0.178269
## 8  0.204954  2.139524         9          3      8    3 37.125 11.337 38.425858
## 9  0.500755  3.169707        10         18      9   18 52.600 17.586 30.515917
## 10 0.246689  2.087235        11         10     10   10 96.400 13.598 34.000835
##        OPEN    PLUMB DISCBD     X     Y NSA NSB EW CP THOUS NEIGNO
## 1  2.850747 0.217155   5.03 38.80 44.07   1   1  1  0  1000   1005
## 2  5.296720 0.320581   4.27 35.62 42.38   1   1  0  0  1000   1001
## 3  4.534649 0.374404   3.89 39.82 41.18   1   1  1  0  1000   1006
## 4  0.394427 1.186944   3.70 36.50 40.52   1   1  0  0  1000   1002
## 5  0.405664 0.624596   2.83 40.01 38.00   1   1  1  0  1000   1007
## 6  0.563075 0.254130   3.78 43.75 39.28   1   1  1  0  1000   1008
## 7  0.000000 2.402402   2.74 33.36 38.41   1   1  0  0  1000   1004
## 8  3.483478 2.739726   2.89 36.71 38.71   1   1  0  0  1000   1003
## 9  0.527488 0.890736   3.17 43.44 35.92   1   1  1  0  1000   1018
## 10 1.548348 0.557724   4.33 47.61 36.42   1   1  1  0  1000   1010
##                          geometry
## 1  POLYGON ((8.624129 14.23698...
## 2  POLYGON ((8.25279 14.23694,...
## 3  POLYGON ((8.653305 14.00809...
## 4  POLYGON ((8.459499 13.82035...
## 5  POLYGON ((8.685274 13.63952...
## 6  POLYGON ((9.401384 13.5504,...
## 7  POLYGON ((8.037741 13.60752...
## 8  POLYGON ((8.247527 13.58651...
## 9  POLYGON ((9.333297 13.27242...
## 10 POLYGON ((10.08251 13.03377...</code></pre>
<p>Start by fitting a ‘global’ linear regression to the crime rates using income and housing values, as you did earlier. First save the model formula as <code>f</code>.</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="thursday-december-1-2022.html#cb5-1" aria-hidden="true" tabindex="-1"></a>f <span class="ot">&lt;-</span> CRIME <span class="sc">~</span> INC <span class="sc">+</span> HOVAL</span>
<span id="cb5-2"><a href="thursday-december-1-2022.html#cb5-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-3"><a href="thursday-december-1-2022.html#cb5-3" aria-hidden="true" tabindex="-1"></a>( model.lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">formula =</span> f,</span>
<span id="cb5-4"><a href="thursday-december-1-2022.html#cb5-4" aria-hidden="true" tabindex="-1"></a>                 <span class="at">data =</span> CC.sf) )</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = f, data = CC.sf)
## 
## Coefficients:
## (Intercept)          INC        HOVAL  
##     68.6190      -1.5973      -0.2739</code></pre>
<p>The coefficients on the two explanatory variables indicate that crime decreases in areas of higher income and higher housing values.</p>
<p>You compare this result to results from geographic regressions. The functions are in the {spgwr} package.</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="thursday-december-1-2022.html#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span>(<span class="sc">!</span><span class="fu">require</span>(spgwr)) <span class="fu">install.packages</span>(<span class="at">pkgs =</span> <span class="st">&quot;spgwr&quot;</span>, <span class="at">repos =</span> <span class="st">&quot;http://cran.us.r-project.org&quot;</span>)</span></code></pre></div>
<pre><code>## Loading required package: spgwr</code></pre>
<pre><code>## Loading required package: sp</code></pre>
<pre><code>## Loading required package: spData</code></pre>
<pre><code>## NOTE: This package does not constitute approval of GWR
## as a method of spatial analysis; see example(gwr)</code></pre>
<p>The <code>sp</code> part of the package name indicates that the functions were developed to work with S4 spatial objects.</p>
<p>The functions allow you to use S3 simple features by specifying the locations as a matrix. Here you extract the centroid from each census tract as a matrix.</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="thursday-december-1-2022.html#cb12-1" aria-hidden="true" tabindex="-1"></a>Locations <span class="ot">&lt;-</span> CC.sf <span class="sc">|&gt;</span></span>
<span id="cb12-2"><a href="thursday-december-1-2022.html#cb12-2" aria-hidden="true" tabindex="-1"></a>  sf<span class="sc">::</span><span class="fu">st_centroid</span>() <span class="sc">|&gt;</span></span>
<span id="cb12-3"><a href="thursday-december-1-2022.html#cb12-3" aria-hidden="true" tabindex="-1"></a>  sf<span class="sc">::</span><span class="fu">st_coordinates</span>()</span></code></pre></div>
<pre><code>## Warning in st_centroid.sf(CC.sf): st_centroid assumes attributes are constant
## over geometries of x</code></pre>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="thursday-december-1-2022.html#cb14-1" aria-hidden="true" tabindex="-1"></a>Locations <span class="sc">|&gt;</span></span>
<span id="cb14-2"><a href="thursday-december-1-2022.html#cb14-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>()</span></code></pre></div>
<pre><code>##          X        Y
## 1 8.827218 14.36908
## 2 8.332658 14.03162
## 3 9.012265 13.81972
## 4 8.460801 13.71696
## 5 9.007982 13.29637
## 6 9.739926 13.47463</code></pre>
<p>These are the X and Y coordinate values specifying the centroid for the first six tracts (out of 49).</p>
<p>To determine the bandwidth for the Gaussian kernel (weighting function) you use the <code>spgwr::gwr.sel()</code> function. You need to specify the arguments, model formula (<code>formula =</code>), the data frame (<code>data =</code>), and the coordinates (<code>coords =</code>) as part of the function call.</p>
<p>The argument <code>coords =</code> is the matrix of coordinates of points representing the spatial locations of the observations. It can be omitted if the data is an S4 spatial data frame from the {sp} package.</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="thursday-december-1-2022.html#cb16-1" aria-hidden="true" tabindex="-1"></a>( bw <span class="ot">&lt;-</span> spgwr<span class="sc">::</span><span class="fu">gwr.sel</span>(<span class="at">formula =</span> f, </span>
<span id="cb16-2"><a href="thursday-december-1-2022.html#cb16-2" aria-hidden="true" tabindex="-1"></a>                       <span class="at">data =</span> CC.sf,</span>
<span id="cb16-3"><a href="thursday-december-1-2022.html#cb16-3" aria-hidden="true" tabindex="-1"></a>                       <span class="at">coords =</span> Locations) )</span></code></pre></div>
<pre><code>## Bandwidth: 2.220031 CV score: 7473.853 
## Bandwidth: 3.588499 CV score: 7479.637 
## Bandwidth: 1.374271 CV score: 7404.175 
## Bandwidth: 0.8515626 CV score: 7389.293 
## Bandwidth: 0.7515898 CV score: 7280.867 
## Bandwidth: 0.4667245 CV score: 6319.861 
## Bandwidth: 0.290668 CV score: 7474.967 
## Bandwidth: 0.5755334 CV score: 6754.626 
## Bandwidth: 0.3994769 CV score: 6197.735 
## Bandwidth: 0.3597549 CV score: 6320.012 
## Bandwidth: 0.4132551 CV score: 6200.674 
## Bandwidth: 0.4028088 CV score: 6196.867 
## Bandwidth: 0.4040147 CV score: 6196.817 
## Bandwidth: 0.4038422 CV score: 6196.816 
## Bandwidth: 0.4038829 CV score: 6196.816 
## Bandwidth: 0.4038015 CV score: 6196.816 
## Bandwidth: 0.4038422 CV score: 6196.816</code></pre>
<pre><code>## [1] 0.4038422</code></pre>
<p>The procedure makes an initial guess at the bandwidth distance and then fits local regression models at each location using weights that decay defined by the kernel and that bandwidth.</p>
<p>The output shows that the first bandwidth chosen was 2.22 in arbitrary distance units. The resulting prediction skill from fitting 49 regression models with that bandwidth is 7474 units.</p>
<p>The resulting CV score is based on cross validation whereby skill is computed at each location when data from that location is not used to fit the regression models.</p>
<p>The procedure continues by increasing the bandwidth distance (to 3.59) and then computing a new CV score after refitting the regression models. Since the new CV score is higher (7480) than the initial CV score (7474), the bandwidth is changed in the other direction (decreasing from 2.22 to 1.37) and the models again are refit.</p>
<p>With that new bandwidth, the CV score is 7404, which is lower than the initial bandwidth so the bandwidth is decreased again. The procedure continues until no additional improvement in the CV score occurs.</p>
<p>The output shows that no additional improvement in score occurs at a bandwidth distance of .404 units, and this single value is assigned to the object you called <code>bw</code>.</p>
<p>Once the bandwidth distance is determined you use the <code>spgwr::gwr()</code> function to fit the regressions using that bandwidth. The arguments are the same as before but now includes the <code>bandwidth =</code> argument where you specify the object <code>bw</code>.</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="thursday-december-1-2022.html#cb19-1" aria-hidden="true" tabindex="-1"></a>models.gwr <span class="ot">&lt;-</span> spgwr<span class="sc">::</span><span class="fu">gwr</span>(<span class="at">formula =</span> f, </span>
<span id="cb19-2"><a href="thursday-december-1-2022.html#cb19-2" aria-hidden="true" tabindex="-1"></a>                         <span class="at">data =</span> CC.sf, </span>
<span id="cb19-3"><a href="thursday-december-1-2022.html#cb19-3" aria-hidden="true" tabindex="-1"></a>                         <span class="at">coords =</span> Locations,</span>
<span id="cb19-4"><a href="thursday-december-1-2022.html#cb19-4" aria-hidden="true" tabindex="-1"></a>                         <span class="at">bandwidth =</span> bw)</span></code></pre></div>
<p>The model and observed data are assigned to a list object with element names listed using the <code>names()</code> function.</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="thursday-december-1-2022.html#cb20-1" aria-hidden="true" tabindex="-1"></a>models.gwr <span class="sc">|&gt;</span></span>
<span id="cb20-2"><a href="thursday-december-1-2022.html#cb20-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">names</span>()</span></code></pre></div>
<pre><code>##  [1] &quot;SDF&quot;       &quot;lhat&quot;      &quot;lm&quot;        &quot;results&quot;   &quot;bandwidth&quot; &quot;adapt&quot;    
##  [7] &quot;hatmatrix&quot; &quot;gweight&quot;   &quot;gTSS&quot;      &quot;this.call&quot; &quot;fp.given&quot;  &quot;timings&quot;</code></pre>
<p>The first element is <code>SDF</code> containing the model output as a S4 spatial data frame.</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="thursday-december-1-2022.html#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(models.gwr<span class="sc">$</span>SDF)</span></code></pre></div>
<pre><code>## [1] &quot;SpatialPointsDataFrame&quot;
## attr(,&quot;package&quot;)
## [1] &quot;sp&quot;</code></pre>
<p>The structure of the spatial data frame is obtained with the <code>str()</code> function and by setting the <code>max.level</code> argument to 2.</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="thursday-december-1-2022.html#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(models.gwr<span class="sc">$</span>SDF, </span>
<span id="cb24-2"><a href="thursday-december-1-2022.html#cb24-2" aria-hidden="true" tabindex="-1"></a>    <span class="at">max.level =</span> <span class="dv">2</span>)</span></code></pre></div>
<pre><code>## Formal class &#39;SpatialPointsDataFrame&#39; [package &quot;sp&quot;] with 5 slots
##   ..@ data       :&#39;data.frame&#39;:  49 obs. of  7 variables:
##   ..@ coords.nrs : num(0) 
##   ..@ coords     : num [1:49, 1:2] 8.83 8.33 9.01 8.46 9.01 ...
##   .. ..- attr(*, &quot;dimnames&quot;)=List of 2
##   ..@ bbox       : num [1:2, 1:2] 6.22 11.01 10.95 14.37
##   .. ..- attr(*, &quot;dimnames&quot;)=List of 2
##   ..@ proj4string:Formal class &#39;CRS&#39; [package &quot;sp&quot;] with 1 slot</code></pre>
<p>Here there are five slots with the first slot labeled <code>@data</code> indicating that it is a data frame. The number of rows and columns in the data frame are listed with the <code>dim()</code> function.</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="thursday-december-1-2022.html#cb26-1" aria-hidden="true" tabindex="-1"></a>models.gwr<span class="sc">$</span>SDF <span class="sc">|&gt;</span></span>
<span id="cb26-2"><a href="thursday-december-1-2022.html#cb26-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">dim</span>()</span></code></pre></div>
<pre><code>## [1] 49  7</code></pre>
<p>There are 49 rows and 7 columns. Each row corresponds to a tract and information about the regressions localized to the tract is given in the columns. Column names are listed with the <code>names()</code> function.</p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="thursday-december-1-2022.html#cb28-1" aria-hidden="true" tabindex="-1"></a>models.gwr<span class="sc">$</span>SDF <span class="sc">|&gt;</span></span>
<span id="cb28-2"><a href="thursday-december-1-2022.html#cb28-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">names</span>()</span></code></pre></div>
<pre><code>## [1] &quot;sum.w&quot;       &quot;(Intercept)&quot; &quot;INC&quot;         &quot;HOVAL&quot;       &quot;gwr.e&quot;      
## [6] &quot;pred&quot;        &quot;localR2&quot;</code></pre>
<p>They include the sum of the weights <code>sum.w</code> (the larger the sum the more often the tract is included in the local regressions–favoring smaller counties and ones farther from the borders of the domain), the three regression coefficients one for each of the explanatory variables (<code>INC</code> and <code>HOVAL</code>) and an intercept term, the residual (<code>gwr.e</code>), the predicted value (<code>pred</code>) and the local goodness-of-fit (<code>localR2</code>).</p>
<p>You create a map displaying where income has the most and least influence on crime by first attaching the income coefficient from the data frame (column labeled <code>INC</code>) to the simple feature data frame since the order of the rows in the <code>SDF</code> matches the order in the simple feature data frame and then using functions from the {ggplot2} package.</p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="thursday-december-1-2022.html#cb30-1" aria-hidden="true" tabindex="-1"></a>CC.sf<span class="sc">$</span>INCcoef <span class="ot">&lt;-</span> models.gwr<span class="sc">$</span>SDF<span class="sc">$</span>INC</span>
<span id="cb30-2"><a href="thursday-december-1-2022.html#cb30-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-3"><a href="thursday-december-1-2022.html#cb30-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(CC.sf) <span class="sc">+</span></span>
<span id="cb30-4"><a href="thursday-december-1-2022.html#cb30-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="fu">aes</span>(<span class="at">fill =</span> INCcoef)) <span class="sc">+</span></span>
<span id="cb30-5"><a href="thursday-december-1-2022.html#cb30-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_viridis_c</span>()</span></code></pre></div>
<p><img src="QG-2022_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
<p>Most tracts have coefficients with values less than zero. Recall the global coefficient is less than zero. But areas in yellow show where the coefficient values are greater than zero indicating a direct relationship between crime and income.</p>
<p>How about the coefficients on housing values?</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="thursday-december-1-2022.html#cb31-1" aria-hidden="true" tabindex="-1"></a>CC.sf<span class="sc">$</span>HOVALcoef <span class="ot">&lt;-</span> models.gwr<span class="sc">$</span>SDF<span class="sc">$</span>HOVAL</span>
<span id="cb31-2"><a href="thursday-december-1-2022.html#cb31-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-3"><a href="thursday-december-1-2022.html#cb31-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(CC.sf) <span class="sc">+</span></span>
<span id="cb31-4"><a href="thursday-december-1-2022.html#cb31-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="fu">aes</span>(<span class="at">fill =</span> HOVALcoef)) <span class="sc">+</span></span>
<span id="cb31-5"><a href="thursday-december-1-2022.html#cb31-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_viridis_c</span>()</span></code></pre></div>
<p><img src="QG-2022_files/figure-html/unnamed-chunk-14-1.png" width="672" /></p>
<p>While the global coefficient is negative indicating crime rates tend to be lower in areas with higher housing values, the opposite is the case over much of city especially on the south side.</p>
<p>You put the vector of GWR predictions into the <code>CC.sf</code> simple feature data frame giving it the column name <code>predGWR</code> and then map the predictions using functions from the {tmap} package.</p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="thursday-december-1-2022.html#cb32-1" aria-hidden="true" tabindex="-1"></a>CC.sf<span class="sc">$</span>predGWR <span class="ot">&lt;-</span> models.gwr<span class="sc">$</span>SDF<span class="sc">$</span>pred</span>
<span id="cb32-2"><a href="thursday-december-1-2022.html#cb32-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-3"><a href="thursday-december-1-2022.html#cb32-3" aria-hidden="true" tabindex="-1"></a>tmap<span class="sc">::</span><span class="fu">tm_shape</span>(CC.sf) <span class="sc">+</span></span>
<span id="cb32-4"><a href="thursday-december-1-2022.html#cb32-4" aria-hidden="true" tabindex="-1"></a>  tmap<span class="sc">::</span><span class="fu">tm_fill</span>(<span class="st">&quot;predGWR&quot;</span>,</span>
<span id="cb32-5"><a href="thursday-december-1-2022.html#cb32-5" aria-hidden="true" tabindex="-1"></a>                <span class="at">title =</span> <span class="st">&quot;Predicted crimes</span><span class="sc">\n</span><span class="st">per 1000&quot;</span>) <span class="sc">+</span></span>
<span id="cb32-6"><a href="thursday-december-1-2022.html#cb32-6" aria-hidden="true" tabindex="-1"></a>  tmap<span class="sc">::</span><span class="fu">tm_layout</span>(<span class="at">legend.outside =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## Warning: Currect projection of shape CC.sf unknown. Long-lat (WGS84) is assumed.</code></pre>
<p><img src="QG-2022_files/figure-html/unnamed-chunk-15-1.png" width="672" /></p>
<p>The geographic regressions capture the spatial pattern of crimes across the city. The spread of predicted values matches the observed spread better than the linear model. The pattern of predicted crime is also smoother than with a global OLS regression.</p>
<p>Where is the relationship between crime and the two explanatory variables the tightest? This is answered by mapping the R squared coefficient for each of the models.</p>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="thursday-december-1-2022.html#cb34-1" aria-hidden="true" tabindex="-1"></a>CC.sf<span class="sc">$</span>localR2 <span class="ot">&lt;-</span> models.gwr<span class="sc">$</span>SDF<span class="sc">$</span>localR2</span>
<span id="cb34-2"><a href="thursday-december-1-2022.html#cb34-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-3"><a href="thursday-december-1-2022.html#cb34-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(CC.sf) <span class="sc">+</span></span>
<span id="cb34-4"><a href="thursday-december-1-2022.html#cb34-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="fu">aes</span>(<span class="at">fill =</span> localR2)) <span class="sc">+</span></span>
<span id="cb34-5"><a href="thursday-december-1-2022.html#cb34-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_viridis_c</span>()</span></code></pre></div>
<p><img src="QG-2022_files/figure-html/unnamed-chunk-16-1.png" width="672" /></p>
<p>Although crime rates are highest in the center, the relationship between crime and income and housing values is largest in tracts across the eastern part of the city.</p>
<p>This type of nuanced exploratory analysis is made possible with GWR.</p>
<p>Also, when fitting a regression model to data that vary spatially you are assuming an underlying stationary process. This means you believe the explanatory variables ‘provoke’ the same response (statistically) across the domain. If this is not the case then it shows up in a map of correlated residuals.</p>
<p>So a way to check the assumption of a stationary process is to use geographic regression. If the coefficients from the geographic regressions match closely the global coefficients then you can assume a stationary process.</p>
<p>That wraps up the material for this semester. I hope you learned a few things and are now comfortable working with data in R. I also hope you sign up for my Applied Spatial Statistics course this spring. You will learn more about spatial statistical analyses and modeling and continue your journey through R’s ecosystem for spatial statistics. The notes for are also on my GitHub site.</p>
<p>Have a wonderful holiday break!</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="tuesday-november-29-2022.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

</body>

</html>
