<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Thursday, October 21, 2022 | GEO5156: Quantitative Geography</title>
  <meta name="description" content="Thursday, October 21, 2022 | GEO5156: Quantitative Geography" />
  <meta name="generator" content="bookdown 0.24 and GitBook 2.6.7" />

  <meta property="og:title" content="Thursday, October 21, 2022 | GEO5156: Quantitative Geography" />
  <meta property="og:type" content="book" />
  
  
  
  <meta name="github-repo" content="jelsner/QG-2022" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Thursday, October 21, 2022 | GEO5156: Quantitative Geography" />
  
  
  

<meta name="author" content="James B. Elsner" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="tuesday-october-19-2022.html"/>

<script src="libs/header-attrs-2.11/header-attrs.js"></script>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Quantitative Geography</a></li>

<li class="divider"></li>
<li><a href="index.html#section"></a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html"><i class="fa fa-check"></i>Syllabus</a>
<ul>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#geo5165c-quantitative-geography"><i class="fa fa-check"></i>GEO5165C: Quantitative Geography</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#contact-information"><i class="fa fa-check"></i>Contact information</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#course-description"><i class="fa fa-check"></i>Course description</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#expected-learning-outcomes"><i class="fa fa-check"></i>Expected learning outcomes</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#materials"><i class="fa fa-check"></i>Materials</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#class-meetings"><i class="fa fa-check"></i>Class meetings</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#grades"><i class="fa fa-check"></i>Grades</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#academic-honor-code"><i class="fa fa-check"></i>Academic honor code</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#students-with-disabilities-act"><i class="fa fa-check"></i>Students With Disabilities Act</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#inclusiveness"><i class="fa fa-check"></i>Inclusiveness</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#more-about-your-instructor"><i class="fa fa-check"></i>More about your instructor</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#syllabus-change-policy"><i class="fa fa-check"></i>Syllabus change policy</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#schedule-subject-to-change-with-notice"><i class="fa fa-check"></i>Schedule (subject to change with notice)</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#other-materials-to-check-out"><i class="fa fa-check"></i>Other materials to check out</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#julia-programming-language"><i class="fa fa-check"></i>Julia programming language</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html"><i class="fa fa-check"></i>Tuesday, August 23, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#today"><i class="fa fa-check"></i>Today</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#what-is-this-course"><i class="fa fa-check"></i>What is this course?</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#where-are-the-materials-for-this-course"><i class="fa fa-check"></i>Where are the materials for this course?</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#join-rstudio-cloud"><i class="fa fa-check"></i>Join RStudio Cloud</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#examples"><i class="fa fa-check"></i>Examples</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#course-syllabus"><i class="fa fa-check"></i>Course Syllabus</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#tallahassee-daily-temperatures"><i class="fa fa-check"></i>Tallahassee daily temperatures</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html"><i class="fa fa-check"></i>Thursday, August 25, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#today-1"><i class="fa fa-check"></i>Today</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#data-analysis"><i class="fa fa-check"></i>Data Analysis</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#reproducibility"><i class="fa fa-check"></i>Reproducibility</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#communication"><i class="fa fa-check"></i>Communication</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#automation"><i class="fa fa-check"></i>Automation</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#the-r-programming-language"><i class="fa fa-check"></i>The R programming language</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#overview-of-this-course"><i class="fa fa-check"></i>Overview of this course</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#work-in-plain-text-using-r-markdown"><i class="fa fa-check"></i>Work in plain text, using R Markdown</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#visualizing-data"><i class="fa fa-check"></i>Visualizing data</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#a-code-template"><i class="fa fa-check"></i>A code template</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#the-code"><i class="fa fa-check"></i>The code</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#a-graphing-workflow"><i class="fa fa-check"></i>A graphing workflow</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#a-graphing-template"><i class="fa fa-check"></i>A graphing template</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#common-problems"><i class="fa fa-check"></i>Common problems</a></li>
<li><a href="thursday-august-25-2022.html#location-of-the-sign">location of the <code>+</code> sign</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#help"><i class="fa fa-check"></i>help</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#things-to-know"><i class="fa fa-check"></i>Things to know</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#everything-has-a-name"><i class="fa fa-check"></i>Everything has a name</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#everything-is-an-object"><i class="fa fa-check"></i>Everything is an object</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#you-do-things-using-functions"><i class="fa fa-check"></i>You do things using functions</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#functions-come-in-packages-libraries"><i class="fa fa-check"></i>Functions come in packages (libraries)</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#your-turn"><i class="fa fa-check"></i>Your turn</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html"><i class="fa fa-check"></i>Tuesday, August 30, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html#today-2"><i class="fa fa-check"></i>Today</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html#scatter-plots"><i class="fa fa-check"></i>Scatter plots</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html#facets"><i class="fa fa-check"></i>Facets</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html#calculations"><i class="fa fa-check"></i>Calculations</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html#functions"><i class="fa fa-check"></i>Functions</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html#syntax-is-important"><i class="fa fa-check"></i>Syntax is important</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html#saving-an-object"><i class="fa fa-check"></i>Saving an object</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html#object-names"><i class="fa fa-check"></i>Object names</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html#entering-data"><i class="fa fa-check"></i>Entering data</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html#applying-a-function"><i class="fa fa-check"></i>Applying a function</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html#averge"><i class="fa fa-check"></i>Averge</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html#data-vectors"><i class="fa fa-check"></i>Data vectors</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html#variance"><i class="fa fa-check"></i>Variance</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html#data-vectors-have-a-type"><i class="fa fa-check"></i>Data vectors have a type</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html#working-smarter"><i class="fa fa-check"></i>Working smarter</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-september-1-2022.html"><a href="thursday-september-1-2022.html"><i class="fa fa-check"></i>Thursday, September 1, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-september-1-2022.html"><a href="thursday-september-1-2022.html#today-3"><i class="fa fa-check"></i>Today</a></li>
<li class="chapter" data-level="" data-path="thursday-september-1-2022.html"><a href="thursday-september-1-2022.html#data-as-vectors"><i class="fa fa-check"></i>Data as vectors</a></li>
<li class="chapter" data-level="" data-path="thursday-september-1-2022.html"><a href="thursday-september-1-2022.html#mean"><i class="fa fa-check"></i>Mean</a></li>
<li class="chapter" data-level="" data-path="thursday-september-1-2022.html"><a href="thursday-september-1-2022.html#variance-1"><i class="fa fa-check"></i>Variance</a></li>
<li class="chapter" data-level="" data-path="thursday-september-1-2022.html"><a href="thursday-september-1-2022.html#median"><i class="fa fa-check"></i>Median</a></li>
<li class="chapter" data-level="" data-path="thursday-september-1-2022.html"><a href="thursday-september-1-2022.html#spread"><i class="fa fa-check"></i>Spread</a></li>
<li class="chapter" data-level="" data-path="thursday-september-1-2022.html"><a href="thursday-september-1-2022.html#vector-types"><i class="fa fa-check"></i>Vector types</a></li>
<li class="chapter" data-level="" data-path="thursday-september-1-2022.html"><a href="thursday-september-1-2022.html#structured-data"><i class="fa fa-check"></i>Structured data</a></li>
<li class="chapter" data-level="" data-path="thursday-september-1-2022.html"><a href="thursday-september-1-2022.html#asking-questions"><i class="fa fa-check"></i>Asking questions</a></li>
<li class="chapter" data-level="" data-path="thursday-september-1-2022.html"><a href="thursday-september-1-2022.html#tables-and-summaries"><i class="fa fa-check"></i>Tables and summaries</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-september-6-2022.html"><a href="tuesday-september-6-2022.html"><i class="fa fa-check"></i>Tuesday, September 6, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-september-6-2022.html"><a href="tuesday-september-6-2022.html#today-4"><i class="fa fa-check"></i>Today</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-6-2022.html"><a href="tuesday-september-6-2022.html#getting-your-data-into-r"><i class="fa fa-check"></i>Getting your data into R</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-6-2022.html"><a href="tuesday-september-6-2022.html#creating-structured-data-files"><i class="fa fa-check"></i>Creating structured data files</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-6-2022.html"><a href="tuesday-september-6-2022.html#data-frames"><i class="fa fa-check"></i>Data frames</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-6-2022.html"><a href="tuesday-september-6-2022.html#quantiles"><i class="fa fa-check"></i>Quantiles</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-6-2022.html"><a href="tuesday-september-6-2022.html#creating-a-data-frame"><i class="fa fa-check"></i>Creating a data frame</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-6-2022.html"><a href="tuesday-september-6-2022.html#pipes"><i class="fa fa-check"></i>Pipes</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-6-2022.html"><a href="tuesday-september-6-2022.html#your-turn-1"><i class="fa fa-check"></i>Your turn</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-september-8-2022.html"><a href="thursday-september-8-2022.html"><i class="fa fa-check"></i>Thursday, September 8, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-september-8-2022.html"><a href="thursday-september-8-2022.html#today-5"><i class="fa fa-check"></i>Today</a></li>
<li class="chapter" data-level="" data-path="thursday-september-8-2022.html"><a href="thursday-september-8-2022.html#pipe-operator"><i class="fa fa-check"></i>Pipe operator</a></li>
<li class="chapter" data-level="" data-path="thursday-september-8-2022.html"><a href="thursday-september-8-2022.html#wrangling-data-frames"><i class="fa fa-check"></i>Wrangling data frames</a></li>
<li class="chapter" data-level="" data-path="thursday-september-8-2022.html"><a href="thursday-september-8-2022.html#selecting-and-filtering"><i class="fa fa-check"></i>Selecting and filtering</a></li>
<li class="chapter" data-level="" data-path="thursday-september-8-2022.html"><a href="thursday-september-8-2022.html#example-palmer-penguins"><i class="fa fa-check"></i>Example: Palmer penguins</a></li>
<li class="chapter" data-level="" data-path="thursday-september-8-2022.html"><a href="thursday-september-8-2022.html#stringing-functions-together"><i class="fa fa-check"></i>Stringing functions together</a></li>
<li class="chapter" data-level="" data-path="thursday-september-8-2022.html"><a href="thursday-september-8-2022.html#summarize"><i class="fa fa-check"></i>Summarize</a></li>
<li class="chapter" data-level="" data-path="thursday-september-8-2022.html"><a href="thursday-september-8-2022.html#grouping"><i class="fa fa-check"></i>Grouping</a></li>
<li class="chapter" data-level="" data-path="thursday-september-8-2022.html"><a href="thursday-september-8-2022.html#your-turn-2"><i class="fa fa-check"></i>Your turn</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-september-12-2022.html"><a href="tuesday-september-12-2022.html"><i class="fa fa-check"></i>Tuesday, September 12, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-september-12-2022.html"><a href="tuesday-september-12-2022.html#today-6"><i class="fa fa-check"></i>Today</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-12-2022.html"><a href="tuesday-september-12-2022.html#example-1-new-york-city-flight-data"><i class="fa fa-check"></i>Example 1: New York City flight data</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-12-2022.html"><a href="tuesday-september-12-2022.html#example-2-daily-weather-data-from-tallahassee"><i class="fa fa-check"></i>Example 2: Daily weather data from Tallahassee</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-12-2022.html"><a href="tuesday-september-12-2022.html#putting-everything-together"><i class="fa fa-check"></i>Putting everything together</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-12-2022.html"><a href="tuesday-september-12-2022.html#example-3-food-consumption-and-co2-emissions"><i class="fa fa-check"></i>Example 3: Food consumption and CO2 emissions</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-12-2022.html"><a href="tuesday-september-12-2022.html#summary"><i class="fa fa-check"></i>Summary</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-september-14-2022.html"><a href="thursday-september-14-2022.html"><i class="fa fa-check"></i>Thursday, September 14, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-september-14-2022.html"><a href="thursday-september-14-2022.html#today-7"><i class="fa fa-check"></i>Today</a></li>
<li class="chapter" data-level="" data-path="thursday-september-14-2022.html"><a href="thursday-september-14-2022.html#bar-chart"><i class="fa fa-check"></i>Bar chart</a></li>
<li class="chapter" data-level="" data-path="thursday-september-14-2022.html"><a href="thursday-september-14-2022.html#pie-preference"><i class="fa fa-check"></i>Pie preference</a></li>
<li class="chapter" data-level="" data-path="thursday-september-14-2022.html"><a href="thursday-september-14-2022.html#histogram"><i class="fa fa-check"></i>Histogram</a></li>
<li class="chapter" data-level="" data-path="thursday-september-14-2022.html"><a href="thursday-september-14-2022.html#density-plot"><i class="fa fa-check"></i>Density plot</a></li>
<li class="chapter" data-level="" data-path="thursday-september-14-2022.html"><a href="thursday-september-14-2022.html#box-plot"><i class="fa fa-check"></i>Box plot</a></li>
<li class="chapter" data-level="" data-path="thursday-september-14-2022.html"><a href="thursday-september-14-2022.html#side-by-side-box-plots"><i class="fa fa-check"></i>Side-by-side box plots</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-september-19-2022.html"><a href="tuesday-september-19-2022.html"><i class="fa fa-check"></i>Tuesday, September 19, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-september-19-2022.html"><a href="tuesday-september-19-2022.html#today-8"><i class="fa fa-check"></i>Today</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-19-2022.html"><a href="tuesday-september-19-2022.html#comparing-distributions"><i class="fa fa-check"></i>Comparing distributions</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-19-2022.html"><a href="tuesday-september-19-2022.html#box-plots"><i class="fa fa-check"></i>Box plots</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-19-2022.html"><a href="tuesday-september-19-2022.html#long-data-frames"><i class="fa fa-check"></i>Long data frames</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-19-2022.html"><a href="tuesday-september-19-2022.html#scatter-plots-1"><i class="fa fa-check"></i>Scatter plots</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-19-2022.html"><a href="tuesday-september-19-2022.html#facets-1"><i class="fa fa-check"></i>Facets</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-19-2022.html"><a href="tuesday-september-19-2022.html#example-palmer-penguins-1"><i class="fa fa-check"></i>Example: Palmer penguins</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-19-2022.html"><a href="tuesday-september-19-2022.html#an-expository-graph"><i class="fa fa-check"></i>An expository graph</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-19-2022.html"><a href="tuesday-september-19-2022.html#exporting-your-graph"><i class="fa fa-check"></i>Exporting your graph</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-september-21-2022.html"><a href="thursday-september-21-2022.html"><i class="fa fa-check"></i>Thursday, September 21, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-september-21-2022.html"><a href="thursday-september-21-2022.html#today-9"><i class="fa fa-check"></i>Today</a></li>
<li class="chapter" data-level="" data-path="thursday-september-21-2022.html"><a href="thursday-september-21-2022.html#simple-feature-data-frames"><i class="fa fa-check"></i>Simple feature data frames</a></li>
<li class="chapter" data-level="" data-path="thursday-september-21-2022.html"><a href="thursday-september-21-2022.html#making-a-boundary-map"><i class="fa fa-check"></i>Making a boundary map</a></li>
<li class="chapter" data-level="" data-path="thursday-september-21-2022.html"><a href="thursday-september-21-2022.html#fills"><i class="fa fa-check"></i>Fills</a></li>
<li class="chapter" data-level="" data-path="thursday-september-21-2022.html"><a href="thursday-september-21-2022.html#adding-data"><i class="fa fa-check"></i>Adding data</a></li>
<li class="chapter" data-level="" data-path="thursday-september-21-2022.html"><a href="thursday-september-21-2022.html#inset-maps"><i class="fa fa-check"></i>Inset maps</a></li>
<li class="chapter" data-level="" data-path="thursday-september-21-2022.html"><a href="thursday-september-21-2022.html#map-projections"><i class="fa fa-check"></i>Map projections</a></li>
<li class="chapter" data-level="" data-path="thursday-september-21-2022.html"><a href="thursday-september-21-2022.html#bivariate-maps"><i class="fa fa-check"></i>Bivariate maps</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-september-21-2022-1.html"><a href="thursday-september-21-2022-1.html"><i class="fa fa-check"></i>Thursday, September 21, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-september-21-2022-1.html"><a href="thursday-september-21-2022-1.html#today-10"><i class="fa fa-check"></i>Today</a></li>
<li class="chapter" data-level="" data-path="thursday-september-21-2022-1.html"><a href="thursday-september-21-2022-1.html#making-maps-using-functions-from-the-tmap-package"><i class="fa fa-check"></i>Making maps using functions from the {tmap} package</a></li>
<li class="chapter" data-level="" data-path="thursday-september-21-2022-1.html"><a href="thursday-september-21-2022-1.html#example-mapping-tornadoes"><i class="fa fa-check"></i>Example: Mapping tornadoes</a></li>
<li class="chapter" data-level="" data-path="thursday-september-21-2022-1.html"><a href="thursday-september-21-2022-1.html#example-mapping-the-frequency-of-tornadoes-by-state"><i class="fa fa-check"></i>Example: Mapping the frequency of tornadoes by state</a></li>
<li class="chapter" data-level="" data-path="thursday-september-21-2022-1.html"><a href="thursday-september-21-2022-1.html#calculations-using-the-geometry-simple-feature-column"><i class="fa fa-check"></i>Calculations using the geometry simple feature column</a></li>
<li class="chapter" data-level="" data-path="thursday-september-21-2022-1.html"><a href="thursday-september-21-2022-1.html#making-raster-maps"><i class="fa fa-check"></i>Making raster maps</a></li>
<li class="chapter" data-level="" data-path="thursday-september-21-2022-1.html"><a href="thursday-september-21-2022-1.html#get-map-images-using-functions-from-the-ggmap-package"><i class="fa fa-check"></i>Get map images using functions from the {ggmap} package</a></li>
<li class="chapter" data-level="" data-path="thursday-september-21-2022-1.html"><a href="thursday-september-21-2022-1.html#add-data-to-the-raster-map"><i class="fa fa-check"></i>Add data to the raster map</a></li>
<li class="chapter" data-level="" data-path="thursday-september-21-2022-1.html"><a href="thursday-september-21-2022-1.html#spatial-density-maps-extra-material"><i class="fa fa-check"></i>Spatial density maps (extra material)</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-september-26-2022.html"><a href="tuesday-september-26-2022.html"><i class="fa fa-check"></i>Tuesday, September 26, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-september-26-2022.html"><a href="tuesday-september-26-2022.html#today-11"><i class="fa fa-check"></i>Today</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-26-2022.html"><a href="tuesday-september-26-2022.html#one-sample-test-of-the-population-mean"><i class="fa fa-check"></i>One-sample test of the population mean</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-26-2022.html"><a href="tuesday-september-26-2022.html#about-p-values"><i class="fa fa-check"></i>About p-values</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-26-2022.html"><a href="tuesday-september-26-2022.html#example-strongest-atlantic-hurricanes"><i class="fa fa-check"></i>Example: Strongest Atlantic hurricanes</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-26-2022.html"><a href="tuesday-september-26-2022.html#graphical-inference"><i class="fa fa-check"></i>Graphical inference</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-26-2022.html"><a href="tuesday-september-26-2022.html#two-sample-test-of-the-difference-in-population-means"><i class="fa fa-check"></i>Two-sample test of the difference in population means</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-26-2022.html"><a href="tuesday-september-26-2022.html#example-hurricanes-in-the-north-atlantic-and-the-eastern-north-pacific"><i class="fa fa-check"></i>Example: hurricanes in the North Atlantic and the eastern North Pacific</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-26-2022.html"><a href="tuesday-september-26-2022.html#example-palmer-penguins-2"><i class="fa fa-check"></i>Example: Palmer penguins</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-26-2022.html"><a href="tuesday-september-26-2022.html#your-turn-3"><i class="fa fa-check"></i>Your turn</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-26-2022.html"><a href="tuesday-september-26-2022.html#test-of-equal-variance"><i class="fa fa-check"></i>Test of equal variance</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-26-2022.html"><a href="tuesday-september-26-2022.html#wilcoxon-mann-whitney-u-non-parameteric-test-of-difference-in-means"><i class="fa fa-check"></i>Wilcoxon (Mann-Whitney U) non-parameteric test of difference in means</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-september-28-2022.html"><a href="thursday-september-28-2022.html"><i class="fa fa-check"></i>Thursday, September 28, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-september-28-2022.html"><a href="thursday-september-28-2022.html#today-12"><i class="fa fa-check"></i>Today</a></li>
<li class="chapter" data-level="" data-path="thursday-september-28-2022.html"><a href="thursday-september-28-2022.html#review"><i class="fa fa-check"></i>Review</a></li>
<li class="chapter" data-level="" data-path="thursday-september-28-2022.html"><a href="thursday-september-28-2022.html#paired-observations"><i class="fa fa-check"></i>Paired observations</a></li>
<li class="chapter" data-level="" data-path="thursday-september-28-2022.html"><a href="thursday-september-28-2022.html#example-reaction-time-while-driving"><i class="fa fa-check"></i>Example: Reaction time while driving</a></li>
<li class="chapter" data-level="" data-path="thursday-september-28-2022.html"><a href="thursday-september-28-2022.html#chi-squared-test-for-independence"><i class="fa fa-check"></i>Chi-squared test for independence</a></li>
<li class="chapter" data-level="" data-path="thursday-september-28-2022.html"><a href="thursday-september-28-2022.html#example-smoking-and-exercise"><i class="fa fa-check"></i>Example: Smoking and exercise</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-october-3-2022.html"><a href="tuesday-october-3-2022.html"><i class="fa fa-check"></i>Tuesday, October 3, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-october-3-2022.html"><a href="tuesday-october-3-2022.html#today-13"><i class="fa fa-check"></i>Today</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-3-2022.html"><a href="tuesday-october-3-2022.html#distributions"><i class="fa fa-check"></i>Distributions</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-3-2022.html"><a href="tuesday-october-3-2022.html#normal-distribution"><i class="fa fa-check"></i>Normal distribution</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-3-2022.html"><a href="tuesday-october-3-2022.html#uniform-distribution"><i class="fa fa-check"></i>Uniform distribution</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-3-2022.html"><a href="tuesday-october-3-2022.html#how-many-blue-marbles"><i class="fa fa-check"></i>How many blue marbles?</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-3-2022.html"><a href="tuesday-october-3-2022.html#what-percentage-of-the-globe-is-covered-by-water"><i class="fa fa-check"></i>What percentage of the globe is covered by water?</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-3-2022.html"><a href="tuesday-october-3-2022.html#how-many-fish-are-in-the-lake"><i class="fa fa-check"></i>How many fish are in the lake?</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-october-5-2022.html"><a href="thursday-october-5-2022.html"><i class="fa fa-check"></i>Thursday, October 5, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-october-5-2022.html"><a href="thursday-october-5-2022.html#today-14"><i class="fa fa-check"></i>Today</a></li>
<li class="chapter" data-level="" data-path="thursday-october-5-2022.html"><a href="thursday-october-5-2022.html#how-many-fish-are-in-the-lake-1"><i class="fa fa-check"></i>How many fish are in the lake?</a></li>
<li class="chapter" data-level="" data-path="thursday-october-5-2022.html"><a href="thursday-october-5-2022.html#percentage-of-survey-signups"><i class="fa fa-check"></i>Percentage of survey signups</a></li>
<li class="chapter" data-level="" data-path="thursday-october-5-2022.html"><a href="thursday-october-5-2022.html#a-generative-model-for-people-agreeing-to-take-your-survey"><i class="fa fa-check"></i>A generative model for people agreeing to take your survey</a></li>
<li class="chapter" data-level="" data-path="thursday-october-5-2022.html"><a href="thursday-october-5-2022.html#prior-for-the-response-rate"><i class="fa fa-check"></i>Prior for the response rate</a></li>
<li class="chapter" data-level="" data-path="thursday-october-5-2022.html"><a href="thursday-october-5-2022.html#define-the-generative-model-and-simulate-the-data"><i class="fa fa-check"></i>Define the generative model and simulate the data</a></li>
<li class="chapter" data-level="" data-path="thursday-october-5-2022.html"><a href="thursday-october-5-2022.html#prediction"><i class="fa fa-check"></i>Prediction</a></li>
<li class="chapter" data-level="" data-path="thursday-october-5-2022.html"><a href="thursday-october-5-2022.html#approximate-bayesian-computation"><i class="fa fa-check"></i>Approximate Bayesian computation</a></li>
<li class="chapter" data-level="" data-path="thursday-october-5-2022.html"><a href="thursday-october-5-2022.html#what-bayesian-data-analysis-is-not"><i class="fa fa-check"></i>What Bayesian data analysis is not</a></li>
<li class="chapter" data-level="" data-path="thursday-october-5-2022.html"><a href="thursday-october-5-2022.html#comparing-two-hypotheses"><i class="fa fa-check"></i>Comparing two hypotheses</a></li>
<li class="chapter" data-level="" data-path="thursday-october-5-2022.html"><a href="thursday-october-5-2022.html#reaction-times-while-driving"><i class="fa fa-check"></i>Reaction times while driving</a></li>
<li class="chapter" data-level="" data-path="thursday-october-5-2022.html"><a href="thursday-october-5-2022.html#repeat-the-survey-example"><i class="fa fa-check"></i>Repeat the survey example</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-october-12-2022.html"><a href="tuesday-october-12-2022.html"><i class="fa fa-check"></i>Tuesday, October 12, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-october-12-2022.html"><a href="tuesday-october-12-2022.html#today-15"><i class="fa fa-check"></i>Today</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-12-2022.html"><a href="tuesday-october-12-2022.html#linear-regression-a-t-test-by-another-name"><i class="fa fa-check"></i>Linear regression: A t test by another name</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-12-2022.html"><a href="tuesday-october-12-2022.html#motivating-regression"><i class="fa fa-check"></i>Motivating regression</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-12-2022.html"><a href="tuesday-october-12-2022.html#eyeballing-the-regression"><i class="fa fa-check"></i>Eyeballing the regression</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-12-2022.html"><a href="tuesday-october-12-2022.html#example-increasing-heart-rates-with-age"><i class="fa fa-check"></i>Example: Increasing heart rates with age</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-12-2022.html"><a href="tuesday-october-12-2022.html#making-predictions-with-regression"><i class="fa fa-check"></i>Making predictions with regression</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-12-2022.html"><a href="tuesday-october-12-2022.html#uncertainty-about-the-regression-coefficients"><i class="fa fa-check"></i>Uncertainty about the regression coefficients</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-12-2022.html"><a href="tuesday-october-12-2022.html#bootstrapping-the-uncertainty"><i class="fa fa-check"></i>Bootstrapping the uncertainty</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-12-2022.html"><a href="tuesday-october-12-2022.html#predictive-uncertainty"><i class="fa fa-check"></i>Predictive uncertainty</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-october-14-2022.html"><a href="thursday-october-14-2022.html"><i class="fa fa-check"></i>Thursday, October 14, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-october-14-2022.html"><a href="thursday-october-14-2022.html#today-16"><i class="fa fa-check"></i>Today</a></li>
<li class="chapter" data-level="" data-path="thursday-october-14-2022.html"><a href="thursday-october-14-2022.html#uncertainty-about-a-particular-predicted-value"><i class="fa fa-check"></i>Uncertainty about a particular predicted value</a></li>
<li class="chapter" data-level="" data-path="thursday-october-14-2022.html"><a href="thursday-october-14-2022.html#example-predicting-body-mass-from-fipper-length"><i class="fa fa-check"></i>Example: Predicting body mass from fipper length</a></li>
<li class="chapter" data-level="" data-path="thursday-october-14-2022.html"><a href="thursday-october-14-2022.html#model-adequacy"><i class="fa fa-check"></i>Model Adequacy</a></li>
<li class="chapter" data-level="" data-path="thursday-october-14-2022.html"><a href="thursday-october-14-2022.html#transforming-the-response-variable"><i class="fa fa-check"></i>Transforming the response variable</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-october-19-2022.html"><a href="tuesday-october-19-2022.html"><i class="fa fa-check"></i>Tuesday, October 19, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-october-19-2022.html"><a href="tuesday-october-19-2022.html#today-17"><i class="fa fa-check"></i>Today</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-19-2022.html"><a href="tuesday-october-19-2022.html#example-average-income-vs-percent-college-graduates-at-the-state-level"><i class="fa fa-check"></i>Example: Average income vs percent college graduates at the state level</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-19-2022.html"><a href="tuesday-october-19-2022.html#outliers"><i class="fa fa-check"></i>Outliers</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-19-2022.html"><a href="tuesday-october-19-2022.html#summarizing"><i class="fa fa-check"></i>Summarizing</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-19-2022.html"><a href="tuesday-october-19-2022.html#example-a-regression-model-for-trend"><i class="fa fa-check"></i>Example: A regression model for trend</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-19-2022.html"><a href="tuesday-october-19-2022.html#simpsons-paradox"><i class="fa fa-check"></i>Simpson’s paradox</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-october-21-2022.html"><a href="thursday-october-21-2022.html"><i class="fa fa-check"></i>Thursday, October 21, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-october-21-2022.html"><a href="thursday-october-21-2022.html#today-18"><i class="fa fa-check"></i>Today</a></li>
<li class="chapter" data-level="" data-path="thursday-october-21-2022.html"><a href="thursday-october-21-2022.html#multiple-variable-linear-regression"><i class="fa fa-check"></i>Multiple variable linear regression</a></li>
<li class="chapter" data-level="" data-path="thursday-october-21-2022.html"><a href="thursday-october-21-2022.html#a-grid-of-scatter-plots"><i class="fa fa-check"></i>A grid of scatter plots</a></li>
<li class="chapter" data-level="" data-path="thursday-october-21-2022.html"><a href="thursday-october-21-2022.html#fit-a-multiple-variable-regression-model"><i class="fa fa-check"></i>Fit a multiple variable regression model</a></li>
<li class="chapter" data-level="" data-path="thursday-october-21-2022.html"><a href="thursday-october-21-2022.html#should-you-remove-a-variable-from-the-model"><i class="fa fa-check"></i>Should you remove a variable from the model?</a></li>
<li class="chapter" data-level="" data-path="thursday-october-21-2022.html"><a href="thursday-october-21-2022.html#checking-on-the-model-assumptions"><i class="fa fa-check"></i>Checking on the model assumptions</a></li>
<li class="chapter" data-level="" data-path="thursday-october-21-2022.html"><a href="thursday-october-21-2022.html#example-predicting-house-prices"><i class="fa fa-check"></i>Example: Predicting house prices</a></li>
<li class="chapter" data-level="" data-path="thursday-october-21-2022.html"><a href="thursday-october-21-2022.html#collinearity"><i class="fa fa-check"></i>Collinearity</a></li>
<li class="chapter" data-level="" data-path="thursday-october-21-2022.html"><a href="thursday-october-21-2022.html#interactions"><i class="fa fa-check"></i>Interactions</a></li>
<li class="chapter" data-level="" data-path="thursday-october-21-2022.html"><a href="thursday-october-21-2022.html#removing-variables-from-the-model"><i class="fa fa-check"></i>Removing variables from the model</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">GEO5156: Quantitative Geography</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="thursday-october-21-2022" class="section level1 unnumbered">
<h1>Thursday, October 21, 2022</h1>
<div id="today-18" class="section level2 unnumbered">
<h2>Today</h2>
<ul>
<li>Multiple variable linear regression</li>
</ul>
</div>
<div id="multiple-variable-linear-regression" class="section level2 unnumbered">
<h2>Multiple variable linear regression</h2>
<p>Multiple variable (multi-variable) linear regression is used to model a dependent variable when there is more than one explanatory variable.</p>
<p>Everything from simple (single explanatory variable) regression carries over to multiple variable linear regression. There is a slope coefficient for each explanatory variable.</p>
<p>Note: You regress the response variable onto the explanatory variables. You do not perform a regression of the variables or regress y AND x or regress y with respect to x. These are ambiguous at best and misleading at worse.</p>
<p>With one explanatory variable the regression model is described with a straight line. With two explanatory variables the regression model is described with a flat surface.</p>
<p>To see this consider a three dimensional scatter plot created with the <code>scatterplot3d()</code> from the {scatterplot3d} package and add the regression plane.</p>
<p>The data comes from the <code>trees</code> data frame. You start with a (simple) linear regression. You regress timber volume (<code>Volume</code>) on tree girth (<code>Girth</code>) and add the model as a line on the scatter plot.</p>
<p>Here I use the <code>plot()</code> method and <code>abline()</code> are base R graphics functions.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="thursday-october-21-2022.html#cb1-1" aria-hidden="true" tabindex="-1"></a>model1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Volume <span class="sc">~</span> Girth, </span>
<span id="cb1-2"><a href="thursday-october-21-2022.html#cb1-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">data =</span> trees)</span>
<span id="cb1-3"><a href="thursday-october-21-2022.html#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(trees<span class="sc">$</span>Volume <span class="sc">~</span> trees<span class="sc">$</span>Girth, <span class="at">pch =</span> <span class="dv">16</span>, </span>
<span id="cb1-4"><a href="thursday-october-21-2022.html#cb1-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">&quot;Tree diameter (in)&quot;</span>, </span>
<span id="cb1-5"><a href="thursday-october-21-2022.html#cb1-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">&quot;Timber volume (cubic ft)&quot;</span>)</span>
<span id="cb1-6"><a href="thursday-october-21-2022.html#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(model1)</span></code></pre></div>
<p><img src="QG-2022_files/figure-html/unnamed-chunk-1-1.png" width="672" /></p>
<p>Next you regress timber volume (<code>Volume</code>) on girth (<code>Girth</code>) and height (<code>Height</code>) and use the <code>scatterplot3d()</code> function to plot the scatter of points. The resulting <code>plane3d()</code> function takes the regression model and adds the surface.</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="thursday-october-21-2022.html#cb2-1" aria-hidden="true" tabindex="-1"></a>model2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Volume <span class="sc">~</span> Girth <span class="sc">+</span> Height, <span class="at">data =</span> trees)</span>
<span id="cb2-2"><a href="thursday-october-21-2022.html#cb2-2" aria-hidden="true" tabindex="-1"></a>s3d <span class="ot">&lt;-</span> scatterplot3d<span class="sc">::</span><span class="fu">scatterplot3d</span>(trees, <span class="at">angle =</span> <span class="dv">55</span>, <span class="at">scale.y =</span> .<span class="dv">7</span>, <span class="at">pch =</span> <span class="dv">16</span>, </span>
<span id="cb2-3"><a href="thursday-october-21-2022.html#cb2-3" aria-hidden="true" tabindex="-1"></a>                                    <span class="at">xlab =</span> <span class="st">&quot;Tree diameter (in)&quot;</span>, </span>
<span id="cb2-4"><a href="thursday-october-21-2022.html#cb2-4" aria-hidden="true" tabindex="-1"></a>                                    <span class="at">zlab =</span> <span class="st">&quot;Timber volume (cubic ft)&quot;</span>,</span>
<span id="cb2-5"><a href="thursday-october-21-2022.html#cb2-5" aria-hidden="true" tabindex="-1"></a>                                    <span class="at">ylab =</span> <span class="st">&quot;Tree height (ft)&quot;</span>)</span>
<span id="cb2-6"><a href="thursday-october-21-2022.html#cb2-6" aria-hidden="true" tabindex="-1"></a>s3d<span class="sc">$</span><span class="fu">plane3d</span>(model2)</span></code></pre></div>
<p><img src="QG-2022_files/figure-html/unnamed-chunk-2-1.png" width="672" /></p>
<p>The graph shows that timber volume increases with tree diameter and tree height.</p>
<p>By changing the view angle (<code>angle =</code>) you can see that some observations are above the surface and some are below.</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="thursday-october-21-2022.html#cb3-1" aria-hidden="true" tabindex="-1"></a>s3d <span class="ot">&lt;-</span> <span class="fu">scatterplot3d</span>(trees, <span class="at">angle =</span> <span class="dv">32</span>, <span class="at">scale.y =</span> .<span class="dv">7</span>, <span class="at">pch =</span> <span class="dv">16</span>, </span>
<span id="cb3-2"><a href="thursday-october-21-2022.html#cb3-2" aria-hidden="true" tabindex="-1"></a>                    <span class="at">xlab =</span> <span class="st">&quot;Tree diameter (in)&quot;</span>, </span>
<span id="cb3-3"><a href="thursday-october-21-2022.html#cb3-3" aria-hidden="true" tabindex="-1"></a>                    <span class="at">zlab =</span> <span class="st">&quot;Timber volume (cubic ft)&quot;</span>,</span>
<span id="cb3-4"><a href="thursday-october-21-2022.html#cb3-4" aria-hidden="true" tabindex="-1"></a>                    <span class="at">ylab =</span> <span class="st">&quot;Tree height (ft)&quot;</span>)</span>
<span id="cb3-5"><a href="thursday-october-21-2022.html#cb3-5" aria-hidden="true" tabindex="-1"></a>s3d<span class="sc">$</span><span class="fu">plane3d</span>(model2)</span></code></pre></div>
<p>The distance along the vertical axis from the observation to the model surface is the residual. So even though there are two explanatory variables there is only one set of residuals as with simple regression.</p>
<p>The multiple linear regression model is given by:
<span class="math display">\[
\hat y = \hat \beta_0 + \hat \beta_1 x_{i1} + \hat \beta_2 x_{i2} + \cdots + \hat \beta_p x_{ip}
\]</span></p>
<p>The explanatory variables are written with a double subscript (there are <span class="math inline">\(p\)</span> of them) to indicate the observation number (1st subscript) and the variable number (2nd subscript).</p>
<p>Each explanatory variable gets a coefficient, so there are <span class="math inline">\(p + 1\)</span> of them (including <span class="math inline">\(\hat \beta_0\)</span>, the y-intercept).</p>
<p>Now for each observation <span class="math inline">\(i\)</span> there is an observed response (<span class="math inline">\(y_i\)</span>) and a predicted response (<span class="math inline">\(\hat y_i\)</span>) and the difference is called the residual.</p>
<p>The residuals are given by the equation
<span class="math display">\[
y_i - \hat y_i = \varepsilon_i
\]</span>
and are assumed to be described by a set of normal distributions each centered on zero and having the same variance (<span class="math inline">\(\sigma^2\)</span>).</p>
</div>
<div id="a-grid-of-scatter-plots" class="section level2 unnumbered">
<h2>A grid of scatter plots</h2>
<p>As with simple linear regression, before you model the data you should make a scatter plot. With more than one explanatory variable you rely on a series of scatter plots.</p>
<p>Consider the data set <code>PetrolConsumption.txt</code> that has gasoline consumption by state for a given year.</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="thursday-october-21-2022.html#cb4-1" aria-hidden="true" tabindex="-1"></a>loc <span class="ot">&lt;-</span> <span class="st">&quot;http://myweb.fsu.edu/jelsner/temp/data/PetrolConsumption.txt&quot;</span></span>
<span id="cb4-2"><a href="thursday-october-21-2022.html#cb4-2" aria-hidden="true" tabindex="-1"></a>PC.df <span class="ot">&lt;-</span> readr<span class="sc">::</span><span class="fu">read_table</span>(loc)</span></code></pre></div>
<pre><code>## 
## ── Column specification ────────────────────────────────────────────────────────
## cols(
##   Petrol.Tax = col_double(),
##   Avg.Inc = col_double(),
##   Pavement = col_double(),
##   Prop.DL = col_double(),
##   Petrol.Consumption = col_double()
## )</code></pre>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="thursday-october-21-2022.html#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(PC.df)</span></code></pre></div>
<pre><code>## # A tibble: 6 × 5
##   Petrol.Tax Avg.Inc Pavement Prop.DL Petrol.Consumption
##        &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;   &lt;dbl&gt;              &lt;dbl&gt;
## 1        9      3571     1976   0.525                541
## 2        9      4092     1250   0.572                524
## 3        9      3865     1586   0.58                 561
## 4        7.5    4870     2351   0.529                414
## 5        8      4399      431   0.544                410
## 6       10      5342     1333   0.571                457</code></pre>
<p>Columns in the data frame include petrol (gas) tax (<code>Petrol.Tax</code>) [cents per gallon], per capita income (<code>Avg.Inc</code>) [$/10], miles of paved highway (<code>Pavement</code>), proportion of drivers (<code>Prop.DL</code>), and consumption of petrol (<code>Petrol.Consumption</code>) [millions of gallons].</p>
<p>First create a panel of scatter plots using all the variables in the data frame with the <code>GGally::ggpairs()</code> function from the {GGally} package.</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="thursday-october-21-2022.html#cb8-1" aria-hidden="true" tabindex="-1"></a>GGally<span class="sc">::</span><span class="fu">ggpairs</span>(PC.df)</span></code></pre></div>
<pre><code>## Registered S3 method overwritten by &#39;GGally&#39;:
##   method from   
##   +.gg   ggplot2</code></pre>
<p><img src="QG-2022_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<p>The plots are arranged in a grid. The rows correspond to the variables as given from left to right in the data frame. The first column in the data set is <code>Petrol.Tax</code> then <code>Avg.Inc</code>, etc.</p>
<p>The plot in row 2, column 1 is shows <code>Avg.Inc</code> on the vertical axis and <code>Petrol.Tax</code> on the horizontal axis. The value in the diagonal panel (row 1, column 2) is the Pearson correlation coefficient between <code>Avg.Inc</code> and <code>Petrol.Tax</code>.</p>
<p>The panel in row 3 column 1 shows <code>Pavement</code> on the vertical axis and <code>Petrol.Tax</code> on the horizontal axis.</p>
<p>You want to quantify how much of the variation in gas consumption at the state level is statistically explained by the variables taxes, income, amount of pavement, and proportional of drivers.</p>
<p>So gas consumption (the variable <code>Petrol.Consumption</code>) is your response variable and you focus on the subset of scatter plots (in row 5) where <code>Petrol.Consumption</code> is on the vertical axis in each plot.</p>
<p>By eye, which of the variables appears to you to be the most (least) related to gas consumption?</p>
<p>The variable with the highest correlation with gas consumption is <code>Prop.DL</code>, the proportion of people with a drivers license. The correlation between these two variables is .7. With more people driving, gas consumption increases.</p>
<p>Gas taxes have an inverse relationship with gas consumption. This is seen in the scatter plot in the lower left corner of the grid and by the negative correlation (-.45) in the upper right corner.</p>
<p>Plots along the diagonal are density plots of each of the variables individually.</p>
<p>Correlations arranged in a matrix like the grid of scatter plots is printed using the <code>cor()</code> function.</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="thursday-october-21-2022.html#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(PC.df)</span></code></pre></div>
<pre><code>##                     Petrol.Tax     Avg.Inc    Pavement    Prop.DL
## Petrol.Tax          1.00000000  0.01266516 -0.52213014 -0.2880372
## Avg.Inc             0.01266516  1.00000000  0.05016279  0.1570701
## Pavement           -0.52213014  0.05016279  1.00000000 -0.0641295
## Prop.DL            -0.28803717  0.15707008 -0.06412950  1.0000000
## Petrol.Consumption -0.45128028 -0.24486207  0.01904194  0.6989654
##                    Petrol.Consumption
## Petrol.Tax                -0.45128028
## Avg.Inc                   -0.24486207
## Pavement                   0.01904194
## Prop.DL                    0.69896542
## Petrol.Consumption         1.00000000</code></pre>
<p>The correlations between the explanatory variables and gas consumption are located in the last column of the matrix under <code>Petrol.Consumption</code>.</p>
<p>From the plots and the correlation matrix you anticipate the proportion of people with drivers licenses to be the most important variable in a regression model and the coefficient on this term will be a positive number.</p>
<p>Further you anticipate that the gas tax will be an important variable but the coefficient on this term will be a negative number.</p>
</div>
<div id="fit-a-multiple-variable-regression-model" class="section level2 unnumbered">
<h2>Fit a multiple variable regression model</h2>
<p>You fit a multiple variable regression model to the gas data using the <code>lm()</code> function. You put the name of the response variable (<code>Petrol.Consumption</code>) to the left of the <code>~</code> and then the names of the explanatory variables to the right. After each variable you include a <code>+</code> sign (except for the last variable).</p>
<p>Here you assign the model to an object called <code>model1</code>.</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="thursday-october-21-2022.html#cb12-1" aria-hidden="true" tabindex="-1"></a>model1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Petrol.Consumption <span class="sc">~</span> Prop.DL <span class="sc">+</span> Pavement <span class="sc">+</span> Avg.Inc <span class="sc">+</span> Petrol.Tax,</span>
<span id="cb12-2"><a href="thursday-october-21-2022.html#cb12-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">data =</span> PC.df)</span>
<span id="cb12-3"><a href="thursday-october-21-2022.html#cb12-3" aria-hidden="true" tabindex="-1"></a>model1</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Petrol.Consumption ~ Prop.DL + Pavement + Avg.Inc + 
##     Petrol.Tax, data = PC.df)
## 
## Coefficients:
## (Intercept)      Prop.DL     Pavement      Avg.Inc   Petrol.Tax  
##   3.773e+02    1.336e+03   -2.426e-03   -6.659e-02   -3.479e+01</code></pre>
<p>You have four explanatory variables so the model has five coefficients. There is a coefficient for the y-intercept (<code>Intercept</code>).</p>
<p>Looking only at the signs on the numbers under the variable names you see that gas consumption <em>increases</em> with the proportion of drivers and <em>decreases</em> with the amount of pavement, average income and gas tax. Why might gas consumption decrease with increasing income?</p>
<p>The model is interpreted as follows:</p>
<p>Average gas consumption [millions of gallons] = 377.3 + 1336 * Prop.DL – 0.0024 * Pavement – 0.06659 * Avg.Inc – 34.79 * Petrol.Tax</p>
<p>The model says that for every 1 percentage point increase in the proportion of drivers (to overall population), the mean gas consumption <em>increases</em> by 1336 million gallons (1.336 billion gallons) assuming <code>Pavement</code>, <code>Avg.Inc</code> and <code>Petrol.Tax</code> are constant.</p>
<p>For every 1 cent/gallon increase in taxes, mean gas consumption <em>decreases</em> by 34.79 million gallons assuming the three other variables are held constant.</p>
<p>The statistically significant variables in the model for explaining gas consumption are identified by looking at the table of coefficients from the <code>summary()</code> function.</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="thursday-october-21-2022.html#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model1)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Petrol.Consumption ~ Prop.DL + Pavement + Avg.Inc + 
##     Petrol.Tax, data = PC.df)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -122.03  -45.57  -10.66   31.53  234.95 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  3.773e+02  1.855e+02   2.033 0.048207 *  
## Prop.DL      1.336e+03  1.923e+02   6.950 1.52e-08 ***
## Pavement    -2.426e-03  3.389e-03  -0.716 0.477999    
## Avg.Inc     -6.659e-02  1.722e-02  -3.867 0.000368 ***
## Petrol.Tax  -3.479e+01  1.297e+01  -2.682 0.010332 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 66.31 on 43 degrees of freedom
## Multiple R-squared:  0.6787, Adjusted R-squared:  0.6488 
## F-statistic: 22.71 on 4 and 43 DF,  p-value: 3.907e-10</code></pre>
<p>You ignore the <code>Intercept</code> term. It represents the value of the response variable where the model line intersects the <span class="math inline">\(y\)</span>-axis.</p>
<p>You see that three of the four coefficients have a <span class="math inline">\(p\)</span>-value at or less than .01. Only the coefficient on the variable <code>Pavement</code> has a <span class="math inline">\(p\)</span>-value greater than .15. Therefore this variable is not significant in explaining the variance in the response variable (the coefficient is not statistically significant from a value of zero).</p>
<p>The null hypothesis is that the variable is NOT important to the model. The <span class="math inline">\(p\)</span>-value on the variable’s coefficient is evidence in support of the null hypothesis. The larger the <span class="math inline">\(p\)</span>-value the more evidence you have that the variable is not important to the model.</p>
<p>In determining which variables are most important in the regression model, the coefficient estimates (effect sizes) cannot be compared directly because they do not have the same units.</p>
<p>Key idea: A regression coefficient has units of the response variable divided by the units of the explanatory variable. But the explanatory variables have different units. For example, <code>Petrol.Tax</code> has units of cents per gallon and <code>Pavement</code> has units of miles.</p>
<p>So instead of comparing the values of the coefficients directly (i.e., instead of looking in the column labeled <code>Estimate</code>) you look at the column labeled <code>t value</code>.</p>
<p>The magnitude of the <span class="math inline">\(t\)</span> values are inter comparable. They are coefficients that have been <em>standardized</em> by dividing by the corresponding standard error. Accordingly, <code>Avg.Inc</code> is more more important than <code>Petrol.Tax</code> even though .0666 is much smaller than 34.79.</p>
<p>Key point: The order of the explanatory variables does not change the magnitude or the sign of the corresponding coefficients.</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="thursday-october-21-2022.html#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(Petrol.Consumption <span class="sc">~</span> Pavement <span class="sc">+</span> Petrol.Tax <span class="sc">+</span> Avg.Inc <span class="sc">+</span> Prop.DL, </span>
<span id="cb16-2"><a href="thursday-october-21-2022.html#cb16-2" aria-hidden="true" tabindex="-1"></a>           <span class="at">data =</span> PC.df))</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Petrol.Consumption ~ Pavement + Petrol.Tax + Avg.Inc + 
##     Prop.DL, data = PC.df)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -122.03  -45.57  -10.66   31.53  234.95 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  3.773e+02  1.855e+02   2.033 0.048207 *  
## Pavement    -2.426e-03  3.389e-03  -0.716 0.477999    
## Petrol.Tax  -3.479e+01  1.297e+01  -2.682 0.010332 *  
## Avg.Inc     -6.659e-02  1.722e-02  -3.867 0.000368 ***
## Prop.DL      1.336e+03  1.923e+02   6.950 1.52e-08 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 66.31 on 43 degrees of freedom
## Multiple R-squared:  0.6787, Adjusted R-squared:  0.6488 
## F-statistic: 22.71 on 4 and 43 DF,  p-value: 3.907e-10</code></pre>
<p>Key point: The model does not change with a linear transformation of the variables. For example, if you multiply <code>Pavement</code> by 20, the coefficient and standard error change accordingly, but not the <span class="math inline">\(t\)</span> value or the corresponding <span class="math inline">\(p\)</span>-value.</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="thursday-october-21-2022.html#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(Petrol.Consumption <span class="sc">~</span> <span class="fu">I</span>(Pavement <span class="sc">*</span> <span class="dv">20</span>) <span class="sc">+</span> Petrol.Tax <span class="sc">+</span> Avg.Inc <span class="sc">+</span> Prop.DL,</span>
<span id="cb18-2"><a href="thursday-october-21-2022.html#cb18-2" aria-hidden="true" tabindex="-1"></a>           <span class="at">data =</span> PC.df))</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Petrol.Consumption ~ I(Pavement * 20) + Petrol.Tax + 
##     Avg.Inc + Prop.DL, data = PC.df)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -122.03  -45.57  -10.66   31.53  234.95 
## 
## Coefficients:
##                    Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)       3.773e+02  1.855e+02   2.033 0.048207 *  
## I(Pavement * 20) -1.213e-04  1.695e-04  -0.716 0.477999    
## Petrol.Tax       -3.479e+01  1.297e+01  -2.682 0.010332 *  
## Avg.Inc          -6.659e-02  1.722e-02  -3.867 0.000368 ***
## Prop.DL           1.336e+03  1.923e+02   6.950 1.52e-08 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 66.31 on 43 degrees of freedom
## Multiple R-squared:  0.6787, Adjusted R-squared:  0.6488 
## F-statistic: 22.71 on 4 and 43 DF,  p-value: 3.907e-10</code></pre>
<p>Side note: Here the multiplication is done inside the function <code>I()</code> to restrict the interpretation of the operator <code>*</code> to multiplication rather than interaction.</p>
<p>The multiple R-squared value is .68 which means the model explains 68% of the variation in gas consumption.</p>
<p>Note that the <span class="math inline">\(p\)</span>-value on the model (given on the last line of the output) is small. The null hypothesis in this case is that none of the variables are important in explaining petrol consumption. You reject this null hypothesis.</p>
</div>
<div id="should-you-remove-a-variable-from-the-model" class="section level2 unnumbered">
<h2>Should you remove a variable from the model?</h2>
<p>A model is said to be simpler if it has fewer explanatory variables.</p>
<p>You try another model without the <code>Pavement</code> variable (the variable that was not significant in the previous model).</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="thursday-october-21-2022.html#cb20-1" aria-hidden="true" tabindex="-1"></a>model2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Petrol.Consumption <span class="sc">~</span> Prop.DL <span class="sc">+</span> Avg.Inc <span class="sc">+</span> Petrol.Tax, </span>
<span id="cb20-2"><a href="thursday-october-21-2022.html#cb20-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">data =</span> PC.df)</span>
<span id="cb20-3"><a href="thursday-october-21-2022.html#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model2)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Petrol.Consumption ~ Prop.DL + Avg.Inc + Petrol.Tax, 
##     data = PC.df)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -110.10  -51.22  -12.89   24.49  238.77 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  307.32790  156.83067   1.960  0.05639 .  
## Prop.DL     1374.76841  183.66954   7.485 2.24e-09 ***
## Avg.Inc       -0.06802    0.01701  -3.999  0.00024 ***
## Petrol.Tax   -29.48381   10.58358  -2.786  0.00785 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 65.94 on 44 degrees of freedom
## Multiple R-squared:  0.6749, Adjusted R-squared:  0.6527 
## F-statistic: 30.44 on 3 and 44 DF,  p-value: 8.235e-11</code></pre>
<p>The remaining explanatory variables are significant. The values are slightly different as the variance in the gas consumption attributed to <code>Pavement</code> is now spread across the remaining variables.</p>
<p>Key point: Removing an explanatory variable changes the coefficient values on the remain variables in the model.</p>
<p>The proportion of the population with licenses is the most important variable. It has the largest <span class="math inline">\(t\)</span> value (in absolute value).</p>
<p>By removing a variable the R-squared statistic DECREASES to .675. This is always the case with a simpler model (fewer explanatory variables). Thus the R-squared statistic should not be used to compare models unless the models have the same number of explanatory variables.</p>
<p>One alternative for comparing models is the adjusted R squared. It is a modification of the R squared that accounts for the number of explanatory variables in the model.</p>
<p>Key point: The adjusted R squared increases only if the new variable improves the model more than would be expected by chance. The adjusted R squared can be negative, and will always be less than or equal to R squared.</p>
<p>To see the importance of the adjusted R squared, first note that <code>Petrol.Tax</code> has the smallest <span class="math inline">\(t\)</span> value. Suppose you remove it. What happens?</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="thursday-october-21-2022.html#cb22-1" aria-hidden="true" tabindex="-1"></a>model3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Petrol.Consumption <span class="sc">~</span> Prop.DL <span class="sc">+</span> Avg.Inc, </span>
<span id="cb22-2"><a href="thursday-october-21-2022.html#cb22-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">data =</span> PC.df)</span>
<span id="cb22-3"><a href="thursday-october-21-2022.html#cb22-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model3)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Petrol.Consumption ~ Prop.DL + Avg.Inc, data = PC.df)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -115.46  -45.93  -13.76   30.12  243.50 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)    7.83709  122.46304   0.064 0.949257    
## Prop.DL     1525.04289  188.29687   8.099 2.47e-10 ***
## Avg.Inc       -0.07092    0.01821  -3.895 0.000323 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 70.72 on 45 degrees of freedom
## Multiple R-squared:  0.6175, Adjusted R-squared:  0.6005 
## F-statistic: 36.33 on 2 and 45 DF,  p-value: 4.064e-10</code></pre>
<p>The adjusted R squared is smaller, so you conclude that this variable should be kept in the model.</p>
<p>Thus you settle on a final model:
Average gas consumption [millions of gallons] = 307.3 + 1375 x Prop.DL - .06802 x Avg.Inc - 29.48 x Petrol.Tax</p>
</div>
<div id="checking-on-the-model-assumptions" class="section level2 unnumbered">
<h2>Checking on the model assumptions</h2>
<p>Next you need to check the model assumptions. Equal variance: You saw how to check this assumption by using the <code>cut()</code> function and creating side-by-side box plots.</p>
<p>Another way is to plot the standardized residuals on the vertical axis and the fitted values along the horizontal axis. Adding a smoothed curve and the y equal zero line makes it easy to see whether there is a pattern to the residuals.</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="thursday-october-21-2022.html#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb24-2"><a href="thursday-october-21-2022.html#cb24-2" aria-hidden="true" tabindex="-1"></a>model2.df <span class="ot">&lt;-</span> <span class="fu">fortify</span>(model2)</span>
<span id="cb24-3"><a href="thursday-october-21-2022.html#cb24-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> model2.df, </span>
<span id="cb24-4"><a href="thursday-october-21-2022.html#cb24-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> .fitted, <span class="at">y =</span> .stdresid)) <span class="sc">+</span></span>
<span id="cb24-5"><a href="thursday-october-21-2022.html#cb24-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb24-6"><a href="thursday-october-21-2022.html#cb24-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>() <span class="sc">+</span></span>
<span id="cb24-7"><a href="thursday-october-21-2022.html#cb24-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>)</span></code></pre></div>
<pre><code>## `geom_smooth()` using method = &#39;loess&#39; and formula &#39;y ~ x&#39;</code></pre>
<p><img src="QG-2022_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
<p>In this case: no pattern in the residuals.</p>
<p>Normality. First you use the <code>sm.density()</code> function.</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="thursday-october-21-2022.html#cb26-1" aria-hidden="true" tabindex="-1"></a>res <span class="ot">&lt;-</span> <span class="fu">residuals</span>(model2)</span>
<span id="cb26-2"><a href="thursday-october-21-2022.html#cb26-2" aria-hidden="true" tabindex="-1"></a>sm<span class="sc">::</span><span class="fu">sm.density</span>(res, <span class="at">xlab =</span> <span class="st">&quot;Model Residuals&quot;</span>, <span class="at">model =</span> <span class="st">&quot;Normal&quot;</span>)</span></code></pre></div>
<p><img src="QG-2022_files/figure-html/unnamed-chunk-14-1.png" width="672" /></p>
<p>You also examine a quantile-normal plot of the residuals.</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="thursday-october-21-2022.html#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qqnorm</span>(model2<span class="sc">$</span>residuals)</span>
<span id="cb27-2"><a href="thursday-october-21-2022.html#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="fu">qqline</span>(model2<span class="sc">$</span>residuals)</span></code></pre></div>
<p><img src="QG-2022_files/figure-html/unnamed-chunk-15-1.png" width="672" /></p>
<p>These plots indicate some evidence against normality and constant variance. The fact that the residuals do not exactly follow a normal distribution decreases the confidence you can place on your inferences (e.g., stating a particular variable is significant in explaining variations in the response variable).</p>
<p>To improve model adequacy you might transform the response variable or use a weighted regression model. We will return to this shortly.</p>
</div>
<div id="example-predicting-house-prices" class="section level2 unnumbered">
<h2>Example: Predicting house prices</h2>
<p>A Realtor can use multiple variable regression to justify a selling price for a house based on a list of features the house has. Here you consider a data file (<code>houseprice.txt</code>) containing a random sample of 107 home sales in Albuquerque, New Mexico during the period February 15 through April 30, 1993 (Albuquerque Board of Realtors, 1993).</p>
<p>Get the data.</p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="thursday-october-21-2022.html#cb28-1" aria-hidden="true" tabindex="-1"></a>url <span class="ot">&lt;-</span> <span class="st">&quot;http://myweb.fsu.edu/jelsner/temp/data/houseprice.txt&quot;</span></span>
<span id="cb28-2"><a href="thursday-october-21-2022.html#cb28-2" aria-hidden="true" tabindex="-1"></a>hp.df <span class="ot">&lt;-</span> readr<span class="sc">::</span><span class="fu">read_table</span>(url)</span></code></pre></div>
<pre><code>## 
## ── Column specification ────────────────────────────────────────────────────────
## cols(
##   price = col_double(),
##   sqft = col_double(),
##   custom = col_double(),
##   corner = col_double(),
##   taxes = col_double()
## )</code></pre>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="thursday-october-21-2022.html#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(hp.df)</span></code></pre></div>
<pre><code>## # A tibble: 6 × 5
##   price  sqft custom corner taxes
##   &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;
## 1  2050  2650      1      0  1639
## 2  2080  2600      1      0  1088
## 3  2150  2664      1      0  1193
## 4  2150  2921      1      0  1635
## 5  1999  2580      1      0  1732
## 6  1900  2580      0      0  1534</code></pre>
<p>The data include:</p>
<ul>
<li><code>price</code>: Selling price in $100s</li>
<li><code>sqft</code>: Square feet of living space</li>
<li><code>custom</code>: Whether the house was built with custom features (1) or not (0)</li>
<li><code>corner</code>: Whether the house sits on a corner lot (1) or not (0)</li>
<li><code>taxes</code>: Annual taxes in $</li>
</ul>
<p>Here you assume that taxes determine price. In some (many?) real estate contexts the causality would work in the opposite direction: selling price affects appraisals and hence taxes.</p>
<p>Use the <code>ggpairs()</code> function from the {GGally} package to get a look at your data.</p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="thursday-october-21-2022.html#cb32-1" aria-hidden="true" tabindex="-1"></a>GGally<span class="sc">::</span><span class="fu">ggpairs</span>(hp.df)</span></code></pre></div>
<p><img src="QG-2022_files/figure-html/unnamed-chunk-17-1.png" width="672" /></p>
<p>As expected selling prices increase with size of the living space and with taxes. Scatter plots are not very informative for binary variables (variables with only two values).</p>
<p>The response variable is selling price (<code>price</code>). You begin with living space (<code>sqft</code>) and whether the house was <code>custom</code> built as the two explanatory variables.</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="thursday-october-21-2022.html#cb33-1" aria-hidden="true" tabindex="-1"></a>model1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(price <span class="sc">~</span> sqft <span class="sc">+</span> custom, </span>
<span id="cb33-2"><a href="thursday-october-21-2022.html#cb33-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">data =</span> hp.df)</span>
<span id="cb33-3"><a href="thursday-october-21-2022.html#cb33-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model1)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = price ~ sqft + custom, data = hp.df)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -1034.29  -105.79    10.53    81.55   648.11 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 143.45904   68.76297   2.086  0.03940 *  
## sqft          0.53696    0.04299  12.489  &lt; 2e-16 ***
## custom      172.20996   54.51139   3.159  0.00207 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 199.3 on 104 degrees of freedom
## Multiple R-squared:  0.7357, Adjusted R-squared:  0.7306 
## F-statistic: 144.8 on 2 and 104 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>The model indicates that for a one square foot increase in living space, selling prices increase by $54 controlling for whether or not it has custom features. You move the decimal place on the coefficient to the right two places because selling price is in 100s of dollars.</p>
<p>The model also indicates that custom-featured houses (indicated with a value of 1 in the variable <code>custom</code>) sell for more by $17,211 on average controlling for living space.</p>
<p>To predict the selling price of a house that has custom features and has 3500 square feet of living space type</p>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="thursday-october-21-2022.html#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(model1, </span>
<span id="cb35-2"><a href="thursday-october-21-2022.html#cb35-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">newdata =</span> <span class="fu">data.frame</span>(<span class="at">sqft =</span> <span class="dv">3500</span>, <span class="at">custom =</span> <span class="dv">1</span>), </span>
<span id="cb35-3"><a href="thursday-october-21-2022.html#cb35-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">interval =</span> <span class="st">&quot;confidence&quot;</span>)</span></code></pre></div>
<pre><code>##        fit      lwr      upr
## 1 2195.045 2057.235 2332.855</code></pre>
<p>The model predicts a selling price of $219.5K with a 95% uncertainty interval between $205.7K and $233.3K.</p>
</div>
<div id="collinearity" class="section level2 unnumbered">
<h2>Collinearity</h2>
<p>With more than one explanatory variable in a regression model you need to consider the possibility that the model coefficients are imprecise (small changes in input can lead to large changes in the model) due to collinearity (multicollinearity). Collinearity is when explanatory variables are highly correlated.</p>
<p>If collinearity exists then your ability to properly interpret the model is compromised.</p>
<p>As an example, consider the data set called <code>fat.txt</code> containing measurements related to body fat from 47 individuals.</p>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="thursday-october-21-2022.html#cb37-1" aria-hidden="true" tabindex="-1"></a>url <span class="ot">&lt;-</span> <span class="st">&quot;http://myweb.fsu.edu/jelsner/temp/data/fat.txt&quot;</span></span>
<span id="cb37-2"><a href="thursday-october-21-2022.html#cb37-2" aria-hidden="true" tabindex="-1"></a>bf.df <span class="ot">&lt;-</span> readr<span class="sc">::</span><span class="fu">read_table</span>(url)</span></code></pre></div>
<pre><code>## 
## ── Column specification ────────────────────────────────────────────────────────
## cols(
##   bodyfat = col_double(),
##   abdomen = col_double(),
##   biceps = col_double(),
##   forearm = col_double(),
##   wrist = col_double()
## )</code></pre>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="thursday-october-21-2022.html#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(bf.df)</span></code></pre></div>
<pre><code>## # A tibble: 6 × 5
##   bodyfat abdomen biceps forearm wrist
##     &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;
## 1    12.6    85.2   32      27.4  17.1
## 2     6.9    83     30.5    28.9  18.2
## 3    24.6    87.9   28.8    25.2  16.6
## 4    10.9    86.4   32.4    29.4  18.2
## 5    27.8   100     32.2    27.7  17.7
## 6    20.6    94.4   35.7    30.6  18.8</code></pre>
<p>The response variable <code>bodyfat</code> is a percentage measured using special equipment. The four explanatory variables are circumferences of different body parts and are easy to measure. So you are interested in a model to predict <code>bodyfat</code> from these easier to measure variables.</p>
<p>As always, you start with a grid of scatter plots.</p>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="thursday-october-21-2022.html#cb41-1" aria-hidden="true" tabindex="-1"></a>GGally<span class="sc">::</span><span class="fu">ggpairs</span>(bf.df)</span></code></pre></div>
<p><img src="QG-2022_files/figure-html/unnamed-chunk-21-1.png" width="672" /></p>
<p>Here <code>abdomen</code> has the strongest linear relationship with <code>bodyfat</code>, but other variables have high direct (positive) correlation. Note the large correlation between the explanatory variables.</p>
<p>Next you regress <code>bodyfat</code> onto the four explanatory variables and summarize the model.</p>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="thursday-october-21-2022.html#cb42-1" aria-hidden="true" tabindex="-1"></a>model1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(bodyfat <span class="sc">~</span> abdomen <span class="sc">+</span> biceps <span class="sc">+</span> forearm <span class="sc">+</span> wrist, </span>
<span id="cb42-2"><a href="thursday-october-21-2022.html#cb42-2" aria-hidden="true" tabindex="-1"></a>            <span class="at">data =</span> bf.df)</span>
<span id="cb42-3"><a href="thursday-october-21-2022.html#cb42-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model1)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = bodyfat ~ abdomen + biceps + forearm + wrist, data = bf.df)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -7.1250 -3.2277  0.0787  3.3325  7.7094 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 11.02650   10.57861   1.042  0.30322    
## abdomen      0.78426    0.06758  11.606  1.1e-14 ***
## biceps      -0.89571    0.31660  -2.829  0.00713 ** 
## forearm      1.45378    0.46132   3.151  0.00299 ** 
## wrist       -4.29502    0.90214  -4.761  2.3e-05 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 4.018 on 42 degrees of freedom
## Multiple R-squared:  0.8173, Adjusted R-squared:  0.7999 
## F-statistic: 46.98 on 4 and 42 DF,  p-value: 5.68e-15</code></pre>
<p>What is wrong here?</p>
<p>The negative coefficient on the variable <code>biceps</code> is opposite of the sign on the correlation between <code>bodyfat</code> and <code>biceps</code>.</p>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="thursday-october-21-2022.html#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(bf.df<span class="sc">$</span>bodyfat, bf.df<span class="sc">$</span>biceps)</span></code></pre></div>
<pre><code>## [1] 0.4720003</code></pre>
<p>This is an indication of collinearity. The problem is that there is a large correlation between <code>abdomen</code> and <code>biceps</code> leading to a model that may not make physical sense.</p>
<p>Key idea: The rule is that when the correlation between two explanatory variables exceeds .6, collinearity can be a problem.</p>
<p>When explanatory variables have large correlation then estimates of the model parameters are not precise. A model with imprecise parameter estimates is not useful. The best way to proceed in this situation is to reduce the set of explanatory variables.</p>
<p>Remove the explanatory variable that makes the least sense from physical arguments. For these data, it is probably best to remove all variables except <code>abdomen</code>.</p>
</div>
<div id="interactions" class="section level2 unnumbered">
<h2>Interactions</h2>
<p>Sometimes the <em>relationship</em> between an explanatory variable and the response variable <em>depends on</em> another explanatory variable. In this case we say there is an interaction between the two explanatory variables.</p>
<p>For instance, the relationship between selling price and living space might depend on whether the house was custom built. To see if the interaction might need to be included in the regression model first make a plot.</p>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="thursday-october-21-2022.html#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> hp.df, </span>
<span id="cb46-2"><a href="thursday-october-21-2022.html#cb46-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">y =</span> price, <span class="at">x =</span> sqft, <span class="at">color =</span> <span class="fu">factor</span>(custom))) <span class="sc">+</span></span>
<span id="cb46-3"><a href="thursday-october-21-2022.html#cb46-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb46-4"><a href="thursday-october-21-2022.html#cb46-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> lm, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb46-5"><a href="thursday-october-21-2022.html#cb46-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Living Space (sq ft)&quot;</span>) <span class="sc">+</span></span>
<span id="cb46-6"><a href="thursday-october-21-2022.html#cb46-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Selling Price ($100)&quot;</span>)</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<p><img src="QG-2022_files/figure-html/unnamed-chunk-24-1.png" width="672" /></p>
<p>Here the conditioning variable must be a factor. You see both regression lines have about the same slope. This implies the relationship between selling price and living space does not depend on whether the house has custom features.</p>
<p>In contrast, whether or not the house is on the corner influences the relationship between selling price and living space.</p>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="thursday-october-21-2022.html#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> hp.df, </span>
<span id="cb48-2"><a href="thursday-october-21-2022.html#cb48-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">y =</span> price, <span class="at">x =</span> sqft, <span class="at">color =</span> <span class="fu">factor</span>(corner))) <span class="sc">+</span></span>
<span id="cb48-3"><a href="thursday-october-21-2022.html#cb48-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb48-4"><a href="thursday-october-21-2022.html#cb48-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> lm, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb48-5"><a href="thursday-october-21-2022.html#cb48-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Living Space (sq ft)&quot;</span>) <span class="sc">+</span></span>
<span id="cb48-6"><a href="thursday-october-21-2022.html#cb48-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Selling Price ($100)&quot;</span>)</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<p><img src="QG-2022_files/figure-html/unnamed-chunk-25-1.png" width="672" /></p>
<p>The slope of the regression line between selling price and house living space is different for corner and non-corner houses. The regression lines have different slopes and cross. This is indicates an interaction between the continuous variable of living space and the categorical variable of corner.</p>
<p>To add an interaction term to the model, you use the <code>:</code> notation. You need to know how the categorical variable is coded to correctly interpret the model [On a corner lot (1), or not (0)]</p>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="thursday-october-21-2022.html#cb50-1" aria-hidden="true" tabindex="-1"></a>model1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(price <span class="sc">~</span> sqft <span class="sc">+</span> corner <span class="sc">+</span> sqft<span class="sc">:</span>corner, </span>
<span id="cb50-2"><a href="thursday-october-21-2022.html#cb50-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">data =</span> hp.df)</span>
<span id="cb50-3"><a href="thursday-october-21-2022.html#cb50-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model1)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = price ~ sqft + corner + sqft:corner, data = hp.df)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -424.73  -87.14    0.13  106.33  658.42 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -149.04760   64.12010  -2.325   0.0221 *  
## sqft           0.75172    0.03701  20.309  &lt; 2e-16 ***
## corner       629.41974  119.09627   5.285 7.07e-07 ***
## sqft:corner   -0.45344    0.06651  -6.818 6.44e-10 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 168.2 on 103 degrees of freedom
## Multiple R-squared:  0.8136, Adjusted R-squared:  0.8082 
## F-statistic: 149.8 on 3 and 103 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Or, you can use the notation <code>*</code> to add both the main effects and the interaction effect to the model. Models with interaction effects should also include the main effects, even if these main effects are not significant.</p>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb52-1"><a href="thursday-october-21-2022.html#cb52-1" aria-hidden="true" tabindex="-1"></a>model1b <span class="ot">&lt;-</span> <span class="fu">lm</span>(price <span class="sc">~</span> sqft <span class="sc">*</span> corner, </span>
<span id="cb52-2"><a href="thursday-october-21-2022.html#cb52-2" aria-hidden="true" tabindex="-1"></a>              <span class="at">data =</span> hp.df)</span>
<span id="cb52-3"><a href="thursday-october-21-2022.html#cb52-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model1b)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = price ~ sqft * corner, data = hp.df)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -424.73  -87.14    0.13  106.33  658.42 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -149.04760   64.12010  -2.325   0.0221 *  
## sqft           0.75172    0.03701  20.309  &lt; 2e-16 ***
## corner       629.41974  119.09627   5.285 7.07e-07 ***
## sqft:corner   -0.45344    0.06651  -6.818 6.44e-10 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 168.2 on 103 degrees of freedom
## Multiple R-squared:  0.8136, Adjusted R-squared:  0.8082 
## F-statistic: 149.8 on 3 and 103 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>The model indicates that for a one square foot increase in living space, selling prices increase by $75 for the non-corner houses. The coefficient for the interaction is -.453 which is the difference in slope between the non-corner and corner houses, i.e., the slope for the corner houses is .752 - .453 = .299 (~$30).</p>
<p>Lastly the coefficient on the corner term of 629 is the difference in the intercepts between non-corner and corner. Or the difference in the y-intercept when living space has a value of zero. The coefficient is significant when living space is zero but this is not realistic. You transform the variables and refit the model.</p>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb54-1"><a href="thursday-october-21-2022.html#cb54-1" aria-hidden="true" tabindex="-1"></a>model1c <span class="ot">&lt;-</span> <span class="fu">lm</span>(price <span class="sc">~</span> <span class="fu">I</span>(sqft <span class="sc">-</span> <span class="fu">mean</span>(sqft)) <span class="sc">+</span> corner <span class="sc">+</span> </span>
<span id="cb54-2"><a href="thursday-october-21-2022.html#cb54-2" aria-hidden="true" tabindex="-1"></a>               <span class="fu">I</span>(sqft <span class="sc">-</span> <span class="fu">mean</span>(sqft))<span class="sc">:</span>corner, </span>
<span id="cb54-3"><a href="thursday-october-21-2022.html#cb54-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">data =</span> hp.df)</span>
<span id="cb54-4"><a href="thursday-october-21-2022.html#cb54-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model1c)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = price ~ I(sqft - mean(sqft)) + corner + I(sqft - 
##     mean(sqft)):corner, data = hp.df)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -424.73  -87.14    0.13  106.33  658.42 
## 
## Coefficients:
##                               Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)                 1104.25833   18.13734  60.883  &lt; 2e-16 ***
## I(sqft - mean(sqft))           0.75172    0.03701  20.309  &lt; 2e-16 ***
## corner                      -126.57787   40.95871  -3.090  0.00257 ** 
## I(sqft - mean(sqft)):corner   -0.45344    0.06651  -6.818 6.44e-10 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 168.2 on 103 degrees of freedom
## Multiple R-squared:  0.8136, Adjusted R-squared:  0.8082 
## F-statistic: 149.8 on 3 and 103 DF,  p-value: &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb56-1"><a href="thursday-october-21-2022.html#cb56-1" aria-hidden="true" tabindex="-1"></a>model1d <span class="ot">&lt;-</span> <span class="fu">lm</span>(price <span class="sc">~</span> <span class="fu">I</span>(sqft <span class="sc">-</span> <span class="dv">1500</span>) <span class="sc">+</span> corner <span class="sc">+</span> <span class="fu">I</span>(sqft <span class="sc">-</span> <span class="dv">1500</span>)<span class="sc">:</span>corner,</span>
<span id="cb56-2"><a href="thursday-october-21-2022.html#cb56-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">data =</span> hp.df)</span>
<span id="cb56-3"><a href="thursday-october-21-2022.html#cb56-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model1d)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = price ~ I(sqft - 1500) + corner + I(sqft - 1500):corner, 
##     data = hp.df)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -424.73  -87.14    0.13  106.33  658.42 
## 
## Coefficients:
##                        Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)           978.52518   19.09682  51.240  &lt; 2e-16 ***
## I(sqft - 1500)          0.75172    0.03701  20.309  &lt; 2e-16 ***
## corner                -50.73529   42.69095  -1.188    0.237    
## I(sqft - 1500):corner  -0.45344    0.06651  -6.818 6.44e-10 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 168.2 on 103 degrees of freedom
## Multiple R-squared:  0.8136, Adjusted R-squared:  0.8082 
## F-statistic: 149.8 on 3 and 103 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>In both cases the intercept difference is negative. In the second case it is insignificant.</p>
<p>When interpreting the results from models with interaction terms, the rule is don’t interpret the coefficients on the main effects (marginal coefficients). As demonstrated the presence of interactions implies that the meaning of coefficients for terms vary depending on the values of the variables.</p>
</div>
<div id="removing-variables-from-the-model" class="section level2 unnumbered">
<h2>Removing variables from the model</h2>
<p>Typically you might begin with a regression model that has many (or all) of your explanatory variables (full model). You then check to see if you can remove some of the variables.</p>
<p>When you have all variables in the model the R squared value is maximized. The cost of each variable is model bias. The model is biased toward the particular set of data. That is, it may not generalize to another sample of data. Therefore it is less useful for inference (e.g., prediction).</p>
<p>By dropping a variable you add one degree of freedom making the model less biased toward the particular data set but you decrease the R squared decreasing the amount of variance explained by the model.</p>
<p>This variance-bias trade-off is solved by considering the adjusted R squared value. You favor a model that has the largest adjusted R squared. If the adjusted R squared gets smaller after you remove a particular variable, then you keep it.</p>
<p>Another useful statistic in this regard is called AIC (Akaike Information Criterion). AIC is more general and can be used with models that are fit with methods other than least-squares minimization.</p>
<p>AIC is rooted in information theory. Values of AIC provide a means for model selection in a relative sense. If all candidate models fit poorly the AIC is not much help.</p>
<p>AIC = <span class="math inline">\(2 k - 2 \log(L)\)</span>, where k is the number of model parameters (1 + number of explanatory variables) and L is the highest value from the likelihood function. The likelihood function (likelihood) is the probability of your data given the model.</p>
<p>AIC rewards goodness of fit, but includes a penalty that is an increasing function of the number of estimated parameters. Given a set of candidate models for our data, you should choose the one with the lowest AIC.</p>
<p>Let’s return to the model of petrol consumption at the state level.</p>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb58-1"><a href="thursday-october-21-2022.html#cb58-1" aria-hidden="true" tabindex="-1"></a>PC.df <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="st">&quot;http://myweb.fsu.edu/jelsner/temp/data/PetrolConsumption.txt&quot;</span>, <span class="at">header =</span> <span class="cn">TRUE</span>)</span>
<span id="cb58-2"><a href="thursday-october-21-2022.html#cb58-2" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(PC.df)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    48 obs. of  5 variables:
##  $ Petrol.Tax        : num  9 9 9 7.5 8 10 8 8 8 7 ...
##  $ Avg.Inc           : int  3571 4092 3865 4870 4399 5342 5319 5126 4447 4512 ...
##  $ Pavement          : int  1976 1250 1586 2351 431 1333 11868 2138 8577 8507 ...
##  $ Prop.DL           : num  0.525 0.572 0.58 0.529 0.544 0.571 0.451 0.553 0.529 0.552 ...
##  $ Petrol.Consumption: int  541 524 561 414 410 457 344 467 464 498 ...</code></pre>
<p>First create a full model. A full model includes all the explanatory variables you think are important in explaining the variability in gas consumption.</p>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb60-1"><a href="thursday-october-21-2022.html#cb60-1" aria-hidden="true" tabindex="-1"></a>modelF <span class="ot">&lt;-</span> <span class="fu">lm</span>(Petrol.Consumption <span class="sc">~</span> Prop.DL <span class="sc">+</span> Pavement <span class="sc">+</span> Avg.Inc <span class="sc">+</span> Petrol.Tax, </span>
<span id="cb60-2"><a href="thursday-october-21-2022.html#cb60-2" aria-hidden="true" tabindex="-1"></a>            <span class="at">data =</span> PC.df)</span></code></pre></div>
<p>Then you use the <code>drop1()</code> function, which takes a regression model object and returns a table showing what happens when each variable is removed from the model.</p>
<div class="sourceCode" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb61-1"><a href="thursday-october-21-2022.html#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">drop1</span>(modelF)</span></code></pre></div>
<pre><code>## Single term deletions
## 
## Model:
## Petrol.Consumption ~ Prop.DL + Pavement + Avg.Inc + Petrol.Tax
##            Df Sum of Sq    RSS    AIC
## &lt;none&gt;                  189050 407.37
## Prop.DL     1    212355 401405 441.51
## Pavement    1      2252 191302 405.94
## Avg.Inc     1     65729 254779 419.69
## Petrol.Tax  1     31632 220682 412.80</code></pre>
<p>The first row (labeled <code>&lt;none&gt;</code>) of the table contains the sum of squared residuals (SSR) (here labeled <code>RSS</code>—residual sum of squares) and the AIC value for the full model (all explanatory variables). The RSS is 189050. Recall this value is the deviance.</p>
<div class="sourceCode" id="cb63"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb63-1"><a href="thursday-october-21-2022.html#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">resid</span>(modelF)<span class="sc">^</span><span class="dv">2</span>)</span></code></pre></div>
<pre><code>## [1] 189050</code></pre>
<div class="sourceCode" id="cb65"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb65-1"><a href="thursday-october-21-2022.html#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="fu">deviance</span>(modelF)</span></code></pre></div>
<pre><code>## [1] 189050</code></pre>
<p>The first row also gives the AIC value for the full model. Here 407.37. The model deviance has units of the response variable. The AIC has no units.</p>
<p>The next row tells you what happens to the RSS if the explanatory variable Prop.DL is removed from the full model. If you drop the <code>Prop.DL</code> variable from the full model, the RSS increases to 401405 (from 189050) and you gain one degree of freedom (less bias).</p>
<p>Said another way, the value of 212355 in the <code>Sum of Sq</code> column indicates how much the variable <code>Prop.DL</code> is worth to the model. By removing it the RSS increases from 189050 to 401405; a difference of 212355.</p>
<p>Apparently that is too much of an increase in RSS for the gain of only 1 degree of freedom as the AIC increases from 407 to 442. Said another way, the AIC is 407 for the full model. In comparison, the AIC is 442 for a model that is otherwise the same but missing <code>Prop.DL</code>.</p>
<p>The next row gives the same information about the <code>Pavement</code> variable. That is, what happens to the RSS from the full model when the variable <code>Pavement</code> is removed.</p>
<p>Here the RSS increases by 2252 to 191302 (the residuals on average get a bit larger), but this increase is worth it as it only costs one degree of freedom. This is indicated by a reduction in the AIC to so 405.94.</p>
<p>The AIC column keeps score. The AIC for the model having all the explanatory variables is 407.37. A model without <code>Prop.DL</code> has an AIC of 441.51, which is LARGER than the AIC for the full model so you keep <code>Prop.DL</code> in the model.</p>
<p>On the other hand, a model without <code>Pavement</code> has an AIC of 405.94, which is SMALLER than the AIC for the full model so you remove <code>Pavement</code> from the model.</p>
<p>So you can simply compare the AIC values for each variable against the AIC value for the full model. If the AIC value for a variable is less than the AIC for the full model then the trade-off is in favor of removing it.</p>
<p>Repeat the procedure after removing <code>Pavement</code>.</p>
<div class="sourceCode" id="cb67"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb67-1"><a href="thursday-october-21-2022.html#cb67-1" aria-hidden="true" tabindex="-1"></a>modelR <span class="ot">&lt;-</span> <span class="fu">lm</span>(Petrol.Consumption <span class="sc">~</span> Prop.DL <span class="sc">+</span> Avg.Inc <span class="sc">+</span> Petrol.Tax, </span>
<span id="cb67-2"><a href="thursday-october-21-2022.html#cb67-2" aria-hidden="true" tabindex="-1"></a>            <span class="at">data =</span> PC.df)</span>
<span id="cb67-3"><a href="thursday-october-21-2022.html#cb67-3" aria-hidden="true" tabindex="-1"></a><span class="fu">drop1</span>(modelR)</span></code></pre></div>
<pre><code>## Single term deletions
## 
## Model:
## Petrol.Consumption ~ Prop.DL + Avg.Inc + Petrol.Tax
##            Df Sum of Sq    RSS    AIC
## &lt;none&gt;                  191302 405.94
## Prop.DL     1    243586 434889 443.36
## Avg.Inc     1     69532 260834 418.82
## Petrol.Tax  1     33742 225044 411.74</code></pre>
<p>Now all the AIC values exceed the value given in the row labeled <code>&lt;none&gt;</code>, so you conclude there is no reason to remove any of the remaining variables. This is your final model.</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="tuesday-october-19-2022.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
