<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Thursday, October 5, 2022 | GEO5156: Quantitative Geography</title>
  <meta name="description" content="Thursday, October 5, 2022 | GEO5156: Quantitative Geography" />
  <meta name="generator" content="bookdown 0.24 and GitBook 2.6.7" />

  <meta property="og:title" content="Thursday, October 5, 2022 | GEO5156: Quantitative Geography" />
  <meta property="og:type" content="book" />
  
  
  
  <meta name="github-repo" content="jelsner/QG-2022" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Thursday, October 5, 2022 | GEO5156: Quantitative Geography" />
  
  
  

<meta name="author" content="James B. Elsner" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="tuesday-october-3-2022.html"/>
<link rel="next" href="tuesday-october-12-2022.html"/>
<script src="libs/header-attrs-2.11/header-attrs.js"></script>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>
<script src="libs/htmlwidgets-1.5.4/htmlwidgets.js"></script>
<script src="libs/viz-1.8.2/viz.js"></script>
<link href="libs/DiagrammeR-styles-0.2/styles.css" rel="stylesheet" />
<script src="libs/grViz-binding-1.0.8/grViz.js"></script>
<script src="libs/plotly-binding-4.10.0/plotly.js"></script>
<script src="libs/typedarray-0.1/typedarray.min.js"></script>
<link href="libs/crosstalk-1.2.0/css/crosstalk.min.css" rel="stylesheet" />
<script src="libs/crosstalk-1.2.0/js/crosstalk.min.js"></script>
<link href="libs/plotly-htmlwidgets-css-2.5.1/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="libs/plotly-main-2.5.1/plotly-latest.min.js"></script>
<link href="libs/leaflet-1.3.1/leaflet.css" rel="stylesheet" />
<script src="libs/leaflet-1.3.1/leaflet.js"></script>
<link href="libs/leafletfix-1.0.0/leafletfix.css" rel="stylesheet" />
<script src="libs/proj4-2.6.2/proj4.min.js"></script>
<script src="libs/Proj4Leaflet-1.0.1/proj4leaflet.js"></script>
<link href="libs/rstudio_leaflet-1.3.1/rstudio_leaflet.css" rel="stylesheet" />
<script src="libs/leaflet-binding-2.0.4.1/leaflet.js"></script>
<script src="libs/leaflet-providers-1.9.0/leaflet-providers_1.9.0.js"></script>
<script src="libs/leaflet-providers-plugin-2.0.4.1/leaflet-providers-plugin.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Quantitative Geography</a></li>

<li class="divider"></li>
<li><a href="index.html#section"></a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html"><i class="fa fa-check"></i>Syllabus</a>
<ul>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#geo5165c-quantitative-geography"><i class="fa fa-check"></i>GEO5165C: Quantitative Geography</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#contact-information"><i class="fa fa-check"></i>Contact information</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#course-description"><i class="fa fa-check"></i>Course description</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#expected-learning-outcomes"><i class="fa fa-check"></i>Expected learning outcomes</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#materials"><i class="fa fa-check"></i>Materials</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#class-meetings"><i class="fa fa-check"></i>Class meetings</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#grades"><i class="fa fa-check"></i>Grades</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#academic-honor-code"><i class="fa fa-check"></i>Academic honor code</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#students-with-disabilities-act"><i class="fa fa-check"></i>Students With Disabilities Act</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#inclusiveness"><i class="fa fa-check"></i>Inclusiveness</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#more-about-your-instructor"><i class="fa fa-check"></i>More about your instructor</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#syllabus-change-policy"><i class="fa fa-check"></i>Syllabus change policy</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#schedule-subject-to-change-with-notice"><i class="fa fa-check"></i>Schedule (subject to change with notice)</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#other-materials-to-check-out"><i class="fa fa-check"></i>Other materials to check out</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#julia-programming-language"><i class="fa fa-check"></i>Julia programming language</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html"><i class="fa fa-check"></i>Tuesday, August 23, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#today"><i class="fa fa-check"></i>Today</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#what-is-this-course"><i class="fa fa-check"></i>What is this course?</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#where-are-the-materials-for-this-course"><i class="fa fa-check"></i>Where are the materials for this course?</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#join-rstudio-cloud"><i class="fa fa-check"></i>Join RStudio Cloud</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#examples"><i class="fa fa-check"></i>Examples</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#course-syllabus"><i class="fa fa-check"></i>Course Syllabus</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#tallahassee-daily-temperatures"><i class="fa fa-check"></i>Tallahassee daily temperatures</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html"><i class="fa fa-check"></i>Thursday, August 25, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#today-1"><i class="fa fa-check"></i>Today</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#data-analysis"><i class="fa fa-check"></i>Data Analysis</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#reproducibility"><i class="fa fa-check"></i>Reproducibility</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#communication"><i class="fa fa-check"></i>Communication</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#automation"><i class="fa fa-check"></i>Automation</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#the-r-programming-language"><i class="fa fa-check"></i>The R programming language</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#overview-of-this-course"><i class="fa fa-check"></i>Overview of this course</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#work-in-plain-text-using-r-markdown"><i class="fa fa-check"></i>Work in plain text, using R Markdown</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#visualizing-data"><i class="fa fa-check"></i>Visualizing data</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#a-code-template"><i class="fa fa-check"></i>A code template</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#the-code"><i class="fa fa-check"></i>The code</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#a-graphing-workflow"><i class="fa fa-check"></i>A graphing workflow</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#a-graphing-template"><i class="fa fa-check"></i>A graphing template</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#common-problems"><i class="fa fa-check"></i>Common problems</a></li>
<li><a href="thursday-august-25-2022.html#location-of-the-sign">location of the <code>+</code> sign</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#help"><i class="fa fa-check"></i>help</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#things-to-know"><i class="fa fa-check"></i>Things to know</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#everything-has-a-name"><i class="fa fa-check"></i>Everything has a name</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#everything-is-an-object"><i class="fa fa-check"></i>Everything is an object</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#you-do-things-using-functions"><i class="fa fa-check"></i>You do things using functions</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#functions-come-in-packages-libraries"><i class="fa fa-check"></i>Functions come in packages (libraries)</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#your-turn"><i class="fa fa-check"></i>Your turn</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html"><i class="fa fa-check"></i>Tuesday, August 30, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html#today-2"><i class="fa fa-check"></i>Today</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html#scatter-plots"><i class="fa fa-check"></i>Scatter plots</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html#facets"><i class="fa fa-check"></i>Facets</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html#calculations"><i class="fa fa-check"></i>Calculations</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html#functions"><i class="fa fa-check"></i>Functions</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html#syntax-is-important"><i class="fa fa-check"></i>Syntax is important</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html#saving-an-object"><i class="fa fa-check"></i>Saving an object</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html#object-names"><i class="fa fa-check"></i>Object names</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html#entering-data"><i class="fa fa-check"></i>Entering data</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html#applying-a-function"><i class="fa fa-check"></i>Applying a function</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html#averge"><i class="fa fa-check"></i>Averge</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html#data-vectors"><i class="fa fa-check"></i>Data vectors</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html#variance"><i class="fa fa-check"></i>Variance</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html#data-vectors-have-a-type"><i class="fa fa-check"></i>Data vectors have a type</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html#working-smarter"><i class="fa fa-check"></i>Working smarter</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-september-1-2022.html"><a href="thursday-september-1-2022.html"><i class="fa fa-check"></i>Thursday, September 1, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-september-1-2022.html"><a href="thursday-september-1-2022.html#today-3"><i class="fa fa-check"></i>Today</a></li>
<li class="chapter" data-level="" data-path="thursday-september-1-2022.html"><a href="thursday-september-1-2022.html#data-as-vectors"><i class="fa fa-check"></i>Data as vectors</a></li>
<li class="chapter" data-level="" data-path="thursday-september-1-2022.html"><a href="thursday-september-1-2022.html#mean"><i class="fa fa-check"></i>Mean</a></li>
<li class="chapter" data-level="" data-path="thursday-september-1-2022.html"><a href="thursday-september-1-2022.html#variance-1"><i class="fa fa-check"></i>Variance</a></li>
<li class="chapter" data-level="" data-path="thursday-september-1-2022.html"><a href="thursday-september-1-2022.html#median"><i class="fa fa-check"></i>Median</a></li>
<li class="chapter" data-level="" data-path="thursday-september-1-2022.html"><a href="thursday-september-1-2022.html#spread"><i class="fa fa-check"></i>Spread</a></li>
<li class="chapter" data-level="" data-path="thursday-september-1-2022.html"><a href="thursday-september-1-2022.html#vector-types"><i class="fa fa-check"></i>Vector types</a></li>
<li class="chapter" data-level="" data-path="thursday-september-1-2022.html"><a href="thursday-september-1-2022.html#structured-data"><i class="fa fa-check"></i>Structured data</a></li>
<li class="chapter" data-level="" data-path="thursday-september-1-2022.html"><a href="thursday-september-1-2022.html#asking-questions"><i class="fa fa-check"></i>Asking questions</a></li>
<li class="chapter" data-level="" data-path="thursday-september-1-2022.html"><a href="thursday-september-1-2022.html#tables-and-summaries"><i class="fa fa-check"></i>Tables and summaries</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-september-6-2022.html"><a href="tuesday-september-6-2022.html"><i class="fa fa-check"></i>Tuesday, September 6, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-september-6-2022.html"><a href="tuesday-september-6-2022.html#today-4"><i class="fa fa-check"></i>Today</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-6-2022.html"><a href="tuesday-september-6-2022.html#getting-your-data-into-r"><i class="fa fa-check"></i>Getting your data into R</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-6-2022.html"><a href="tuesday-september-6-2022.html#creating-structured-data-files"><i class="fa fa-check"></i>Creating structured data files</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-6-2022.html"><a href="tuesday-september-6-2022.html#data-frames"><i class="fa fa-check"></i>Data frames</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-6-2022.html"><a href="tuesday-september-6-2022.html#quantiles"><i class="fa fa-check"></i>Quantiles</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-6-2022.html"><a href="tuesday-september-6-2022.html#creating-a-data-frame"><i class="fa fa-check"></i>Creating a data frame</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-6-2022.html"><a href="tuesday-september-6-2022.html#pipes"><i class="fa fa-check"></i>Pipes</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-6-2022.html"><a href="tuesday-september-6-2022.html#your-turn-1"><i class="fa fa-check"></i>Your turn</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-september-8-2022.html"><a href="thursday-september-8-2022.html"><i class="fa fa-check"></i>Thursday, September 8, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-september-8-2022.html"><a href="thursday-september-8-2022.html#today-5"><i class="fa fa-check"></i>Today</a></li>
<li class="chapter" data-level="" data-path="thursday-september-8-2022.html"><a href="thursday-september-8-2022.html#pipe-operator"><i class="fa fa-check"></i>Pipe operator</a></li>
<li class="chapter" data-level="" data-path="thursday-september-8-2022.html"><a href="thursday-september-8-2022.html#wrangling-data-frames"><i class="fa fa-check"></i>Wrangling data frames</a></li>
<li class="chapter" data-level="" data-path="thursday-september-8-2022.html"><a href="thursday-september-8-2022.html#selecting-and-filtering"><i class="fa fa-check"></i>Selecting and filtering</a></li>
<li class="chapter" data-level="" data-path="thursday-september-8-2022.html"><a href="thursday-september-8-2022.html#example-palmer-penguins"><i class="fa fa-check"></i>Example: Palmer penguins</a></li>
<li class="chapter" data-level="" data-path="thursday-september-8-2022.html"><a href="thursday-september-8-2022.html#stringing-functions-together"><i class="fa fa-check"></i>Stringing functions together</a></li>
<li class="chapter" data-level="" data-path="thursday-september-8-2022.html"><a href="thursday-september-8-2022.html#summarize"><i class="fa fa-check"></i>Summarize</a></li>
<li class="chapter" data-level="" data-path="thursday-september-8-2022.html"><a href="thursday-september-8-2022.html#grouping"><i class="fa fa-check"></i>Grouping</a></li>
<li class="chapter" data-level="" data-path="thursday-september-8-2022.html"><a href="thursday-september-8-2022.html#your-turn-2"><i class="fa fa-check"></i>Your turn</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-september-12-2022.html"><a href="tuesday-september-12-2022.html"><i class="fa fa-check"></i>Tuesday, September 12, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-september-12-2022.html"><a href="tuesday-september-12-2022.html#today-6"><i class="fa fa-check"></i>Today</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-12-2022.html"><a href="tuesday-september-12-2022.html#example-1-new-york-city-flight-data"><i class="fa fa-check"></i>Example 1: New York City flight data</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-12-2022.html"><a href="tuesday-september-12-2022.html#example-2-daily-weather-data-from-tallahassee"><i class="fa fa-check"></i>Example 2: Daily weather data from Tallahassee</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-12-2022.html"><a href="tuesday-september-12-2022.html#putting-everything-together"><i class="fa fa-check"></i>Putting everything together</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-12-2022.html"><a href="tuesday-september-12-2022.html#example-3-food-consumption-and-co2-emissions"><i class="fa fa-check"></i>Example 3: Food consumption and CO2 emissions</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-12-2022.html"><a href="tuesday-september-12-2022.html#summary"><i class="fa fa-check"></i>Summary</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-september-14-2022.html"><a href="thursday-september-14-2022.html"><i class="fa fa-check"></i>Thursday, September 14, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-september-14-2022.html"><a href="thursday-september-14-2022.html#today-7"><i class="fa fa-check"></i>Today</a></li>
<li class="chapter" data-level="" data-path="thursday-september-14-2022.html"><a href="thursday-september-14-2022.html#bar-chart"><i class="fa fa-check"></i>Bar chart</a></li>
<li class="chapter" data-level="" data-path="thursday-september-14-2022.html"><a href="thursday-september-14-2022.html#pie-preference"><i class="fa fa-check"></i>Pie preference</a></li>
<li class="chapter" data-level="" data-path="thursday-september-14-2022.html"><a href="thursday-september-14-2022.html#histogram"><i class="fa fa-check"></i>Histogram</a></li>
<li class="chapter" data-level="" data-path="thursday-september-14-2022.html"><a href="thursday-september-14-2022.html#density-plot"><i class="fa fa-check"></i>Density plot</a></li>
<li class="chapter" data-level="" data-path="thursday-september-14-2022.html"><a href="thursday-september-14-2022.html#box-plot"><i class="fa fa-check"></i>Box plot</a></li>
<li class="chapter" data-level="" data-path="thursday-september-14-2022.html"><a href="thursday-september-14-2022.html#side-by-side-box-plots"><i class="fa fa-check"></i>Side-by-side box plots</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-september-19-2022.html"><a href="tuesday-september-19-2022.html"><i class="fa fa-check"></i>Tuesday, September 19, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-september-19-2022.html"><a href="tuesday-september-19-2022.html#today-8"><i class="fa fa-check"></i>Today</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-19-2022.html"><a href="tuesday-september-19-2022.html#comparing-distributions"><i class="fa fa-check"></i>Comparing distributions</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-19-2022.html"><a href="tuesday-september-19-2022.html#box-plots"><i class="fa fa-check"></i>Box plots</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-19-2022.html"><a href="tuesday-september-19-2022.html#long-data-frames"><i class="fa fa-check"></i>Long data frames</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-19-2022.html"><a href="tuesday-september-19-2022.html#scatter-plots-1"><i class="fa fa-check"></i>Scatter plots</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-19-2022.html"><a href="tuesday-september-19-2022.html#facets-1"><i class="fa fa-check"></i>Facets</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-19-2022.html"><a href="tuesday-september-19-2022.html#example-palmer-penguins-1"><i class="fa fa-check"></i>Example: Palmer penguins</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-19-2022.html"><a href="tuesday-september-19-2022.html#an-expository-graph"><i class="fa fa-check"></i>An expository graph</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-19-2022.html"><a href="tuesday-september-19-2022.html#exporting-your-graph"><i class="fa fa-check"></i>Exporting your graph</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-september-21-2022.html"><a href="thursday-september-21-2022.html"><i class="fa fa-check"></i>Thursday, September 21, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-september-21-2022.html"><a href="thursday-september-21-2022.html#today-9"><i class="fa fa-check"></i>Today</a></li>
<li class="chapter" data-level="" data-path="thursday-september-21-2022.html"><a href="thursday-september-21-2022.html#simple-feature-data-frames"><i class="fa fa-check"></i>Simple feature data frames</a></li>
<li class="chapter" data-level="" data-path="thursday-september-21-2022.html"><a href="thursday-september-21-2022.html#making-a-boundary-map"><i class="fa fa-check"></i>Making a boundary map</a></li>
<li class="chapter" data-level="" data-path="thursday-september-21-2022.html"><a href="thursday-september-21-2022.html#fills"><i class="fa fa-check"></i>Fills</a></li>
<li class="chapter" data-level="" data-path="thursday-september-21-2022.html"><a href="thursday-september-21-2022.html#adding-data"><i class="fa fa-check"></i>Adding data</a></li>
<li class="chapter" data-level="" data-path="thursday-september-21-2022.html"><a href="thursday-september-21-2022.html#inset-maps"><i class="fa fa-check"></i>Inset maps</a></li>
<li class="chapter" data-level="" data-path="thursday-september-21-2022.html"><a href="thursday-september-21-2022.html#map-projections"><i class="fa fa-check"></i>Map projections</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-september-21-2022-1.html"><a href="thursday-september-21-2022-1.html"><i class="fa fa-check"></i>Thursday, September 21, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-september-21-2022-1.html"><a href="thursday-september-21-2022-1.html#today-10"><i class="fa fa-check"></i>Today</a></li>
<li class="chapter" data-level="" data-path="thursday-september-21-2022-1.html"><a href="thursday-september-21-2022-1.html#making-maps-using-functions-from-the-tmap-package"><i class="fa fa-check"></i>Making maps using functions from the {tmap} package</a></li>
<li class="chapter" data-level="" data-path="thursday-september-21-2022-1.html"><a href="thursday-september-21-2022-1.html#example-mapping-tornadoes"><i class="fa fa-check"></i>Example: Mapping tornadoes</a></li>
<li class="chapter" data-level="" data-path="thursday-september-21-2022-1.html"><a href="thursday-september-21-2022-1.html#example-mapping-the-frequency-of-tornadoes-by-state"><i class="fa fa-check"></i>Example: Mapping the frequency of tornadoes by state</a></li>
<li class="chapter" data-level="" data-path="thursday-september-21-2022-1.html"><a href="thursday-september-21-2022-1.html#calculations-using-the-geometry-simple-feature-column"><i class="fa fa-check"></i>Calculations using the geometry simple feature column</a></li>
<li class="chapter" data-level="" data-path="thursday-september-21-2022-1.html"><a href="thursday-september-21-2022-1.html#making-raster-maps"><i class="fa fa-check"></i>Making raster maps</a></li>
<li class="chapter" data-level="" data-path="thursday-september-21-2022-1.html"><a href="thursday-september-21-2022-1.html#get-map-images-using-functions-from-the-ggmap-package"><i class="fa fa-check"></i>Get map images using functions from the {ggmap} package</a></li>
<li class="chapter" data-level="" data-path="thursday-september-21-2022-1.html"><a href="thursday-september-21-2022-1.html#add-data-to-the-raster-map"><i class="fa fa-check"></i>Add data to the raster map</a></li>
<li class="chapter" data-level="" data-path="thursday-september-21-2022-1.html"><a href="thursday-september-21-2022-1.html#spatial-density-maps-extra-material"><i class="fa fa-check"></i>Spatial density maps (extra material)</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-september-26-2022.html"><a href="tuesday-september-26-2022.html"><i class="fa fa-check"></i>Tuesday, September 26, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-september-26-2022.html"><a href="tuesday-september-26-2022.html#today-11"><i class="fa fa-check"></i>Today</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-26-2022.html"><a href="tuesday-september-26-2022.html#one-sample-test-of-the-population-mean"><i class="fa fa-check"></i>One-sample test of the population mean</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-26-2022.html"><a href="tuesday-september-26-2022.html#about-p-values"><i class="fa fa-check"></i>About p-values</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-26-2022.html"><a href="tuesday-september-26-2022.html#example-strongest-atlantic-hurricanes"><i class="fa fa-check"></i>Example: Strongest Atlantic hurricanes</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-26-2022.html"><a href="tuesday-september-26-2022.html#graphical-inference"><i class="fa fa-check"></i>Graphical inference</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-26-2022.html"><a href="tuesday-september-26-2022.html#two-sample-test-of-the-difference-in-population-means"><i class="fa fa-check"></i>Two-sample test of the difference in population means</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-26-2022.html"><a href="tuesday-september-26-2022.html#example-hurricanes-in-the-north-atlantic-and-the-eastern-north-pacific"><i class="fa fa-check"></i>Example: hurricanes in the North Atlantic and the eastern North Pacific</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-26-2022.html"><a href="tuesday-september-26-2022.html#example-palmer-penguins-2"><i class="fa fa-check"></i>Example: Palmer penguins</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-26-2022.html"><a href="tuesday-september-26-2022.html#your-turn-3"><i class="fa fa-check"></i>Your turn</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-26-2022.html"><a href="tuesday-september-26-2022.html#test-of-equal-variance"><i class="fa fa-check"></i>Test of equal variance</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-26-2022.html"><a href="tuesday-september-26-2022.html#wilcoxon-mann-whitney-u-non-parameteric-test-of-difference-in-means"><i class="fa fa-check"></i>Wilcoxon (Mann-Whitney U) non-parameteric test of difference in means</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-september-28-2022.html"><a href="thursday-september-28-2022.html"><i class="fa fa-check"></i>Thursday, September 28, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-september-28-2022.html"><a href="thursday-september-28-2022.html#today-12"><i class="fa fa-check"></i>Today</a></li>
<li class="chapter" data-level="" data-path="thursday-september-28-2022.html"><a href="thursday-september-28-2022.html#review"><i class="fa fa-check"></i>Review</a></li>
<li class="chapter" data-level="" data-path="thursday-september-28-2022.html"><a href="thursday-september-28-2022.html#paired-observations"><i class="fa fa-check"></i>Paired observations</a></li>
<li class="chapter" data-level="" data-path="thursday-september-28-2022.html"><a href="thursday-september-28-2022.html#example-reaction-time-while-driving"><i class="fa fa-check"></i>Example: Reaction time while driving</a></li>
<li class="chapter" data-level="" data-path="thursday-september-28-2022.html"><a href="thursday-september-28-2022.html#chi-squared-test-for-independence"><i class="fa fa-check"></i>Chi-squared test for independence</a></li>
<li class="chapter" data-level="" data-path="thursday-september-28-2022.html"><a href="thursday-september-28-2022.html#example-smoking-and-exercise"><i class="fa fa-check"></i>Example: Smoking and exercise</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-october-3-2022.html"><a href="tuesday-october-3-2022.html"><i class="fa fa-check"></i>Tuesday, October 3, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-october-3-2022.html"><a href="tuesday-october-3-2022.html#today-13"><i class="fa fa-check"></i>Today</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-3-2022.html"><a href="tuesday-october-3-2022.html#distributions"><i class="fa fa-check"></i>Distributions</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-3-2022.html"><a href="tuesday-october-3-2022.html#normal-distribution"><i class="fa fa-check"></i>Normal distribution</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-3-2022.html"><a href="tuesday-october-3-2022.html#uniform-distribution"><i class="fa fa-check"></i>Uniform distribution</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-3-2022.html"><a href="tuesday-october-3-2022.html#how-many-blue-marbles"><i class="fa fa-check"></i>How many blue marbles?</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-3-2022.html"><a href="tuesday-october-3-2022.html#what-percentage-of-the-globe-is-covered-by-water"><i class="fa fa-check"></i>What percentage of the globe is covered by water?</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-3-2022.html"><a href="tuesday-october-3-2022.html#how-many-fish-are-in-the-lake"><i class="fa fa-check"></i>How many fish are in the lake?</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-october-5-2022.html"><a href="thursday-october-5-2022.html"><i class="fa fa-check"></i>Thursday, October 5, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-october-5-2022.html"><a href="thursday-october-5-2022.html#today-14"><i class="fa fa-check"></i>Today</a></li>
<li class="chapter" data-level="" data-path="thursday-october-5-2022.html"><a href="thursday-october-5-2022.html#how-many-fish-are-in-the-lake-1"><i class="fa fa-check"></i>How many fish are in the lake?</a></li>
<li class="chapter" data-level="" data-path="thursday-october-5-2022.html"><a href="thursday-october-5-2022.html#percentage-of-survey-signups"><i class="fa fa-check"></i>Percentage of survey signups</a></li>
<li class="chapter" data-level="" data-path="thursday-october-5-2022.html"><a href="thursday-october-5-2022.html#a-generative-model-for-people-agreeing-to-take-your-survey"><i class="fa fa-check"></i>A generative model for people agreeing to take your survey</a></li>
<li class="chapter" data-level="" data-path="thursday-october-5-2022.html"><a href="thursday-october-5-2022.html#prior-for-the-response-rate"><i class="fa fa-check"></i>Prior for the response rate</a></li>
<li class="chapter" data-level="" data-path="thursday-october-5-2022.html"><a href="thursday-october-5-2022.html#define-the-generative-model-and-simulate-the-data"><i class="fa fa-check"></i>Define the generative model and simulate the data</a></li>
<li class="chapter" data-level="" data-path="thursday-october-5-2022.html"><a href="thursday-october-5-2022.html#prediction"><i class="fa fa-check"></i>Prediction</a></li>
<li class="chapter" data-level="" data-path="thursday-october-5-2022.html"><a href="thursday-october-5-2022.html#approximate-bayesian-computation"><i class="fa fa-check"></i>Approximate Bayesian computation</a></li>
<li class="chapter" data-level="" data-path="thursday-october-5-2022.html"><a href="thursday-october-5-2022.html#what-bayesian-data-analysis-is-not"><i class="fa fa-check"></i>What Bayesian data analysis is not</a></li>
<li class="chapter" data-level="" data-path="thursday-october-5-2022.html"><a href="thursday-october-5-2022.html#comparing-two-hypotheses"><i class="fa fa-check"></i>Comparing two hypotheses</a></li>
<li class="chapter" data-level="" data-path="thursday-october-5-2022.html"><a href="thursday-october-5-2022.html#reaction-times-while-driving"><i class="fa fa-check"></i>Reaction times while driving</a></li>
<li class="chapter" data-level="" data-path="thursday-october-5-2022.html"><a href="thursday-october-5-2022.html#repeat-the-survey-example"><i class="fa fa-check"></i>Repeat the survey example</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-october-12-2022.html"><a href="tuesday-october-12-2022.html"><i class="fa fa-check"></i>Tuesday, October 12, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-october-12-2022.html"><a href="tuesday-october-12-2022.html#today-15"><i class="fa fa-check"></i>Today</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-12-2022.html"><a href="tuesday-october-12-2022.html#linear-regression-a-t-test-by-another-name"><i class="fa fa-check"></i>Linear regression: A t test by another name</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-12-2022.html"><a href="tuesday-october-12-2022.html#motivating-regression"><i class="fa fa-check"></i>Motivating regression</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-12-2022.html"><a href="tuesday-october-12-2022.html#eyeballing-the-regression"><i class="fa fa-check"></i>Eyeballing the regression</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-12-2022.html"><a href="tuesday-october-12-2022.html#example-increasing-heart-rates-with-age"><i class="fa fa-check"></i>Example: Increasing heart rates with age</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-12-2022.html"><a href="tuesday-october-12-2022.html#making-predictions-with-regression"><i class="fa fa-check"></i>Making predictions with regression</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-12-2022.html"><a href="tuesday-october-12-2022.html#uncertainty-about-the-regression-coefficients"><i class="fa fa-check"></i>Uncertainty about the regression coefficients</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-12-2022.html"><a href="tuesday-october-12-2022.html#bootstrapping-the-uncertainty"><i class="fa fa-check"></i>Bootstrapping the uncertainty</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-12-2022.html"><a href="tuesday-october-12-2022.html#predictive-uncertainty"><i class="fa fa-check"></i>Predictive uncertainty</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-october-14-2022.html"><a href="thursday-october-14-2022.html"><i class="fa fa-check"></i>Thursday, October 14, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-october-14-2022.html"><a href="thursday-october-14-2022.html#today-16"><i class="fa fa-check"></i>Today</a></li>
<li class="chapter" data-level="" data-path="thursday-october-14-2022.html"><a href="thursday-october-14-2022.html#uncertainty-about-a-particular-predicted-value"><i class="fa fa-check"></i>Uncertainty about a particular predicted value</a></li>
<li class="chapter" data-level="" data-path="thursday-october-14-2022.html"><a href="thursday-october-14-2022.html#example-predicting-body-mass-from-fipper-length"><i class="fa fa-check"></i>Example: Predicting body mass from fipper length</a></li>
<li class="chapter" data-level="" data-path="thursday-october-14-2022.html"><a href="thursday-october-14-2022.html#model-adequacy"><i class="fa fa-check"></i>Model Adequacy</a></li>
<li class="chapter" data-level="" data-path="thursday-october-14-2022.html"><a href="thursday-october-14-2022.html#transforming-the-response-variable"><i class="fa fa-check"></i>Transforming the response variable</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">GEO5156: Quantitative Geography</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="thursday-october-5-2022" class="section level1 unnumbered">
<h1>Thursday, October 5, 2022</h1>
<div id="today-14" class="section level2 unnumbered">
<h2>Today</h2>
<ul>
<li>More examples of Bayesian data analyses</li>
</ul>
</div>
<div id="how-many-fish-are-in-the-lake-1" class="section level2 unnumbered">
<h2>How many fish are in the lake?</h2>
<p>A common problem in wildlife management is the estimation of a species abundance. For example: Start by catching and marking 20 fish. Then after some time catch another 20 fish and count how many of them have a mark. Suppose that out of the 20 fish caught 5 are marked. How many fish are in the lake?</p>
<p>Parameter = Number of fish in the lake (the unknown that you want to estimate)
Generative Model: First mark 20 fish and release them back into the lake, then recapture 20 fish and count how many are marked.</p>
<p>Data: Five of the 20 fish were marked.</p>
<p>Here is what you will do to answer the question how many fish are in the lake.</p>
<ol style="list-style-type: decimal">
<li>Draw a random sample from the prior distribution on the parameter.</li>
<li>Plug in each sampled value (draw) into the generative model to get a vector of ‘fake’ data. For example: If the number of fish in the lake is 80 you might get four marked fish on our recapture sample. If the number of fish is only 30, you might get 13 marked fish on our sample, etc. That makes sense, right?</li>
<li>Keep only those parameter values that generated the data that was actually observed (5 out of the 20 sampled).</li>
</ol>
<p>Let’s see this in action with code. Draw a large (<code>M = 100000</code>) sample from the prior distribution (discrete uniform) on the parameter representing the number of fish in the lake (<code>priorNF</code>). Here you use the <code>sample()</code> function on a vector of counts between 21 and 250.</p>
<div class="sourceCode" id="cb888"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb888-1"><a href="thursday-october-5-2022.html#cb888-1" aria-hidden="true" tabindex="-1"></a>M <span class="ot">&lt;-</span> <span class="dv">100000</span></span>
<span id="cb888-2"><a href="thursday-october-5-2022.html#cb888-2" aria-hidden="true" tabindex="-1"></a>priorNF <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="dv">21</span><span class="sc">:</span><span class="dv">250</span>, <span class="at">size =</span> M, <span class="at">replace =</span> <span class="cn">TRUE</span>)</span>
<span id="cb888-3"><a href="thursday-october-5-2022.html#cb888-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(priorNF, <span class="at">n =</span> <span class="dv">20</span>)</span></code></pre></div>
<pre><code>##  [1] 237  45 127  89 119  25  67 105  64 238 139  56  61 140 126 102  62 103 131
## [20] 217</code></pre>
<p>The result is a vector of length <code>M</code> containing counts with values between 21 and 250. What is the shape on the distribution of values?</p>
<div class="sourceCode" id="cb890"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb890-1"><a href="thursday-october-5-2022.html#cb890-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(<span class="fu">table</span>(priorNF))</span></code></pre></div>
<pre><code>## priorNF
##  21  22  23  24  25  26 
## 466 450 437 410 491 448</code></pre>
<div class="sourceCode" id="cb892"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb892-1"><a href="thursday-october-5-2022.html#cb892-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tail</span>(<span class="fu">table</span>(priorNF))</span></code></pre></div>
<pre><code>## priorNF
## 245 246 247 248 249 250 
## 418 431 431 450 410 410</code></pre>
<p>Plot a histogram of the parameter values.</p>
<div class="sourceCode" id="cb894"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb894-1"><a href="thursday-october-5-2022.html#cb894-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb894-2"><a href="thursday-october-5-2022.html#cb894-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb894-3"><a href="thursday-october-5-2022.html#cb894-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> <span class="fu">as.data.frame</span>(priorNF), </span>
<span id="cb894-4"><a href="thursday-october-5-2022.html#cb894-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">mapping =</span> <span class="fu">aes</span>(priorNF)) <span class="sc">+</span></span>
<span id="cb894-5"><a href="thursday-october-5-2022.html#cb894-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">10</span>, <span class="at">boundary =</span> <span class="dv">20</span>, </span>
<span id="cb894-6"><a href="thursday-october-5-2022.html#cb894-6" aria-hidden="true" tabindex="-1"></a>                 <span class="at">color =</span> <span class="st">&quot;white&quot;</span>, <span class="at">fill =</span> <span class="st">&quot;salmon&quot;</span>) <span class="sc">+</span></span>
<span id="cb894-7"><a href="thursday-october-5-2022.html#cb894-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Number of Fish in the Lake&quot;</span>) <span class="sc">+</span></span>
<span id="cb894-8"><a href="thursday-october-5-2022.html#cb894-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="at">label =</span> <span class="st">&quot;Prior distribution on the number of fish in the lake&quot;</span>) <span class="sc">+</span></span>
<span id="cb894-9"><a href="thursday-october-5-2022.html#cb894-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="QG-2022_files/figure-html/unnamed-chunk-424-1.png" width="672" /></p>
<p>Uniform distribution. This is how you should start if you have no knowledge about how many fish are in the lake. You are maximally non-committal to any particular count.</p>
<p>Next you define the generative model. Here you create a function that takes a value for the unknown parameter (number of fish in the lake) as input and returns a data value. The data value is the number of tagged fish on recapture.</p>
<p>Suppose for example that the number of fish in the lake is in fact 63. Then you set up a vector of length 63 where 20 are labeled as marked and 63 - 20 = 43 are labeled as not marked.</p>
<div class="sourceCode" id="cb895"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb895-1"><a href="thursday-october-5-2022.html#cb895-1" aria-hidden="true" tabindex="-1"></a>fish <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">0</span><span class="sc">:</span><span class="dv">1</span>, <span class="fu">c</span>(<span class="dv">63</span> <span class="sc">-</span> <span class="dv">20</span>, <span class="dv">20</span>))</span>
<span id="cb895-2"><a href="thursday-october-5-2022.html#cb895-2" aria-hidden="true" tabindex="-1"></a>fish</span></code></pre></div>
<pre><code>##  [1] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
## [39] 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1</code></pre>
<p>Then you take a sample of size 20 without replacement (this is equivalent to catching 20 fish in a lake with 63 fish of which twenty of them are marked) from this vector and add the sampled values. This value represents the number of fish caught that were marked.</p>
<div class="sourceCode" id="cb897"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb897-1"><a href="thursday-october-5-2022.html#cb897-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">sample</span>(fish, <span class="at">size =</span> <span class="dv">20</span>))</span></code></pre></div>
<pre><code>## [1] 6</code></pre>
<p>Sample and sum again.</p>
<p>Let’s save 1000 of these and then make a histogram. The <code>for(){}</code> function is used to create a loop over this process of sampling and summing. Here it says to repeat the sample and sum 1000 times. <code>j</code> is used as a ‘dummy’ indexing the set of integers between 1 and 1000. Each time you get a sum <code>nM</code> you include it as an element in the vector <code>nMarked</code>.</p>
<div class="sourceCode" id="cb899"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb899-1"><a href="thursday-october-5-2022.html#cb899-1" aria-hidden="true" tabindex="-1"></a>nMarked <span class="ot">&lt;-</span> <span class="fu">numeric</span>()</span>
<span id="cb899-2"><a href="thursday-october-5-2022.html#cb899-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(j <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">1000</span>){</span>
<span id="cb899-3"><a href="thursday-october-5-2022.html#cb899-3" aria-hidden="true" tabindex="-1"></a>  nM <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="fu">sample</span>(fish, <span class="dv">20</span>))</span>
<span id="cb899-4"><a href="thursday-october-5-2022.html#cb899-4" aria-hidden="true" tabindex="-1"></a>  nMarked <span class="ot">&lt;-</span> <span class="fu">c</span>(nMarked, nM)</span>
<span id="cb899-5"><a href="thursday-october-5-2022.html#cb899-5" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb899-6"><a href="thursday-october-5-2022.html#cb899-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb899-7"><a href="thursday-october-5-2022.html#cb899-7" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> <span class="fu">as.data.frame</span>(nMarked), </span>
<span id="cb899-8"><a href="thursday-october-5-2022.html#cb899-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">mapping =</span> <span class="fu">aes</span>(nMarked)) <span class="sc">+</span></span>
<span id="cb899-9"><a href="thursday-october-5-2022.html#cb899-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">breaks =</span> <span class="fu">seq</span>(<span class="sc">-</span>.<span class="dv">5</span>, <span class="fl">12.5</span>, <span class="dv">1</span>),</span>
<span id="cb899-10"><a href="thursday-october-5-2022.html#cb899-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">&quot;white&quot;</span>, <span class="at">fill =</span> <span class="st">&quot;salmon&quot;</span>) <span class="sc">+</span></span>
<span id="cb899-11"><a href="thursday-october-5-2022.html#cb899-11" aria-hidden="true" tabindex="-1"></a>    <span class="fu">xlab</span>(<span class="st">&quot;Number of Recaptured Fish&quot;</span>) <span class="sc">+</span></span>
<span id="cb899-12"><a href="thursday-october-5-2022.html#cb899-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="at">label =</span> <span class="st">&quot;Conditional likelihood on the number of recaptured fish&quot;</span>) <span class="sc">+</span></span>
<span id="cb899-13"><a href="thursday-october-5-2022.html#cb899-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="QG-2022_files/figure-html/unnamed-chunk-427-1.png" width="672" /></p>
<p>This tells us that <em>IF</em> the number of fish in the lake is 63, the <em>most likely</em> number of marked recaptures would be either 6 or 7.</p>
<p>But what if the number of fish in the lake is 64 or 74, or any other number? That is exactly what you want to estimate. So you create a function from your sampling code.</p>
<div class="sourceCode" id="cb900"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb900-1"><a href="thursday-october-5-2022.html#cb900-1" aria-hidden="true" tabindex="-1"></a>pickFish <span class="ot">&lt;-</span> <span class="cf">function</span>(priorNF){</span>
<span id="cb900-2"><a href="thursday-october-5-2022.html#cb900-2" aria-hidden="true" tabindex="-1"></a>  fish <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">0</span><span class="sc">:</span><span class="dv">1</span>, <span class="fu">c</span>(priorNF <span class="sc">-</span> <span class="dv">20</span>, <span class="dv">20</span>))</span>
<span id="cb900-3"><a href="thursday-october-5-2022.html#cb900-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sum</span>(<span class="fu">sample</span>(fish, <span class="dv">20</span>))</span>
<span id="cb900-4"><a href="thursday-october-5-2022.html#cb900-4" aria-hidden="true" tabindex="-1"></a>  }</span></code></pre></div>
<p>The <code>function()</code> function takes as it’s single input the prior guess at the number of fish in the lake. The two lines of code between the left <code>{</code> and the right <code>}</code> samples and sums. The only thing returned by the function is the number of marked fish on recapture. The function is assigned to the object you call <code>pickFish()</code>.</p>
<p>To apply the function include a guess at the number of fish in the lake.</p>
<div class="sourceCode" id="cb901"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb901-1"><a href="thursday-october-5-2022.html#cb901-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pickFish</span>(<span class="dv">104</span>)</span></code></pre></div>
<pre><code>## [1] 4</code></pre>
<div class="sourceCode" id="cb903"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb903-1"><a href="thursday-october-5-2022.html#cb903-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pickFish</span>(priorNF[<span class="dv">10</span>])</span></code></pre></div>
<pre><code>## [1] 4</code></pre>
<p>Now you can simulate the data. The data are the number of marked fish on the recapture given a parameter value. The parameter values come from the prior distribution. You start by ‘initializing’ the object <code>nMarked</code>.</p>
<div class="sourceCode" id="cb905"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb905-1"><a href="thursday-october-5-2022.html#cb905-1" aria-hidden="true" tabindex="-1"></a>nMarked <span class="ot">&lt;-</span> <span class="cn">NULL</span></span>
<span id="cb905-2"><a href="thursday-october-5-2022.html#cb905-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>M) {</span>
<span id="cb905-3"><a href="thursday-october-5-2022.html#cb905-3" aria-hidden="true" tabindex="-1"></a>  nMarked[i] <span class="ot">&lt;-</span> <span class="fu">pickFish</span>(priorNF[i])</span>
<span id="cb905-4"><a href="thursday-october-5-2022.html#cb905-4" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb905-5"><a href="thursday-october-5-2022.html#cb905-5" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(nMarked)</span></code></pre></div>
<pre><code>## [1]  1  8  3  5  3 17</code></pre>
<p>The <code>for</code> loop uses the <code>pickFish()</code> function for each count in the prior and there are <code>M</code> of them. The output of applying the function is saved, element by element, in the vector <code>nMarked</code>.</p>
<p>Finally, you <em>keep</em> only those parameter values that resulted in the data you actually observed (5 marked fish re-caught) and plot those as a histogram.</p>
<div class="sourceCode" id="cb907"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb907-1"><a href="thursday-october-5-2022.html#cb907-1" aria-hidden="true" tabindex="-1"></a>postNF <span class="ot">&lt;-</span> priorNF[nMarked <span class="sc">==</span> <span class="dv">5</span>]</span>
<span id="cb907-2"><a href="thursday-october-5-2022.html#cb907-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> <span class="fu">as.data.frame</span>(postNF), </span>
<span id="cb907-3"><a href="thursday-october-5-2022.html#cb907-3" aria-hidden="true" tabindex="-1"></a>       <span class="at">mapping =</span> <span class="fu">aes</span>(postNF)) <span class="sc">+</span></span>
<span id="cb907-4"><a href="thursday-october-5-2022.html#cb907-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">10</span>, <span class="at">boundary =</span> <span class="dv">20</span>, </span>
<span id="cb907-5"><a href="thursday-october-5-2022.html#cb907-5" aria-hidden="true" tabindex="-1"></a>                 <span class="at">color =</span> <span class="st">&quot;white&quot;</span>, <span class="at">fill =</span> <span class="st">&quot;salmon&quot;</span>) <span class="sc">+</span></span>
<span id="cb907-6"><a href="thursday-october-5-2022.html#cb907-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Number of Fish in the Lake&quot;</span>) <span class="sc">+</span></span>
<span id="cb907-7"><a href="thursday-october-5-2022.html#cb907-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="at">label =</span> <span class="st">&quot;Posterior distribution on the number of fish in the lake&quot;</span>) <span class="sc">+</span></span>
<span id="cb907-8"><a href="thursday-october-5-2022.html#cb907-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="QG-2022_files/figure-html/unnamed-chunk-431-1.png" width="672" /></p>
<p>The result is a distribution on the unknown parameter (number of fish in the lake). It is called the posterior distribution. It shows us how many times the particular value of number of fish in the lake results in 5 out of 20 marked on recapture.</p>
<p>It tells us that it is unlikely there are more than 200 or less than 50 fish in the lake.</p>
<p>For insight, put the prior and posterior values into a data frame.</p>
<div class="sourceCode" id="cb908"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb908-1"><a href="thursday-october-5-2022.html#cb908-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Distribution =</span> <span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">&quot;(A) Prior Distribution&quot;</span>, </span>
<span id="cb908-2"><a href="thursday-october-5-2022.html#cb908-2" aria-hidden="true" tabindex="-1"></a>                                      <span class="st">&quot;(B) Posterior Distribution&quot;</span>), </span>
<span id="cb908-3"><a href="thursday-october-5-2022.html#cb908-3" aria-hidden="true" tabindex="-1"></a>                                    <span class="fu">c</span>(M, <span class="fu">length</span>(postNF))), </span>
<span id="cb908-4"><a href="thursday-october-5-2022.html#cb908-4" aria-hidden="true" tabindex="-1"></a>                 <span class="at">Values =</span> <span class="fu">c</span>(priorNF, postNF))</span>
<span id="cb908-5"><a href="thursday-october-5-2022.html#cb908-5" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(df)</span></code></pre></div>
<pre><code>##             Distribution Values
## 1 (A) Prior Distribution    237
## 2 (A) Prior Distribution     45
## 3 (A) Prior Distribution    127
## 4 (A) Prior Distribution     89
## 5 (A) Prior Distribution    119
## 6 (A) Prior Distribution     25</code></pre>
<div class="sourceCode" id="cb910"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb910-1"><a href="thursday-october-5-2022.html#cb910-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tail</span>(df)</span></code></pre></div>
<pre><code>##                      Distribution Values
## 108273 (B) Posterior Distribution    120
## 108274 (B) Posterior Distribution     62
## 108275 (B) Posterior Distribution    165
## 108276 (B) Posterior Distribution     98
## 108277 (B) Posterior Distribution    117
## 108278 (B) Posterior Distribution     78</code></pre>
<p>Then plot the prior and posterior distributions side by side.</p>
<div class="sourceCode" id="cb912"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb912-1"><a href="thursday-october-5-2022.html#cb912-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> df, </span>
<span id="cb912-2"><a href="thursday-october-5-2022.html#cb912-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> Values)) <span class="sc">+</span></span>
<span id="cb912-3"><a href="thursday-october-5-2022.html#cb912-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">y =</span> (..density..) <span class="sc">*</span> <span class="dv">20</span>), </span>
<span id="cb912-4"><a href="thursday-october-5-2022.html#cb912-4" aria-hidden="true" tabindex="-1"></a>                 <span class="at">binwidth =</span> <span class="dv">10</span>, <span class="at">color =</span> <span class="st">&quot;white&quot;</span>, </span>
<span id="cb912-5"><a href="thursday-october-5-2022.html#cb912-5" aria-hidden="true" tabindex="-1"></a>                 <span class="at">fill =</span> <span class="st">&quot;salmon&quot;</span>) <span class="sc">+</span></span>
<span id="cb912-6"><a href="thursday-october-5-2022.html#cb912-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">20</span>, <span class="dv">250</span>)) <span class="sc">+</span></span>
<span id="cb912-7"><a href="thursday-october-5-2022.html#cb912-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> Distribution, <span class="at">ncol =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb912-8"><a href="thursday-october-5-2022.html#cb912-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Number of Fish in the Lake&quot;</span>) <span class="sc">+</span></span>
<span id="cb912-9"><a href="thursday-october-5-2022.html#cb912-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Probability&quot;</span>) <span class="sc">+</span></span>
<span id="cb912-10"><a href="thursday-october-5-2022.html#cb912-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="at">label =</span> <span class="st">&quot;How many fish are there in the lake?&quot;</span>) <span class="sc">+</span></span>
<span id="cb912-11"><a href="thursday-october-5-2022.html#cb912-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<pre><code>## Warning: Removed 4 rows containing missing values (geom_bar).</code></pre>
<p><img src="QG-2022_files/figure-html/unnamed-chunk-433-1.png" width="672" /></p>
<p>As an answer to the question how many fish are in the lake, you start by thinking that there is no preference for any number between 20 and 250. That uniform uncertainty is the prior. It is quantified as a uniform distribution.</p>
<p>Then, after collecting data and combining the information with the prior, the uncertainty is reduced. The reduction in uncertainty is seen in the posterior distribution.</p>
<p>The most likely value for the number of fish in the lake is somewhere between 70 and 120 as seen by location of the tallest bar in the histogram. There is a 50% chance that the number of fish in the lake is between 78 and 132. This is obtained by using the <code>quantile()</code> function on the posterior values stored in <code>postNF</code>.</p>
<div class="sourceCode" id="cb914"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb914-1"><a href="thursday-october-5-2022.html#cb914-1" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span>(postNF, <span class="at">probs =</span> <span class="fu">c</span>(.<span class="dv">25</span>, .<span class="dv">75</span>))</span></code></pre></div>
<pre><code>## 25% 75% 
##  78 132</code></pre>
<p>If you want to be 95% certain of the correct answer to the question then you increase the interval to</p>
<div class="sourceCode" id="cb916"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb916-1"><a href="thursday-october-5-2022.html#cb916-1" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span>(postNF, <span class="at">probs =</span> <span class="fu">c</span>(.<span class="dv">025</span>, .<span class="dv">975</span>))</span></code></pre></div>
<pre><code>##  2.5% 97.5% 
##    54   218</code></pre>
<p>If you need to make a single best guess you take the median of the posterior.</p>
<div class="sourceCode" id="cb918"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb918-1"><a href="thursday-october-5-2022.html#cb918-1" aria-hidden="true" tabindex="-1"></a><span class="fu">median</span>(postNF)</span></code></pre></div>
<pre><code>## [1] 100</code></pre>
<p>Let’s look at the bars centered on the value of 100 fish. You start with the prior. The probability that there are 100 fish (more precisely between 90 &amp; 110 fish) in the lake before you mark and recapture is .09 (9%). You write this as</p>
<p>P(100 fish) = 9%</p>
<p>After observing 5 marked fish in 20 on the recapture the probability increases to 20%. You write this as</p>
<p>P(100 fish | 5 marked recaptured) = 20%</p>
<p>Combining the prior with data results in the posterior. P(<span class="math inline">\(\theta\)</span> | D) <span class="math inline">\(\propto\)</span> P(<span class="math inline">\(\theta\)</span>) <span class="math inline">\(\times\)</span> P(D | <span class="math inline">\(\theta\)</span>): Bayes Theorem.</p>
<p>In this example you used a capture-recapture model with one parameter. But the general method works on any generative model and with any number of parameters.</p>
<p>The specific computational method (approximate Bayes calculation: ABC) you used only works in rare cases.</p>
<p>Why use Bayesian data analysis?</p>
<p>You can build more flexible models. You can use models to answer specific questions in a natural way. For example, what is the probability that the number of fish in the lake exceeds 200?</p>
<div class="sourceCode" id="cb920"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb920-1"><a href="thursday-october-5-2022.html#cb920-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(postNF <span class="sc">&gt;</span> <span class="dv">200</span>)<span class="sc">/</span><span class="fu">length</span>(postNF) <span class="sc">*</span> <span class="dv">100</span></span></code></pre></div>
<pre><code>## [1] 4.614641</code></pre>
<p>Less the 5% chance. Note: There is no reference null hypothesis or <span class="math inline">\(p\)</span>-value.</p>
<p>Suppose you get some additional data. Let’s say you catch another sample of fish from the lake and find that 6 are marked. You can use your posterior distribution as the new prior distribution.</p>
<div class="sourceCode" id="cb922"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb922-1"><a href="thursday-october-5-2022.html#cb922-1" aria-hidden="true" tabindex="-1"></a>nMarked <span class="ot">&lt;-</span> <span class="cn">NULL</span></span>
<span id="cb922-2"><a href="thursday-october-5-2022.html#cb922-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(postNF)) {</span>
<span id="cb922-3"><a href="thursday-october-5-2022.html#cb922-3" aria-hidden="true" tabindex="-1"></a>  nMarked[i] <span class="ot">&lt;-</span> <span class="fu">pickFish</span>(postNF[i])</span>
<span id="cb922-4"><a href="thursday-october-5-2022.html#cb922-4" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb922-5"><a href="thursday-october-5-2022.html#cb922-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb922-6"><a href="thursday-october-5-2022.html#cb922-6" aria-hidden="true" tabindex="-1"></a>post2NF <span class="ot">&lt;-</span> postNF[nMarked <span class="sc">==</span> <span class="dv">6</span>]</span></code></pre></div>
<p>Again put the prior and posterior in a single data frame and plot.</p>
<div class="sourceCode" id="cb923"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb923-1"><a href="thursday-october-5-2022.html#cb923-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Distribution =</span> <span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">&quot;(A) Prior Distribution&quot;</span>, <span class="st">&quot;(B) Posterior Distribution&quot;</span>), </span>
<span id="cb923-2"><a href="thursday-october-5-2022.html#cb923-2" aria-hidden="true" tabindex="-1"></a>                                   <span class="fu">c</span>(<span class="fu">length</span>(postNF), <span class="fu">length</span>(post2NF))), </span>
<span id="cb923-3"><a href="thursday-october-5-2022.html#cb923-3" aria-hidden="true" tabindex="-1"></a>                 <span class="at">Values =</span> <span class="fu">c</span>(postNF, post2NF))</span>
<span id="cb923-4"><a href="thursday-october-5-2022.html#cb923-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> df, </span>
<span id="cb923-5"><a href="thursday-october-5-2022.html#cb923-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> Values)) <span class="sc">+</span></span>
<span id="cb923-6"><a href="thursday-october-5-2022.html#cb923-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">y =</span> (..density..) <span class="sc">*</span> <span class="dv">20</span>), </span>
<span id="cb923-7"><a href="thursday-october-5-2022.html#cb923-7" aria-hidden="true" tabindex="-1"></a>                 <span class="at">binwidth =</span> <span class="dv">10</span>, <span class="at">color =</span> <span class="st">&quot;white&quot;</span>, </span>
<span id="cb923-8"><a href="thursday-october-5-2022.html#cb923-8" aria-hidden="true" tabindex="-1"></a>                 <span class="at">fill =</span> <span class="st">&quot;salmon&quot;</span>) <span class="sc">+</span></span>
<span id="cb923-9"><a href="thursday-october-5-2022.html#cb923-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">20</span>, <span class="dv">250</span>)) <span class="sc">+</span></span>
<span id="cb923-10"><a href="thursday-october-5-2022.html#cb923-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> Distribution, <span class="at">ncol =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb923-11"><a href="thursday-october-5-2022.html#cb923-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Number of Fish in the Lake&quot;</span>) <span class="sc">+</span></span>
<span id="cb923-12"><a href="thursday-october-5-2022.html#cb923-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Probability&quot;</span>) <span class="sc">+</span></span>
<span id="cb923-13"><a href="thursday-october-5-2022.html#cb923-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="at">label =</span> <span class="st">&quot;How many fish are there in the lake?&quot;</span>) <span class="sc">+</span></span>
<span id="cb923-14"><a href="thursday-october-5-2022.html#cb923-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<pre><code>## Warning: Removed 4 rows containing missing values (geom_bar).</code></pre>
<p><img src="QG-2022_files/figure-html/unnamed-chunk-439-1.png" width="672" /></p>
<p>The new data pushes the posterior median toward a lower count relative to the posterior median from the original model. It also considerably reduces the uncertainty. Given this model, the probability that there are more than 200 fish in the lake is about .1%, down from 5%.</p>
<div class="sourceCode" id="cb925"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb925-1"><a href="thursday-october-5-2022.html#cb925-1" aria-hidden="true" tabindex="-1"></a><span class="fu">median</span>(post2NF)</span></code></pre></div>
<pre><code>## [1] 79</code></pre>
<div class="sourceCode" id="cb927"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb927-1"><a href="thursday-october-5-2022.html#cb927-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(post2NF <span class="sc">&gt;</span> <span class="dv">200</span>)<span class="sc">/</span><span class="fu">length</span>(post2NF) <span class="sc">*</span> <span class="dv">100</span></span></code></pre></div>
<pre><code>## [1] 0</code></pre>
</div>
<div id="percentage-of-survey-signups" class="section level2 unnumbered">
<h2>Percentage of survey signups</h2>
<p>Let’s consider another example. You are studying attitudes toward race in America since the election of Trump and you want to determine the likely response rate before you send out a large survey on attitudes. I use the pronoun ‘you’ because I really want you to imagine yourself in this situation.</p>
<p>Your adviser suggests that you will get the best response rate using an email listserv (your advisor is obviously older than you). So you ask 16 people on the listserv and get 6 positive responses (6 are willing to take your survey): 6/16 = 38%</p>
<p>What is a good guess for the positive response rate when you start sending out the survey to everyone on the listserv? How uncertain is this guess? Perhaps 38% is good guess, but the uncertainty is large.</p>
<p>Recall: A Bayesian data analysis requires three things: 1) Data, 2) Generative Model, and 3) Prior: information you have before examining the data.</p>
</div>
<div id="a-generative-model-for-people-agreeing-to-take-your-survey" class="section level2 unnumbered">
<h2>A generative model for people agreeing to take your survey</h2>
<p>A. Assume there is single underlying rate at which each person agrees to take your survey. Say 55%.
B. “Ask” a number of people, where the chance of each person agreeing to take the survey is 55%.</p>
<p>“Ask” is in quotes because you are not going to actual ask. Rather you will use a random number function where the probability of getting a ‘yes’ is 55% and the probability of getting ‘no’ is 45%.</p>
<div class="sourceCode" id="cb929"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb929-1"><a href="thursday-october-5-2022.html#cb929-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">3045</span>)</span>
<span id="cb929-2"><a href="thursday-october-5-2022.html#cb929-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sample</span>(<span class="fu">c</span>(<span class="st">&quot;yes&quot;</span>, <span class="st">&quot;no&quot;</span>), </span>
<span id="cb929-3"><a href="thursday-october-5-2022.html#cb929-3" aria-hidden="true" tabindex="-1"></a>       <span class="at">size =</span> <span class="dv">16</span>,</span>
<span id="cb929-4"><a href="thursday-october-5-2022.html#cb929-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">prob =</span> <span class="fu">c</span>(.<span class="dv">55</span>, .<span class="dv">45</span>),</span>
<span id="cb929-5"><a href="thursday-october-5-2022.html#cb929-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">replace =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>##  [1] &quot;yes&quot; &quot;no&quot;  &quot;yes&quot; &quot;yes&quot; &quot;yes&quot; &quot;yes&quot; &quot;yes&quot; &quot;no&quot;  &quot;yes&quot; &quot;yes&quot; &quot;no&quot;  &quot;no&quot; 
## [13] &quot;no&quot;  &quot;no&quot;  &quot;no&quot;  &quot;yes&quot;</code></pre>
<p>C. Count how many people agreed to be surveyed.</p>
<p>In this case it is 9/16.</p>
<p>This is your generative model. A model where you can plug in the rate (parameter of interest) and generate data. Parameter values (e.g., 55%) –&gt; Ask 16 people –&gt; Data (positive response rate).</p>
<p>The problem is these simulated data are not really what you want. In fact you want just the opposite. You have data. You know that when you asked 16 actual people 6 of them said ‘yes.’</p>
<p>You want to go backwards. You have P(D|<span class="math inline">\(\theta\)</span>) but you want P(<span class="math inline">\(\theta\)</span>|D). From the data you want to figure out what the response rate could be. Data –&gt; Parameter values (theta?). What are reasonable values for theta that would give you the data you have (6 out 16).</p>
<p>The good news is you’re almost there. You just need one more thing; a prior.</p>
</div>
<div id="prior-for-the-response-rate" class="section level2 unnumbered">
<h2>Prior for the response rate</h2>
<p>What information do you have before seeing the data?</p>
<p>You need to use probability to represent uncertainty in all parts of your model. You have already included uncertainty in the generative model (e.g., through the <code>sample</code> function). But you need to include it on the parameter.</p>
<p>Here as before, you represent the uncertainty about the response rate as a uniform distribution between 0 and 1. Prior to seeing any data you assume that the response rate is equally likely to be any value between 0 and 100%.</p>
<p>Generate values from the prior and plot the distribution. Always a good idea to look at the distribution of your prior. Is it reasonable?</p>
<div class="sourceCode" id="cb931"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb931-1"><a href="thursday-october-5-2022.html#cb931-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb931-2"><a href="thursday-october-5-2022.html#cb931-2" aria-hidden="true" tabindex="-1"></a>M <span class="ot">&lt;-</span> <span class="dv">100000</span></span>
<span id="cb931-3"><a href="thursday-october-5-2022.html#cb931-3" aria-hidden="true" tabindex="-1"></a>priorRate <span class="ot">&lt;-</span> <span class="fu">runif</span>(<span class="at">n =</span> M, <span class="at">min =</span> <span class="dv">0</span>, <span class="at">max =</span> <span class="dv">1</span>)</span>
<span id="cb931-4"><a href="thursday-october-5-2022.html#cb931-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> <span class="fu">as.data.frame</span>(priorRate), </span>
<span id="cb931-5"><a href="thursday-october-5-2022.html#cb931-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> priorRate)) <span class="sc">+</span></span>
<span id="cb931-6"><a href="thursday-october-5-2022.html#cb931-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> .<span class="dv">1</span>, <span class="at">boundary =</span> <span class="dv">1</span>, </span>
<span id="cb931-7"><a href="thursday-october-5-2022.html#cb931-7" aria-hidden="true" tabindex="-1"></a>                 <span class="at">color =</span> <span class="st">&quot;white&quot;</span>, <span class="at">fill =</span> <span class="st">&quot;gray&quot;</span>) <span class="sc">+</span></span>
<span id="cb931-8"><a href="thursday-october-5-2022.html#cb931-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Response Rate&quot;</span>) <span class="sc">+</span></span>
<span id="cb931-9"><a href="thursday-october-5-2022.html#cb931-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="at">lab =</span> <span class="st">&quot;Prior distribution on the survey response rate&quot;</span>) <span class="sc">+</span></span>
<span id="cb931-10"><a href="thursday-october-5-2022.html#cb931-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="QG-2022_files/figure-html/unnamed-chunk-442-1.png" width="672" /></p>
</div>
<div id="define-the-generative-model-and-simulate-the-data" class="section level2 unnumbered">
<h2>Define the generative model and simulate the data</h2>
<p>You could use the <code>sample()</code> function as before and then added up all the <code>yes</code> responses but here the <code>rbinom()</code> function does that for you. It returns the number of 1’s in a sample of <code>size =</code> (here 16) when the probability of agreeing equals the <code>rate</code>.</p>
<div class="sourceCode" id="cb932"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb932-1"><a href="thursday-october-5-2022.html#cb932-1" aria-hidden="true" tabindex="-1"></a>genModel <span class="ot">&lt;-</span> <span class="cf">function</span>(rate){</span>
<span id="cb932-2"><a href="thursday-october-5-2022.html#cb932-2" aria-hidden="true" tabindex="-1"></a>  nYes <span class="ot">&lt;-</span> <span class="fu">rbinom</span>(<span class="dv">1</span>, <span class="at">size =</span> <span class="dv">16</span>, <span class="at">prob =</span> rate)</span>
<span id="cb932-3"><a href="thursday-october-5-2022.html#cb932-3" aria-hidden="true" tabindex="-1"></a>  nYes</span>
<span id="cb932-4"><a href="thursday-october-5-2022.html#cb932-4" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb932-5"><a href="thursday-october-5-2022.html#cb932-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb932-6"><a href="thursday-october-5-2022.html#cb932-6" aria-hidden="true" tabindex="-1"></a>nYes <span class="ot">&lt;-</span> <span class="cn">NULL</span></span>
<span id="cb932-7"><a href="thursday-october-5-2022.html#cb932-7" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>M) {</span>
<span id="cb932-8"><a href="thursday-october-5-2022.html#cb932-8" aria-hidden="true" tabindex="-1"></a>  nYes[i] <span class="ot">&lt;-</span> <span class="fu">genModel</span>(priorRate[i])</span>
<span id="cb932-9"><a href="thursday-october-5-2022.html#cb932-9" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div>
<p>Keep only those parameter values that resulted in the data that you actually observed (6 “yes”’s). Check that there are enough samples remaining (at least 1000).</p>
<div class="sourceCode" id="cb933"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb933-1"><a href="thursday-october-5-2022.html#cb933-1" aria-hidden="true" tabindex="-1"></a>postRate <span class="ot">&lt;-</span> priorRate[nYes <span class="sc">==</span> <span class="dv">6</span>]</span>
<span id="cb933-2"><a href="thursday-october-5-2022.html#cb933-2" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(postRate)</span></code></pre></div>
<pre><code>## [1] 5792</code></pre>
<p>Plot a histogram from the posterior values.</p>
<div class="sourceCode" id="cb935"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb935-1"><a href="thursday-october-5-2022.html#cb935-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> <span class="fu">as.data.frame</span>(postRate), </span>
<span id="cb935-2"><a href="thursday-october-5-2022.html#cb935-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> postRate)) <span class="sc">+</span></span>
<span id="cb935-3"><a href="thursday-october-5-2022.html#cb935-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> .<span class="dv">05</span>, <span class="at">boundary =</span> <span class="dv">1</span>, </span>
<span id="cb935-4"><a href="thursday-october-5-2022.html#cb935-4" aria-hidden="true" tabindex="-1"></a>                 <span class="at">color =</span> <span class="st">&quot;white&quot;</span>, <span class="at">fill =</span> <span class="st">&quot;gray&quot;</span>) <span class="sc">+</span></span>
<span id="cb935-5"><a href="thursday-october-5-2022.html#cb935-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb935-6"><a href="thursday-october-5-2022.html#cb935-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Response Rate&quot;</span>) <span class="sc">+</span></span>
<span id="cb935-7"><a href="thursday-october-5-2022.html#cb935-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="at">lab =</span> <span class="st">&quot;Posterior distribution on the survey response rate&quot;</span>) <span class="sc">+</span></span>
<span id="cb935-8"><a href="thursday-october-5-2022.html#cb935-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="QG-2022_files/figure-html/unnamed-chunk-445-1.png" width="672" /></p>
<p>Use sample statistic functions to summarize information about the posterior distribution.</p>
<div class="sourceCode" id="cb936"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb936-1"><a href="thursday-october-5-2022.html#cb936-1" aria-hidden="true" tabindex="-1"></a><span class="fu">median</span>(postRate)</span></code></pre></div>
<pre><code>## [1] 0.3850391</code></pre>
<div class="sourceCode" id="cb938"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb938-1"><a href="thursday-october-5-2022.html#cb938-1" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span>(postRate, <span class="at">probs =</span> <span class="fu">c</span>(.<span class="dv">25</span>, .<span class="dv">75</span>))</span></code></pre></div>
<pre><code>##       25%       75% 
## 0.3102800 0.4661823</code></pre>
<p>A good estimate of the response rate is 39% with there being a 50% (75% - 25%) chance that the response rate will be between 31% and 46%.</p>
<p>There is slightly more than a 1% chance that you will do better than a 65% positive response rate.</p>
<div class="sourceCode" id="cb940"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb940-1"><a href="thursday-october-5-2022.html#cb940-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(postRate <span class="sc">&gt;</span> .<span class="dv">65</span>)<span class="sc">/</span><span class="fu">length</span>(postRate) <span class="sc">*</span> <span class="dv">100</span></span></code></pre></div>
<pre><code>## [1] 1.260359</code></pre>
<p>Plot the prior and posterior distributions together.</p>
<div class="sourceCode" id="cb942"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb942-1"><a href="thursday-october-5-2022.html#cb942-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Distribution =</span> <span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">&quot;(A) Prior Distribution&quot;</span>, </span>
<span id="cb942-2"><a href="thursday-october-5-2022.html#cb942-2" aria-hidden="true" tabindex="-1"></a>                                     <span class="st">&quot;(B) Posterior Distribution&quot;</span>), </span>
<span id="cb942-3"><a href="thursday-october-5-2022.html#cb942-3" aria-hidden="true" tabindex="-1"></a>                                    <span class="fu">c</span>(M, <span class="fu">length</span>(postRate))), </span>
<span id="cb942-4"><a href="thursday-october-5-2022.html#cb942-4" aria-hidden="true" tabindex="-1"></a>                <span class="at">Rate =</span> <span class="fu">c</span>(priorRate, postRate))</span>
<span id="cb942-5"><a href="thursday-october-5-2022.html#cb942-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> df, </span>
<span id="cb942-6"><a href="thursday-october-5-2022.html#cb942-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> Rate)) <span class="sc">+</span></span>
<span id="cb942-7"><a href="thursday-october-5-2022.html#cb942-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">y =</span> (..density..) <span class="sc">*</span> .<span class="dv">1</span>), <span class="at">binwidth =</span> .<span class="dv">05</span>, <span class="at">boundary =</span> <span class="dv">1</span>,</span>
<span id="cb942-8"><a href="thursday-october-5-2022.html#cb942-8" aria-hidden="true" tabindex="-1"></a>                 <span class="at">color =</span> <span class="st">&quot;white&quot;</span>, <span class="at">fill =</span> <span class="st">&quot;gray&quot;</span>) <span class="sc">+</span></span>
<span id="cb942-9"><a href="thursday-october-5-2022.html#cb942-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb942-10"><a href="thursday-october-5-2022.html#cb942-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> Distribution, <span class="at">ncol =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb942-11"><a href="thursday-october-5-2022.html#cb942-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Probability&quot;</span>) <span class="sc">+</span> </span>
<span id="cb942-12"><a href="thursday-october-5-2022.html#cb942-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Response Rate&quot;</span>) <span class="sc">+</span></span>
<span id="cb942-13"><a href="thursday-october-5-2022.html#cb942-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="QG-2022_files/figure-html/unnamed-chunk-448-1.png" width="672" /></p>
<p>So how did you go from the prior to the posterior? Let’s take a response rate of 35% as an example. First a response rate of 35% had to be drawn from the prior and it did it with some probability you denote P(35%). That is, the probability of drawing a response rate of 35% is P(35%).</p>
<p>Now in order to keep this 35% it had to simulate data that matched the data you actually observed. And it did that with some probability that you denote P(6 “yes” | 35%). Probability of 6 positive responses (out of 16) given a response rate of 35%. Recall: the vertical line is read: “given.”</p>
<p>By multiplying these two probabilities you get the probability that 35% is the best estimate for the response rate given 6 yes responses, proportionally. That is,
<span class="math display">\[
P(35\% | 6 ) \propto P(35\%) \times P(6 | 35\%)
\]</span></p>
<p>To turn that proportionality into an equality you need to divide by the sum of all parameter value probabilities given the data.
<span class="math display">\[
P(35\% | 6 ) = \frac{P(35\%) \times P(6 | 35\%)}{\sum P(\theta\%) \times P(6 | \theta\%)}
\]</span></p>
<p>To review: You specified prior information <span class="math inline">\(P(\theta)\)</span>, a generative model <span class="math inline">\(P(D|\theta)\)</span>, and you calculated probabilities for the different parameter values given the data. In this case there was a single parameter value indicating the response rate.</p>
<p>But the cool thing is this general method works for any generative model and any number of parameter values.
<span class="math display">\[
P(\theta | D) = \frac{P(\theta) \times P(D|\theta)}{\sum P(\theta) \times P(D|\theta)}
\]</span>
Bayes Theorem.</p>
</div>
<div id="prediction" class="section level2 unnumbered">
<h2>Prediction</h2>
<p>Suppose the listserv you used had 100 people. What is the likely number of surveys that will get returned?</p>
<ol style="list-style-type: decimal">
<li>The answer is not a single number but a distribution over probable number of survey takers.</li>
<li>As before, the binomial distribution is a good candidate for how many people are willing to take the survey out of the 100 possible.</li>
<li>Don’t ‘throw away’ uncertainty, for example by using a summary of the posterior distribution. Instead use the full original posterior sample (all the values in the posterior).</li>
<li>The general pattern when calculating ‘derivatives’ of posterior values is to go through the values one-by-one, and perform a transformation (say, plugging in the value in a binomial distribution), and collect the new values in a vector.</li>
</ol>
<p>For example the first six values in the vector of posterior values are:</p>
<div class="sourceCode" id="cb943"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb943-1"><a href="thursday-october-5-2022.html#cb943-1" aria-hidden="true" tabindex="-1"></a>postRate[<span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>]</span></code></pre></div>
<pre><code>## [1] 0.4820880 0.2671866 0.3797752 0.3082588 0.2774445 0.2366580</code></pre>
<p>You can multiply any of these by 100 (and round) to get a count. But what value do you choose? Also, given a rate the count is a random value.</p>
<div class="sourceCode" id="cb945"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb945-1"><a href="thursday-october-5-2022.html#cb945-1" aria-hidden="true" tabindex="-1"></a>nSurveysX <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="dv">100</span> <span class="sc">*</span> postRate, <span class="dv">0</span>)</span></code></pre></div>
<p>To get a prediction about how many responses you need to take both these uncertainties into account.</p>
<p>This can be done with a <code>for</code> loop.</p>
<div class="sourceCode" id="cb946"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb946-1"><a href="thursday-october-5-2022.html#cb946-1" aria-hidden="true" tabindex="-1"></a>nSurveys <span class="ot">&lt;-</span> <span class="cn">NULL</span></span>
<span id="cb946-2"><a href="thursday-october-5-2022.html#cb946-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(postRate)){</span>
<span id="cb946-3"><a href="thursday-october-5-2022.html#cb946-3" aria-hidden="true" tabindex="-1"></a>  nSurveys[i] <span class="ot">&lt;-</span> <span class="fu">rbinom</span>(<span class="at">n =</span> <span class="dv">1</span>, <span class="at">size =</span> <span class="dv">100</span>, </span>
<span id="cb946-4"><a href="thursday-october-5-2022.html#cb946-4" aria-hidden="true" tabindex="-1"></a>                       <span class="at">prob =</span> postRate[i])</span>
<span id="cb946-5"><a href="thursday-october-5-2022.html#cb946-5" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div>
<p>But since <code>rbinom()</code> is vectorized (calculations are done in tandem) you can simply write it like this:</p>
<div class="sourceCode" id="cb947"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb947-1"><a href="thursday-october-5-2022.html#cb947-1" aria-hidden="true" tabindex="-1"></a>nSurveys <span class="ot">&lt;-</span> <span class="fu">rbinom</span>(<span class="at">n =</span> <span class="fu">length</span>(postRate), </span>
<span id="cb947-2"><a href="thursday-october-5-2022.html#cb947-2" aria-hidden="true" tabindex="-1"></a>                  <span class="at">size =</span> <span class="dv">100</span>, </span>
<span id="cb947-3"><a href="thursday-october-5-2022.html#cb947-3" aria-hidden="true" tabindex="-1"></a>                  <span class="at">prob =</span> postRate)</span>
<span id="cb947-4"><a href="thursday-october-5-2022.html#cb947-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb947-5"><a href="thursday-october-5-2022.html#cb947-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> <span class="fu">as.data.frame</span>(nSurveys), </span>
<span id="cb947-6"><a href="thursday-october-5-2022.html#cb947-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> nSurveys)) <span class="sc">+</span></span>
<span id="cb947-7"><a href="thursday-october-5-2022.html#cb947-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">5</span>, <span class="at">color =</span> <span class="st">&quot;white&quot;</span>) <span class="sc">+</span></span>
<span id="cb947-8"><a href="thursday-october-5-2022.html#cb947-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Number of Responses&quot;</span>) <span class="sc">+</span></span>
<span id="cb947-9"><a href="thursday-october-5-2022.html#cb947-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="at">lab =</span> <span class="st">&quot;Posterior predicted number of responses&quot;</span>, </span>
<span id="cb947-10"><a href="thursday-october-5-2022.html#cb947-10" aria-hidden="true" tabindex="-1"></a>          <span class="at">subtitle =</span> <span class="st">&quot;Given that 100 people were asked&quot;</span>) <span class="sc">+</span></span>
<span id="cb947-11"><a href="thursday-october-5-2022.html#cb947-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="QG-2022_files/figure-html/unnamed-chunk-452-1.png" width="672" /></p>
<p>So you are most likely to get about 40 surveys returned but it could be anywhere between 20 and 60.</p>
<p>Compare with <code>nSurveysX</code> where only one source of uncertainty is included.</p>
<div class="sourceCode" id="cb948"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb948-1"><a href="thursday-october-5-2022.html#cb948-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Uncertainty =</span> <span class="fu">c</span>(<span class="fu">rep</span>(<span class="st">&quot;Both&quot;</span>, <span class="fu">length</span>(nSurveys)), <span class="fu">rep</span>(<span class="st">&quot;One&quot;</span>, <span class="fu">length</span>(nSurveysX))), </span>
<span id="cb948-2"><a href="thursday-october-5-2022.html#cb948-2" aria-hidden="true" tabindex="-1"></a>                                 <span class="at">nSurveys =</span> <span class="fu">c</span>(nSurveys, nSurveysX))</span>
<span id="cb948-3"><a href="thursday-october-5-2022.html#cb948-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> df, </span>
<span id="cb948-4"><a href="thursday-october-5-2022.html#cb948-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> nSurveys)) <span class="sc">+</span></span>
<span id="cb948-5"><a href="thursday-october-5-2022.html#cb948-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">5</span>, <span class="at">color =</span> <span class="st">&quot;white&quot;</span>) <span class="sc">+</span></span>
<span id="cb948-6"><a href="thursday-october-5-2022.html#cb948-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> Uncertainty) <span class="sc">+</span></span>
<span id="cb948-7"><a href="thursday-october-5-2022.html#cb948-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Number of Responses&quot;</span>) <span class="sc">+</span></span>
<span id="cb948-8"><a href="thursday-october-5-2022.html#cb948-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="at">lab =</span> <span class="st">&quot;Posterior predicted number of responses&quot;</span>, </span>
<span id="cb948-9"><a href="thursday-october-5-2022.html#cb948-9" aria-hidden="true" tabindex="-1"></a>          <span class="at">subtitle =</span> <span class="st">&quot;Given that 100 people were asked&quot;</span>) <span class="sc">+</span></span>
<span id="cb948-10"><a href="thursday-october-5-2022.html#cb948-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="QG-2022_files/figure-html/unnamed-chunk-453-1.png" width="672" /></p>
<p>The histogram is slightly wider when both sources of uncertainty are included. Quantitatively you can see this with</p>
<div class="sourceCode" id="cb949"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb949-1"><a href="thursday-october-5-2022.html#cb949-1" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span>(nSurveys, <span class="at">probs =</span> <span class="fu">c</span>(.<span class="dv">25</span>, .<span class="dv">75</span>))</span></code></pre></div>
<pre><code>## 25% 75% 
##  30  47</code></pre>
<div class="sourceCode" id="cb951"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb951-1"><a href="thursday-october-5-2022.html#cb951-1" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span>(nSurveysX, <span class="at">probs =</span> <span class="fu">c</span>(.<span class="dv">25</span>, .<span class="dv">75</span>))</span></code></pre></div>
<pre><code>## 25% 75% 
##  31  47</code></pre>
</div>
<div id="approximate-bayesian-computation" class="section level2 unnumbered">
<h2>Approximate Bayesian computation</h2>
<p>The approximate Bayesian computation only works in rare cases. Conceptually easy, but very slow. Other much faster methods are available. All with the same end result (posterior distribution).</p>
<p>You don’t really need to worry about how they work precisely. They are just different ways of applying Bayes Theorem (combining the prior with the generative model (likelihood function) to get the posterior).</p>
</div>
<div id="what-bayesian-data-analysis-is-not" class="section level2 unnumbered">
<h2>What Bayesian data analysis is not</h2>
<p>A category of models (e.g., regression models, decision trees). Rather it is a way of thinking about and constructing models. You can do regression or machine learning with a Bayesian framework (e.g., Bayesian decision analysis).</p>
<p>Not subjective. All statistics require you make assumptions. Results have to be interpreted in light of those assumptions.</p>
<p>Nothing new. Thomas Bayes, Simon LaPlace, Ronald Fischer (first to use the term Bayesian statistics).</p>
</div>
<div id="comparing-two-hypotheses" class="section level2 unnumbered">
<h2>Comparing two hypotheses</h2>
<p>Recall that your adviser suggested that you will get the best response rate using a listserv. So you asked 16 people on the listserv and get 6 to respond positively (they would be willing to take your survey).</p>
<p>However, you feel that using social media might be better. So you direct message 16 randomly selected people from your twitter followers and get 10 people to respond positively.</p>
<p>Which seems to be the better method? Yes, there is some evidence that using social media is better. But how certain or uncertain should you be that this is the case?</p>
<p>You want to specify and fit a Bayesian model to answer these questions. The cool thing is that all you need to do is copy and paste the single-rate model.</p>
<p>Define and draw from the prior distributions.</p>
<div class="sourceCode" id="cb953"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb953-1"><a href="thursday-october-5-2022.html#cb953-1" aria-hidden="true" tabindex="-1"></a>priorRate1 <span class="ot">&lt;-</span> <span class="fu">runif</span>(<span class="at">n =</span> M, <span class="at">min =</span> <span class="dv">0</span>, <span class="at">max =</span> <span class="dv">1</span>)</span>
<span id="cb953-2"><a href="thursday-october-5-2022.html#cb953-2" aria-hidden="true" tabindex="-1"></a>priorRate2 <span class="ot">&lt;-</span> <span class="fu">runif</span>(<span class="at">n =</span> M, <span class="at">min =</span> <span class="dv">0</span>, <span class="at">max =</span> <span class="dv">1</span>)</span></code></pre></div>
<p>Generate data.</p>
<div class="sourceCode" id="cb954"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb954-1"><a href="thursday-october-5-2022.html#cb954-1" aria-hidden="true" tabindex="-1"></a>nYes1 <span class="ot">=</span> <span class="cn">NULL</span></span>
<span id="cb954-2"><a href="thursday-october-5-2022.html#cb954-2" aria-hidden="true" tabindex="-1"></a>nYes2 <span class="ot">=</span> <span class="cn">NULL</span></span>
<span id="cb954-3"><a href="thursday-october-5-2022.html#cb954-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>M) {</span>
<span id="cb954-4"><a href="thursday-october-5-2022.html#cb954-4" aria-hidden="true" tabindex="-1"></a>  nYes1[i] <span class="ot">&lt;-</span> <span class="fu">genModel</span>(priorRate1[i])</span>
<span id="cb954-5"><a href="thursday-october-5-2022.html#cb954-5" aria-hidden="true" tabindex="-1"></a>  nYes2[i] <span class="ot">&lt;-</span> <span class="fu">genModel</span>(priorRate2[i])</span>
<span id="cb954-6"><a href="thursday-october-5-2022.html#cb954-6" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div>
<p>Keep only those parameter values that result in the data that you actually observed (6 “yes”’s with rate 1 and 10 “yes”’s with rate 2).</p>
<div class="sourceCode" id="cb955"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb955-1"><a href="thursday-october-5-2022.html#cb955-1" aria-hidden="true" tabindex="-1"></a>postRate1 <span class="ot">&lt;-</span> priorRate1[nYes1 <span class="sc">==</span> <span class="dv">6</span>]</span>
<span id="cb955-2"><a href="thursday-october-5-2022.html#cb955-2" aria-hidden="true" tabindex="-1"></a>postRate2 <span class="ot">&lt;-</span> priorRate2[nYes2 <span class="sc">==</span> <span class="dv">10</span>]</span>
<span id="cb955-3"><a href="thursday-october-5-2022.html#cb955-3" aria-hidden="true" tabindex="-1"></a>difference <span class="ot">&lt;-</span> postRate2 <span class="sc">-</span> postRate1</span></code></pre></div>
<pre><code>## Warning in postRate2 - postRate1: longer object length is not a multiple of
## shorter object length</code></pre>
<div class="sourceCode" id="cb957"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb957-1"><a href="thursday-october-5-2022.html#cb957-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> <span class="fu">as.data.frame</span>(difference), </span>
<span id="cb957-2"><a href="thursday-october-5-2022.html#cb957-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> difference)) <span class="sc">+</span></span>
<span id="cb957-3"><a href="thursday-october-5-2022.html#cb957-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> .<span class="dv">05</span>, <span class="at">boundary =</span> <span class="dv">0</span>, <span class="at">color =</span> <span class="st">&quot;white&quot;</span>) <span class="sc">+</span></span>
<span id="cb957-4"><a href="thursday-october-5-2022.html#cb957-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">0</span>, <span class="at">color =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span></span>
<span id="cb957-5"><a href="thursday-october-5-2022.html#cb957-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Difference in Response Rates&quot;</span>) <span class="sc">+</span></span>
<span id="cb957-6"><a href="thursday-october-5-2022.html#cb957-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="at">lab =</span> <span class="st">&quot;Posterior distribution of difference in response rates&quot;</span>) <span class="sc">+</span></span>
<span id="cb957-7"><a href="thursday-october-5-2022.html#cb957-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="QG-2022_files/figure-html/unnamed-chunk-457-1.png" width="672" /></p>
<p>Positive differences indicate you are correct and that using social media will give you a better response rate.</p>
<p>What is the probability you are correct? That is answered from the posterior values as the relative number of positive differences.</p>
<div class="sourceCode" id="cb958"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb958-1"><a href="thursday-october-5-2022.html#cb958-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(difference <span class="sc">&gt;</span> <span class="dv">0</span>)<span class="sc">/</span><span class="fu">length</span>(difference) <span class="sc">*</span> <span class="dv">100</span></span></code></pre></div>
<pre><code>## [1] 91.6091</code></pre>
</div>
<div id="reaction-times-while-driving" class="section level2 unnumbered">
<h2>Reaction times while driving</h2>
<p>Cell phone use while driving is believed to increase the chance of an accident due to slowed reaction time. Recall that the data set <code>reaction.time</code> {UsingR} gives the time it takes to react to an external event while driving by various groups.</p>
<div class="sourceCode" id="cb960"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb960-1"><a href="thursday-october-5-2022.html#cb960-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> UsingR<span class="sc">::</span>reaction.time</span>
<span id="cb960-2"><a href="thursday-october-5-2022.html#cb960-2" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(df)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    60 obs. of  4 variables:
##  $ age    : Factor w/ 2 levels &quot;16-24&quot;,&quot;25+&quot;: 1 1 1 1 1 1 1 1 1 1 ...
##  $ gender : Factor w/ 2 levels &quot;F&quot;,&quot;M&quot;: 1 2 2 1 2 2 2 1 1 2 ...
##  $ control: Factor w/ 2 levels &quot;C&quot;,&quot;T&quot;: 2 2 2 2 2 1 2 2 2 1 ...
##  $ time   : num  1.36 1.47 1.51 1.39 1.38 ...</code></pre>
<p>The numeric variable ‘time’ is the reaction time in seconds. This is the response variable. The factor variable ‘control’ has two groups ‘C’ control (not using cell phone) and ‘T’ (using cell). The groups are not paired. The data set is in the long format.</p>
<p>Suppose you’re asked to see if the reaction time is shorter for those not using a cell phone. Start with a box plot of reaction times for the two groups (<code>C</code>: control and <code>T</code>: cell phone users).</p>
<div class="sourceCode" id="cb962"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb962-1"><a href="thursday-october-5-2022.html#cb962-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> df, </span>
<span id="cb962-2"><a href="thursday-october-5-2022.html#cb962-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> control, <span class="at">y =</span> time)) <span class="sc">+</span></span>
<span id="cb962-3"><a href="thursday-october-5-2022.html#cb962-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>()</span></code></pre></div>
<p><img src="QG-2022_files/figure-html/unnamed-chunk-460-1.png" width="672" /></p>
<p>In the classical setting you use a <span class="math inline">\(t\)</span>-test to examine whether the reaction time is slower for those not using a phone. In this setting the null hypothesis is that there is no difference in reaction times.</p>
<p>You use the model syntax: response ~ explanatory as the first argument in the <code>t.test()</code> function. You include an argument that names the data frame where the columns <code>time</code> and <code>control</code> are located. Here the alternative hypothesis is the reaction time is shorter in the control group so you include the argument <code>alternative = 'less'</code>.</p>
<div class="sourceCode" id="cb963"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb963-1"><a href="thursday-october-5-2022.html#cb963-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(time <span class="sc">~</span> control, </span>
<span id="cb963-2"><a href="thursday-october-5-2022.html#cb963-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">data =</span> df, </span>
<span id="cb963-3"><a href="thursday-october-5-2022.html#cb963-3" aria-hidden="true" tabindex="-1"></a>       <span class="at">alternative =</span> <span class="st">&#39;less&#39;</span>)</span></code></pre></div>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  time by control
## t = -2.2052, df = 29.834, p-value = 0.01765
## alternative hypothesis: true difference in means between group C and group T is less than 0
## 95 percent confidence interval:
##         -Inf -0.01288125
## sample estimates:
## mean in group C mean in group T 
##        1.389613        1.445571</code></pre>
<p>The evidence in support of the null hypothesis that the reaction times are the same in the population is summarized by the <span class="math inline">\(p\)</span>-value. The <span class="math inline">\(p\)</span>-value is .0176, so you conclude there is moderate evidence indicating cell phone use slows reaction times.</p>
<p>In a Bayesian setting, you can answer the question: what is the probability that mean reaction time is longer when using the phone?</p>
<p>The package {bayesAB} provides functions to analyze these kinds of comparison problems in a Bayesian framework. It is intended as a replacement for common hypothesis tests like the t-test and the chi-squared test.</p>
<div class="sourceCode" id="cb965"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb965-1"><a href="thursday-october-5-2022.html#cb965-1" aria-hidden="true" tabindex="-1"></a>control <span class="ot">&lt;-</span> df<span class="sc">$</span>time[df<span class="sc">$</span>control <span class="sc">==</span> <span class="st">&quot;C&quot;</span>]</span>
<span id="cb965-2"><a href="thursday-october-5-2022.html#cb965-2" aria-hidden="true" tabindex="-1"></a>cellUse <span class="ot">&lt;-</span> df<span class="sc">$</span>time[df<span class="sc">$</span>control <span class="sc">==</span> <span class="st">&quot;T&quot;</span>]</span>
<span id="cb965-3"><a href="thursday-october-5-2022.html#cb965-3" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(control, cellUse, <span class="at">alternative =</span> <span class="st">&#39;less&#39;</span>)</span></code></pre></div>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  control and cellUse
## t = -2.2052, df = 29.834, p-value = 0.01765
## alternative hypothesis: true difference in means is less than 0
## 95 percent confidence interval:
##         -Inf -0.01288125
## sample estimates:
## mean of x mean of y 
##  1.389613  1.445571</code></pre>
<p>Here the hyper priors come from a normal-inverse-gamma distribution.</p>
<div class="sourceCode" id="cb967"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb967-1"><a href="thursday-october-5-2022.html#cb967-1" aria-hidden="true" tabindex="-1"></a>AB <span class="ot">&lt;-</span> bayesAB<span class="sc">::</span><span class="fu">bayesTest</span>(cellUse, control, </span>
<span id="cb967-2"><a href="thursday-october-5-2022.html#cb967-2" aria-hidden="true" tabindex="-1"></a>                         <span class="at">priors =</span> <span class="fu">c</span>(<span class="st">&#39;mu&#39;</span> <span class="ot">=</span> <span class="dv">0</span>, <span class="st">&#39;lambda&#39;</span> <span class="ot">=</span> <span class="dv">1</span>, <span class="st">&#39;alpha&#39;</span> <span class="ot">=</span> <span class="dv">1</span>, <span class="st">&#39;beta&#39;</span> <span class="ot">=</span> <span class="dv">1</span>),</span>
<span id="cb967-3"><a href="thursday-october-5-2022.html#cb967-3" aria-hidden="true" tabindex="-1"></a>                         <span class="at">distribution =</span> <span class="st">&quot;normal&quot;</span>)</span>
<span id="cb967-4"><a href="thursday-october-5-2022.html#cb967-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(AB)</span></code></pre></div>
<pre><code>## Quantiles of posteriors for A and B:
## 
## $Mu
## $Mu$A
##       0%      25%      50%      75%     100% 
## 1.176399 1.376478 1.410490 1.444104 1.657856 
## 
## $Mu$B
##        0%       25%       50%       75%      100% 
## 0.8270401 1.2602478 1.3234247 1.3875455 1.8063457 
## 
## 
## $Sig_Sq
## $Sig_Sq$A
##         0%        25%        50%        75%       100% 
## 0.04577819 0.08921473 0.10295778 0.11990917 0.29091943 
## 
## $Sig_Sq$B
##         0%        25%        50%        75%       100% 
## 0.05628581 0.15481025 0.18908270 0.23426011 0.89825548 
## 
## 
## --------------------------------------------
## 
## P(A &gt; B) by (0, 0)%: 
## 
## $Mu
## [1] 0.78829
## 
## $Sig_Sq
## [1] 0.04959
## 
## --------------------------------------------
## 
## Credible Interval on (A - B) / B for interval length(s) (0.9, 0.9) : 
## 
## $Mu
##          5%         95% 
## -0.06527243  0.22799916 
## 
## $Sig_Sq
##           5%          95% 
## -0.714669531 -0.001414716 
## 
## --------------------------------------------
## 
## Posterior Expected Loss for choosing A over B:
## 
## $Mu
## [1] 0.0100392
## 
## $Sig_Sq
## [1] 0.997203</code></pre>
<p>The answer to our question is given after the <code>$Mu</code> in the output chunk that begins with <code>P(A &gt; B) by (0, 0)%</code>: .79 or 79% plus or minus 5%.</p>
<p>You can use the <code>plot</code> method on our <code>bayesAB</code> object to plot the prior and posterior distributions.</p>
<div class="sourceCode" id="cb969"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb969-1"><a href="thursday-october-5-2022.html#cb969-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(AB)</span></code></pre></div>
</div>
<div id="repeat-the-survey-example" class="section level2 unnumbered">
<h2>Repeat the survey example</h2>
<p>Here you repeat the survey example using function from the {bayesAB} package.</p>
<div class="sourceCode" id="cb970"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb970-1"><a href="thursday-october-5-2022.html#cb970-1" aria-hidden="true" tabindex="-1"></a>yourAdvisor <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>)</span>
<span id="cb970-2"><a href="thursday-october-5-2022.html#cb970-2" aria-hidden="true" tabindex="-1"></a>you <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>)</span>
<span id="cb970-3"><a href="thursday-october-5-2022.html#cb970-3" aria-hidden="true" tabindex="-1"></a>AB <span class="ot">&lt;-</span> bayesAB<span class="sc">::</span><span class="fu">bayesTest</span>(you, yourAdvisor, </span>
<span id="cb970-4"><a href="thursday-october-5-2022.html#cb970-4" aria-hidden="true" tabindex="-1"></a>                         <span class="at">priors =</span> <span class="fu">c</span>(<span class="st">&#39;alpha&#39;</span> <span class="ot">=</span> <span class="dv">1</span>, <span class="st">&#39;beta&#39;</span> <span class="ot">=</span> <span class="dv">1</span>), </span>
<span id="cb970-5"><a href="thursday-october-5-2022.html#cb970-5" aria-hidden="true" tabindex="-1"></a>                         <span class="at">distribution =</span> <span class="st">&quot;bernoulli&quot;</span>)</span>
<span id="cb970-6"><a href="thursday-october-5-2022.html#cb970-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(AB)</span></code></pre></div>
<pre><code>## Quantiles of posteriors for A and B:
## 
## $Probability
## $Probability$A
##        0%       25%       50%       75%      100% 
## 0.1454211 0.5350259 0.6149686 0.6903685 0.9507137 
## 
## $Probability$B
##        0%       25%       50%       75%      100% 
## 0.0581556 0.3089805 0.3848638 0.4651543 0.8241117 
## 
## 
## --------------------------------------------
## 
## P(A &gt; B) by (0)%: 
## 
## $Probability
## [1] 0.91488
## 
## --------------------------------------------
## 
## Credible Interval on (A - B) / B for interval length(s) (0.9) : 
## 
## $Probability
##          5%         95% 
## -0.08583841  2.03055869 
## 
## --------------------------------------------
## 
## Posterior Expected Loss for choosing A over B:
## 
## $Probability
## [1] 0.01554517</code></pre>
<p>More information:
<a href="https://www.youtube.com/watch?v=HZGCoVF3YvM">Bayes Theorem explained</a>.</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="tuesday-october-3-2022.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="tuesday-october-12-2022.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
