<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Thursday, September 8, 2022 | GEO5156: Quantitative Geography</title>
  <meta name="description" content="Thursday, September 8, 2022 | GEO5156: Quantitative Geography" />
  <meta name="generator" content="bookdown 0.27 and GitBook 2.6.7" />

  <meta property="og:title" content="Thursday, September 8, 2022 | GEO5156: Quantitative Geography" />
  <meta property="og:type" content="book" />
  
  
  <meta name="github-repo" content="jelsner/QG-2022" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Thursday, September 8, 2022 | GEO5156: Quantitative Geography" />
  
  
  

<meta name="author" content="James B. Elsner" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="tuesday-september-6-2022.html"/>
<link rel="next" href="tuesday-september-13-2022.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/htmlwidgets-1.5.4/htmlwidgets.js"></script>
<script src="libs/plotly-binding-4.10.0/plotly.js"></script>
<script src="libs/typedarray-0.1/typedarray.min.js"></script>
<link href="libs/crosstalk-1.2.0/css/crosstalk.min.css" rel="stylesheet" />
<script src="libs/crosstalk-1.2.0/js/crosstalk.min.js"></script>
<link href="libs/plotly-htmlwidgets-css-2.5.1/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="libs/plotly-main-2.5.1/plotly-latest.min.js"></script>
<link href="libs/leaflet-1.3.1/leaflet.css" rel="stylesheet" />
<script src="libs/leaflet-1.3.1/leaflet.js"></script>
<link href="libs/leafletfix-1.0.0/leafletfix.css" rel="stylesheet" />
<script src="libs/proj4-2.6.2/proj4.min.js"></script>
<script src="libs/Proj4Leaflet-1.0.1/proj4leaflet.js"></script>
<link href="libs/rstudio_leaflet-1.3.1/rstudio_leaflet.css" rel="stylesheet" />
<script src="libs/leaflet-binding-2.1.1/leaflet.js"></script>
<script src="libs/leaflet-providers-1.9.0/leaflet-providers_1.9.0.js"></script>
<script src="libs/leaflet-providers-plugin-2.1.1/leaflet-providers-plugin.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Quantitative Geography</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html"><i class="fa fa-check"></i>Syllabus</a>
<ul>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#geo5165c-quantitative-geography"><i class="fa fa-check"></i>GEO5165C: Quantitative Geography</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#contact-information"><i class="fa fa-check"></i>Contact information</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#course-description"><i class="fa fa-check"></i>Course description</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#grades"><i class="fa fa-check"></i>Grades</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#ethics"><i class="fa fa-check"></i>Ethics</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#schedule-subject-to-change-with-notice"><i class="fa fa-check"></i>Schedule (subject to change with notice)</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#deeper-dives"><i class="fa fa-check"></i>Deeper dives</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html"><i class="fa fa-check"></i>Tuesday, August 23, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#what-is-this-course"><i class="fa fa-check"></i>What is this course?</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#where-are-the-materials-for-this-course"><i class="fa fa-check"></i>Where are the materials for this course?</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#syllabus-1"><i class="fa fa-check"></i>Syllabus</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#getting-setup"><i class="fa fa-check"></i>Getting setup</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#rstudios-integrated-development-environment-ide"><i class="fa fa-check"></i>RStudio’s integrated development environment (IDE)</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#example-tallahassee-daily-temperatures"><i class="fa fa-check"></i>Example: Tallahassee daily temperatures</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html"><i class="fa fa-check"></i>Thursday, August 25, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#data-science"><i class="fa fa-check"></i>Data science</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#structure-of-markdown-files"><i class="fa fa-check"></i>Structure of markdown files</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#how-to-make-a-plot"><i class="fa fa-check"></i>How to make a plot</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#getting-started-using-r"><i class="fa fa-check"></i>Getting started using R</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html"><i class="fa fa-check"></i>Tuesday, August 30, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html#graphing-examples"><i class="fa fa-check"></i>Graphing examples</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html#working-with-r"><i class="fa fa-check"></i>Working with R</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html#data-vectors"><i class="fa fa-check"></i>Data vectors</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-september-1-2022.html"><a href="thursday-september-1-2022.html"><i class="fa fa-check"></i>Thursday, September 1, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-september-1-2022.html"><a href="thursday-september-1-2022.html#sample-statistics"><i class="fa fa-check"></i>Sample statistics</a></li>
<li class="chapter" data-level="" data-path="thursday-september-1-2022.html"><a href="thursday-september-1-2022.html#structured-data"><i class="fa fa-check"></i>Structured data</a></li>
<li class="chapter" data-level="" data-path="thursday-september-1-2022.html"><a href="thursday-september-1-2022.html#tables-and-summaries"><i class="fa fa-check"></i>Tables and summaries</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-september-6-2022.html"><a href="tuesday-september-6-2022.html"><i class="fa fa-check"></i>Tuesday, September 6, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-september-6-2022.html"><a href="tuesday-september-6-2022.html#getting-your-data-into-r"><i class="fa fa-check"></i>Getting your data into R</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-6-2022.html"><a href="tuesday-september-6-2022.html#data-frames"><i class="fa fa-check"></i>Data frames</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-september-8-2022.html"><a href="thursday-september-8-2022.html"><i class="fa fa-check"></i>Thursday, September 8, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-september-8-2022.html"><a href="thursday-september-8-2022.html#using-pipes"><i class="fa fa-check"></i>Using pipes</a></li>
<li class="chapter" data-level="" data-path="thursday-september-8-2022.html"><a href="thursday-september-8-2022.html#wrangling-data-frames"><i class="fa fa-check"></i>Wrangling data frames</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-september-13-2022.html"><a href="tuesday-september-13-2022.html"><i class="fa fa-check"></i>Tuesday, September 13, 2022</a>
<ul>
<li class="chapter" data-level="0.1" data-path="tuesday-september-13-2022.html"><a href="tuesday-september-13-2022.html#data-munging-examples"><i class="fa fa-check"></i><b>0.1</b> Data munging examples</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-13-2022.html"><a href="tuesday-september-13-2022.html#putting-things-together"><i class="fa fa-check"></i>Putting things together</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-september-15-2022.html"><a href="thursday-september-15-2022.html"><i class="fa fa-check"></i>Thursday, September 15, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-september-15-2022.html"><a href="thursday-september-15-2022.html#data-visualization"><i class="fa fa-check"></i>Data visualization</a></li>
<li class="chapter" data-level="" data-path="thursday-september-15-2022.html"><a href="thursday-september-15-2022.html#transforming-the-response-variable"><i class="fa fa-check"></i>Transforming the response variable</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-october-20-2022.html"><a href="thursday-october-20-2022.html"><i class="fa fa-check"></i>Thursday, October 20, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-october-20-2022.html"><a href="thursday-october-20-2022.html#more-regression-examples"><i class="fa fa-check"></i>More regression examples</a></li>
<li class="chapter" data-level="" data-path="thursday-october-20-2022.html"><a href="thursday-october-20-2022.html#outliers"><i class="fa fa-check"></i>Outliers</a></li>
<li class="chapter" data-level="" data-path="thursday-october-20-2022.html"><a href="thursday-october-20-2022.html#simpsons-paradox"><i class="fa fa-check"></i>Simpson’s paradox</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-october-25-2022.html"><a href="tuesday-october-25-2022.html"><i class="fa fa-check"></i>Tuesday, October 25, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-october-25-2022.html"><a href="tuesday-october-25-2022.html#a-regression-plane"><i class="fa fa-check"></i>A regression plane</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-25-2022.html"><a href="tuesday-october-25-2022.html#fitting-a-multiple-variable-regression-model"><i class="fa fa-check"></i>Fitting a multiple variable regression model</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-25-2022.html"><a href="tuesday-october-25-2022.html#should-you-remove-a-variable-from-the-model"><i class="fa fa-check"></i>Should you remove a variable from the model?</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-25-2022.html"><a href="tuesday-october-25-2022.html#checking-on-the-model-assumptions"><i class="fa fa-check"></i>Checking on the model assumptions</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-25-2022.html"><a href="tuesday-october-25-2022.html#using-the-model-to-make-predictions"><i class="fa fa-check"></i>Using the model to make predictions</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-25-2022.html"><a href="tuesday-october-25-2022.html#collinearity"><i class="fa fa-check"></i>Collinearity</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-25-2022.html"><a href="tuesday-october-25-2022.html#interactions"><i class="fa fa-check"></i>Interactions</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-october-27-2022.html"><a href="thursday-october-27-2022.html"><i class="fa fa-check"></i>Thursday, October 27, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-october-27-2022.html"><a href="thursday-october-27-2022.html#removing-variables-from-a-regression-model"><i class="fa fa-check"></i>Removing variables from a regression model</a></li>
<li class="chapter" data-level="" data-path="thursday-october-27-2022.html"><a href="thursday-october-27-2022.html#the-stepwise-selection-procedure"><i class="fa fa-check"></i>The stepwise selection procedure</a></li>
<li class="chapter" data-level="" data-path="thursday-october-27-2022.html"><a href="thursday-october-27-2022.html#transforming-a-response-variable"><i class="fa fa-check"></i>Transforming a response variable</a></li>
<li class="chapter" data-level="" data-path="thursday-october-27-2022.html"><a href="thursday-october-27-2022.html#regression-trees"><i class="fa fa-check"></i>Regression trees</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-november-1-2022.html"><a href="tuesday-november-1-2022.html"><i class="fa fa-check"></i>Tuesday, November 1, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-november-1-2022.html"><a href="tuesday-november-1-2022.html#predictive-uncertainty-with-regression-trees"><i class="fa fa-check"></i>Predictive uncertainty with regression trees</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-1-2022.html"><a href="tuesday-november-1-2022.html#the-random-forest-algorithm"><i class="fa fa-check"></i>The random forest algorithm</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-1-2022.html"><a href="tuesday-november-1-2022.html#cross-validation"><i class="fa fa-check"></i>Cross validation</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-1-2022.html"><a href="tuesday-november-1-2022.html#classification-trees"><i class="fa fa-check"></i>Classification trees</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-november-3-2022.html"><a href="thursday-november-3-2022.html"><i class="fa fa-check"></i>Thursday, November 3, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-november-3-2022.html"><a href="thursday-november-3-2022.html#binary-outcomes-and-probabilities"><i class="fa fa-check"></i>Binary outcomes and probabilities</a></li>
<li class="chapter" data-level="" data-path="thursday-november-3-2022.html"><a href="thursday-november-3-2022.html#logistic-regression"><i class="fa fa-check"></i>Logistic regression</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-november-8-2022.html"><a href="tuesday-november-8-2022.html"><i class="fa fa-check"></i>Tuesday, November 8, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-november-8-2022.html"><a href="tuesday-november-8-2022.html#quantifying-autocorrelation-in-spatial-data"><i class="fa fa-check"></i>Quantifying autocorrelation in spatial data</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-8-2022.html"><a href="tuesday-november-8-2022.html#spatial-data-as-polygon-areas"><i class="fa fa-check"></i>Spatial data as polygon areas</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-8-2022.html"><a href="tuesday-november-8-2022.html#nearest-neighbors"><i class="fa fa-check"></i>Nearest neighbors</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-8-2022.html"><a href="tuesday-november-8-2022.html#spatial-weights"><i class="fa fa-check"></i>Spatial weights</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-8-2022.html"><a href="tuesday-november-8-2022.html#morans-i"><i class="fa fa-check"></i>Moran’s I</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-8-2022.html"><a href="tuesday-november-8-2022.html#spatial-lag-variable"><i class="fa fa-check"></i>Spatial lag variable</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-november-10-2022.html"><a href="thursday-november-10-2022.html"><i class="fa fa-check"></i>Thursday, November 10, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-november-10-2022.html"><a href="thursday-november-10-2022.html#statistical-significance-of-spatial-autocorrelation"><i class="fa fa-check"></i>Statistical significance of spatial autocorrelation</a></li>
<li class="chapter" data-level="" data-path="thursday-november-10-2022.html"><a href="thursday-november-10-2022.html#a-monte-carlo-approach-to-inference-about-spatial-autocorrelation"><i class="fa fa-check"></i>A Monte Carlo approach to inference about spatial autocorrelation</a></li>
<li class="chapter" data-level="" data-path="thursday-november-10-2022.html"><a href="thursday-november-10-2022.html#spatial-autocorrelation-in-model-residuals"><i class="fa fa-check"></i>Spatial autocorrelation in model residuals</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-november-15-2022.html"><a href="tuesday-november-15-2022.html"><i class="fa fa-check"></i>Tuesday, November 15, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-november-15-2022.html"><a href="tuesday-november-15-2022.html#bi-variate-spatial-autocorrelation"><i class="fa fa-check"></i>Bi-variate spatial autocorrelation</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-15-2022.html"><a href="tuesday-november-15-2022.html#local-autocorrelation"><i class="fa fa-check"></i>Local autocorrelation</a></li>
<li class="chapter" data-level="0.2" data-path="tuesday-november-15-2022.html"><a href="tuesday-november-15-2022.html#local-regression"><i class="fa fa-check"></i><b>0.2</b> Local regression</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-15-2022.html"><a href="tuesday-november-15-2022.html#spatial-weights-1"><i class="fa fa-check"></i>Spatial weights</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-november-17-2022.html"><a href="thursday-november-17-2022.html"><i class="fa fa-check"></i>Thursday, November 17, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-november-17-2022.html"><a href="thursday-november-17-2022.html#geographic-regression"><i class="fa fa-check"></i>Geographic regression</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">GEO5156: Quantitative Geography</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="thursday-september-8-2022" class="section level1 unnumbered hasAnchor">
<h1>Thursday, September 8, 2022<a href="thursday-september-8-2022.html#thursday-september-8-2022" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>Today</p>
<ul>
<li>Using pipes</li>
<li>Wrangling data</li>
</ul>
<div id="using-pipes" class="section level2 unnumbered hasAnchor">
<h2>Using pipes<a href="thursday-september-8-2022.html#using-pipes" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Data wrangling (munging) is the process of transforming data from one format into another to make it easier to interpret it.</p>
<p>The {dplyr} package includes functions that wrangle data frames in a logical way. Key idea: The functions operate on data frames and return data frames.</p>
<p>Operations include selecting columns, filtering rows, re-ordering rows, adding new columns, and summarizing data.</p>
<div class="sourceCode" id="cb378"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb378-1"><a href="thursday-september-8-2022.html#cb378-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code></pre></div>
<p>Recall the object <code>airquality</code> is a data frame containing New York air quality measurements from May to September 1973. (<code>?airquality</code>).</p>
<p>You get a statistical summary of the values in each column with the <code>summary()</code> method.</p>
<div class="sourceCode" id="cb379"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb379-1"><a href="thursday-september-8-2022.html#cb379-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(airquality)</span></code></pre></div>
<pre><code>##      Ozone           Solar.R           Wind             Temp      
##  Min.   :  1.00   Min.   :  7.0   Min.   : 1.700   Min.   :56.00  
##  1st Qu.: 18.00   1st Qu.:115.8   1st Qu.: 7.400   1st Qu.:72.00  
##  Median : 31.50   Median :205.0   Median : 9.700   Median :79.00  
##  Mean   : 42.13   Mean   :185.9   Mean   : 9.958   Mean   :77.88  
##  3rd Qu.: 63.25   3rd Qu.:258.8   3rd Qu.:11.500   3rd Qu.:85.00  
##  Max.   :168.00   Max.   :334.0   Max.   :20.700   Max.   :97.00  
##  NA&#39;s   :37       NA&#39;s   :7                                       
##      Month            Day      
##  Min.   :5.000   Min.   : 1.0  
##  1st Qu.:6.000   1st Qu.: 8.0  
##  Median :7.000   Median :16.0  
##  Mean   :6.993   Mean   :15.8  
##  3rd Qu.:8.000   3rd Qu.:23.0  
##  Max.   :9.000   Max.   :31.0  
## </code></pre>
<p>Importantly you can apply the <code>summary()</code> function using the pipe operator (<code>|&gt;</code>). The pipe operator is part of the {dplyr} package and when used together with the wrangling functions, it provides a easy way to make code easy to read.</p>
<p>For example, you read the pipe as THEN. “<code>airquality</code> data frame THEN summarize”.</p>
<div class="sourceCode" id="cb381"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb381-1"><a href="thursday-september-8-2022.html#cb381-1" aria-hidden="true" tabindex="-1"></a>airquality <span class="sc">|&gt;</span> </span>
<span id="cb381-2"><a href="thursday-september-8-2022.html#cb381-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summary</span>()</span></code></pre></div>
<pre><code>##      Ozone           Solar.R           Wind             Temp      
##  Min.   :  1.00   Min.   :  7.0   Min.   : 1.700   Min.   :56.00  
##  1st Qu.: 18.00   1st Qu.:115.8   1st Qu.: 7.400   1st Qu.:72.00  
##  Median : 31.50   Median :205.0   Median : 9.700   Median :79.00  
##  Mean   : 42.13   Mean   :185.9   Mean   : 9.958   Mean   :77.88  
##  3rd Qu.: 63.25   3rd Qu.:258.8   3rd Qu.:11.500   3rd Qu.:85.00  
##  Max.   :168.00   Max.   :334.0   Max.   :20.700   Max.   :97.00  
##  NA&#39;s   :37       NA&#39;s   :7                                       
##      Month            Day      
##  Min.   :5.000   Min.   : 1.0  
##  1st Qu.:6.000   1st Qu.: 8.0  
##  Median :7.000   Median :16.0  
##  Mean   :6.993   Mean   :15.8  
##  3rd Qu.:8.000   3rd Qu.:23.0  
##  Max.   :9.000   Max.   :31.0  
## </code></pre>
<p>The pipe operator allows you to string together functions while keeping the code readable. You want your code to be machine readable (correct syntax) but also human readable.</p>
<p>For example, suppose the object of interest is called <code>me</code> and suppose there is a function called <code>wake_up()</code>. I can apply the function in two ways.</p>
<div class="sourceCode" id="cb383"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb383-1"><a href="thursday-september-8-2022.html#cb383-1" aria-hidden="true" tabindex="-1"></a><span class="fu">wake_up</span>(me)</span>
<span id="cb383-2"><a href="thursday-september-8-2022.html#cb383-2" aria-hidden="true" tabindex="-1"></a>me <span class="sc">|&gt;</span> </span>
<span id="cb383-3"><a href="thursday-september-8-2022.html#cb383-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">wake_up</span>()</span></code></pre></div>
<p>The second way involves a bit more typing but it is easier for someone to read and thus it is easier to understand. This becomes clear when stringing together many functions.</p>
<p>For example, what happens to the result of <code>me</code> after the function <code>wake_up()</code> has been applied? How about <code>get_out_of_bed()</code> and then <code>get_dressed()</code>? I can apply these functions in two ways.</p>
<div class="sourceCode" id="cb384"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb384-1"><a href="thursday-september-8-2022.html#cb384-1" aria-hidden="true" tabindex="-1"></a><span class="fu">get_dressed</span>(<span class="fu">get_out_of_bed</span>(<span class="fu">wake_up</span>(me)))</span>
<span id="cb384-2"><a href="thursday-september-8-2022.html#cb384-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb384-3"><a href="thursday-september-8-2022.html#cb384-3" aria-hidden="true" tabindex="-1"></a>me <span class="sc">|&gt;</span></span>
<span id="cb384-4"><a href="thursday-september-8-2022.html#cb384-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">wake_up</span>() <span class="sc">|&gt;</span></span>
<span id="cb384-5"><a href="thursday-september-8-2022.html#cb384-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">get_out_of_bed</span>() <span class="sc">|&gt;</span></span>
<span id="cb384-6"><a href="thursday-september-8-2022.html#cb384-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">get_dressed</span>()</span></code></pre></div>
<p>Continuing</p>
<div class="sourceCode" id="cb385"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb385-1"><a href="thursday-september-8-2022.html#cb385-1" aria-hidden="true" tabindex="-1"></a>me <span class="sc">|&gt;</span></span>
<span id="cb385-2"><a href="thursday-september-8-2022.html#cb385-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">wake_up</span>() <span class="sc">|&gt;</span></span>
<span id="cb385-3"><a href="thursday-september-8-2022.html#cb385-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">get_out_of_bed</span>() <span class="sc">|&gt;</span></span>
<span id="cb385-4"><a href="thursday-september-8-2022.html#cb385-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">get_dressed</span>() <span class="sc">|&gt;</span></span>
<span id="cb385-5"><a href="thursday-september-8-2022.html#cb385-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">make_coffee</span>() <span class="sc">|&gt;</span></span>
<span id="cb385-6"><a href="thursday-september-8-2022.html#cb385-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">drink_coffee</span>() <span class="sc">|&gt;</span></span>
<span id="cb385-7"><a href="thursday-september-8-2022.html#cb385-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">leave_house</span>()</span></code></pre></div>
<p>Which is much better in terms of ‘readability’ then <code>leave_house(drink_coffee(make_coffee(get_dressed(get_out_of_bed(wake_up(me))))))</code>.</p>
<p>Consider again the <code>FLp.df</code>.</p>
<div class="sourceCode" id="cb386"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb386-1"><a href="thursday-september-8-2022.html#cb386-1" aria-hidden="true" tabindex="-1"></a>loc <span class="ot">&lt;-</span> <span class="st">&quot;http://myweb.fsu.edu/jelsner/temp/data/FLprecip.txt&quot;</span></span>
<span id="cb386-2"><a href="thursday-september-8-2022.html#cb386-2" aria-hidden="true" tabindex="-1"></a>FLp.df <span class="ot">&lt;-</span> <span class="fu">read.table</span>(loc, </span>
<span id="cb386-3"><a href="thursday-september-8-2022.html#cb386-3" aria-hidden="true" tabindex="-1"></a>                     <span class="at">header =</span> <span class="cn">TRUE</span>,</span>
<span id="cb386-4"><a href="thursday-september-8-2022.html#cb386-4" aria-hidden="true" tabindex="-1"></a>                     <span class="at">na.string =</span> <span class="st">&quot;-9.900&quot;</span>)</span></code></pre></div>
<p>How would you use the above readable syntax to compute the mean value of June precipitation?</p>
<p>You ask three questions: what function, applied to what variable, from what data frame? Answers: <code>mean()</code>, <code>Jun</code>, <code>FLp.df</code>. You then write the code starting with the answer to the last question first.</p>
<div class="sourceCode" id="cb387"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb387-1"><a href="thursday-september-8-2022.html#cb387-1" aria-hidden="true" tabindex="-1"></a>FLp.df <span class="sc">|&gt;</span></span>
<span id="cb387-2"><a href="thursday-september-8-2022.html#cb387-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pull</span>(Jun)</span></code></pre></div>
<pre><code>##   [1]  4.500 11.228  5.221  3.292  5.803  9.993 10.360  6.220  7.012  6.591
##  [11]  5.160  8.040  6.392  6.351  6.739 10.288  4.820 12.379  5.531  4.202
##  [21]  5.321  6.541  5.362  5.349  7.481  6.258  3.673  6.540  9.308  6.470
##  [31]  6.281  8.168  7.450  7.057  8.158 10.858  2.303  8.378  5.182  9.865
##  [41]  5.099  8.940  5.931  6.998  9.734  7.049  7.707 10.529  7.348  5.607
##  [51]  8.578  7.098  9.106  3.908  8.000  4.089  4.747  3.643  7.876  5.588
##  [61]  6.392  5.422  7.748  6.147  8.389  6.789  5.896  8.317  7.118  5.614
##  [71] 10.032  8.880  8.488  9.939  6.142  5.866  5.602  8.432  5.887 10.276
##  [81]  6.269  7.002  4.401  6.900  3.898  4.838  5.718 10.280  8.969  5.098
##  [91]  7.009  7.451  5.696  4.739  8.976  5.724  7.666 12.034  4.598  9.349
## [101]  8.874  7.306  7.208  2.445  9.481  5.971  8.663 10.309 11.014  8.243
## [111] 11.824  5.752  5.998  6.991  6.171  5.440  4.965</code></pre>
<p>The function <code>pull()</code> from the {dplyr} packages pulls out the column named <code>Jun</code> and returns a vector of the values.</p>
<p>Then the <code>mean()</code> function takes these 118 values and computes the average.</p>
<div class="sourceCode" id="cb389"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb389-1"><a href="thursday-september-8-2022.html#cb389-1" aria-hidden="true" tabindex="-1"></a>FLp.df <span class="sc">|&gt;</span></span>
<span id="cb389-2"><a href="thursday-september-8-2022.html#cb389-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pull</span>(Jun) <span class="sc">|&gt;</span></span>
<span id="cb389-3"><a href="thursday-september-8-2022.html#cb389-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mean</span>()</span></code></pre></div>
<pre><code>## [1] 7.045692</code></pre>
<p>IMPORTANT: the next function in the sequence receives the output from the previous function as its FIRST argument so the function <code>mean()</code> has nothing inside the parentheses.</p>
<ol style="list-style-type: decimal">
<li>Use the piping operator and compute the average wind speed in the <code>airquality</code> data frame.</li>
</ol>
<div class="sourceCode" id="cb391"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb391-1"><a href="thursday-september-8-2022.html#cb391-1" aria-hidden="true" tabindex="-1"></a>airquality <span class="sc">|&gt;</span></span>
<span id="cb391-2"><a href="thursday-september-8-2022.html#cb391-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pull</span>(Wind) <span class="sc">|&gt;</span></span>
<span id="cb391-3"><a href="thursday-september-8-2022.html#cb391-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mean</span>()</span></code></pre></div>
<pre><code>## [1] 9.957516</code></pre>
<ol start="2" style="list-style-type: decimal">
<li>Use the piping operator and compute the 10th and 90th percentiles (lower and upper decile values) of May precipitation in Florida.</li>
</ol>
<div class="sourceCode" id="cb393"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb393-1"><a href="thursday-september-8-2022.html#cb393-1" aria-hidden="true" tabindex="-1"></a>FLp.df <span class="sc">|&gt;</span></span>
<span id="cb393-2"><a href="thursday-september-8-2022.html#cb393-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pull</span>(May) <span class="sc">|&gt;</span></span>
<span id="cb393-3"><a href="thursday-september-8-2022.html#cb393-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">quantile</span>(<span class="at">probs =</span> <span class="fu">c</span>(.<span class="dv">1</span>, .<span class="dv">9</span>))</span></code></pre></div>
<pre><code>##    10%    90% 
## 1.7954 6.0828</code></pre>
</div>
<div id="wrangling-data-frames" class="section level2 unnumbered hasAnchor">
<h2>Wrangling data frames<a href="thursday-september-8-2022.html#wrangling-data-frames" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>You will wrangle data with functions from the {dplyr} package. The functions work on data frames but they work better if the data frame is a <em>tibble</em>. Tibbles are data frames that make life a little easier.</p>
<p>R is an old language, and some things that were useful 10 or 20 years ago now get in the way. To make a data frame a tibble (tabular data frame) type</p>
<div class="sourceCode" id="cb395"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb395-1"><a href="thursday-september-8-2022.html#cb395-1" aria-hidden="true" tabindex="-1"></a>airquality <span class="ot">&lt;-</span> <span class="fu">as_tibble</span>(airquality)</span>
<span id="cb395-2"><a href="thursday-september-8-2022.html#cb395-2" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(airquality)</span></code></pre></div>
<pre><code>## [1] &quot;tbl_df&quot;     &quot;tbl&quot;        &quot;data.frame&quot;</code></pre>
<p>Click on <code>airquality</code> in the environment. It is a data frame.</p>
<p>Selecting and filtering</p>
<p>The function <code>select()</code> chooses variables by name to create a data frame with fewer columns. For example, choose the month, day, and temperature columns from the <code>airquality</code> data frame.</p>
<div class="sourceCode" id="cb397"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb397-1"><a href="thursday-september-8-2022.html#cb397-1" aria-hidden="true" tabindex="-1"></a>airquality <span class="sc">|&gt;</span></span>
<span id="cb397-2"><a href="thursday-september-8-2022.html#cb397-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(Month, Day, Temp)</span></code></pre></div>
<pre><code>## # A tibble: 153 × 3
##    Month   Day  Temp
##    &lt;int&gt; &lt;int&gt; &lt;int&gt;
##  1     5     1    67
##  2     5     2    72
##  3     5     3    74
##  4     5     4    62
##  5     5     5    56
##  6     5     6    66
##  7     5     7    65
##  8     5     8    59
##  9     5     9    61
## 10     5    10    69
## # … with 143 more rows
## # ℹ Use `print(n = ...)` to see more rows</code></pre>
<p>Suppose you want a new data frame with only the temperature and ozone concentrations.</p>
<div class="sourceCode" id="cb399"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb399-1"><a href="thursday-september-8-2022.html#cb399-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> airquality <span class="sc">|&gt;</span></span>
<span id="cb399-2"><a href="thursday-september-8-2022.html#cb399-2" aria-hidden="true" tabindex="-1"></a>        dplyr<span class="sc">::</span><span class="fu">select</span>(Temp, Ozone)</span>
<span id="cb399-3"><a href="thursday-september-8-2022.html#cb399-3" aria-hidden="true" tabindex="-1"></a>df</span></code></pre></div>
<pre><code>## # A tibble: 153 × 2
##     Temp Ozone
##    &lt;int&gt; &lt;int&gt;
##  1    67    41
##  2    72    36
##  3    74    12
##  4    62    18
##  5    56    NA
##  6    66    28
##  7    65    23
##  8    59    19
##  9    61     8
## 10    69    NA
## # … with 143 more rows
## # ℹ Use `print(n = ...)` to see more rows</code></pre>
<p>You include an assignment operator (<code>&lt;-</code>, left pointing arrow) and an object name (here <code>df</code>).</p>
<p>Note: The result of applying most {dplyr} verbs is a data frame. The take only data frames and return only data frames.</p>
<p>The function <code>filter()</code> chooses observations based on specific values.
<img src="https://raw.githubusercontent.com/allisonhorst/stats-illustrations/master/rstats-artwork/dplyr_filter.jpg" alt="filter" /></p>
<p>Suppose you want only the observations where the temperature is at or above 80F.</p>
<div class="sourceCode" id="cb401"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb401-1"><a href="thursday-september-8-2022.html#cb401-1" aria-hidden="true" tabindex="-1"></a>airquality <span class="sc">|&gt;</span></span>
<span id="cb401-2"><a href="thursday-september-8-2022.html#cb401-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">filter</span>(Temp <span class="sc">&gt;=</span> <span class="dv">80</span>)</span></code></pre></div>
<pre><code>## # A tibble: 73 × 6
##    Ozone Solar.R  Wind  Temp Month   Day
##    &lt;int&gt;   &lt;int&gt; &lt;dbl&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt;
##  1    45     252  14.9    81     5    29
##  2    NA     186   9.2    84     6     4
##  3    NA     220   8.6    85     6     5
##  4    29     127   9.7    82     6     7
##  5    NA     273   6.9    87     6     8
##  6    71     291  13.8    90     6     9
##  7    39     323  11.5    87     6    10
##  8    NA     259  10.9    93     6    11
##  9    NA     250   9.2    92     6    12
## 10    23     148   8      82     6    13
## # … with 63 more rows
## # ℹ Use `print(n = ...)` to see more rows</code></pre>
<p>The result is a data frame with the same 6 columns but now only 73 observations. Each of the observations has a temperature of at least 80F.</p>
<p>Suppose you want a new data frame keeping only observations where temperature is at least 80F AND winds less than 5 mph.</p>
<div class="sourceCode" id="cb403"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb403-1"><a href="thursday-september-8-2022.html#cb403-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> airquality <span class="sc">|&gt;</span> </span>
<span id="cb403-2"><a href="thursday-september-8-2022.html#cb403-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">filter</span>(Temp <span class="sc">&gt;=</span> <span class="dv">80</span> <span class="sc">&amp;</span> Wind <span class="sc">&lt;</span> <span class="dv">5</span>)</span>
<span id="cb403-3"><a href="thursday-september-8-2022.html#cb403-3" aria-hidden="true" tabindex="-1"></a>df</span></code></pre></div>
<pre><code>## # A tibble: 8 × 6
##   Ozone Solar.R  Wind  Temp Month   Day
##   &lt;int&gt;   &lt;int&gt; &lt;dbl&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt;
## 1   135     269   4.1    84     7     1
## 2    64     175   4.6    83     7     5
## 3    66      NA   4.6    87     8     6
## 4   122     255   4      89     8     7
## 5   168     238   3.4    81     8    25
## 6   118     225   2.3    94     8    29
## 7    73     183   2.8    93     9     3
## 8    91     189   4.6    93     9     4</code></pre>
<p>Example: Palmer penguins</p>
<p>Let’s return to the penguins data set. The data set is located on the web, and you import it as a data frame using the <code>readr::read_csv()</code> function.</p>
<div class="sourceCode" id="cb405"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb405-1"><a href="thursday-september-8-2022.html#cb405-1" aria-hidden="true" tabindex="-1"></a>loc <span class="ot">&lt;-</span> <span class="st">&quot;https://raw.githubusercontent.com/allisonhorst/palmerpenguins/master/inst/extdata/penguins.csv&quot;</span></span>
<span id="cb405-2"><a href="thursday-september-8-2022.html#cb405-2" aria-hidden="true" tabindex="-1"></a>penguins <span class="ot">&lt;-</span> readr<span class="sc">::</span><span class="fu">read_csv</span>(loc)</span></code></pre></div>
<pre><code>## Rows: 344 Columns: 8
## ── Column specification ────────────────────────────────────────────────────────
## Delimiter: &quot;,&quot;
## chr (3): species, island, sex
## dbl (5): bill_length_mm, bill_depth_mm, flipper_length_mm, body_mass_g, year
## 
## ℹ Use `spec()` to retrieve the full column specification for this data.
## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
<div class="sourceCode" id="cb407"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb407-1"><a href="thursday-september-8-2022.html#cb407-1" aria-hidden="true" tabindex="-1"></a>penguins</span></code></pre></div>
<pre><code>## # A tibble: 344 × 8
##    species island    bill_length_mm bill_depth_mm flipper_…¹ body_…² sex    year
##    &lt;chr&gt;   &lt;chr&gt;              &lt;dbl&gt;         &lt;dbl&gt;      &lt;dbl&gt;   &lt;dbl&gt; &lt;chr&gt; &lt;dbl&gt;
##  1 Adelie  Torgersen           39.1          18.7        181    3750 male   2007
##  2 Adelie  Torgersen           39.5          17.4        186    3800 fema…  2007
##  3 Adelie  Torgersen           40.3          18          195    3250 fema…  2007
##  4 Adelie  Torgersen           NA            NA           NA      NA &lt;NA&gt;   2007
##  5 Adelie  Torgersen           36.7          19.3        193    3450 fema…  2007
##  6 Adelie  Torgersen           39.3          20.6        190    3650 male   2007
##  7 Adelie  Torgersen           38.9          17.8        181    3625 fema…  2007
##  8 Adelie  Torgersen           39.2          19.6        195    4675 male   2007
##  9 Adelie  Torgersen           34.1          18.1        193    3475 &lt;NA&gt;   2007
## 10 Adelie  Torgersen           42            20.2        190    4250 &lt;NA&gt;   2007
## # … with 334 more rows, and abbreviated variable names ¹​flipper_length_mm,
## #   ²​body_mass_g
## # ℹ Use `print(n = ...)` to see more rows</code></pre>
<p>To keep only the penguins labeled in the column <code>sex</code> as <code>female</code> type</p>
<div class="sourceCode" id="cb409"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb409-1"><a href="thursday-september-8-2022.html#cb409-1" aria-hidden="true" tabindex="-1"></a>penguins <span class="sc">|&gt;</span> </span>
<span id="cb409-2"><a href="thursday-september-8-2022.html#cb409-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">filter</span>(sex <span class="sc">==</span> <span class="st">&quot;female&quot;</span>)</span></code></pre></div>
<pre><code>## # A tibble: 165 × 8
##    species island    bill_length_mm bill_depth_mm flipper_…¹ body_…² sex    year
##    &lt;chr&gt;   &lt;chr&gt;              &lt;dbl&gt;         &lt;dbl&gt;      &lt;dbl&gt;   &lt;dbl&gt; &lt;chr&gt; &lt;dbl&gt;
##  1 Adelie  Torgersen           39.5          17.4        186    3800 fema…  2007
##  2 Adelie  Torgersen           40.3          18          195    3250 fema…  2007
##  3 Adelie  Torgersen           36.7          19.3        193    3450 fema…  2007
##  4 Adelie  Torgersen           38.9          17.8        181    3625 fema…  2007
##  5 Adelie  Torgersen           41.1          17.6        182    3200 fema…  2007
##  6 Adelie  Torgersen           36.6          17.8        185    3700 fema…  2007
##  7 Adelie  Torgersen           38.7          19          195    3450 fema…  2007
##  8 Adelie  Torgersen           34.4          18.4        184    3325 fema…  2007
##  9 Adelie  Biscoe              37.8          18.3        174    3400 fema…  2007
## 10 Adelie  Biscoe              35.9          19.2        189    3800 fema…  2007
## # … with 155 more rows, and abbreviated variable names ¹​flipper_length_mm,
## #   ²​body_mass_g
## # ℹ Use `print(n = ...)` to see more rows</code></pre>
<p>To filter rows keeping only species that are not Adalie penguins.</p>
<div class="sourceCode" id="cb411"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb411-1"><a href="thursday-september-8-2022.html#cb411-1" aria-hidden="true" tabindex="-1"></a>penguins <span class="sc">|&gt;</span> </span>
<span id="cb411-2"><a href="thursday-september-8-2022.html#cb411-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">filter</span>(species <span class="sc">!=</span> <span class="st">&quot;Adelie&quot;</span>)</span></code></pre></div>
<pre><code>## # A tibble: 192 × 8
##    species island bill_length_mm bill_depth_mm flipper_len…¹ body_…² sex    year
##    &lt;chr&gt;   &lt;chr&gt;           &lt;dbl&gt;         &lt;dbl&gt;         &lt;dbl&gt;   &lt;dbl&gt; &lt;chr&gt; &lt;dbl&gt;
##  1 Gentoo  Biscoe           46.1          13.2           211    4500 fema…  2007
##  2 Gentoo  Biscoe           50            16.3           230    5700 male   2007
##  3 Gentoo  Biscoe           48.7          14.1           210    4450 fema…  2007
##  4 Gentoo  Biscoe           50            15.2           218    5700 male   2007
##  5 Gentoo  Biscoe           47.6          14.5           215    5400 male   2007
##  6 Gentoo  Biscoe           46.5          13.5           210    4550 fema…  2007
##  7 Gentoo  Biscoe           45.4          14.6           211    4800 fema…  2007
##  8 Gentoo  Biscoe           46.7          15.3           219    5200 male   2007
##  9 Gentoo  Biscoe           43.3          13.4           209    4400 fema…  2007
## 10 Gentoo  Biscoe           46.8          15.4           215    5150 male   2007
## # … with 182 more rows, and abbreviated variable names ¹​flipper_length_mm,
## #   ²​body_mass_g
## # ℹ Use `print(n = ...)` to see more rows</code></pre>
<p>When the column of interest is a numerical, you can filter rows by using greater than condition. For example, to create a data frame containing the heaviest penguins you filter keeping only rows with body mass greater than 6000 g.</p>
<div class="sourceCode" id="cb413"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb413-1"><a href="thursday-september-8-2022.html#cb413-1" aria-hidden="true" tabindex="-1"></a>penguins <span class="sc">|&gt;</span> </span>
<span id="cb413-2"><a href="thursday-september-8-2022.html#cb413-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">filter</span>(body_mass_g <span class="sc">&gt;</span> <span class="dv">6000</span>)</span></code></pre></div>
<pre><code>## # A tibble: 2 × 8
##   species island bill_length_mm bill_depth_mm flipper_leng…¹ body_…² sex    year
##   &lt;chr&gt;   &lt;chr&gt;           &lt;dbl&gt;         &lt;dbl&gt;          &lt;dbl&gt;   &lt;dbl&gt; &lt;chr&gt; &lt;dbl&gt;
## 1 Gentoo  Biscoe           49.2          15.2            221    6300 male   2007
## 2 Gentoo  Biscoe           59.6          17              230    6050 male   2007
## # … with abbreviated variable names ¹​flipper_length_mm, ²​body_mass_g</code></pre>
<p>You can also filter rows of a data frame with less than condition. For example, to create a data frame containing only penguins with short flippers you filter keeping only rows with flipper length less than 175 mm.</p>
<div class="sourceCode" id="cb415"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb415-1"><a href="thursday-september-8-2022.html#cb415-1" aria-hidden="true" tabindex="-1"></a>penguins <span class="sc">|&gt;</span> </span>
<span id="cb415-2"><a href="thursday-september-8-2022.html#cb415-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">filter</span>(flipper_length_mm <span class="sc">&lt;</span> <span class="dv">175</span>)</span></code></pre></div>
<pre><code>## # A tibble: 2 × 8
##   species island bill_length_mm bill_depth_mm flipper_leng…¹ body_…² sex    year
##   &lt;chr&gt;   &lt;chr&gt;           &lt;dbl&gt;         &lt;dbl&gt;          &lt;dbl&gt;   &lt;dbl&gt; &lt;chr&gt; &lt;dbl&gt;
## 1 Adelie  Biscoe           37.8          18.3            174    3400 fema…  2007
## 2 Adelie  Biscoe           37.9          18.6            172    3150 fema…  2007
## # … with abbreviated variable names ¹​flipper_length_mm, ²​body_mass_g</code></pre>
<p>You can also specify more than one conditions. For example to create a data frame with female penguins that have larger flippers you filter keeping only rows with flipper length greater than 220 mm and with sex equal to female.</p>
<div class="sourceCode" id="cb417"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb417-1"><a href="thursday-september-8-2022.html#cb417-1" aria-hidden="true" tabindex="-1"></a>penguins <span class="sc">|&gt;</span> </span>
<span id="cb417-2"><a href="thursday-september-8-2022.html#cb417-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">filter</span>(flipper_length_mm <span class="sc">&gt;</span> <span class="dv">220</span> <span class="sc">&amp;</span> </span>
<span id="cb417-3"><a href="thursday-september-8-2022.html#cb417-3" aria-hidden="true" tabindex="-1"></a>                sex <span class="sc">==</span> <span class="st">&quot;female&quot;</span>)</span></code></pre></div>
<pre><code>## # A tibble: 1 × 8
##   species island bill_length_mm bill_depth_mm flipper_leng…¹ body_…² sex    year
##   &lt;chr&gt;   &lt;chr&gt;           &lt;dbl&gt;         &lt;dbl&gt;          &lt;dbl&gt;   &lt;dbl&gt; &lt;chr&gt; &lt;dbl&gt;
## 1 Gentoo  Biscoe           46.9          14.6            222    4875 fema…  2009
## # … with abbreviated variable names ¹​flipper_length_mm, ²​body_mass_g</code></pre>
<p>You can also filter a data frame for rows satisfying one of the two conditions using OR. For example to create a data frame with penguins have large flippers or short bills you filter keeping rows with flipper length of at least 220 mm or with bill depth less than 10 mm.</p>
<div class="sourceCode" id="cb419"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb419-1"><a href="thursday-september-8-2022.html#cb419-1" aria-hidden="true" tabindex="-1"></a>penguins <span class="sc">|&gt;</span> </span>
<span id="cb419-2"><a href="thursday-september-8-2022.html#cb419-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">filter</span>(flipper_length_mm <span class="sc">&gt;</span> <span class="dv">220</span> <span class="sc">|</span> </span>
<span id="cb419-3"><a href="thursday-september-8-2022.html#cb419-3" aria-hidden="true" tabindex="-1"></a>                bill_depth_mm <span class="sc">&lt;</span> <span class="dv">10</span>)</span></code></pre></div>
<pre><code>## # A tibble: 35 × 8
##    species island bill_length_mm bill_depth_mm flipper_len…¹ body_…² sex    year
##    &lt;chr&gt;   &lt;chr&gt;           &lt;dbl&gt;         &lt;dbl&gt;         &lt;dbl&gt;   &lt;dbl&gt; &lt;chr&gt; &lt;dbl&gt;
##  1 Gentoo  Biscoe           50            16.3           230    5700 male   2007
##  2 Gentoo  Biscoe           49.2          15.2           221    6300 male   2007
##  3 Gentoo  Biscoe           48.7          15.1           222    5350 male   2007
##  4 Gentoo  Biscoe           47.3          15.3           222    5250 male   2007
##  5 Gentoo  Biscoe           59.6          17             230    6050 male   2007
##  6 Gentoo  Biscoe           49.6          16             225    5700 male   2008
##  7 Gentoo  Biscoe           50.5          15.9           222    5550 male   2008
##  8 Gentoo  Biscoe           50.5          15.9           225    5400 male   2008
##  9 Gentoo  Biscoe           50.1          15             225    5000 male   2008
## 10 Gentoo  Biscoe           50.4          15.3           224    5550 male   2008
## # … with 25 more rows, and abbreviated variable names ¹​flipper_length_mm,
## #   ²​body_mass_g
## # ℹ Use `print(n = ...)` to see more rows</code></pre>
<p>Often you want to remove rows if one of the columns has a missing value. With <code>is.na()</code> on the column of interest, you can filter rows based on whether or not a column value is missing.</p>
<p>Note the <code>is.na()</code> function returns a vector of TRUEs and FALSEs</p>
<div class="sourceCode" id="cb421"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb421-1"><a href="thursday-september-8-2022.html#cb421-1" aria-hidden="true" tabindex="-1"></a><span class="fu">is.na</span>(airquality<span class="sc">$</span>Ozone)</span></code></pre></div>
<pre><code>##   [1] FALSE FALSE FALSE FALSE  TRUE FALSE FALSE FALSE FALSE  TRUE FALSE FALSE
##  [13] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
##  [25]  TRUE  TRUE  TRUE FALSE FALSE FALSE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE
##  [37]  TRUE FALSE  TRUE FALSE FALSE  TRUE  TRUE FALSE  TRUE  TRUE FALSE FALSE
##  [49] FALSE FALSE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
##  [61]  TRUE FALSE FALSE FALSE  TRUE FALSE FALSE FALSE FALSE FALSE FALSE  TRUE
##  [73] FALSE FALSE  TRUE FALSE FALSE FALSE FALSE FALSE FALSE FALSE  TRUE  TRUE
##  [85] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
##  [97] FALSE FALSE FALSE FALSE FALSE  TRUE  TRUE FALSE FALSE FALSE  TRUE FALSE
## [109] FALSE FALSE FALSE FALSE FALSE FALSE  TRUE FALSE FALSE FALSE  TRUE FALSE
## [121] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
## [133] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
## [145] FALSE FALSE FALSE FALSE FALSE  TRUE FALSE FALSE FALSE</code></pre>
<p>The first four rows of the vector <code>Ozone</code> in the <code>airquality</code> data frame are not missing so the function <code>is.na()</code> returns four <code>FALSE</code>s.</p>
<p>When you combine that with the <code>filter()</code> function you get a data frame containing all the rows where <code>is.na()</code> returns a <code>TRUE</code>. For example, create a data frame containing rows where the bill length value is missing.</p>
<div class="sourceCode" id="cb423"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb423-1"><a href="thursday-september-8-2022.html#cb423-1" aria-hidden="true" tabindex="-1"></a>penguins <span class="sc">|&gt;</span> </span>
<span id="cb423-2"><a href="thursday-september-8-2022.html#cb423-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">filter</span>(<span class="fu">is.na</span>(bill_length_mm))</span></code></pre></div>
<pre><code>## # A tibble: 2 × 8
##   species island    bill_length_mm bill_depth_mm flipper_l…¹ body_…² sex    year
##   &lt;chr&gt;   &lt;chr&gt;              &lt;dbl&gt;         &lt;dbl&gt;       &lt;dbl&gt;   &lt;dbl&gt; &lt;chr&gt; &lt;dbl&gt;
## 1 Adelie  Torgersen             NA            NA          NA      NA &lt;NA&gt;   2007
## 2 Gentoo  Biscoe                NA            NA          NA      NA &lt;NA&gt;   2009
## # … with abbreviated variable names ¹​flipper_length_mm, ²​body_mass_g</code></pre>
<p>Usually you will want to do the reverse of this. That is keep all the rows where the column value is not missing. In this case use negation symbol <code>!</code> to reverse the selection. In this example, filter rows with no missing values for <code>sex</code> column.</p>
<div class="sourceCode" id="cb425"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb425-1"><a href="thursday-september-8-2022.html#cb425-1" aria-hidden="true" tabindex="-1"></a>penguins <span class="sc">|&gt;</span> </span>
<span id="cb425-2"><a href="thursday-september-8-2022.html#cb425-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(sex))</span></code></pre></div>
<pre><code>## # A tibble: 333 × 8
##    species island    bill_length_mm bill_depth_mm flipper_…¹ body_…² sex    year
##    &lt;chr&gt;   &lt;chr&gt;              &lt;dbl&gt;         &lt;dbl&gt;      &lt;dbl&gt;   &lt;dbl&gt; &lt;chr&gt; &lt;dbl&gt;
##  1 Adelie  Torgersen           39.1          18.7        181    3750 male   2007
##  2 Adelie  Torgersen           39.5          17.4        186    3800 fema…  2007
##  3 Adelie  Torgersen           40.3          18          195    3250 fema…  2007
##  4 Adelie  Torgersen           36.7          19.3        193    3450 fema…  2007
##  5 Adelie  Torgersen           39.3          20.6        190    3650 male   2007
##  6 Adelie  Torgersen           38.9          17.8        181    3625 fema…  2007
##  7 Adelie  Torgersen           39.2          19.6        195    4675 male   2007
##  8 Adelie  Torgersen           41.1          17.6        182    3200 fema…  2007
##  9 Adelie  Torgersen           38.6          21.2        191    3800 male   2007
## 10 Adelie  Torgersen           34.6          21.1        198    4400 male   2007
## # … with 323 more rows, and abbreviated variable names ¹​flipper_length_mm,
## #   ²​body_mass_g
## # ℹ Use `print(n = ...)` to see more rows</code></pre>
<p>Note that this filtering will keep rows with other column values that are missing values but there will be no penguins where the <code>sex</code> value is <code>NA</code>.</p>
<p>Stringing functions together</p>
<p>The function <code>arrange()</code> orders the rows by values given in a particular column.</p>
<div class="sourceCode" id="cb427"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb427-1"><a href="thursday-september-8-2022.html#cb427-1" aria-hidden="true" tabindex="-1"></a>airquality <span class="sc">|&gt;</span></span>
<span id="cb427-2"><a href="thursday-september-8-2022.html#cb427-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">arrange</span>(Solar.R)</span></code></pre></div>
<pre><code>## # A tibble: 153 × 6
##    Ozone Solar.R  Wind  Temp Month   Day
##    &lt;int&gt;   &lt;int&gt; &lt;dbl&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt;
##  1    16       7   6.9    74     7    21
##  2     1       8   9.7    59     5    21
##  3    23      13  12      67     5    28
##  4    23      14   9.2    71     9    22
##  5     8      19  20.1    61     5     9
##  6    14      20  16.6    63     9    25
##  7     9      24  13.8    81     8     2
##  8     9      24  10.9    71     9    14
##  9     4      25   9.7    61     5    23
## 10    13      27  10.3    76     9    18
## # … with 143 more rows
## # ℹ Use `print(n = ...)` to see more rows</code></pre>
<p>The ordering is from lowest value to highest value. Here the first 10 rows. Note <code>Month</code> and <code>Day</code> are no longer chronological.</p>
<p>Repeat but order by the value of air temperature.</p>
<div class="sourceCode" id="cb429"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb429-1"><a href="thursday-september-8-2022.html#cb429-1" aria-hidden="true" tabindex="-1"></a>airquality <span class="sc">|&gt;</span></span>
<span id="cb429-2"><a href="thursday-september-8-2022.html#cb429-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">arrange</span>(Temp)</span></code></pre></div>
<pre><code>## # A tibble: 153 × 6
##    Ozone Solar.R  Wind  Temp Month   Day
##    &lt;int&gt;   &lt;int&gt; &lt;dbl&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt;
##  1    NA      NA  14.3    56     5     5
##  2     6      78  18.4    57     5    18
##  3    NA      66  16.6    57     5    25
##  4    NA      NA   8      57     5    27
##  5    18      65  13.2    58     5    15
##  6    NA     266  14.9    58     5    26
##  7    19      99  13.8    59     5     8
##  8     1       8   9.7    59     5    21
##  9     8      19  20.1    61     5     9
## 10     4      25   9.7    61     5    23
## # … with 143 more rows
## # ℹ Use `print(n = ...)` to see more rows</code></pre>
<p>Importantly you can string the functions together. For example select the variables radiation, wind, and temperature then filter by temperatures above 90F and arrange from coolest to warmest by temperature.</p>
<div class="sourceCode" id="cb431"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb431-1"><a href="thursday-september-8-2022.html#cb431-1" aria-hidden="true" tabindex="-1"></a>airquality <span class="sc">|&gt;</span></span>
<span id="cb431-2"><a href="thursday-september-8-2022.html#cb431-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(Solar.R, Wind, Temp) <span class="sc">|&gt;</span></span>
<span id="cb431-3"><a href="thursday-september-8-2022.html#cb431-3" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">filter</span>(Temp <span class="sc">&gt;</span> <span class="dv">90</span>) <span class="sc">|&gt;</span></span>
<span id="cb431-4"><a href="thursday-september-8-2022.html#cb431-4" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">arrange</span>(Temp)</span></code></pre></div>
<pre><code>## # A tibble: 14 × 3
##    Solar.R  Wind  Temp
##      &lt;int&gt; &lt;dbl&gt; &lt;int&gt;
##  1     291  14.9    91
##  2     167   6.9    91
##  3     250   9.2    92
##  4     267   6.3    92
##  5     272   5.7    92
##  6     222   8.6    92
##  7     197   5.1    92
##  8     259  10.9    93
##  9     183   2.8    93
## 10     189   4.6    93
## 11     225   2.3    94
## 12     188   6.3    94
## 13     237   6.3    96
## 14     203   9.7    97</code></pre>
<p>The result is a data frame with three columns and 14 rows arranged by increasing temperatures above 90F.</p>
<p>The <code>mutate()</code> function adds new columns to the data frame.
<img src="figures/dplyr_mutate.png" alt="mutate" /></p>
<p>For example, create a new column called <code>TempC</code> as the temperature in degrees Celcius. Also create a column called <code>WindMS</code> as the wind speed in meters per second.</p>
<div class="sourceCode" id="cb433"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb433-1"><a href="thursday-september-8-2022.html#cb433-1" aria-hidden="true" tabindex="-1"></a>airquality <span class="sc">|&gt;</span></span>
<span id="cb433-2"><a href="thursday-september-8-2022.html#cb433-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">TempC =</span> (Temp <span class="sc">-</span> <span class="dv">32</span>) <span class="sc">*</span> <span class="dv">5</span><span class="sc">/</span><span class="dv">9</span>,</span>
<span id="cb433-3"><a href="thursday-september-8-2022.html#cb433-3" aria-hidden="true" tabindex="-1"></a>                <span class="at">WindMS =</span> Wind <span class="sc">*</span> .<span class="dv">44704</span>) </span></code></pre></div>
<pre><code>## # A tibble: 153 × 8
##    Ozone Solar.R  Wind  Temp Month   Day TempC WindMS
##    &lt;int&gt;   &lt;int&gt; &lt;dbl&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;dbl&gt;  &lt;dbl&gt;
##  1    41     190   7.4    67     5     1  19.4   3.31
##  2    36     118   8      72     5     2  22.2   3.58
##  3    12     149  12.6    74     5     3  23.3   5.63
##  4    18     313  11.5    62     5     4  16.7   5.14
##  5    NA      NA  14.3    56     5     5  13.3   6.39
##  6    28      NA  14.9    66     5     6  18.9   6.66
##  7    23     299   8.6    65     5     7  18.3   3.84
##  8    19      99  13.8    59     5     8  15     6.17
##  9     8      19  20.1    61     5     9  16.1   8.99
## 10    NA     194   8.6    69     5    10  20.6   3.84
## # … with 143 more rows
## # ℹ Use `print(n = ...)` to see more rows</code></pre>
<p>The resulting data frame has 8 columns (two new ones) labeled <code>TempC</code> and <code>WindMS</code>.</p>
<p>On days when the temperature is below 60 F add a column giving the apparent temperature based on the cooling effect of the wind (wind chill) and then arrange from coldest to warmest apparent temperature.</p>
<div class="sourceCode" id="cb435"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb435-1"><a href="thursday-september-8-2022.html#cb435-1" aria-hidden="true" tabindex="-1"></a>airquality <span class="sc">|&gt;</span></span>
<span id="cb435-2"><a href="thursday-september-8-2022.html#cb435-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">filter</span>(Temp <span class="sc">&lt;</span> <span class="dv">60</span>) <span class="sc">|&gt;</span></span>
<span id="cb435-3"><a href="thursday-september-8-2022.html#cb435-3" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">TempAp =</span> <span class="fl">35.74</span> <span class="sc">+</span> .<span class="dv">6215</span> <span class="sc">*</span> Temp <span class="sc">-</span> <span class="fl">35.75</span> <span class="sc">*</span> Wind<span class="sc">^</span>.<span class="dv">16</span> <span class="sc">+</span> .<span class="dv">4275</span> <span class="sc">*</span> Temp <span class="sc">*</span> Wind<span class="sc">^</span>.<span class="dv">16</span>) <span class="sc">|&gt;</span></span>
<span id="cb435-4"><a href="thursday-september-8-2022.html#cb435-4" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">arrange</span>(TempAp)</span></code></pre></div>
<pre><code>## # A tibble: 8 × 7
##   Ozone Solar.R  Wind  Temp Month   Day TempAp
##   &lt;int&gt;   &lt;int&gt; &lt;dbl&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt;  &lt;dbl&gt;
## 1    NA      NA  14.3    56     5     5   52.5
## 2     6      78  18.4    57     5    18   53.0
## 3    NA      66  16.6    57     5    25   53.3
## 4    NA     266  14.9    58     5    26   54.9
## 5    18      65  13.2    58     5    15   55.2
## 6    NA      NA   8      57     5    27   55.3
## 7    19      99  13.8    59     5     8   56.4
## 8     1       8   9.7    59     5    21   57.3</code></pre>
<p>Summarize</p>
<p>The <code>summarize()</code> function reduces (flattens) the data frame based on a function that computes a statistic. For example, to compute the average wind speed during July type</p>
<div class="sourceCode" id="cb437"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb437-1"><a href="thursday-september-8-2022.html#cb437-1" aria-hidden="true" tabindex="-1"></a>airquality <span class="sc">|&gt;</span></span>
<span id="cb437-2"><a href="thursday-september-8-2022.html#cb437-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">filter</span>(Month <span class="sc">==</span> <span class="dv">7</span>) <span class="sc">|&gt;</span></span>
<span id="cb437-3"><a href="thursday-september-8-2022.html#cb437-3" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">summarize</span>(<span class="at">Wavg =</span> <span class="fu">mean</span>(Wind))</span></code></pre></div>
<pre><code>## # A tibble: 1 × 1
##    Wavg
##   &lt;dbl&gt;
## 1  8.94</code></pre>
<div class="sourceCode" id="cb439"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb439-1"><a href="thursday-september-8-2022.html#cb439-1" aria-hidden="true" tabindex="-1"></a>airquality <span class="sc">|&gt;</span></span>
<span id="cb439-2"><a href="thursday-september-8-2022.html#cb439-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">filter</span>(Month <span class="sc">==</span> <span class="dv">6</span>) <span class="sc">|&gt;</span></span>
<span id="cb439-3"><a href="thursday-september-8-2022.html#cb439-3" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">summarize</span>(<span class="at">Tavg =</span> <span class="fu">mean</span>(Temp))</span></code></pre></div>
<pre><code>## # A tibble: 1 × 1
##    Tavg
##   &lt;dbl&gt;
## 1  79.1</code></pre>
<p>We have seen functions that compute statistics on vectors including <code>sum()</code>, <code>sd()</code>, <code>min()</code>, <code>max()</code>, <code>var()</code>, <code>range()</code>, <code>median()</code>. Others include</p>
<table>
<thead>
<tr class="header">
<th align="right">Summary function</th>
<th align="left">Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right"><code>dplyr::n()</code></td>
<td align="left">Length of the column</td>
</tr>
<tr class="even">
<td align="right"><code>dplyr::first()</code></td>
<td align="left">First value of the column</td>
</tr>
<tr class="odd">
<td align="right"><code>dplyr::last()</code></td>
<td align="left">Last value of the column</td>
</tr>
<tr class="even">
<td align="right"><code>dplyr::n_distinct()</code></td>
<td align="left">Number of distinct values</td>
</tr>
</tbody>
</table>
<p>Find the maximum and median wind speed and maximum ozone concentration values during the month of May. Also determine the number of observations during May.</p>
<div class="sourceCode" id="cb441"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb441-1"><a href="thursday-september-8-2022.html#cb441-1" aria-hidden="true" tabindex="-1"></a>airquality <span class="sc">|&gt;</span></span>
<span id="cb441-2"><a href="thursday-september-8-2022.html#cb441-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">filter</span>(Month <span class="sc">==</span> <span class="dv">5</span>) <span class="sc">|&gt;</span></span>
<span id="cb441-3"><a href="thursday-september-8-2022.html#cb441-3" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">summarize</span>(<span class="at">Wmax =</span> <span class="fu">max</span>(Wind), </span>
<span id="cb441-4"><a href="thursday-september-8-2022.html#cb441-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">Wmed =</span> <span class="fu">median</span>(Wind), </span>
<span id="cb441-5"><a href="thursday-september-8-2022.html#cb441-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">OzoneMax =</span> <span class="fu">max</span>(Ozone, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), </span>
<span id="cb441-6"><a href="thursday-september-8-2022.html#cb441-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">NumDays =</span> dplyr<span class="sc">::</span><span class="fu">n</span>())</span></code></pre></div>
<pre><code>## # A tibble: 1 × 4
##    Wmax  Wmed OzoneMax NumDays
##   &lt;dbl&gt; &lt;dbl&gt;    &lt;int&gt;   &lt;int&gt;
## 1  20.1  11.5      115      31</code></pre>
<p>Why do you get an <code>NA</code> for <code>OzoneMax</code>?</p>
<p>Fix this by including the argument <code>na.rm = TRUE</code> inside the <code>max()</code> function.</p>
<div class="sourceCode" id="cb443"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb443-1"><a href="thursday-september-8-2022.html#cb443-1" aria-hidden="true" tabindex="-1"></a>airquality <span class="sc">|&gt;</span></span>
<span id="cb443-2"><a href="thursday-september-8-2022.html#cb443-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">filter</span>(Month <span class="sc">==</span> <span class="dv">5</span>) <span class="sc">|&gt;</span></span>
<span id="cb443-3"><a href="thursday-september-8-2022.html#cb443-3" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">summarize</span>(<span class="at">Wmax =</span> <span class="fu">max</span>(Wind),</span>
<span id="cb443-4"><a href="thursday-september-8-2022.html#cb443-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">Wmed =</span> <span class="fu">median</span>(Wind),</span>
<span id="cb443-5"><a href="thursday-september-8-2022.html#cb443-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">OzoneMax =</span> <span class="fu">max</span>(Ozone, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb443-6"><a href="thursday-september-8-2022.html#cb443-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">NumDays =</span> dplyr<span class="sc">::</span><span class="fu">n</span>())</span></code></pre></div>
<pre><code>## # A tibble: 1 × 4
##    Wmax  Wmed OzoneMax NumDays
##   &lt;dbl&gt; &lt;dbl&gt;    &lt;int&gt;   &lt;int&gt;
## 1  20.1  11.5      115      31</code></pre>
<p>Grouping by column name</p>
<p>If you want to summarize separately for each month you use the <code>group_by()</code> function. You split the data frame by some variable (e.g., <code>Month</code>), apply a function to the individual data frames, and then combine the output.</p>
<p>Find the highest ozone concentration by month. Include the number of observations (days) in the month.</p>
<div class="sourceCode" id="cb445"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb445-1"><a href="thursday-september-8-2022.html#cb445-1" aria-hidden="true" tabindex="-1"></a>airquality <span class="sc">|&gt;</span></span>
<span id="cb445-2"><a href="thursday-september-8-2022.html#cb445-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">group_by</span>(Month) <span class="sc">|&gt;</span></span>
<span id="cb445-3"><a href="thursday-september-8-2022.html#cb445-3" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">summarize</span>(<span class="at">OzoneMax =</span>  <span class="fu">max</span>(Ozone, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb445-4"><a href="thursday-september-8-2022.html#cb445-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">NumDays =</span> dplyr<span class="sc">::</span><span class="fu">n</span>())</span></code></pre></div>
<pre><code>## # A tibble: 5 × 3
##   Month OzoneMax NumDays
##   &lt;int&gt;    &lt;int&gt;   &lt;int&gt;
## 1     5      115      31
## 2     6       71      30
## 3     7      135      31
## 4     8      168      31
## 5     9       96      30</code></pre>
<p>Find the average ozone concentration when temperatures are above and below 70 F. Include the number of observations (days) in the two groups.</p>
<div class="sourceCode" id="cb447"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb447-1"><a href="thursday-september-8-2022.html#cb447-1" aria-hidden="true" tabindex="-1"></a>airquality <span class="sc">|&gt;</span></span>
<span id="cb447-2"><a href="thursday-september-8-2022.html#cb447-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">group_by</span>(Temp <span class="sc">&gt;=</span> <span class="dv">70</span>) <span class="sc">|&gt;</span></span>
<span id="cb447-3"><a href="thursday-september-8-2022.html#cb447-3" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">summarize</span>(<span class="at">OzoneAvg =</span>  <span class="fu">mean</span>(Ozone, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb447-4"><a href="thursday-september-8-2022.html#cb447-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">NumDays =</span> dplyr<span class="sc">::</span><span class="fu">n</span>())</span></code></pre></div>
<pre><code>## # A tibble: 2 × 3
##   `Temp &gt;= 70` OzoneAvg NumDays
##   &lt;lgl&gt;           &lt;dbl&gt;   &lt;int&gt;
## 1 FALSE            18.0      32
## 2 TRUE             49.1     121</code></pre>
<p>On average ozone concentration is higher on warm days (Temp &gt;= 70 F) days. Said another way; mean ozone concentration statistically depends on temperature.</p>
<p>The mean is a model for the data. The statistical dependency of the mean implies that a model for ozone concentration will likely be improved by including temperature as an explanatory variable.</p>
<p>To summarize, the important verbs are</p>
<table>
<colgroup>
<col width="53%" />
<col width="46%" />
</colgroup>
<thead>
<tr class="header">
<th align="right">Verb</th>
<th align="left">Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right"><code>dplyr::select()</code></td>
<td align="left">selects columns; pick variables by their names</td>
</tr>
<tr class="even">
<td align="right"><code>dplyr::filter()</code></td>
<td align="left">filters rows; pick observations by their values</td>
</tr>
<tr class="odd">
<td align="right"><code>dplyr::mutate()</code></td>
<td align="left">creates new columns; create new variables with functions of existing variables</td>
</tr>
<tr class="even">
<td align="right"><code>dplyr::summarize()</code></td>
<td align="left">summarizes values; collapse many values down to a single summary</td>
</tr>
<tr class="odd">
<td align="right"><code>dplyr::group_by()</code></td>
<td align="left">allows operations to be grouped</td>
</tr>
</tbody>
</table>
<p>The syntax of the verb functions are all the same:</p>
<p>Properties
* The first argument is a data frame. This argument is implicit when using the <code>|&gt;</code> operator.
* The subsequent arguments describe what to do with the data frame. You refer to columns in the data frame directly (without using <code>$</code>).
* The result is a new data frame</p>
<p>These properties make it easy to chain together many simple lines of code to do something complex.</p>
<p>The five functions form the basis of a grammar for data. At the most basic level, you can only alter a data frame in five useful ways: you can reorder the rows (<code>arrange()</code>), pick observations and variables of interest (<code>filter()</code> and <code>select()</code>), add new variables that are functions of existing variables (<code>mutate()</code>), or collapse many values to a summary (<code>summarise()</code>).</p>
<p>Your turn</p>
<p>Consider again the Florida precipitation data set (<a href="http://myweb.fsu.edu/jelsner/temp/data/FLprecip.txt" class="uri">http://myweb.fsu.edu/jelsner/temp/data/FLprecip.txt</a>). Import the data as a data frame, select the columns <code>April</code> and <code>Year</code>, group by years &gt; 1960, then compute the mean and variance of the April rainfall with the <code>summarize()</code> function.</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="tuesday-september-6-2022.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="tuesday-september-13-2022.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
