<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Thursday, November 3, 2022 | GEO5156: Quantitative Geography</title>
  <meta name="description" content="Thursday, November 3, 2022 | GEO5156: Quantitative Geography" />
  <meta name="generator" content="bookdown 0.29 and GitBook 2.6.7" />

  <meta property="og:title" content="Thursday, November 3, 2022 | GEO5156: Quantitative Geography" />
  <meta property="og:type" content="book" />
  
  
  <meta name="github-repo" content="jelsner/QG-2022" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Thursday, November 3, 2022 | GEO5156: Quantitative Geography" />
  
  
  

<meta name="author" content="James B. Elsner" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="tuesday-november-1-2022.html"/>
<link rel="next" href="thursday-november-3-2022-1.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Quantitative Geography</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html"><i class="fa fa-check"></i>Syllabus</a>
<ul>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#geo5165c-quantitative-geography"><i class="fa fa-check"></i>GEO5165C: Quantitative Geography</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#contact-information"><i class="fa fa-check"></i>Contact information</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#course-description-and-expected-learning-outcomes"><i class="fa fa-check"></i>Course description and expected learning outcomes</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#grades-and-ethics"><i class="fa fa-check"></i>Grades and ethics</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#schedule-subject-to-change-with-notice"><i class="fa fa-check"></i>Schedule (subject to change with notice)</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#deeper-dives"><i class="fa fa-check"></i>Deeper dives</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html"><i class="fa fa-check"></i>Tuesday, August 23, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#what-is-this-course"><i class="fa fa-check"></i>What is this course?</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#where-are-the-materials-for-this-course"><i class="fa fa-check"></i>Where are the materials for this course?</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#get-the-syllabus"><i class="fa fa-check"></i>Get the syllabus</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#getting-setup"><i class="fa fa-check"></i>Getting setup</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#getting-to-know-rstudios-integrated-development-environment-ide"><i class="fa fa-check"></i>Getting to know RStudio’s integrated development environment (IDE)</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html"><i class="fa fa-check"></i>Thursday, August 25, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#data-science"><i class="fa fa-check"></i>Data science</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#structure-of-markdown-files"><i class="fa fa-check"></i>Structure of markdown files</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#how-to-make-a-plot"><i class="fa fa-check"></i>How to make a plot</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#getting-started-using-r"><i class="fa fa-check"></i>Getting started using R</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html"><i class="fa fa-check"></i>Tuesday, August 30, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html#graphing-examples"><i class="fa fa-check"></i>Graphing examples</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html#introduction-to-working-with-base-r"><i class="fa fa-check"></i>Introduction to working with base R</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html#data-as-vectors"><i class="fa fa-check"></i>Data as vectors</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-september-1-2022.html"><a href="thursday-september-1-2022.html"><i class="fa fa-check"></i>Thursday, September 1, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-september-1-2022.html"><a href="thursday-september-1-2022.html#statistical-summaries-of-data"><i class="fa fa-check"></i>Statistical summaries of data</a></li>
<li class="chapter" data-level="" data-path="thursday-september-1-2022.html"><a href="thursday-september-1-2022.html#structured-data"><i class="fa fa-check"></i>Structured data</a></li>
<li class="chapter" data-level="" data-path="thursday-september-1-2022.html"><a href="thursday-september-1-2022.html#tables"><i class="fa fa-check"></i>Tables</a></li>
<li class="chapter" data-level="" data-path="thursday-september-1-2022.html"><a href="thursday-september-1-2022.html#assignment-1"><i class="fa fa-check"></i>Assignment #1</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-september-6-2022.html"><a href="tuesday-september-6-2022.html"><i class="fa fa-check"></i>Tuesday, September 6, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-september-6-2022.html"><a href="tuesday-september-6-2022.html#getting-data-into-r"><i class="fa fa-check"></i>Getting data into R</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-6-2022.html"><a href="tuesday-september-6-2022.html#data-frames"><i class="fa fa-check"></i>Data frames</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-6-2022.html"><a href="tuesday-september-6-2022.html#piping-your-commands"><i class="fa fa-check"></i>Piping your commands</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-september-8-2022.html"><a href="thursday-september-8-2022.html"><i class="fa fa-check"></i>Thursday, September 8, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-september-8-2022.html"><a href="thursday-september-8-2022.html#data-transformation-with-dplyr"><i class="fa fa-check"></i>Data transformation with {dplyr}</a></li>
<li class="chapter" data-level="" data-path="thursday-september-8-2022.html"><a href="thursday-september-8-2022.html#from-data-import-to-final-plot"><i class="fa fa-check"></i>From data import to final plot</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-september-13-2022.html"><a href="tuesday-september-13-2022.html"><i class="fa fa-check"></i>Tuesday, September 13, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-september-13-2022.html"><a href="tuesday-september-13-2022.html#data-visualization"><i class="fa fa-check"></i>Data visualization</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-september-20-2022.html"><a href="tuesday-september-20-2022.html"><i class="fa fa-check"></i>Tuesday, September 20, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-september-20-2022.html"><a href="tuesday-september-20-2022.html#comparing-distributions"><i class="fa fa-check"></i>Comparing distributions</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-20-2022.html"><a href="tuesday-september-20-2022.html#visualizing-uncertainty"><i class="fa fa-check"></i>Visualizing uncertainty</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-20-2022.html"><a href="tuesday-september-20-2022.html#simple-feature-data-frames"><i class="fa fa-check"></i>Simple feature data frames</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-20-2022.html"><a href="tuesday-september-20-2022.html#making-a-boundary-map"><i class="fa fa-check"></i>Making a boundary map</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-september-22-2022.html"><a href="thursday-september-22-2022.html"><i class="fa fa-check"></i>Thursday, September 22, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-september-22-2022.html"><a href="thursday-september-22-2022.html#adding-data-to-boundary-maps"><i class="fa fa-check"></i>Adding data to boundary maps</a></li>
<li class="chapter" data-level="" data-path="thursday-september-22-2022.html"><a href="thursday-september-22-2022.html#changing-projections"><i class="fa fa-check"></i>Changing projections</a></li>
<li class="chapter" data-level="" data-path="thursday-september-22-2022.html"><a href="thursday-september-22-2022.html#mapping-using-functions-from-tmap"><i class="fa fa-check"></i>Mapping using functions from tmap</a></li>
<li class="chapter" data-level="" data-path="thursday-september-22-2022.html"><a href="thursday-september-22-2022.html#making-an-interactive-map"><i class="fa fa-check"></i>Making an interactive map</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-october-4-2022.html"><a href="tuesday-october-4-2022.html"><i class="fa fa-check"></i>Tuesday, October 4, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-october-4-2022.html"><a href="tuesday-october-4-2022.html#extended-mapping-example-tornado-frequency"><i class="fa fa-check"></i>Extended mapping example: tornado frequency</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-4-2022.html"><a href="tuesday-october-4-2022.html#geo-computation-on-simple-feature-data-frames"><i class="fa fa-check"></i>Geo-computation on simple feature data frames</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-4-2022.html"><a href="tuesday-october-4-2022.html#making-raster-maps"><i class="fa fa-check"></i>Making raster maps</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-4-2022.html"><a href="tuesday-october-4-2022.html#spatial-density-maps"><i class="fa fa-check"></i>Spatial density maps</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-4-2022.html"><a href="tuesday-october-4-2022.html#assignment-3"><i class="fa fa-check"></i>Assignment #3</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-september-29-2022.html"><a href="thursday-september-29-2022.html"><i class="fa fa-check"></i>Thursday, September 29, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-september-29-2022.html"><a href="thursday-september-29-2022.html#one-sample-test-for-the-value-of-the-population-mean"><i class="fa fa-check"></i>One-sample test for the value of the population mean</a></li>
<li class="chapter" data-level="" data-path="thursday-september-29-2022.html"><a href="thursday-september-29-2022.html#graphical-inference"><i class="fa fa-check"></i>Graphical inference</a></li>
<li class="chapter" data-level="" data-path="thursday-september-29-2022.html"><a href="thursday-september-29-2022.html#two-sample-test-for-a-difference-in-population-means"><i class="fa fa-check"></i>Two-sample test for a difference in population means</a></li>
<li class="chapter" data-level="" data-path="thursday-september-29-2022.html"><a href="thursday-september-29-2022.html#a-non-parameteric-test-for-difference-in-population-means"><i class="fa fa-check"></i>A non-parameteric test for difference in population means</a></li>
<li class="chapter" data-level="" data-path="thursday-september-29-2022.html"><a href="thursday-september-29-2022.html#paired-observations"><i class="fa fa-check"></i>Paired observations</a></li>
<li class="chapter" data-level="" data-path="thursday-september-29-2022.html"><a href="thursday-september-29-2022.html#chi-squared-test-for-independence"><i class="fa fa-check"></i>Chi-squared test for independence</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-october-11-2022.html"><a href="tuesday-october-11-2022.html"><i class="fa fa-check"></i>Tuesday, October 11, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-october-11-2022.html"><a href="tuesday-october-11-2022.html#distributions-as-lego-bricks"><i class="fa fa-check"></i>Distributions as Lego bricks</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-11-2022.html"><a href="tuesday-october-11-2022.html#bayesian-computation"><i class="fa fa-check"></i>Bayesian computation</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-11-2022.html"><a href="tuesday-october-11-2022.html#real-world-example"><i class="fa fa-check"></i>Real world example</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-11-2022.html"><a href="tuesday-october-11-2022.html#why-use-bayesian-models"><i class="fa fa-check"></i>Why use Bayesian models?</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-october-13-2022.html"><a href="thursday-october-13-2022.html"><i class="fa fa-check"></i>Thursday, October 13, 2022</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-18-2022.html"><a href="tuesday-october-18-2022.html"><i class="fa fa-check"></i>Tuesday, October 18, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-october-18-2022.html"><a href="tuesday-october-18-2022.html#linear-regression-a-t-test-by-another-name"><i class="fa fa-check"></i>Linear regression: A t test by another name</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-18-2022.html"><a href="tuesday-october-18-2022.html#motivation-for-the-regression-model"><i class="fa fa-check"></i>Motivation for the regression model</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-18-2022.html"><a href="tuesday-october-18-2022.html#making-predictions-with-the-regression-model"><i class="fa fa-check"></i>Making predictions with the regression model</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-18-2022.html"><a href="tuesday-october-18-2022.html#uncertainty-about-the-regression-model-coefficients"><i class="fa fa-check"></i>Uncertainty about the regression model coefficients</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-18-2022.html"><a href="tuesday-october-18-2022.html#bootstrapping-the-uncertainty"><i class="fa fa-check"></i>Bootstrapping the uncertainty</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-october-20-2022.html"><a href="thursday-october-20-2022.html"><i class="fa fa-check"></i>Thursday, October 20, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-october-20-2022.html"><a href="thursday-october-20-2022.html#predictive-uncertainty"><i class="fa fa-check"></i>Predictive uncertainty</a></li>
<li class="chapter" data-level="" data-path="thursday-october-20-2022.html"><a href="thursday-october-20-2022.html#model-adequacy"><i class="fa fa-check"></i>Model adequacy</a></li>
<li class="chapter" data-level="" data-path="thursday-october-20-2022.html"><a href="thursday-october-20-2022.html#regression-examples"><i class="fa fa-check"></i>Regression examples</a></li>
<li class="chapter" data-level="" data-path="thursday-october-20-2022.html"><a href="thursday-october-20-2022.html#outliers"><i class="fa fa-check"></i>Outliers</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-october-25-2022.html"><a href="tuesday-october-25-2022.html"><i class="fa fa-check"></i>Tuesday, October 25, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-october-25-2022.html"><a href="tuesday-october-25-2022.html#simpsons-paradox"><i class="fa fa-check"></i>Simpson’s paradox</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-25-2022.html"><a href="tuesday-october-25-2022.html#multiple-variable-regression"><i class="fa fa-check"></i>Multiple variable regression</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-25-2022.html"><a href="tuesday-october-25-2022.html#fitting-a-multiple-variable-regression-model"><i class="fa fa-check"></i>Fitting a multiple variable regression model</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-25-2022.html"><a href="tuesday-october-25-2022.html#should-you-remove-a-variable-from-your-model"><i class="fa fa-check"></i>Should you remove a variable from your model?</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-25-2022.html"><a href="tuesday-october-25-2022.html#checking-the-model-assumptions"><i class="fa fa-check"></i>Checking the model assumptions</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-25-2022.html"><a href="tuesday-october-25-2022.html#using-the-model-to-make-predictions"><i class="fa fa-check"></i>Using the model to make predictions</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-25-2022.html"><a href="tuesday-october-25-2022.html#collinearity-and-what-to-do-about-it"><i class="fa fa-check"></i>Collinearity and what to do about it</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-25-2022.html"><a href="tuesday-october-25-2022.html#how-to-include-and-interpret-interactions-terms"><i class="fa fa-check"></i>How to include and interpret interactions terms</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-november-1-2022.html"><a href="tuesday-november-1-2022.html"><i class="fa fa-check"></i>Tuesday, November 1, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-november-1-2022.html"><a href="tuesday-november-1-2022.html#removing-variables-from-a-regression-model"><i class="fa fa-check"></i>Removing variables from a regression model</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-1-2022.html"><a href="tuesday-november-1-2022.html#automatic-selection-of-variables"><i class="fa fa-check"></i>Automatic selection of variables</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-1-2022.html"><a href="tuesday-november-1-2022.html#transforming-the-response-variable"><i class="fa fa-check"></i>Transforming the response variable</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-1-2022.html"><a href="tuesday-november-1-2022.html#fitting-a-regression-tree-model"><i class="fa fa-check"></i>Fitting a regression tree model</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-november-3-2022.html"><a href="thursday-november-3-2022.html"><i class="fa fa-check"></i>Thursday, November 3, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-november-3-2022.html"><a href="thursday-november-3-2022.html#predictive-uncertainty-with-regression-trees"><i class="fa fa-check"></i>Predictive uncertainty with regression trees</a></li>
<li class="chapter" data-level="" data-path="thursday-november-3-2022.html"><a href="thursday-november-3-2022.html#the-random-forest-algorithm"><i class="fa fa-check"></i>The random forest algorithm</a></li>
<li class="chapter" data-level="" data-path="thursday-november-3-2022.html"><a href="thursday-november-3-2022.html#cross-validation"><i class="fa fa-check"></i>Cross validation</a></li>
<li class="chapter" data-level="" data-path="thursday-november-3-2022.html"><a href="thursday-november-3-2022.html#classification-trees"><i class="fa fa-check"></i>Classification trees</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-november-3-2022-1.html"><a href="thursday-november-3-2022-1.html"><i class="fa fa-check"></i>Thursday, November 3, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-november-3-2022-1.html"><a href="thursday-november-3-2022-1.html#binary-outcomes-and-probabilities"><i class="fa fa-check"></i>Binary outcomes and probabilities</a></li>
<li class="chapter" data-level="" data-path="thursday-november-3-2022-1.html"><a href="thursday-november-3-2022-1.html#logistic-regression"><i class="fa fa-check"></i>Logistic regression</a></li>
<li class="chapter" data-level="0.1" data-path="thursday-november-3-2022-1.html"><a href="thursday-november-3-2022-1.html#cluster-analysis"><i class="fa fa-check"></i><b>0.1</b> Cluster analysis</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-november-8-2022.html"><a href="tuesday-november-8-2022.html"><i class="fa fa-check"></i>Tuesday, November 8, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-november-8-2022.html"><a href="tuesday-november-8-2022.html#quantifying-autocorrelation-in-spatial-data"><i class="fa fa-check"></i>Quantifying autocorrelation in spatial data</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-8-2022.html"><a href="tuesday-november-8-2022.html#spatial-data-as-polygon-areas"><i class="fa fa-check"></i>Spatial data as polygon areas</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-8-2022.html"><a href="tuesday-november-8-2022.html#nearest-neighbors"><i class="fa fa-check"></i>Nearest neighbors</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-8-2022.html"><a href="tuesday-november-8-2022.html#spatial-weights"><i class="fa fa-check"></i>Spatial weights</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-8-2022.html"><a href="tuesday-november-8-2022.html#morans-i"><i class="fa fa-check"></i>Moran’s I</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-8-2022.html"><a href="tuesday-november-8-2022.html#spatial-lag-variable"><i class="fa fa-check"></i>Spatial lag variable</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-november-10-2022.html"><a href="thursday-november-10-2022.html"><i class="fa fa-check"></i>Thursday, November 10, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-november-10-2022.html"><a href="thursday-november-10-2022.html#statistical-significance-of-spatial-autocorrelation"><i class="fa fa-check"></i>Statistical significance of spatial autocorrelation</a></li>
<li class="chapter" data-level="" data-path="thursday-november-10-2022.html"><a href="thursday-november-10-2022.html#a-monte-carlo-approach-to-inference-about-spatial-autocorrelation"><i class="fa fa-check"></i>A Monte Carlo approach to inference about spatial autocorrelation</a></li>
<li class="chapter" data-level="" data-path="thursday-november-10-2022.html"><a href="thursday-november-10-2022.html#spatial-autocorrelation-in-model-residuals"><i class="fa fa-check"></i>Spatial autocorrelation in model residuals</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-november-15-2022.html"><a href="tuesday-november-15-2022.html"><i class="fa fa-check"></i>Tuesday, November 15, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-november-15-2022.html"><a href="tuesday-november-15-2022.html#bi-variate-spatial-autocorrelation"><i class="fa fa-check"></i>Bi-variate spatial autocorrelation</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-15-2022.html"><a href="tuesday-november-15-2022.html#local-autocorrelation"><i class="fa fa-check"></i>Local autocorrelation</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-15-2022.html"><a href="tuesday-november-15-2022.html#local-regression"><i class="fa fa-check"></i>Local regression</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-15-2022.html"><a href="tuesday-november-15-2022.html#spatial-weights-1"><i class="fa fa-check"></i>Spatial weights</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-november-17-2022.html"><a href="thursday-november-17-2022.html"><i class="fa fa-check"></i>Thursday, November 17, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-november-17-2022.html"><a href="thursday-november-17-2022.html#geographic-regression"><i class="fa fa-check"></i>Geographic regression</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">GEO5156: Quantitative Geography</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="thursday-november-3-2022" class="section level1 unnumbered hasAnchor">
<h1>Thursday, November 3, 2022<a href="thursday-november-3-2022.html#thursday-november-3-2022" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>Today</p>
<ul>
<li>Predictive uncertainty with regression trees</li>
<li>The random forest algorithm</li>
<li>Cross validation</li>
<li>Classification trees</li>
</ul>
<p>Example: Let’s again look at the Palmer penguins data frame. You are interested in using machine learning (regression tree) to predict the body mass of male Gentoo penguins using the penguin’s bill and flipper dimensions.</p>
<p>First you filter the data frame keeping only the male Gentoo penguins.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="thursday-november-3-2022.html#cb1-1" aria-hidden="true" tabindex="-1"></a>Gentoo.df <span class="ot">&lt;-</span> palmerpenguins<span class="sc">::</span>penguins <span class="sc">|&gt;</span></span>
<span id="cb1-2"><a href="thursday-november-3-2022.html#cb1-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">filter</span>(species <span class="sc">==</span> <span class="st">&quot;Gentoo&quot;</span>, </span>
<span id="cb1-3"><a href="thursday-november-3-2022.html#cb1-3" aria-hidden="true" tabindex="-1"></a>                sex <span class="sc">==</span> <span class="st">&quot;male&quot;</span>)</span></code></pre></div>
<p>To train (fit) the model you use the <code>tree()</code> function from the {tree} package. The response variable is <code>body_mass_g</code> and the explanatory variables are <code>bill_length_mm</code>, <code>bill_depth_mm</code>, and <code>flipper_length_mm</code>.</p>
<p>The first argument in the function is the model formula and the formula has the same format as that for fitting a linear regression model.</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="thursday-november-3-2022.html#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tree)</span>
<span id="cb2-2"><a href="thursday-november-3-2022.html#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="thursday-november-3-2022.html#cb2-3" aria-hidden="true" tabindex="-1"></a>model.tr <span class="ot">&lt;-</span> <span class="fu">tree</span>(body_mass_g <span class="sc">~</span> </span>
<span id="cb2-4"><a href="thursday-november-3-2022.html#cb2-4" aria-hidden="true" tabindex="-1"></a>                  bill_length_mm <span class="sc">+</span> </span>
<span id="cb2-5"><a href="thursday-november-3-2022.html#cb2-5" aria-hidden="true" tabindex="-1"></a>                  bill_depth_mm <span class="sc">+</span> </span>
<span id="cb2-6"><a href="thursday-november-3-2022.html#cb2-6" aria-hidden="true" tabindex="-1"></a>                  flipper_length_mm,</span>
<span id="cb2-7"><a href="thursday-november-3-2022.html#cb2-7" aria-hidden="true" tabindex="-1"></a>              <span class="at">data =</span> Gentoo.df)</span>
<span id="cb2-8"><a href="thursday-november-3-2022.html#cb2-8" aria-hidden="true" tabindex="-1"></a>model.tr</span></code></pre></div>
<pre><code>## node), split, n, deviance, yval
##       * denotes terminal node
## 
##   1) root 61 5884000 5485  
##     2) bill_length_mm &lt; 47.45 13  795800 5238  
##       4) bill_depth_mm &lt; 15.7 8   89690 5131 *
##       5) bill_depth_mm &gt; 15.7 5  467000 5410 *
##     3) bill_length_mm &gt; 47.45 48 4086000 5552  
##       6) flipper_length_mm &lt; 228.5 38 3300000 5498  
##        12) flipper_length_mm &lt; 216.5 9  942500 5375 *
##        13) flipper_length_mm &gt; 216.5 29 2179000 5536  
##          26) flipper_length_mm &lt; 224.5 20 1554000 5595  
##            52) bill_length_mm &lt; 49 5  458000 5430 *
##            53) bill_length_mm &gt; 49 15  915000 5650  
##             106) bill_length_mm &lt; 50.45 9  553900 5711 *
##             107) bill_length_mm &gt; 50.45 6  277100 5558 *
##          27) flipper_length_mm &gt; 224.5 9  402200 5406 *
##       7) flipper_length_mm &gt; 228.5 10  262200 5755 *</code></pre>
<p>A <em>tree diagram</em> helps you interpret this output. Use the <code>plot()</code> method and add text with the <code>text()</code> function.</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="thursday-november-3-2022.html#cb4-1" aria-hidden="true" tabindex="-1"></a>model.tr <span class="sc">|&gt;</span></span>
<span id="cb4-2"><a href="thursday-november-3-2022.html#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>()</span>
<span id="cb4-3"><a href="thursday-november-3-2022.html#cb4-3" aria-hidden="true" tabindex="-1"></a>model.tr <span class="sc">|&gt;</span></span>
<span id="cb4-4"><a href="thursday-november-3-2022.html#cb4-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">text</span>()</span></code></pre></div>
<p><img src="QG-2022_files/figure-html/unnamed-chunk-3-1.png" width="672" /></p>
<p>The most important variable in explaining body mass of the male Gentoo penguins is bill length. It is the variable named on the top of the tree diagram. For penguins with bills less than 47.45 mm, the next most important variable is bill depth (if the condition is true, then branch to the left). For those penguins with shorter bills if bill depth is less than 15.7 mm then the average body mass is 5131 grams and if the bill depth is greater or equal to 15.7 mm then the average body mass is larger at 5410 g. Again, if the condition is true, then branch left.</p>
<p>For male Gentoo penguins with a bills at least 47.45 mm in length, the next most important variable is flipper length. For these larger-billed penguins, if flippers are longer (at least 228.5 mm) then the average body mass is 5755 g. For these larger-bill length penguins, if flippers are shorter than 228.5 mm, then split on flipper length again.</p>
<p>As you move down the tree the branches get smaller (the vertical lines get shorter) indicating the splits are <em>less</em> important in reducing the residual sum of squares (RSS).</p>
<p>Interpreting a tree regression is easier than interpreting a linear regression because the splits have the same units as the explanatory variables. In a linear regression the coefficient has units of response variable divided by the units of the explanatory variable.</p>
<p>Machine learning algorithms are often used solely for predictions. Given the branching structure of the tree, the predicted values are easy to anticipate.</p>
<p>Prediction amounts to following the rules defined by the final model. You start with the value of the variable <code>bill_length_mm</code> and work your way down until you come to a terminal node (a branch that ends in a value rather than a split). The value is the <em>average of the response variable</em> conditional on the splits.</p>
<p>For example, if <code>bill_length_mm</code> is less than 47.45 mm and <code>bill_depth_mm</code> is less than 15.7 mm, then the mass of the penguin is predicted to be 5131 grams. Said another way, 5131 is the average body mass for all male Gentoo penguins with bill length less than 47.45 and bill depth less than 15.7.</p>
<p>You can check this as follows.</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="thursday-november-3-2022.html#cb5-1" aria-hidden="true" tabindex="-1"></a>Gentoo.df <span class="sc">|&gt;</span></span>
<span id="cb5-2"><a href="thursday-november-3-2022.html#cb5-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">filter</span>(bill_length_mm <span class="sc">&lt;</span> <span class="fl">47.45</span> <span class="sc">&amp;</span> </span>
<span id="cb5-3"><a href="thursday-november-3-2022.html#cb5-3" aria-hidden="true" tabindex="-1"></a>                bill_depth_mm <span class="sc">&lt;</span> <span class="fl">15.7</span>) <span class="sc">|&gt;</span></span>
<span id="cb5-4"><a href="thursday-november-3-2022.html#cb5-4" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">summarize</span>(<span class="fu">mean</span>(body_mass_g))</span></code></pre></div>
<pre><code>## # A tibble: 1 × 1
##   `mean(body_mass_g)`
##                 &lt;dbl&gt;
## 1               5131.</code></pre>
<p>The <code>predict()</code> method is used to make predictions with the model. The first argument is the model object and the next is the data frame containing the variables.</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="thursday-november-3-2022.html#cb7-1" aria-hidden="true" tabindex="-1"></a>model.tr <span class="sc">|&gt;</span></span>
<span id="cb7-2"><a href="thursday-november-3-2022.html#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">predict</span>(<span class="at">newdata =</span> <span class="fu">data.frame</span>(<span class="at">bill_length_mm =</span> <span class="dv">45</span>,</span>
<span id="cb7-3"><a href="thursday-november-3-2022.html#cb7-3" aria-hidden="true" tabindex="-1"></a>                               <span class="at">bill_depth_mm =</span> <span class="dv">15</span>,</span>
<span id="cb7-4"><a href="thursday-november-3-2022.html#cb7-4" aria-hidden="true" tabindex="-1"></a>                               <span class="at">flipper_length_mm =</span> <span class="dv">220</span>))</span></code></pre></div>
<pre><code>##       1 
## 5131.25</code></pre>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="thursday-november-3-2022.html#cb9-1" aria-hidden="true" tabindex="-1"></a>model.tr <span class="sc">|&gt;</span></span>
<span id="cb9-2"><a href="thursday-november-3-2022.html#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(<span class="at">newdata =</span> <span class="fu">data.frame</span>(<span class="at">bill_length_mm =</span> <span class="dv">45</span>,</span>
<span id="cb9-3"><a href="thursday-november-3-2022.html#cb9-3" aria-hidden="true" tabindex="-1"></a>                             <span class="at">bill_depth_mm =</span> <span class="dv">16</span>,</span>
<span id="cb9-4"><a href="thursday-november-3-2022.html#cb9-4" aria-hidden="true" tabindex="-1"></a>                             <span class="at">flipper_length_mm =</span> <span class="dv">220</span>))</span></code></pre></div>
<pre><code>##    1 
## 5410</code></pre>
<p>Note that you need to specify values for all the explanatory variables.</p>
<p>The uncertainty on the predicted value is more difficult to work out. You can use the standard error on the mean for that terminal node, but this error ignores the uncertainty surrounding what variable to split and at what value to make the split. Because of this limitation machine learning algorithms are not usually used for inference.</p>
<p>Another question that arises is can the tree be simplified? The question is answered by considering the trade-off between minimizing the bias and maximizing the variance explained in the response variable.</p>
<p>If the tree has many explanatory variables and lots of decision splits then it will explain more variance. But this will make the tree biased toward the particular data set used in the training and predictions made with the model on new data (data not used in the training) will be poor. On the other hand, if the tree is too simple (few variables and few splits), it will not explain much of the variance in the response.</p>
<p>Pruning the tree solves for this trade-off. The <code>prune.tree()</code> function gives a sequence of smaller trees from the largest tree by removing the least important splits.</p>
<p>The function returns the tree size (number of terminal nodes), the total deviance for each tree, and the increase in deviance by going from a larger tree to a smaller tree.</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="thursday-november-3-2022.html#cb11-1" aria-hidden="true" tabindex="-1"></a>model.tr <span class="sc">|&gt;</span></span>
<span id="cb11-2"><a href="thursday-november-3-2022.html#cb11-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">prune.tree</span>()</span></code></pre></div>
<pre><code>## $size
## [1] 8 7 6 4 3 2 1
## 
## $dev
## [1] 3452632 3536660 3718160 4119414 4358496 4881277 5884098
## 
## $k
## [1]       -Inf   84027.78  181500.00  200627.38  239081.73  522780.84 1002821.32
## 
## $method
## [1] &quot;deviance&quot;
## 
## attr(,&quot;class&quot;)
## [1] &quot;prune&quot;         &quot;tree.sequence&quot;</code></pre>
<p>From the output you see the largest tree (8 terminal nodes) results in the smallest deviance (<code>$dev</code>) (3452632). By pruning one branch the deviance increases (3536660) but only by a relatively small amount (84028 which is an increase of about 2.4%). Similarly by pruning a second branch the deviance increases, this time a bit more.</p>
<p>Suppose you want a tree with six terminal nodes. You specify this with the <code>best = 6</code> argument in the <code>prune.tree()</code> function.</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="thursday-november-3-2022.html#cb13-1" aria-hidden="true" tabindex="-1"></a>model2.tr <span class="ot">&lt;-</span> model.tr <span class="sc">|&gt;</span></span>
<span id="cb13-2"><a href="thursday-november-3-2022.html#cb13-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">prune.tree</span>(<span class="at">best =</span> <span class="dv">6</span>)</span>
<span id="cb13-3"><a href="thursday-november-3-2022.html#cb13-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-4"><a href="thursday-november-3-2022.html#cb13-4" aria-hidden="true" tabindex="-1"></a>model2.tr <span class="sc">|&gt;</span></span>
<span id="cb13-5"><a href="thursday-november-3-2022.html#cb13-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>()</span>
<span id="cb13-6"><a href="thursday-november-3-2022.html#cb13-6" aria-hidden="true" tabindex="-1"></a>model2.tr <span class="sc">|&gt;</span></span>
<span id="cb13-7"><a href="thursday-november-3-2022.html#cb13-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">text</span>()</span></code></pre></div>
<p><img src="QG-2022_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<div id="predictive-uncertainty-with-regression-trees" class="section level2 unnumbered hasAnchor">
<h2>Predictive uncertainty with regression trees<a href="thursday-november-3-2022.html#predictive-uncertainty-with-regression-trees" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Let’s look at another example. Predicting Atlantic hurricanes using a regression tree.</p>
<p>Import the annual hurricane data and filter on years since 1950. Create a data frame containing only the basin-wide hurricane counts and Southern Oscillation Index (El Nino) and SST as the two explanatory variables. The SOI has units of standard deviation and the SST has units of degrees C.</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="thursday-november-3-2022.html#cb14-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> readr<span class="sc">::</span><span class="fu">read_table</span>(<span class="st">&quot;http://myweb.fsu.edu/jelsner/temp/data/AnnualData.txt&quot;</span>) <span class="sc">|&gt;</span></span>
<span id="cb14-2"><a href="thursday-november-3-2022.html#cb14-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">filter</span>(Year <span class="sc">&gt;=</span> <span class="dv">1950</span>) <span class="sc">|&gt;</span></span>
<span id="cb14-3"><a href="thursday-november-3-2022.html#cb14-3" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(<span class="at">Year =</span> Year, <span class="at">H =</span> B<span class="fl">.1</span>, <span class="at">SOI =</span> soi, <span class="at">SST =</span> sst)</span></code></pre></div>
<pre><code>## 
## ── Column specification ────────────────────────────────────────────────────────
## cols(
##   .default = col_double(),
##   RowID = col_character()
## )
## ℹ Use `spec()` for the full column specifications.</code></pre>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="thursday-november-3-2022.html#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(df)</span></code></pre></div>
<pre><code>## # A tibble: 6 × 4
##    Year     H    SOI       SST
##   &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;     &lt;dbl&gt;
## 1  1950    11  3.43  -0.000737
## 2  1951     8 -3.47   0.293   
## 3  1952     6 -0.567  0.399   
## 4  1953     6 -3.6    0.257   
## 5  1954     8  1.07   0.0113  
## 6  1955     9  4.23   0.252</code></pre>
<p>Then fit a regression tree to these data with the annual count of hurricanes as the response variable and <code>SOI</code> and <code>SST</code> as the explanatory variables.</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="thursday-november-3-2022.html#cb18-1" aria-hidden="true" tabindex="-1"></a>model.tr <span class="ot">&lt;-</span> <span class="fu">tree</span>(H <span class="sc">~</span> </span>
<span id="cb18-2"><a href="thursday-november-3-2022.html#cb18-2" aria-hidden="true" tabindex="-1"></a>                 SOI <span class="sc">+</span></span>
<span id="cb18-3"><a href="thursday-november-3-2022.html#cb18-3" aria-hidden="true" tabindex="-1"></a>                 SST, </span>
<span id="cb18-4"><a href="thursday-november-3-2022.html#cb18-4" aria-hidden="true" tabindex="-1"></a>              <span class="at">data =</span> df)</span>
<span id="cb18-5"><a href="thursday-november-3-2022.html#cb18-5" aria-hidden="true" tabindex="-1"></a>model.tr <span class="sc">|&gt;</span></span>
<span id="cb18-6"><a href="thursday-november-3-2022.html#cb18-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>()</span>
<span id="cb18-7"><a href="thursday-november-3-2022.html#cb18-7" aria-hidden="true" tabindex="-1"></a>model.tr <span class="sc">|&gt;</span></span>
<span id="cb18-8"><a href="thursday-november-3-2022.html#cb18-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">text</span>()</span></code></pre></div>
<p><img src="QG-2022_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<p>The predicted number of hurricanes when <code>SOI</code> is -2 s.d. and when <code>SST</code> is .2C is found using the <code>predict()</code> method.</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="thursday-november-3-2022.html#cb19-1" aria-hidden="true" tabindex="-1"></a>model.tr <span class="sc">|&gt;</span></span>
<span id="cb19-2"><a href="thursday-november-3-2022.html#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(<span class="at">newdata =</span> <span class="fu">data.frame</span>(<span class="at">SOI =</span> <span class="sc">-</span><span class="dv">2</span>, </span>
<span id="cb19-3"><a href="thursday-november-3-2022.html#cb19-3" aria-hidden="true" tabindex="-1"></a>                             <span class="at">SST =</span> .<span class="dv">2</span>))</span></code></pre></div>
<pre><code>##        1 
## 7.347826</code></pre>
<p>So, on average, you can expect between 7 and 8 hurricanes in the Atlantic in years with the SOI is -2 s.d. and the SST is .2C above normal.</p>
<p>The predicted value depends on the tree, which in turn depends exactly on what values of SOI and SST are used to train it.</p>
<p>To see this, you train a new tree for hurricane count, but this time leaving out the values of SOI and SST from the last year in the data frame.</p>
<p>Since there are 61 years, leaving the last year out amounts to sub-setting the data frame as <code>df[-61, ]</code>.</p>
<p>Then you fit a new tree model (<code>model2</code>) and make a prediction for the same values of <code>SOI</code> and <code>SST</code> (<code>SOI</code> = -2 s.d. and <code>SST</code> = .2C).</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="thursday-november-3-2022.html#cb21-1" aria-hidden="true" tabindex="-1"></a>model2.tr <span class="ot">&lt;-</span> <span class="fu">tree</span>(H <span class="sc">~</span> </span>
<span id="cb21-2"><a href="thursday-november-3-2022.html#cb21-2" aria-hidden="true" tabindex="-1"></a>                    SOI <span class="sc">+</span> </span>
<span id="cb21-3"><a href="thursday-november-3-2022.html#cb21-3" aria-hidden="true" tabindex="-1"></a>                    SST, </span>
<span id="cb21-4"><a href="thursday-november-3-2022.html#cb21-4" aria-hidden="true" tabindex="-1"></a>                  <span class="at">data =</span> df[<span class="sc">-</span><span class="dv">61</span>, ])</span>
<span id="cb21-5"><a href="thursday-november-3-2022.html#cb21-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-6"><a href="thursday-november-3-2022.html#cb21-6" aria-hidden="true" tabindex="-1"></a>model2.tr <span class="sc">|&gt;</span></span>
<span id="cb21-7"><a href="thursday-november-3-2022.html#cb21-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">predict</span>(<span class="at">newdata =</span> <span class="fu">data.frame</span>(<span class="at">SOI =</span> <span class="sc">-</span><span class="dv">2</span>, </span>
<span id="cb21-8"><a href="thursday-november-3-2022.html#cb21-8" aria-hidden="true" tabindex="-1"></a>                               <span class="at">SST =</span> .<span class="dv">2</span>))</span></code></pre></div>
<pre><code>##        1 
## 5.714286</code></pre>
<p>The predicted value is quite different even though you left out only one year of data when training this tree!</p>
<p>Predictive uncertainty occurs with any model, but the level of uncertainty is much larger with machine learning algorithms because they have many parameters. Each branch in a regression tree is a parameter and so is every split so with our two explanatory variables there are at least 10 parameters.</p>
<p>For example, compare the predicted hurricane rates from a linear regression model with and without the last year.</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="thursday-november-3-2022.html#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(<span class="fu">lm</span>(H <span class="sc">~</span> SOI <span class="sc">+</span> SST, <span class="at">data =</span> df),</span>
<span id="cb23-2"><a href="thursday-november-3-2022.html#cb23-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">newdata =</span> <span class="fu">data.frame</span>(<span class="at">SOI =</span> <span class="sc">-</span><span class="dv">2</span>, <span class="at">SST =</span> .<span class="dv">2</span>))</span></code></pre></div>
<pre><code>##        1 
## 6.230173</code></pre>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="thursday-november-3-2022.html#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(<span class="fu">lm</span>(H <span class="sc">~</span> SOI <span class="sc">+</span> SST, <span class="at">data =</span> df[<span class="sc">-</span><span class="dv">61</span>, ]),</span>
<span id="cb25-2"><a href="thursday-november-3-2022.html#cb25-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">newdata =</span> <span class="fu">data.frame</span>(<span class="at">SOI =</span> <span class="sc">-</span><span class="dv">2</span>, <span class="at">SST =</span> .<span class="dv">2</span>))</span></code></pre></div>
<pre><code>##        1 
## 6.219233</code></pre>
<p>The difference in predicted values is very small with a linear regression model. On the order of .2% 0.1605136 compared with 22% (<code>(7.35 - 5.71)/7.35 * 100</code>) for the machine learning algorithm</p>
</div>
<div id="the-random-forest-algorithm" class="section level2 unnumbered hasAnchor">
<h2>The random forest algorithm<a href="thursday-november-3-2022.html#the-random-forest-algorithm" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>A random forest algorithm solves some of the problem of large predictive uncertainty by fitting many regression trees (a ‘forest’). The algorithm takes many samples (e.g., 100) from the set of all observations and then using these samples fits many regression trees. Given a set of new values for the explanatory variables, each regression tree provides a predicted value. The average over all predicted values is taken as the random forest prediction.</p>
<p>The <code>randomForest()</code> function in the {randomForest} package provides a random forest algorithm.</p>
<p>For comparison here you apply a random forest algorithm to the hurricane data frame. I use the word <em>algorithm</em> because there is no single model. The number of trees is set at 500 (by default).</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="thursday-november-3-2022.html#cb27-1" aria-hidden="true" tabindex="-1"></a>rfa <span class="ot">&lt;-</span> randomForest<span class="sc">::</span><span class="fu">randomForest</span>(H <span class="sc">~</span> SOI <span class="sc">+</span> SST,</span>
<span id="cb27-2"><a href="thursday-november-3-2022.html#cb27-2" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">data =</span> df,</span>
<span id="cb27-3"><a href="thursday-november-3-2022.html#cb27-3" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">ntree =</span> <span class="dv">500</span>)</span></code></pre></div>
<p>Then to make a prediction you use (again) the <code>predict()</code> method.</p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="thursday-november-3-2022.html#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(rfa, </span>
<span id="cb28-2"><a href="thursday-november-3-2022.html#cb28-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">newdata =</span> <span class="fu">data.frame</span>(<span class="at">SOI =</span> <span class="sc">-</span><span class="dv">2</span>, <span class="at">SST =</span> .<span class="dv">2</span>))</span></code></pre></div>
<pre><code>##        1 
## 4.672867</code></pre>
<p>The predicted value is less sensitive to removing single observations. To see this you apply the random forest algorithm with the last observation removed.</p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="thursday-november-3-2022.html#cb30-1" aria-hidden="true" tabindex="-1"></a>rfa <span class="ot">&lt;-</span> randomForest<span class="sc">::</span><span class="fu">randomForest</span>(H <span class="sc">~</span> SOI <span class="sc">+</span> SST, </span>
<span id="cb30-2"><a href="thursday-november-3-2022.html#cb30-2" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">data =</span> df[<span class="sc">-</span><span class="dv">61</span>, ],</span>
<span id="cb30-3"><a href="thursday-november-3-2022.html#cb30-3" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">ntree =</span> <span class="dv">500</span>)</span>
<span id="cb30-4"><a href="thursday-november-3-2022.html#cb30-4" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(rfa, </span>
<span id="cb30-5"><a href="thursday-november-3-2022.html#cb30-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">newdata =</span> <span class="fu">data.frame</span>(<span class="at">SOI =</span> <span class="sc">-</span><span class="dv">2</span>, <span class="at">SST =</span> .<span class="dv">2</span>))</span></code></pre></div>
<pre><code>##        1 
## 4.726267</code></pre>
<p>In summary: Regression trees tend to produce predicted values that are unstable, which means a small change in the data used to grow the tree results in a large difference in the predicted value.</p>
<p>The <em>in-sample error</em> (the error made when using the model to predict the data that you used to fit the model) might be small, but the <em>out-of-sample error</em> (the error made when using the model to predict new data) can be large.</p>
<p>A random forest algorithm solves some of the problem (but not all) of unstable predictions by growing many trees.</p>
</div>
<div id="cross-validation" class="section level2 unnumbered hasAnchor">
<h2>Cross validation<a href="thursday-november-3-2022.html#cross-validation" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Why use a machine learning algorithm? They are useful when you have a large amount of data. They can find features in the data that are not accessible with linear regression.</p>
<p>But how do you compare the predictive skill of a random forest algorithm against the predictive skill of another model?</p>
<p>You use a method called <em>cross validation</em>. Cross validation helps you decide what model to use across the span of many models.</p>
<p><em>Key idea</em>: Cross validation is a method that removes noise specific to each observation and estimates how well the model/algorithm finds useful prediction rules when this coincident information is unavailable.</p>
<p>For example, here you compare the skill of a random forest algorithm against the skill of a <em>Poisson</em> regression model for predicting hurricane counts. You arrange the cross validation as follows.</p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="thursday-november-3-2022.html#cb32-1" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">length</span>(df<span class="sc">$</span>H)</span>
<span id="cb32-2"><a href="thursday-november-3-2022.html#cb32-2" aria-hidden="true" tabindex="-1"></a>rfx <span class="ot">&lt;-</span> <span class="fu">numeric</span>(n)</span>
<span id="cb32-3"><a href="thursday-november-3-2022.html#cb32-3" aria-hidden="true" tabindex="-1"></a>prx <span class="ot">&lt;-</span> <span class="fu">numeric</span>(n)</span>
<span id="cb32-4"><a href="thursday-november-3-2022.html#cb32-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>n){</span>
<span id="cb32-5"><a href="thursday-november-3-2022.html#cb32-5" aria-hidden="true" tabindex="-1"></a>  rfa <span class="ot">&lt;-</span> randomForest<span class="sc">::</span><span class="fu">randomForest</span>(H <span class="sc">~</span> SOI <span class="sc">+</span> SST, </span>
<span id="cb32-6"><a href="thursday-november-3-2022.html#cb32-6" aria-hidden="true" tabindex="-1"></a>                                    <span class="at">data =</span> df[<span class="sc">-</span>i, ])</span>
<span id="cb32-7"><a href="thursday-november-3-2022.html#cb32-7" aria-hidden="true" tabindex="-1"></a>  prm <span class="ot">&lt;-</span> <span class="fu">glm</span>(H <span class="sc">~</span> SOI <span class="sc">+</span> SST, <span class="at">data =</span> df[<span class="sc">-</span>i, ], </span>
<span id="cb32-8"><a href="thursday-november-3-2022.html#cb32-8" aria-hidden="true" tabindex="-1"></a>             <span class="at">family =</span> <span class="st">&quot;poisson&quot;</span>)</span>
<span id="cb32-9"><a href="thursday-november-3-2022.html#cb32-9" aria-hidden="true" tabindex="-1"></a>  new <span class="ot">&lt;-</span> df[i, ]</span>
<span id="cb32-10"><a href="thursday-november-3-2022.html#cb32-10" aria-hidden="true" tabindex="-1"></a>  rfx[i] <span class="ot">&lt;-</span> <span class="fu">predict</span>(rfa, <span class="at">newdata =</span> new)</span>
<span id="cb32-11"><a href="thursday-november-3-2022.html#cb32-11" aria-hidden="true" tabindex="-1"></a>  prx[i] <span class="ot">&lt;-</span> <span class="fu">predict</span>(prm, <span class="at">newdata =</span> new, </span>
<span id="cb32-12"><a href="thursday-november-3-2022.html#cb32-12" aria-hidden="true" tabindex="-1"></a>                    <span class="at">type =</span> <span class="st">&quot;response&quot;</span>)</span>
<span id="cb32-13"><a href="thursday-november-3-2022.html#cb32-13" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div>
<p>You compute the out-of-sample averaged prediction error squared (mean squared prediction error) for both models.</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="thursday-november-3-2022.html#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>((df<span class="sc">$</span>H <span class="sc">-</span> prx)<span class="sc">^</span><span class="dv">2</span>)</span></code></pre></div>
<pre><code>## [1] 5.070468</code></pre>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="thursday-november-3-2022.html#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>((df<span class="sc">$</span>H <span class="sc">-</span> rfx)<span class="sc">^</span><span class="dv">2</span>)</span></code></pre></div>
<pre><code>## [1] 5.261964</code></pre>
<p>The Poisson regression model performs slightly better than the random forest model in this case although the difference is not large.</p>
<p>Correlations between the actual and predicted value are</p>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="thursday-november-3-2022.html#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(df<span class="sc">$</span>H, prx)</span></code></pre></div>
<pre><code>## [1] 0.5385559</code></pre>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="thursday-november-3-2022.html#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(df<span class="sc">$</span>H, rfx)</span></code></pre></div>
<pre><code>## [1] 0.5135856</code></pre>
<p>The influence each of the two explanatory variables has on the hurricane counts is seen by plotting the predictions on a grid.</p>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="thursday-november-3-2022.html#cb41-1" aria-hidden="true" tabindex="-1"></a>newdat <span class="ot">&lt;-</span> <span class="fu">expand.grid</span>(<span class="at">SST =</span> <span class="fu">seq</span>(<span class="sc">-</span>.<span class="dv">5</span>, .<span class="dv">7</span>, .<span class="dv">01</span>), </span>
<span id="cb41-2"><a href="thursday-november-3-2022.html#cb41-2" aria-hidden="true" tabindex="-1"></a>                      <span class="at">SOI =</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="dv">5</span>, <span class="dv">4</span>, .<span class="dv">1</span>))</span>
<span id="cb41-3"><a href="thursday-november-3-2022.html#cb41-3" aria-hidden="true" tabindex="-1"></a>z1 <span class="ot">&lt;-</span> <span class="fu">predict</span>(rfa, <span class="at">newdata =</span> newdat)</span>
<span id="cb41-4"><a href="thursday-november-3-2022.html#cb41-4" aria-hidden="true" tabindex="-1"></a>prm <span class="ot">&lt;-</span> <span class="fu">glm</span>(H <span class="sc">~</span> SOI <span class="sc">+</span> SST, <span class="at">data =</span> df, <span class="at">family =</span> <span class="st">&quot;poisson&quot;</span>)</span>
<span id="cb41-5"><a href="thursday-november-3-2022.html#cb41-5" aria-hidden="true" tabindex="-1"></a>z2 <span class="ot">&lt;-</span> <span class="fu">predict</span>(prm, <span class="at">newdata =</span> newdat, <span class="at">type =</span> <span class="st">&quot;response&quot;</span>)</span>
<span id="cb41-6"><a href="thursday-november-3-2022.html#cb41-6" aria-hidden="true" tabindex="-1"></a>newdat<span class="sc">$</span>Hrf <span class="ot">&lt;-</span> z1</span>
<span id="cb41-7"><a href="thursday-november-3-2022.html#cb41-7" aria-hidden="true" tabindex="-1"></a>newdat<span class="sc">$</span>Hpr <span class="ot">&lt;-</span> z2</span>
<span id="cb41-8"><a href="thursday-november-3-2022.html#cb41-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-9"><a href="thursday-november-3-2022.html#cb41-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb41-10"><a href="thursday-november-3-2022.html#cb41-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-11"><a href="thursday-november-3-2022.html#cb41-11" aria-hidden="true" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(newdat, <span class="fu">aes</span>(<span class="at">x =</span> SST, <span class="at">y =</span> SOI, <span class="at">fill =</span> Hrf)) <span class="sc">+</span> </span>
<span id="cb41-12"><a href="thursday-november-3-2022.html#cb41-12" aria-hidden="true" tabindex="-1"></a>        <span class="fu">geom_tile</span>() <span class="sc">+</span></span>
<span id="cb41-13"><a href="thursday-november-3-2022.html#cb41-13" aria-hidden="true" tabindex="-1"></a>        <span class="fu">scale_fill_viridis_c</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">12</span>)) <span class="sc">+</span></span>
<span id="cb41-14"><a href="thursday-november-3-2022.html#cb41-14" aria-hidden="true" tabindex="-1"></a>        <span class="fu">labs</span>(<span class="at">fill =</span> <span class="st">&quot;Rate&quot;</span>) <span class="sc">+</span></span>
<span id="cb41-15"><a href="thursday-november-3-2022.html#cb41-15" aria-hidden="true" tabindex="-1"></a>        <span class="fu">xlab</span>(<span class="st">&quot;Atlantic Sea Surface Temperature (°C)&quot;</span>) <span class="sc">+</span> </span>
<span id="cb41-16"><a href="thursday-november-3-2022.html#cb41-16" aria-hidden="true" tabindex="-1"></a>        <span class="fu">ylab</span>(<span class="st">&quot;Southern Oscillation Index (s.d.)&quot;</span>) <span class="sc">+</span></span>
<span id="cb41-17"><a href="thursday-november-3-2022.html#cb41-17" aria-hidden="true" tabindex="-1"></a>        <span class="fu">ggtitle</span>(<span class="at">subtitle =</span> <span class="st">&quot;Random forest algorithm&quot;</span>,</span>
<span id="cb41-18"><a href="thursday-november-3-2022.html#cb41-18" aria-hidden="true" tabindex="-1"></a>                <span class="at">label =</span> <span class="st">&quot;Annual Atlantic hurricane rate&quot;</span>) <span class="sc">+</span></span>
<span id="cb41-19"><a href="thursday-november-3-2022.html#cb41-19" aria-hidden="true" tabindex="-1"></a>        <span class="fu">theme_minimal</span>()</span>
<span id="cb41-20"><a href="thursday-november-3-2022.html#cb41-20" aria-hidden="true" tabindex="-1"></a>p2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(newdat, <span class="fu">aes</span>(<span class="at">x =</span> SST, <span class="at">y =</span> SOI, <span class="at">fill =</span> Hpr)) <span class="sc">+</span> </span>
<span id="cb41-21"><a href="thursday-november-3-2022.html#cb41-21" aria-hidden="true" tabindex="-1"></a>        <span class="fu">geom_tile</span>() <span class="sc">+</span></span>
<span id="cb41-22"><a href="thursday-november-3-2022.html#cb41-22" aria-hidden="true" tabindex="-1"></a>        <span class="fu">scale_fill_viridis_c</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">12</span>)) <span class="sc">+</span></span>
<span id="cb41-23"><a href="thursday-november-3-2022.html#cb41-23" aria-hidden="true" tabindex="-1"></a>        <span class="fu">labs</span>(<span class="at">fill =</span> <span class="st">&quot;Rate&quot;</span>) <span class="sc">+</span></span>
<span id="cb41-24"><a href="thursday-november-3-2022.html#cb41-24" aria-hidden="true" tabindex="-1"></a>        <span class="fu">xlab</span>(<span class="st">&quot;Atlantic Sea Surface Temperature (°C)&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;Southern Oscillation Index (s.d.)&quot;</span>) <span class="sc">+</span></span>
<span id="cb41-25"><a href="thursday-november-3-2022.html#cb41-25" aria-hidden="true" tabindex="-1"></a>        <span class="fu">ggtitle</span>(<span class="at">subtitle =</span> <span class="st">&quot;Poisson regression model&quot;</span>,</span>
<span id="cb41-26"><a href="thursday-november-3-2022.html#cb41-26" aria-hidden="true" tabindex="-1"></a>                <span class="at">label =</span> <span class="st">&quot;Annual Atlantic hurricane rate&quot;</span>) <span class="sc">+</span></span>
<span id="cb41-27"><a href="thursday-november-3-2022.html#cb41-27" aria-hidden="true" tabindex="-1"></a>        <span class="fu">theme_minimal</span>()</span>
<span id="cb41-28"><a href="thursday-november-3-2022.html#cb41-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-29"><a href="thursday-november-3-2022.html#cb41-29" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(patchwork)</span>
<span id="cb41-30"><a href="thursday-november-3-2022.html#cb41-30" aria-hidden="true" tabindex="-1"></a>p1 <span class="sc">+</span> p2</span></code></pre></div>
<p><img src="QG-2022_files/figure-html/unnamed-chunk-19-1.png" width="672" /></p>
<p>Hurricane counts increase with SST and SOI but for high values of SOI the influence of SST is stronger. For high values of SST the influence of the SOI is more pronounced. The random forest algorithm is able to capture more subtle features (plaid pattern) but at the expense of interpreting some noise as signal as seen by the relative high count with SOI values near -3 s.d. and SST values near -.1 C.</p>
</div>
<div id="classification-trees" class="section level2 unnumbered hasAnchor">
<h2>Classification trees<a href="thursday-november-3-2022.html#classification-trees" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>When the response variable is categorical (e.g., species) a regression tree is called a <em>classification tree</em>. The classification tree is a set of if-then rules that results in a probability for each category.</p>
<p>If instability is high and wind shear is strong, then predict a high chance of damaging tornadoes. If a patient’s resting heart rate exceeds 120 bpm, then predict a high chance that the patient will suffer a heart attack within the next 5 years.</p>
<p>Returning again the <code>penguins</code> data frame from the {palmerpenguins} package.</p>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="thursday-november-3-2022.html#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(palmerpenguins<span class="sc">::</span>penguins)</span></code></pre></div>
<pre><code>## # A tibble: 6 × 8
##   species island    bill_length_mm bill_depth_mm flipper_l…¹ body_…² sex    year
##   &lt;fct&gt;   &lt;fct&gt;              &lt;dbl&gt;         &lt;dbl&gt;       &lt;int&gt;   &lt;int&gt; &lt;fct&gt; &lt;int&gt;
## 1 Adelie  Torgersen           39.1          18.7         181    3750 male   2007
## 2 Adelie  Torgersen           39.5          17.4         186    3800 fema…  2007
## 3 Adelie  Torgersen           40.3          18           195    3250 fema…  2007
## 4 Adelie  Torgersen           NA            NA            NA      NA &lt;NA&gt;   2007
## 5 Adelie  Torgersen           36.7          19.3         193    3450 fema…  2007
## 6 Adelie  Torgersen           39.3          20.6         190    3650 male   2007
## # … with abbreviated variable names ¹​flipper_length_mm, ²​body_mass_g</code></pre>
<p>With <code>species</code> as the categorical response variable (there are three different penguin species) and the other columns as explanatory variables you can specify the model formula as <code>species ~ .</code>. The period after the tilde (<code>~</code>) indicating all other variables in the data frame.</p>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="thursday-november-3-2022.html#cb44-1" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">tree</span>(species <span class="sc">~</span> .,</span>
<span id="cb44-2"><a href="thursday-november-3-2022.html#cb44-2" aria-hidden="true" tabindex="-1"></a>              <span class="at">data =</span> palmerpenguins<span class="sc">::</span>penguins)</span>
<span id="cb44-3"><a href="thursday-november-3-2022.html#cb44-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(model)</span>
<span id="cb44-4"><a href="thursday-november-3-2022.html#cb44-4" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(model)</span></code></pre></div>
<p><img src="QG-2022_files/figure-html/unnamed-chunk-21-1.png" width="672" /></p>
<p>From the plot you see that flipper length split at 206.5 mm is the most important variable in distinguishing the species. The next two branches are bill length split at 43.45 mm and island.</p>
<p>Since island is a categorical explanatory variable there is a <code>:a</code> next to the name <code>island</code>. This indicates that the spit is on the first island in alphabetical order. The island names are</p>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="thursday-november-3-2022.html#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(palmerpenguins<span class="sc">::</span>penguins<span class="sc">$</span>island)</span></code></pre></div>
<pre><code>## [1] Torgersen Biscoe    Dream    
## Levels: Biscoe Dream Torgersen</code></pre>
<p>Biscoe Island is the first in alphabetical order so the split says that if the island is Biscoe (yes, means branch left) then predict the species is Gentoo and if the island is not Biscoe (either Dream or Torgersen) then predict the species to be Chinstrap.</p>
<p>After these three splits resulting in four branches, the branches become very small (the vertical lines are short) indicating that these additional splits do not reduce the RSS by much at all.</p>
<p>So you prune the tree by setting <code>best = 4</code>. That is, you ask the model to grow a tree with the four most important branches.</p>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="thursday-november-3-2022.html#cb47-1" aria-hidden="true" tabindex="-1"></a>model2 <span class="ot">&lt;-</span> <span class="fu">prune.tree</span>(model, </span>
<span id="cb47-2"><a href="thursday-november-3-2022.html#cb47-2" aria-hidden="true" tabindex="-1"></a>                     <span class="at">best =</span> <span class="dv">4</span>)</span>
<span id="cb47-3"><a href="thursday-november-3-2022.html#cb47-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(model2)</span>
<span id="cb47-4"><a href="thursday-november-3-2022.html#cb47-4" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(model2)</span></code></pre></div>
<p><img src="QG-2022_files/figure-html/unnamed-chunk-23-1.png" width="672" /></p>
<p>You examine the model quantitatively by the misclassification error rate. This is given in the last line of the output from the <code>summary()</code> method.</p>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="thursday-november-3-2022.html#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model2)</span></code></pre></div>
<pre><code>## 
## Classification tree:
## snip.tree(tree = model, nodes = 4:5)
## Variables actually used in tree construction:
## [1] &quot;flipper_length_mm&quot; &quot;bill_length_mm&quot;    &quot;island&quot;           
## Number of terminal nodes:  4 
## Residual mean deviance:  0.2791 = 91.81 / 329 
## Misclassification error rate: 0.03604 = 12 / 333</code></pre>
<p>You see that the model misclassifies the species in 12 of the 333 penguins resulting in a misclassification error rate of 3.6%.</p>
<p>Note that the full model has a misclassification error rate of only 1.8% (6 out of the 333 penguins). But this requires twice as many nodes so the model has greater bias.</p>
<p>Suppose you are able to observe a penguin on Biscoe Island with a flipper length of 200 mm, a bill length of 44 mm, a bill depth 18 mm, and a body mass of 4000 g. What is the likely species?</p>
<p>You use the <code>predict()</code> method with the <code>newdata =</code> argument specified as a data frame. You must include by name all the variables in the model specification. This includes <code>island</code> and <code>sex</code> as factors along with <code>year</code>, <code>flipper_length_mm</code>, <code>bill_length_mm</code>, <code>bill_depth_mm</code>, and <code>body_mass_g</code> as integers or numeric values. Note that since the final tree only includes the variables <code>island</code>, <code>flipper_length_mm</code>, and <code>bill_length_mm</code> it does not matter what values you use for the other variables.</p>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="thursday-november-3-2022.html#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(model2,</span>
<span id="cb50-2"><a href="thursday-november-3-2022.html#cb50-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">newdata =</span> <span class="fu">data.frame</span>(<span class="at">island =</span> <span class="fu">factor</span>(<span class="st">&quot;Biscoe&quot;</span>),</span>
<span id="cb50-3"><a href="thursday-november-3-2022.html#cb50-3" aria-hidden="true" tabindex="-1"></a>                             <span class="at">sex =</span> <span class="fu">factor</span>(<span class="st">&quot;male&quot;</span>),</span>
<span id="cb50-4"><a href="thursday-november-3-2022.html#cb50-4" aria-hidden="true" tabindex="-1"></a>                             <span class="at">year =</span> <span class="dv">2020</span>,</span>
<span id="cb50-5"><a href="thursday-november-3-2022.html#cb50-5" aria-hidden="true" tabindex="-1"></a>                             <span class="at">flipper_length_mm =</span> <span class="dv">200</span>,</span>
<span id="cb50-6"><a href="thursday-november-3-2022.html#cb50-6" aria-hidden="true" tabindex="-1"></a>                             <span class="at">bill_length_mm =</span> <span class="dv">44</span>,</span>
<span id="cb50-7"><a href="thursday-november-3-2022.html#cb50-7" aria-hidden="true" tabindex="-1"></a>                             <span class="at">bill_depth_mm =</span> <span class="dv">18</span>,</span>
<span id="cb50-8"><a href="thursday-november-3-2022.html#cb50-8" aria-hidden="true" tabindex="-1"></a>                             <span class="at">body_mass_g =</span> <span class="dv">4000</span>))</span></code></pre></div>
<pre><code>##       Adelie Chinstrap     Gentoo
## 1 0.06349206 0.9206349 0.01587302</code></pre>
<p>The result says that there is a 92% chance that it is a Chinstrap penguin, a 6% chance that it is an Adelie penguin and a 2% chance that it is a Gentoo penguin.</p>
<p>The <code>ctree()</code> function in {party} package can be used to model binary, nominal, ordinal and numeric variables.</p>
<p>The {rpart} packages contains additional functions for modeling our data with decision trees. See also: <a href="http://rstatistics.net/decision-trees-with-r/" class="uri">http://rstatistics.net/decision-trees-with-r/</a></p>
<p>Summary: It is relative easy to fit (train) statistical and machine learning models in R. We saw how to train a random forest model. Predictive uncertainty is harder to work out especially for more complex models. Cross validation provides one way to do this. It removes noise specific to each observation and estimates how well the model finds useful prediction rules when this coincident information is unavailable.</p>
<p>Next time: logistic regression and cluster analysis</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="tuesday-november-1-2022.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="thursday-november-3-2022-1.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

</body>

</html>
