<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Tuesday, October 12, 2022 | GEO5156: Quantitative Geography</title>
  <meta name="description" content="Tuesday, October 12, 2022 | GEO5156: Quantitative Geography" />
  <meta name="generator" content="bookdown 0.24 and GitBook 2.6.7" />

  <meta property="og:title" content="Tuesday, October 12, 2022 | GEO5156: Quantitative Geography" />
  <meta property="og:type" content="book" />
  
  
  
  <meta name="github-repo" content="jelsner/QG-2022" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Tuesday, October 12, 2022 | GEO5156: Quantitative Geography" />
  
  
  

<meta name="author" content="James B. Elsner" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="thursday-october-5-2022.html"/>

<script src="libs/header-attrs-2.11/header-attrs.js"></script>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Quantitative Geography</a></li>

<li class="divider"></li>
<li><a href="index.html#section"></a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html"><i class="fa fa-check"></i>Syllabus</a>
<ul>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#geo5165c-quantitative-geography"><i class="fa fa-check"></i>GEO5165C: Quantitative Geography</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#contact-information"><i class="fa fa-check"></i>Contact information</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#course-description"><i class="fa fa-check"></i>Course description</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#expected-learning-outcomes"><i class="fa fa-check"></i>Expected learning outcomes</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#materials"><i class="fa fa-check"></i>Materials</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#class-meetings"><i class="fa fa-check"></i>Class meetings</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#grades"><i class="fa fa-check"></i>Grades</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#academic-honor-code"><i class="fa fa-check"></i>Academic honor code</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#students-with-disabilities-act"><i class="fa fa-check"></i>Students With Disabilities Act</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#inclusiveness"><i class="fa fa-check"></i>Inclusiveness</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#more-about-your-instructor"><i class="fa fa-check"></i>More about your instructor</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#syllabus-change-policy"><i class="fa fa-check"></i>Syllabus change policy</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#schedule-subject-to-change-with-notice"><i class="fa fa-check"></i>Schedule (subject to change with notice)</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#other-materials-to-check-out"><i class="fa fa-check"></i>Other materials to check out</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#julia-programming-language"><i class="fa fa-check"></i>Julia programming language</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html"><i class="fa fa-check"></i>Tuesday, August 23, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#today"><i class="fa fa-check"></i>Today</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#what-is-this-course"><i class="fa fa-check"></i>What is this course?</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#where-are-the-materials-for-this-course"><i class="fa fa-check"></i>Where are the materials for this course?</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#join-rstudio-cloud"><i class="fa fa-check"></i>Join RStudio Cloud</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#examples"><i class="fa fa-check"></i>Examples</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#course-syllabus"><i class="fa fa-check"></i>Course Syllabus</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#tallahassee-daily-temperatures"><i class="fa fa-check"></i>Tallahassee daily temperatures</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html"><i class="fa fa-check"></i>Thursday, August 25, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#today-1"><i class="fa fa-check"></i>Today</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#data-analysis"><i class="fa fa-check"></i>Data Analysis</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#reproducibility"><i class="fa fa-check"></i>Reproducibility</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#communication"><i class="fa fa-check"></i>Communication</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#automation"><i class="fa fa-check"></i>Automation</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#the-r-programming-language"><i class="fa fa-check"></i>The R programming language</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#overview-of-this-course"><i class="fa fa-check"></i>Overview of this course</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#work-in-plain-text-using-r-markdown"><i class="fa fa-check"></i>Work in plain text, using R Markdown</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#visualizing-data"><i class="fa fa-check"></i>Visualizing data</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#a-code-template"><i class="fa fa-check"></i>A code template</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#the-code"><i class="fa fa-check"></i>The code</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#a-graphing-workflow"><i class="fa fa-check"></i>A graphing workflow</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#a-graphing-template"><i class="fa fa-check"></i>A graphing template</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#common-problems"><i class="fa fa-check"></i>Common problems</a></li>
<li><a href="thursday-august-25-2022.html#location-of-the-sign">location of the <code>+</code> sign</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#help"><i class="fa fa-check"></i>help</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#things-to-know"><i class="fa fa-check"></i>Things to know</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#everything-has-a-name"><i class="fa fa-check"></i>Everything has a name</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#everything-is-an-object"><i class="fa fa-check"></i>Everything is an object</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#you-do-things-using-functions"><i class="fa fa-check"></i>You do things using functions</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#functions-come-in-packages-libraries"><i class="fa fa-check"></i>Functions come in packages (libraries)</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#your-turn"><i class="fa fa-check"></i>Your turn</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html"><i class="fa fa-check"></i>Tuesday, August 30, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html#today-2"><i class="fa fa-check"></i>Today</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html#scatter-plots"><i class="fa fa-check"></i>Scatter plots</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html#facets"><i class="fa fa-check"></i>Facets</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html#calculations"><i class="fa fa-check"></i>Calculations</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html#functions"><i class="fa fa-check"></i>Functions</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html#syntax-is-important"><i class="fa fa-check"></i>Syntax is important</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html#saving-an-object"><i class="fa fa-check"></i>Saving an object</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html#object-names"><i class="fa fa-check"></i>Object names</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html#entering-data"><i class="fa fa-check"></i>Entering data</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html#applying-a-function"><i class="fa fa-check"></i>Applying a function</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html#averge"><i class="fa fa-check"></i>Averge</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html#data-vectors"><i class="fa fa-check"></i>Data vectors</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html#variance"><i class="fa fa-check"></i>Variance</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html#data-vectors-have-a-type"><i class="fa fa-check"></i>Data vectors have a type</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html#working-smarter"><i class="fa fa-check"></i>Working smarter</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-september-1-2022.html"><a href="thursday-september-1-2022.html"><i class="fa fa-check"></i>Thursday, September 1, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-september-1-2022.html"><a href="thursday-september-1-2022.html#today-3"><i class="fa fa-check"></i>Today</a></li>
<li class="chapter" data-level="" data-path="thursday-september-1-2022.html"><a href="thursday-september-1-2022.html#data-as-vectors"><i class="fa fa-check"></i>Data as vectors</a></li>
<li class="chapter" data-level="" data-path="thursday-september-1-2022.html"><a href="thursday-september-1-2022.html#mean"><i class="fa fa-check"></i>Mean</a></li>
<li class="chapter" data-level="" data-path="thursday-september-1-2022.html"><a href="thursday-september-1-2022.html#variance-1"><i class="fa fa-check"></i>Variance</a></li>
<li class="chapter" data-level="" data-path="thursday-september-1-2022.html"><a href="thursday-september-1-2022.html#median"><i class="fa fa-check"></i>Median</a></li>
<li class="chapter" data-level="" data-path="thursday-september-1-2022.html"><a href="thursday-september-1-2022.html#spread"><i class="fa fa-check"></i>Spread</a></li>
<li class="chapter" data-level="" data-path="thursday-september-1-2022.html"><a href="thursday-september-1-2022.html#vector-types"><i class="fa fa-check"></i>Vector types</a></li>
<li class="chapter" data-level="" data-path="thursday-september-1-2022.html"><a href="thursday-september-1-2022.html#structured-data"><i class="fa fa-check"></i>Structured data</a></li>
<li class="chapter" data-level="" data-path="thursday-september-1-2022.html"><a href="thursday-september-1-2022.html#asking-questions"><i class="fa fa-check"></i>Asking questions</a></li>
<li class="chapter" data-level="" data-path="thursday-september-1-2022.html"><a href="thursday-september-1-2022.html#tables-and-summaries"><i class="fa fa-check"></i>Tables and summaries</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-september-6-2022.html"><a href="tuesday-september-6-2022.html"><i class="fa fa-check"></i>Tuesday, September 6, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-september-6-2022.html"><a href="tuesday-september-6-2022.html#today-4"><i class="fa fa-check"></i>Today</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-6-2022.html"><a href="tuesday-september-6-2022.html#getting-your-data-into-r"><i class="fa fa-check"></i>Getting your data into R</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-6-2022.html"><a href="tuesday-september-6-2022.html#creating-structured-data-files"><i class="fa fa-check"></i>Creating structured data files</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-6-2022.html"><a href="tuesday-september-6-2022.html#data-frames"><i class="fa fa-check"></i>Data frames</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-6-2022.html"><a href="tuesday-september-6-2022.html#quantiles"><i class="fa fa-check"></i>Quantiles</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-6-2022.html"><a href="tuesday-september-6-2022.html#creating-a-data-frame"><i class="fa fa-check"></i>Creating a data frame</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-6-2022.html"><a href="tuesday-september-6-2022.html#pipes"><i class="fa fa-check"></i>Pipes</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-6-2022.html"><a href="tuesday-september-6-2022.html#your-turn-1"><i class="fa fa-check"></i>Your turn</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-september-8-2022.html"><a href="thursday-september-8-2022.html"><i class="fa fa-check"></i>Thursday, September 8, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-september-8-2022.html"><a href="thursday-september-8-2022.html#today-5"><i class="fa fa-check"></i>Today</a></li>
<li class="chapter" data-level="" data-path="thursday-september-8-2022.html"><a href="thursday-september-8-2022.html#pipe-operator"><i class="fa fa-check"></i>Pipe operator</a></li>
<li class="chapter" data-level="" data-path="thursday-september-8-2022.html"><a href="thursday-september-8-2022.html#wrangling-data-frames"><i class="fa fa-check"></i>Wrangling data frames</a></li>
<li class="chapter" data-level="" data-path="thursday-september-8-2022.html"><a href="thursday-september-8-2022.html#selecting-and-filtering"><i class="fa fa-check"></i>Selecting and filtering</a></li>
<li class="chapter" data-level="" data-path="thursday-september-8-2022.html"><a href="thursday-september-8-2022.html#example-palmer-penguins"><i class="fa fa-check"></i>Example: Palmer penguins</a></li>
<li class="chapter" data-level="" data-path="thursday-september-8-2022.html"><a href="thursday-september-8-2022.html#stringing-functions-together"><i class="fa fa-check"></i>Stringing functions together</a></li>
<li class="chapter" data-level="" data-path="thursday-september-8-2022.html"><a href="thursday-september-8-2022.html#summarize"><i class="fa fa-check"></i>Summarize</a></li>
<li class="chapter" data-level="" data-path="thursday-september-8-2022.html"><a href="thursday-september-8-2022.html#grouping"><i class="fa fa-check"></i>Grouping</a></li>
<li class="chapter" data-level="" data-path="thursday-september-8-2022.html"><a href="thursday-september-8-2022.html#your-turn-2"><i class="fa fa-check"></i>Your turn</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-september-12-2022.html"><a href="tuesday-september-12-2022.html"><i class="fa fa-check"></i>Tuesday, September 12, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-september-12-2022.html"><a href="tuesday-september-12-2022.html#today-6"><i class="fa fa-check"></i>Today</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-12-2022.html"><a href="tuesday-september-12-2022.html#example-1-new-york-city-flight-data"><i class="fa fa-check"></i>Example 1: New York City flight data</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-12-2022.html"><a href="tuesday-september-12-2022.html#example-2-daily-weather-data-from-tallahassee"><i class="fa fa-check"></i>Example 2: Daily weather data from Tallahassee</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-12-2022.html"><a href="tuesday-september-12-2022.html#putting-everything-together"><i class="fa fa-check"></i>Putting everything together</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-12-2022.html"><a href="tuesday-september-12-2022.html#example-3-food-consumption-and-co2-emissions"><i class="fa fa-check"></i>Example 3: Food consumption and CO2 emissions</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-12-2022.html"><a href="tuesday-september-12-2022.html#summary"><i class="fa fa-check"></i>Summary</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-september-14-2022.html"><a href="thursday-september-14-2022.html"><i class="fa fa-check"></i>Thursday, September 14, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-september-14-2022.html"><a href="thursday-september-14-2022.html#today-7"><i class="fa fa-check"></i>Today</a></li>
<li class="chapter" data-level="" data-path="thursday-september-14-2022.html"><a href="thursday-september-14-2022.html#bar-chart"><i class="fa fa-check"></i>Bar chart</a></li>
<li class="chapter" data-level="" data-path="thursday-september-14-2022.html"><a href="thursday-september-14-2022.html#pie-preference"><i class="fa fa-check"></i>Pie preference</a></li>
<li class="chapter" data-level="" data-path="thursday-september-14-2022.html"><a href="thursday-september-14-2022.html#histogram"><i class="fa fa-check"></i>Histogram</a></li>
<li class="chapter" data-level="" data-path="thursday-september-14-2022.html"><a href="thursday-september-14-2022.html#density-plot"><i class="fa fa-check"></i>Density plot</a></li>
<li class="chapter" data-level="" data-path="thursday-september-14-2022.html"><a href="thursday-september-14-2022.html#box-plot"><i class="fa fa-check"></i>Box plot</a></li>
<li class="chapter" data-level="" data-path="thursday-september-14-2022.html"><a href="thursday-september-14-2022.html#side-by-side-box-plots"><i class="fa fa-check"></i>Side-by-side box plots</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-september-19-2022.html"><a href="tuesday-september-19-2022.html"><i class="fa fa-check"></i>Tuesday, September 19, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-september-19-2022.html"><a href="tuesday-september-19-2022.html#today-8"><i class="fa fa-check"></i>Today</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-19-2022.html"><a href="tuesday-september-19-2022.html#comparing-distributions"><i class="fa fa-check"></i>Comparing distributions</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-19-2022.html"><a href="tuesday-september-19-2022.html#box-plots"><i class="fa fa-check"></i>Box plots</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-19-2022.html"><a href="tuesday-september-19-2022.html#long-data-frames"><i class="fa fa-check"></i>Long data frames</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-19-2022.html"><a href="tuesday-september-19-2022.html#scatter-plots-1"><i class="fa fa-check"></i>Scatter plots</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-19-2022.html"><a href="tuesday-september-19-2022.html#facets-1"><i class="fa fa-check"></i>Facets</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-19-2022.html"><a href="tuesday-september-19-2022.html#example-palmer-penguins-1"><i class="fa fa-check"></i>Example: Palmer penguins</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-19-2022.html"><a href="tuesday-september-19-2022.html#an-expository-graph"><i class="fa fa-check"></i>An expository graph</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-19-2022.html"><a href="tuesday-september-19-2022.html#exporting-your-graph"><i class="fa fa-check"></i>Exporting your graph</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-september-21-2022.html"><a href="thursday-september-21-2022.html"><i class="fa fa-check"></i>Thursday, September 21, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-september-21-2022.html"><a href="thursday-september-21-2022.html#today-9"><i class="fa fa-check"></i>Today</a></li>
<li class="chapter" data-level="" data-path="thursday-september-21-2022.html"><a href="thursday-september-21-2022.html#simple-feature-data-frames"><i class="fa fa-check"></i>Simple feature data frames</a></li>
<li class="chapter" data-level="" data-path="thursday-september-21-2022.html"><a href="thursday-september-21-2022.html#making-a-boundary-map"><i class="fa fa-check"></i>Making a boundary map</a></li>
<li class="chapter" data-level="" data-path="thursday-september-21-2022.html"><a href="thursday-september-21-2022.html#fills"><i class="fa fa-check"></i>Fills</a></li>
<li class="chapter" data-level="" data-path="thursday-september-21-2022.html"><a href="thursday-september-21-2022.html#overlays"><i class="fa fa-check"></i>Overlays</a></li>
<li class="chapter" data-level="" data-path="thursday-september-21-2022.html"><a href="thursday-september-21-2022.html#map-projections"><i class="fa fa-check"></i>Map projections</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-september-21-2022-1.html"><a href="thursday-september-21-2022-1.html"><i class="fa fa-check"></i>Thursday, September 21, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-september-21-2022-1.html"><a href="thursday-september-21-2022-1.html#today-10"><i class="fa fa-check"></i>Today</a></li>
<li class="chapter" data-level="" data-path="thursday-september-21-2022-1.html"><a href="thursday-september-21-2022-1.html#making-maps-using-functions-from-the-tmap-package"><i class="fa fa-check"></i>Making maps using functions from the {tmap} package</a></li>
<li class="chapter" data-level="" data-path="thursday-september-21-2022-1.html"><a href="thursday-september-21-2022-1.html#example-mapping-tornadoes"><i class="fa fa-check"></i>Example: Mapping tornadoes</a></li>
<li class="chapter" data-level="" data-path="thursday-september-21-2022-1.html"><a href="thursday-september-21-2022-1.html#example-mapping-the-frequency-of-tornadoes-by-state"><i class="fa fa-check"></i>Example: Mapping the frequency of tornadoes by state</a></li>
<li class="chapter" data-level="" data-path="thursday-september-21-2022-1.html"><a href="thursday-september-21-2022-1.html#calculations-using-the-geometry-simple-feature-column"><i class="fa fa-check"></i>Calculations using the geometry simple feature column</a></li>
<li class="chapter" data-level="" data-path="thursday-september-21-2022-1.html"><a href="thursday-september-21-2022-1.html#making-raster-maps"><i class="fa fa-check"></i>Making raster maps</a></li>
<li class="chapter" data-level="" data-path="thursday-september-21-2022-1.html"><a href="thursday-september-21-2022-1.html#get-map-images-using-functions-from-the-ggmap-package"><i class="fa fa-check"></i>Get map images using functions from the {ggmap} package</a></li>
<li class="chapter" data-level="" data-path="thursday-september-21-2022-1.html"><a href="thursday-september-21-2022-1.html#add-data-to-the-raster-map"><i class="fa fa-check"></i>Add data to the raster map</a></li>
<li class="chapter" data-level="" data-path="thursday-september-21-2022-1.html"><a href="thursday-september-21-2022-1.html#spatial-density-maps-extra-material"><i class="fa fa-check"></i>Spatial density maps (extra material)</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-september-26-2022.html"><a href="tuesday-september-26-2022.html"><i class="fa fa-check"></i>Tuesday, September 26, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-september-26-2022.html"><a href="tuesday-september-26-2022.html#today-11"><i class="fa fa-check"></i>Today</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-26-2022.html"><a href="tuesday-september-26-2022.html#one-sample-test-of-the-population-mean"><i class="fa fa-check"></i>One-sample test of the population mean</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-26-2022.html"><a href="tuesday-september-26-2022.html#about-p-values"><i class="fa fa-check"></i>About p-values</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-26-2022.html"><a href="tuesday-september-26-2022.html#example-strongest-atlantic-hurricanes"><i class="fa fa-check"></i>Example: Strongest Atlantic hurricanes</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-26-2022.html"><a href="tuesday-september-26-2022.html#graphical-inference"><i class="fa fa-check"></i>Graphical inference</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-26-2022.html"><a href="tuesday-september-26-2022.html#two-sample-test-of-the-difference-in-population-means"><i class="fa fa-check"></i>Two-sample test of the difference in population means</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-26-2022.html"><a href="tuesday-september-26-2022.html#example-hurricanes-in-the-north-atlantic-and-the-eastern-north-pacific"><i class="fa fa-check"></i>Example: hurricanes in the North Atlantic and the eastern North Pacific</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-26-2022.html"><a href="tuesday-september-26-2022.html#example-palmer-penguins-2"><i class="fa fa-check"></i>Example: Palmer penguins</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-26-2022.html"><a href="tuesday-september-26-2022.html#your-turn-3"><i class="fa fa-check"></i>Your turn</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-26-2022.html"><a href="tuesday-september-26-2022.html#test-of-equal-variance"><i class="fa fa-check"></i>Test of equal variance</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-26-2022.html"><a href="tuesday-september-26-2022.html#wilcoxon-mann-whitney-u-non-parameteric-test-of-difference-in-means"><i class="fa fa-check"></i>Wilcoxon (Mann-Whitney U) non-parameteric test of difference in means</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-september-28-2022.html"><a href="thursday-september-28-2022.html"><i class="fa fa-check"></i>Thursday, September 28, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-september-28-2022.html"><a href="thursday-september-28-2022.html#today-12"><i class="fa fa-check"></i>Today</a></li>
<li class="chapter" data-level="" data-path="thursday-september-28-2022.html"><a href="thursday-september-28-2022.html#review"><i class="fa fa-check"></i>Review</a></li>
<li class="chapter" data-level="" data-path="thursday-september-28-2022.html"><a href="thursday-september-28-2022.html#paired-observations"><i class="fa fa-check"></i>Paired observations</a></li>
<li class="chapter" data-level="" data-path="thursday-september-28-2022.html"><a href="thursday-september-28-2022.html#example-reaction-time-while-driving"><i class="fa fa-check"></i>Example: Reaction time while driving</a></li>
<li class="chapter" data-level="" data-path="thursday-september-28-2022.html"><a href="thursday-september-28-2022.html#chi-squared-test-for-independence"><i class="fa fa-check"></i>Chi-squared test for independence</a></li>
<li class="chapter" data-level="" data-path="thursday-september-28-2022.html"><a href="thursday-september-28-2022.html#example-smoking-and-exercise"><i class="fa fa-check"></i>Example: Smoking and exercise</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-october-3-2022.html"><a href="tuesday-october-3-2022.html"><i class="fa fa-check"></i>Tuesday, October 3, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-october-3-2022.html"><a href="tuesday-october-3-2022.html#today-13"><i class="fa fa-check"></i>Today</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-3-2022.html"><a href="tuesday-october-3-2022.html#distributions"><i class="fa fa-check"></i>Distributions</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-3-2022.html"><a href="tuesday-october-3-2022.html#normal-distribution"><i class="fa fa-check"></i>Normal distribution</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-3-2022.html"><a href="tuesday-october-3-2022.html#uniform-distribution"><i class="fa fa-check"></i>Uniform distribution</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-3-2022.html"><a href="tuesday-october-3-2022.html#how-many-blue-marbles"><i class="fa fa-check"></i>How many blue marbles?</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-3-2022.html"><a href="tuesday-october-3-2022.html#what-percentage-of-the-globe-is-covered-by-water"><i class="fa fa-check"></i>What percentage of the globe is covered by water?</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-3-2022.html"><a href="tuesday-october-3-2022.html#how-many-fish-are-in-the-lake"><i class="fa fa-check"></i>How many fish are in the lake?</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-october-5-2022.html"><a href="thursday-october-5-2022.html"><i class="fa fa-check"></i>Thursday, October 5, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-october-5-2022.html"><a href="thursday-october-5-2022.html#today-14"><i class="fa fa-check"></i>Today</a></li>
<li class="chapter" data-level="" data-path="thursday-october-5-2022.html"><a href="thursday-october-5-2022.html#how-many-fish-are-in-the-lake-1"><i class="fa fa-check"></i>How many fish are in the lake?</a></li>
<li class="chapter" data-level="" data-path="thursday-october-5-2022.html"><a href="thursday-october-5-2022.html#percentage-of-survey-signups"><i class="fa fa-check"></i>Percentage of survey signups</a></li>
<li class="chapter" data-level="" data-path="thursday-october-5-2022.html"><a href="thursday-october-5-2022.html#a-generative-model-for-people-agreeing-to-take-your-survey"><i class="fa fa-check"></i>A generative model for people agreeing to take your survey</a></li>
<li class="chapter" data-level="" data-path="thursday-october-5-2022.html"><a href="thursday-october-5-2022.html#prior-for-the-response-rate"><i class="fa fa-check"></i>Prior for the response rate</a></li>
<li class="chapter" data-level="" data-path="thursday-october-5-2022.html"><a href="thursday-october-5-2022.html#define-the-generative-model-and-simulate-the-data"><i class="fa fa-check"></i>Define the generative model and simulate the data</a></li>
<li class="chapter" data-level="" data-path="thursday-october-5-2022.html"><a href="thursday-october-5-2022.html#prediction"><i class="fa fa-check"></i>Prediction</a></li>
<li class="chapter" data-level="" data-path="thursday-october-5-2022.html"><a href="thursday-october-5-2022.html#approximate-bayesian-computation"><i class="fa fa-check"></i>Approximate Bayesian computation</a></li>
<li class="chapter" data-level="" data-path="thursday-october-5-2022.html"><a href="thursday-october-5-2022.html#what-bayesian-data-analysis-is-not"><i class="fa fa-check"></i>What Bayesian data analysis is not</a></li>
<li class="chapter" data-level="" data-path="thursday-october-5-2022.html"><a href="thursday-october-5-2022.html#comparing-two-hypotheses"><i class="fa fa-check"></i>Comparing two hypotheses</a></li>
<li class="chapter" data-level="" data-path="thursday-october-5-2022.html"><a href="thursday-october-5-2022.html#reaction-times-while-driving"><i class="fa fa-check"></i>Reaction times while driving</a></li>
<li class="chapter" data-level="" data-path="thursday-october-5-2022.html"><a href="thursday-october-5-2022.html#repeat-the-survey-example"><i class="fa fa-check"></i>Repeat the survey example</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-october-12-2022.html"><a href="tuesday-october-12-2022.html"><i class="fa fa-check"></i>Tuesday, October 12, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-october-12-2022.html"><a href="tuesday-october-12-2022.html#today-15"><i class="fa fa-check"></i>Today</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-12-2022.html"><a href="tuesday-october-12-2022.html#linear-regression-a-t-test-by-another-name"><i class="fa fa-check"></i>Linear regression: A t test by another name</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-12-2022.html"><a href="tuesday-october-12-2022.html#motivating-regression"><i class="fa fa-check"></i>Motivating regression</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-12-2022.html"><a href="tuesday-october-12-2022.html#eyeballing-the-regression"><i class="fa fa-check"></i>Eyeballing the regression</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-12-2022.html"><a href="tuesday-october-12-2022.html#example-increasing-heart-rates-with-age"><i class="fa fa-check"></i>Example: Increasing heart rates with age</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-12-2022.html"><a href="tuesday-october-12-2022.html#making-predictions-with-regression"><i class="fa fa-check"></i>Making predictions with regression</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-12-2022.html"><a href="tuesday-october-12-2022.html#uncertainty-about-the-regression-coefficients"><i class="fa fa-check"></i>Uncertainty about the regression coefficients</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-12-2022.html"><a href="tuesday-october-12-2022.html#bootstrapping-the-uncertainty"><i class="fa fa-check"></i>Bootstrapping the uncertainty</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-12-2022.html"><a href="tuesday-october-12-2022.html#predictive-uncertainty"><i class="fa fa-check"></i>Predictive uncertainty</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">GEO5156: Quantitative Geography</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="tuesday-october-12-2022" class="section level1 unnumbered">
<h1>Tuesday, October 12, 2022</h1>
<div id="today-15" class="section level2 unnumbered">
<h2>Today</h2>
<ul>
<li>Regression</li>
</ul>
<p>Regression provides another way to implement a <span class="math inline">\(t\)</span> test but it is much more than that. In this lesson: how to fit a regression model, make predictions, interpret the output, and quantify the uncertainty about the model (coefficients) and about predictions made from the model.</p>
</div>
<div id="linear-regression-a-t-test-by-another-name" class="section level2 unnumbered">
<h2>Linear regression: A t test by another name</h2>
<p>Recall that a <span class="math inline">\(t\)</span> test quantifies the evidence about whether population means from two groups are statistically different. Regression extends this test to an arbitrary number of groups.</p>
<p>Consider again the <code>mtcars</code> data frame.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="tuesday-october-12-2022.html#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(mtcars)</span></code></pre></div>
<pre><code>##                    mpg cyl disp  hp drat    wt  qsec vs am gear carb
## Mazda RX4         21.0   6  160 110 3.90 2.620 16.46  0  1    4    4
## Mazda RX4 Wag     21.0   6  160 110 3.90 2.875 17.02  0  1    4    4
## Datsun 710        22.8   4  108  93 3.85 2.320 18.61  1  1    4    1
## Hornet 4 Drive    21.4   6  258 110 3.08 3.215 19.44  1  0    3    1
## Hornet Sportabout 18.7   8  360 175 3.15 3.440 17.02  0  0    3    2
## Valiant           18.1   6  225 105 2.76 3.460 20.22  1  0    3    1</code></pre>
<p>You test the null hypothesis that there is no difference in average miles per gallon (<code>mpg</code> variable) between cars with and without automatic transmission (<code>am</code> variable). If you assume the variance in the gas mileage is the same for both groups (recall the box plots will look similar) then you implement the test as follows.</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="tuesday-october-12-2022.html#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(mpg <span class="sc">~</span> am, </span>
<span id="cb3-2"><a href="tuesday-october-12-2022.html#cb3-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">data =</span> mtcars, </span>
<span id="cb3-3"><a href="tuesday-october-12-2022.html#cb3-3" aria-hidden="true" tabindex="-1"></a>       <span class="at">var.equal =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## 
##  Two Sample t-test
## 
## data:  mpg by am
## t = -4.1061, df = 30, p-value = 0.000285
## alternative hypothesis: true difference in means between group 0 and group 1 is not equal to 0
## 95 percent confidence interval:
##  -10.84837  -3.64151
## sample estimates:
## mean in group 0 mean in group 1 
##        17.14737        24.39231</code></pre>
<p>The <span class="math inline">\(t\)</span> value, computed as the difference in means divided by the standard error of the difference, is -4.1061.</p>
<p>With 30 degrees of freedom (sample size = 32 and you loose one degree of freedom for each mean), the <span class="math inline">\(p\)</span>-value is less than .01 so you reject the null hypothesis of no difference in average miles per gallon between the two types of transmission.</p>
<p>The average miles per gallon over the sample of cars is 17.1 and 24.4 mpg for automatic and manual transmissions, respectively.</p>
<p>The test can be done with linear regression. Linear regression is a statistical model for data that uses a straight line to describe the relationship between variables.</p>
<p>The function for linear regression is <code>lm()</code>. The syntax is the same as the <code>t.test()</code> function except the assumption of equal variance is the default. Here you first assign the output of the <code>lm()</code> function to an object (call the object <code>model</code>). Then to see the output use the <code>summary()</code> method.</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="tuesday-october-12-2022.html#cb5-1" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(mpg <span class="sc">~</span> am, </span>
<span id="cb5-2"><a href="tuesday-october-12-2022.html#cb5-2" aria-hidden="true" tabindex="-1"></a>            <span class="at">data =</span> mtcars)</span>
<span id="cb5-3"><a href="tuesday-october-12-2022.html#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = mpg ~ am, data = mtcars)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -9.3923 -3.0923 -0.2974  3.2439  9.5077 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   17.147      1.125  15.247 1.13e-15 ***
## am             7.245      1.764   4.106 0.000285 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 4.902 on 30 degrees of freedom
## Multiple R-squared:  0.3598, Adjusted R-squared:  0.3385 
## F-statistic: 16.86 on 1 and 30 DF,  p-value: 0.000285</code></pre>
<p>You see the <span class="math inline">\(p\)</span>-value from the linear regression is identical to the <span class="math inline">\(p\)</span>-value from the <span class="math inline">\(t\)</span> test. You state, as before, that you reject the null hypothesis of no difference in average miles per gallon between the two types of transmission.</p>
<p>In the table of coefficients you see the value of <code>7.245</code> next to <code>am</code> in the column labeled <code>Estimate</code>. This is the difference in average mpg grouped by transmission (<code>mean in group 1</code> minus <code>mean in group 0</code>).</p>
<p>Linear regression provides a way to generalize comparisons across any number of groups (not just two as is the case with a <span class="math inline">\(t\)</span> test).</p>
</div>
<div id="motivating-regression" class="section level2 unnumbered">
<h2>Motivating regression</h2>
<p>Suppose you have the following values for variables <code>y</code> and <code>x</code>. Let <code>y</code> be the ‘response’ variable and <code>x</code> be the ‘explanatory’ variable.</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="tuesday-october-12-2022.html#cb7-1" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">2.9</span>, <span class="sc">-</span><span class="fl">2.1</span>, <span class="sc">-</span><span class="fl">0.5</span>, <span class="fl">2.9</span>, <span class="fl">4.2</span>)</span>
<span id="cb7-2"><a href="tuesday-october-12-2022.html#cb7-2" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">5</span></span></code></pre></div>
<p>You start with a scatter plot and assign the graph to an object called <code>p</code>.</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="tuesday-october-12-2022.html#cb8-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(x, y)</span>
<span id="cb8-2"><a href="tuesday-october-12-2022.html#cb8-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-3"><a href="tuesday-october-12-2022.html#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb8-4"><a href="tuesday-october-12-2022.html#cb8-4" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> df, </span>
<span id="cb8-5"><a href="tuesday-october-12-2022.html#cb8-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> x, <span class="at">y =</span> y)) <span class="sc">+</span></span>
<span id="cb8-6"><a href="tuesday-october-12-2022.html#cb8-6" aria-hidden="true" tabindex="-1"></a>       <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">2</span>)</span>
<span id="cb8-7"><a href="tuesday-october-12-2022.html#cb8-7" aria-hidden="true" tabindex="-1"></a>p</span></code></pre></div>
<p><img src="QG-2022_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<p>Next you add a horizontal line to the graph at the mean of <code>y</code>. The mean of <code>y</code> is given by the <code>mean()</code> function. The <code>scale_y_continuous()</code> function is used to set the range on y-axis scale.</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="tuesday-october-12-2022.html#cb9-1" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> p <span class="sc">+</span> <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="fu">mean</span>(y)) <span class="sc">+</span></span>
<span id="cb9-2"><a href="tuesday-october-12-2022.html#cb9-2" aria-hidden="true" tabindex="-1"></a>           <span class="fu">scale_y_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">6</span>, <span class="dv">6</span>))</span>
<span id="cb9-3"><a href="tuesday-october-12-2022.html#cb9-3" aria-hidden="true" tabindex="-1"></a>p</span></code></pre></div>
<p>The mean, indicated by the horizontal line, is a model for these data. Some points are above the line and other points are below it. No individual value of <code>y</code> fits the model precisely (no points are exactly on the line), but the model represents the ‘best’ guess at where the average from a set of new values will be.</p>
<p>The closer the points are to the line, the better the data fit the model. Closeness is defined as the distance along the y axis (vertical) between the point and the line.</p>
<p>Points above the line indicate values that are larger than the mean, so <code>y - mean(y)</code> is positive for these values. Points below the line indicate values that are smaller than the mean, so <code>y - mean(y)</code> is negative for these values.</p>
<p>You include these distances on the graph using the <code>geom_segment()</code> layer. Aesthetics for this layer include the begin and end values for the x and y variables.</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="tuesday-october-12-2022.html#cb10-1" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> p <span class="sc">+</span> <span class="fu">geom_segment</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">y =</span> <span class="fu">mean</span>(y), <span class="at">yend =</span> y, </span>
<span id="cb10-2"><a href="tuesday-october-12-2022.html#cb10-2" aria-hidden="true" tabindex="-1"></a>                                    <span class="at">x =</span> x, <span class="at">xend =</span> x))</span>
<span id="cb10-3"><a href="tuesday-october-12-2022.html#cb10-3" aria-hidden="true" tabindex="-1"></a>p</span></code></pre></div>
<p><img src="QG-2022_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<p>The individual distances are called “errors.” Statisticians call them “residuals.” <em>Key idea</em>: A residual is always the observed value minus the modeled value.</p>
<p>The sum of the five residuals is zero.</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="tuesday-october-12-2022.html#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>( y <span class="sc">-</span> <span class="fu">mean</span>(y) )</span></code></pre></div>
<pre><code>## [1] -4.440892e-16</code></pre>
<p>If you sum the five residuals after squaring each of them you get a measure of how well the model fits the data. The smaller the sum, the better the fit.</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="tuesday-october-12-2022.html#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>( (y <span class="sc">-</span> <span class="fu">mean</span>(y))<span class="sc">^</span><span class="dv">2</span> )</span></code></pre></div>
<pre><code>## [1] 28.168</code></pre>
<p>This sum is called the <em>residual sum of squares</em> (RSS). An RSS equal to 0 indicates that all points fall exactly on the line.</p>
<p>You include the RSS value as a label on the plot using the <code>geom_label()</code> function.</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="tuesday-october-12-2022.html#cb15-1" aria-hidden="true" tabindex="-1"></a>RSS <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">sum</span>((y <span class="sc">-</span> <span class="fu">mean</span>(y))<span class="sc">^</span><span class="dv">2</span>), <span class="dv">1</span>)</span>
<span id="cb15-2"><a href="tuesday-october-12-2022.html#cb15-2" aria-hidden="true" tabindex="-1"></a>lab <span class="ot">&lt;-</span> <span class="fu">paste</span>(<span class="st">&quot;RSS = &quot;</span>, RSS)</span>
<span id="cb15-3"><a href="tuesday-october-12-2022.html#cb15-3" aria-hidden="true" tabindex="-1"></a>lab</span></code></pre></div>
<pre><code>## [1] &quot;RSS =  28.2&quot;</code></pre>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="tuesday-october-12-2022.html#cb17-1" aria-hidden="true" tabindex="-1"></a>p <span class="sc">+</span> <span class="fu">geom_label</span>(<span class="at">x =</span> <span class="dv">4</span>, <span class="at">y =</span> <span class="sc">-</span><span class="dv">2</span>, <span class="at">label =</span> lab)</span></code></pre></div>
<p><img src="QG-2022_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
<p>Notice the pattern. With the exception of the first, the residuals go from large negative with the 2nd value to large positive with the 5th value.</p>
<p>This pattern suggests that perhaps you can find a line through the data that has a smaller RSS. A line that is not horizontal but slopes upward.</p>
<p>Let’s draw another graph.</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="tuesday-october-12-2022.html#cb18-1" aria-hidden="true" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> <span class="fu">data.frame</span>(x, y), </span>
<span id="cb18-2"><a href="tuesday-october-12-2022.html#cb18-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">mapping =</span> <span class="fu">aes</span>(x, y)) <span class="sc">+</span></span>
<span id="cb18-3"><a href="tuesday-october-12-2022.html#cb18-3" aria-hidden="true" tabindex="-1"></a>        <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb18-4"><a href="tuesday-october-12-2022.html#cb18-4" aria-hidden="true" tabindex="-1"></a>        <span class="fu">scale_y_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">6</span>, <span class="dv">6</span>)) </span>
<span id="cb18-5"><a href="tuesday-october-12-2022.html#cb18-5" aria-hidden="true" tabindex="-1"></a>p1</span></code></pre></div>
<p>Next add a sloped line using</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="tuesday-october-12-2022.html#cb19-1" aria-hidden="true" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> p1 <span class="sc">+</span> <span class="fu">geom_smooth</span>(<span class="at">method =</span> lm, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">col =</span> <span class="st">&quot;blue&quot;</span>)</span>
<span id="cb19-2"><a href="tuesday-october-12-2022.html#cb19-2" aria-hidden="true" tabindex="-1"></a>p1</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<p>This is the regression line. You can again plot the distance from a particular value to this new line (the residual).</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="tuesday-october-12-2022.html#cb21-1" aria-hidden="true" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> p1 <span class="sc">+</span> <span class="fu">geom_segment</span>(<span class="fu">aes</span>(<span class="at">y =</span> <span class="fu">predict</span>(<span class="fu">lm</span>(y <span class="sc">~</span> x)), <span class="at">yend =</span> y, </span>
<span id="cb21-2"><a href="tuesday-october-12-2022.html#cb21-2" aria-hidden="true" tabindex="-1"></a>                            <span class="at">x =</span> x, <span class="at">xend =</span> x))</span>
<span id="cb21-3"><a href="tuesday-october-12-2022.html#cb21-3" aria-hidden="true" tabindex="-1"></a>p1</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<p>The RSS for the regression model is</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="tuesday-october-12-2022.html#cb23-1" aria-hidden="true" tabindex="-1"></a>lrm <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> x)</span>
<span id="cb23-2"><a href="tuesday-october-12-2022.html#cb23-2" aria-hidden="true" tabindex="-1"></a>epsilon <span class="ot">&lt;-</span> <span class="fu">residuals</span>(lrm)</span>
<span id="cb23-3"><a href="tuesday-october-12-2022.html#cb23-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-4"><a href="tuesday-october-12-2022.html#cb23-4" aria-hidden="true" tabindex="-1"></a>RSS <span class="ot">&lt;-</span> <span class="fu">sum</span>(epsilon<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb23-5"><a href="tuesday-october-12-2022.html#cb23-5" aria-hidden="true" tabindex="-1"></a>RSS</span></code></pre></div>
<pre><code>## [1] 22.392</code></pre>
<p>Include this value on the plot.</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="tuesday-october-12-2022.html#cb25-1" aria-hidden="true" tabindex="-1"></a>lab <span class="ot">&lt;-</span> <span class="fu">paste</span>(<span class="st">&quot;RSS = &quot;</span>, RSS)</span>
<span id="cb25-2"><a href="tuesday-october-12-2022.html#cb25-2" aria-hidden="true" tabindex="-1"></a>p1 <span class="sc">+</span> <span class="fu">geom_label</span>(<span class="at">x =</span> <span class="dv">4</span>, <span class="at">y =</span> <span class="sc">-</span><span class="dv">2</span>, <span class="at">label =</span> lab)</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<p><img src="QG-2022_files/figure-html/unnamed-chunk-15-1.png" width="672" /></p>
<p>Since the RSS from the sloped line is smaller than the RSS from the flat line you say that the regression line (conditional mean) provides a more precise model. Rule: When choosing a regression model from a set of competing models you choose the model that minimizes the RSS.</p>
<p>For each value of <code>x</code> you have a corresponding value for <code>y</code> and a predicted value for <code>y</code>.</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="tuesday-october-12-2022.html#cb27-1" aria-hidden="true" tabindex="-1"></a>p1 <span class="sc">+</span> <span class="fu">geom_point</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(x, <span class="fu">predict</span>(<span class="fu">lm</span>(y <span class="sc">~</span> x))), </span>
<span id="cb27-2"><a href="tuesday-october-12-2022.html#cb27-2" aria-hidden="true" tabindex="-1"></a>                <span class="at">pch =</span> <span class="dv">15</span>, <span class="at">size =</span> <span class="dv">2</span>)</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<p>You refer to the predicted value at <span class="math inline">\(x_i\)</span> as <span class="math inline">\(\hat y_i\)</span> and refer to the estimated regression line as the prediction line.</p>
<p>The difference between the actual value <span class="math inline">\(y_i\)</span> and this predicted value <span class="math inline">\(\hat y_i\)</span> is the residual, <span class="math inline">\(\varepsilon_i\)</span>. The residual is the vertical distance between the squares to the circles.</p>
<p>The method of least squares determines the line such that the RSS is as small as possible.</p>
<p>Recall that a line is uniquely determined by its slope and the value at which it intersects the vertical axis at x = 0 (y-intercept).</p>
<p>Mathematically the slope is determined by
<span class="math display">\[
\hat \beta_1 = \frac{\sum (x_i-\bar x)(y_i-\bar y)}{\sum (x_i-\bar x)^2}
\]</span></p>
<p>And the y-intercept by
<span class="math display">\[
\hat \beta_0 = \bar y - \hat \beta_1 \bar x
\]</span></p>
<p>As a code chunk.</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="tuesday-october-12-2022.html#cb29-1" aria-hidden="true" tabindex="-1"></a>beta1 <span class="ot">&lt;-</span> <span class="fu">sum</span>((x <span class="sc">-</span> <span class="fu">mean</span>(x)) <span class="sc">*</span> (y <span class="sc">-</span> <span class="fu">mean</span>(y)))<span class="sc">/</span><span class="fu">sum</span>((x <span class="sc">-</span> <span class="fu">mean</span>(x))<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb29-2"><a href="tuesday-october-12-2022.html#cb29-2" aria-hidden="true" tabindex="-1"></a>beta1</span></code></pre></div>
<pre><code>## [1] 0.76</code></pre>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="tuesday-october-12-2022.html#cb31-1" aria-hidden="true" tabindex="-1"></a>beta0 <span class="ot">&lt;-</span> <span class="fu">mean</span>(y) <span class="sc">-</span> beta1 <span class="sc">*</span> <span class="fu">mean</span>(x)</span>
<span id="cb31-2"><a href="tuesday-october-12-2022.html#cb31-2" aria-hidden="true" tabindex="-1"></a>beta0</span></code></pre></div>
<pre><code>## [1] -0.8</code></pre>
<p>The <code>beta1</code> (<span class="math inline">\(\beta_1\)</span>) and <code>beta0</code> (<span class="math inline">\(\beta_0\)</span>) are called regression model coefficients. <span class="math inline">\(\beta_1\)</span> is the slope coefficient and <span class="math inline">\(\beta_0\)</span> is the y-intercept coefficient.</p>
<p>The regression line goes through the point defined by the average value of <code>x</code> and the average value of <code>y</code>.</p>
<p>You could use the above code chunk to determine the regression coefficients but you will always use the <code>lm()</code> function.</p>
<p>The notation is <code>lm(y ~ x)</code>. The <code>~</code> (tilde) in this notation is read “is modeled by” or “is conditional on.” So the model formula <code>y ~ x</code> is read “y is modeled by x.” If you use <code>lm(y ~ x)</code> then you say “y is modeled by x” in a linear way.</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="tuesday-october-12-2022.html#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(y <span class="sc">~</span> x)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = y ~ x)
## 
## Coefficients:
## (Intercept)            x  
##       -0.80         0.76</code></pre>
<p>The value of <span class="math inline">\(\beta_0\)</span> is listed below the word (<code>Intercept</code>) and the value of <span class="math inline">\(\beta_1\)</span> is listed below the explanatory variable name (in this case, simply <code>x</code>).</p>
<p>With this output you write that the mean of y = -0.8 + 0.76x.</p>
<p>Question: Does <code>y</code> modeled by <code>x</code> give the same coefficient values as <code>x</code> modeled by <code>y</code>? Try it.</p>
</div>
<div id="eyeballing-the-regression" class="section level2 unnumbered">
<h2>Eyeballing the regression</h2>
<p><a href="https://sophieehill.shinyapps.io/eyeball-regression/" class="uri">https://sophieehill.shinyapps.io/eyeball-regression/</a></p>
</div>
<div id="example-increasing-heart-rates-with-age" class="section level2 unnumbered">
<h2>Example: Increasing heart rates with age</h2>
<p>The maximum heart rate in beats per minute of a person declines with age. You say maximum heart rate is inversely related to the person’s age.</p>
<p>Suppose 15 randomly chosen people of varying ages are tested for maximum heart rate and the following data are collected. Create a data frame and assign it to the object <code>heart.df</code>.</p>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="tuesday-october-12-2022.html#cb35-1" aria-hidden="true" tabindex="-1"></a>Age <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">18</span>, <span class="dv">23</span>, <span class="dv">25</span>, <span class="dv">35</span>, <span class="dv">65</span>, <span class="dv">54</span>, <span class="dv">34</span>, <span class="dv">56</span>, <span class="dv">72</span>, <span class="dv">19</span>, <span class="dv">23</span>, <span class="dv">42</span>, <span class="dv">18</span>, <span class="dv">39</span>, <span class="dv">37</span>)</span>
<span id="cb35-2"><a href="tuesday-october-12-2022.html#cb35-2" aria-hidden="true" tabindex="-1"></a>HR <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">202</span>, <span class="dv">186</span>, <span class="dv">187</span>, <span class="dv">180</span>, <span class="dv">156</span>, <span class="dv">169</span>, <span class="dv">174</span>, <span class="dv">172</span>, <span class="dv">153</span>, <span class="dv">199</span>, <span class="dv">193</span>, <span class="dv">174</span>, <span class="dv">198</span>, <span class="dv">183</span>, <span class="dv">178</span>)</span>
<span id="cb35-3"><a href="tuesday-october-12-2022.html#cb35-3" aria-hidden="true" tabindex="-1"></a>heart.df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(HR, Age)</span></code></pre></div>
<p>Age is in years and the heart rate is in beats per minute.</p>
<p>The first question you need to ask is; which of the two variables is the response variable? The question is answered without regard to coding or statistics. It must be answered before you model the data.</p>
<p>With the heart rate data you want to <em>predict</em> heart rate given someone’s age. In this case <code>HR</code> is the response variable and <code>Age</code> is the explanatory variable.</p>
<p>This is the difference between summarizing the values in your data and making inferences (like predictions). When making inferences you must first stop and think (e.g., what is my null hypothesis? What is my response variable? What are my explanatory variables?).</p>
<p>Next you create a scatter plot of the data and add the regression line as a layer.</p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="tuesday-october-12-2022.html#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> heart.df, </span>
<span id="cb36-2"><a href="tuesday-october-12-2022.html#cb36-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> Age, <span class="at">y =</span> HR)) <span class="sc">+</span> </span>
<span id="cb36-3"><a href="tuesday-october-12-2022.html#cb36-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb36-4"><a href="tuesday-october-12-2022.html#cb36-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Age [yr]&quot;</span>) <span class="sc">+</span></span>
<span id="cb36-5"><a href="tuesday-october-12-2022.html#cb36-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Heart Rate [bpm]&quot;</span>) <span class="sc">+</span> </span>
<span id="cb36-6"><a href="tuesday-october-12-2022.html#cb36-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> lm, <span class="at">se =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<p><img src="QG-2022_files/figure-html/unnamed-chunk-20-1.png" width="672" /></p>
<p>Next you determine the equation for the line. You do this using the <code>lm()</code> function by typing</p>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="tuesday-october-12-2022.html#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(HR <span class="sc">~</span> Age, <span class="at">data =</span> heart.df)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = HR ~ Age, data = heart.df)
## 
## Coefficients:
## (Intercept)          Age  
##    210.0485      -0.7977</code></pre>
<p>You interpret the model as follows: On average a person’s maximum HR <em>decreases</em> by .8 beats per minute (bpm) every year. Or more easily understood as a decrease of 8 bpm every 10 years.</p>
</div>
<div id="making-predictions-with-regression" class="section level2 unnumbered">
<h2>Making predictions with regression</h2>
<p>The model is useful for making predictions. Suppose you want to predict the maximum heart rate for 50-year old individuals. You apply the equation</p>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="tuesday-october-12-2022.html#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fl">210.0485</span> <span class="sc">-</span> <span class="fl">0.7977</span> <span class="sc">*</span> <span class="dv">50</span></span></code></pre></div>
<pre><code>## [1] 170.1635</code></pre>
<p>The model predicts that a 50 year old person can expect to have a maximum heart rate of 170 bpm. More precisely, given a set of 50 year old people, the model predicts that, on average, the maximum heart rate of the set of people will be 170 bpm.</p>
<p>Predictions with the model are made without typing the coefficients. Instead, first save the model as an object and then use the <code>predict()</code> function on the object. In the <code>predict()</code> function you <em>must</em> specify the data as a data frame using the <code>newdata =</code> argument.</p>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="tuesday-october-12-2022.html#cb42-1" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(HR <span class="sc">~</span> Age, </span>
<span id="cb42-2"><a href="tuesday-october-12-2022.html#cb42-2" aria-hidden="true" tabindex="-1"></a>            <span class="at">data =</span> heart.df)</span>
<span id="cb42-3"><a href="tuesday-october-12-2022.html#cb42-3" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(model, </span>
<span id="cb42-4"><a href="tuesday-october-12-2022.html#cb42-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">newdata =</span> <span class="fu">data.frame</span>(<span class="at">Age =</span> <span class="dv">50</span>))</span></code></pre></div>
<pre><code>##        1 
## 170.1621</code></pre>
<p>You can input a vector of age values for which you want predictions.</p>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="tuesday-october-12-2022.html#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(model, </span>
<span id="cb44-2"><a href="tuesday-october-12-2022.html#cb44-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">newdata =</span> <span class="fu">data.frame</span>(<span class="at">Age =</span> <span class="fu">seq</span>(<span class="at">from =</span> <span class="dv">40</span>, <span class="at">to =</span> <span class="dv">60</span>, <span class="at">by =</span> <span class="dv">10</span>)))</span></code></pre></div>
<pre><code>##        1        2        3 
## 178.1394 170.1621 162.1849</code></pre>
</div>
<div id="uncertainty-about-the-regression-coefficients" class="section level2 unnumbered">
<h2>Uncertainty about the regression coefficients</h2>
<p>Information about the model is obtained with the <code>summary()</code> method.</p>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="tuesday-october-12-2022.html#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = HR ~ Age, data = heart.df)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -8.9258 -2.5383  0.3879  3.1867  6.6242 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 210.04846    2.86694   73.27  &lt; 2e-16 ***
## Age          -0.79773    0.06996  -11.40 3.85e-08 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 4.578 on 13 degrees of freedom
## Multiple R-squared:  0.9091, Adjusted R-squared:  0.9021 
## F-statistic:   130 on 1 and 13 DF,  p-value: 3.848e-08</code></pre>
<p>The first bit of information is the code you used to create the model.</p>
<p>The second bit is a summary of the model residuals: observed value minus the modeled value.</p>
<p>The most important output is the table of coefficients. The table shows the slope and intercept coefficients in the column labeled <code>Estimate</code>. The adjacent column labeled <code>Std. Error</code> lists the standard errors on these coefficients. The standard error (or margin of error) is a measure of the uncertainty surrounding the coefficient estimate. For the slope coefficient it is computed as
<span class="math display">\[
s_{\beta_1} = \sqrt{ \frac{\frac{1}{n - 2}\sum_{i=1}^n \varepsilon_i^{\,2}} {\sum_{i=1}^n (x_i -\bar{x})^2} },
\]</span>
where
<span class="math display">\[
\varepsilon_i  = y_i - \beta_0 - \beta_1 x_i
\]</span></p>
<p>The best estimate for the (population) slope is -.798 with a margin of error of +/- .07.</p>
<p>The uncertainty about the model coefficient is used to test hypotheses and to compute confidence intervals.</p>
<p>Interest typically centers on the null hypothesis that the slope = 0. A zero slope implies the line is horizontal and thus, in this case, that maximum heart rate is independent of how old an individual is.</p>
<p>The <span class="math inline">\(t\)</span> value for the zero-slope hypothesis is computed as the slope value divided by its standard error. The <span class="math inline">\(t\)</span> value has a <span class="math inline">\(t\)</span> distribution with <span class="math inline">\(n-2\)</span> degrees of freedom if the slope is zero.</p>
<p>Here the <span class="math inline">\(t\)</span> value is -11.4 which gives a <span class="math inline">\(p\)</span>-value (Pr(&gt;|t|)) of .0000000385 (3.85e-08). It is written this way, because the <span class="math inline">\(p\)</span>-value is the probability of observing a more extreme <span class="math inline">\(t\)</span> value (positive or negative) assuming the null hypothesis is true (slope is zero).</p>
<p>The symbols to the right indicate a category of confidence in the inference. The line below the table shows the definitions which you can interpret using our definition. Three asterisks: overwhelming, Two asterisks: convincing, One asterisk: moderate, Point: suggestive but inconclusive.</p>
<p>So you have overwhelming evidence that, given these data, on average maximum heart rate depends on age.</p>
<p>The next line of output from the <code>summary()</code> method gives the residual standard error. This tells you how close (on average) the observations are from the regression line. The degrees of freedom are again <span class="math inline">\(n-2\)</span>.</p>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="tuesday-october-12-2022.html#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sqrt</span>(<span class="fu">sum</span>(<span class="fu">residuals</span>(model)<span class="sc">^</span><span class="dv">2</span>)<span class="sc">/</span><span class="dv">13</span>)</span></code></pre></div>
<pre><code>## [1] 4.577799</code></pre>
<p>Note the <code>resid()</code> [or <code>residual()</code>] outputs the residuals from the model object.</p>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="tuesday-october-12-2022.html#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">resid</span>(model)</span></code></pre></div>
<pre><code>##          1          2          3          4          5          6          7 
##  6.3106197 -5.7007474 -3.1052943 -2.1280287 -2.1962317  2.0287761 -8.9257552 
##          8          9         10         11         12         13         14 
##  6.6242292  0.3878543  4.1083463  1.2992526 -2.5439427  2.3106197  4.0628776 
##         15 
## -2.5325755</code></pre>
<p>The next line of output gives the multiple R-squared value. Also called the coefficient of determination. And the adjusted R-squared value. The multiple R-squared is equal to the square of the Pearson correlation coefficient.</p>
<p>The multiple R-squared = 1 - RSS/SSY, where RSS is the residual sum of squares and SSY is the total variation about a constant mean response.</p>
<p>It is useful to see how these are computed. The RSS is the sum of the squared residuals. This is computed with the <code>deviance()</code> function.</p>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb52-1"><a href="tuesday-october-12-2022.html#cb52-1" aria-hidden="true" tabindex="-1"></a>RSS <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="fu">resid</span>(model)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb52-2"><a href="tuesday-october-12-2022.html#cb52-2" aria-hidden="true" tabindex="-1"></a>RSS</span></code></pre></div>
<pre><code>## [1] 272.4312</code></pre>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb54-1"><a href="tuesday-october-12-2022.html#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">deviance</span>(model)</span></code></pre></div>
<pre><code>## [1] 272.4312</code></pre>
<p>To compute the multiple R-squared you need SSY. SSY is the deviance from the constant mean model. This constant mean model is estimated using the <code>lm()</code> function as</p>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb56-1"><a href="tuesday-october-12-2022.html#cb56-1" aria-hidden="true" tabindex="-1"></a>model0 <span class="ot">&lt;-</span> <span class="fu">lm</span>(HR <span class="sc">~</span> <span class="dv">1</span>, </span>
<span id="cb56-2"><a href="tuesday-october-12-2022.html#cb56-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">data =</span> heart.df)</span>
<span id="cb56-3"><a href="tuesday-october-12-2022.html#cb56-3" aria-hidden="true" tabindex="-1"></a>SSY <span class="ot">&lt;-</span> <span class="fu">deviance</span>(model0)</span>
<span id="cb56-4"><a href="tuesday-october-12-2022.html#cb56-4" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span> <span class="sc">-</span> RSS<span class="sc">/</span>SSY</span></code></pre></div>
<pre><code>## [1] 0.9090967</code></pre>
<p>One minus the ratio of the explained variation to the total variation.</p>
<p>RSS is less than SSY so RSS/SSY will be less that 1. If RSS is much less than SSY then, RSS/SSY is close to zero so R squared is close to 1.</p>
<p>The R-squared multiplied by 100% is the variance of the response variable explained (statistically) by the explanatory variable.</p>
<p>The adjusted R-squared value is smaller than the R-squared value. How much smaller depends on how many variables are in the model.
<span class="math display">\[
1 - \frac{n - 1}{n - p} (1 - R^2 )
\]</span></p>
<p>where <span class="math inline">\(n\)</span> is the sample size and <span class="math inline">\(p\)</span> is the number of parameters in the model. Note: The number of parameters in a regression is the number of coefficients plus one. The ‘plus one’ comes from the residual standard error.</p>
<p>The adjusted R-squared is always smaller than the multiple R-squared, can decrease as new explanatory variables are added, and can even be negative for really poorly fitting models. It is important in the context of multiple regression.</p>
<p>The final line of output is the F-value, degrees of freedom, and associated <span class="math inline">\(p\)</span>-value.
<span class="math display">\[
F_\hbox{statistic} = \frac{(SSY - RSS)/(p - 1)}{RSS/(n - p)}
\]</span></p>
<p>Under the null hypothesis that the regression is no better than the unconditional mean as a model for the data, the <span class="math inline">\(F\)</span> statistic comes from an <span class="math inline">\(F\)</span> distribution with (<span class="math inline">\(p-1\)</span>) and <span class="math inline">\(n\)</span> degrees of freedom.</p>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb58-1"><a href="tuesday-october-12-2022.html#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pf</span>(<span class="dv">130</span>, <span class="at">df1 =</span> <span class="dv">1</span>, <span class="at">df2 =</span> <span class="dv">13</span>, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## [1] 3.849584e-08</code></pre>
<p>The <span class="math inline">\(p\)</span>-value is very small (&lt; .001) so we reject the null hypothesis that the mean model is better than the linear regression model.</p>
</div>
<div id="bootstrapping-the-uncertainty" class="section level2 unnumbered">
<h2>Bootstrapping the uncertainty</h2>
<p>Suppose you choose another 15 people and test for maximum heart rate and record ages. Will the slope be different? Almost certainly, yes.</p>
<p>Although you don’t have access to a new set of people, you can create samples from the original set of subjects (bootstrapping).</p>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb60-1"><a href="tuesday-october-12-2022.html#cb60-1" aria-hidden="true" tabindex="-1"></a>I1 <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">15</span>, <span class="at">size =</span> <span class="dv">15</span>, <span class="at">replace =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<p><code>I1</code> is a sample of the integers from 1 to 15 with repeats. Not all numbers are picked and some are picked more than once.</p>
<div class="sourceCode" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb61-1"><a href="tuesday-october-12-2022.html#cb61-1" aria-hidden="true" tabindex="-1"></a>I1</span></code></pre></div>
<pre><code>##  [1]  7 10  7 15  4  4  9 13 10  7 15 14  2  6  2</code></pre>
<div class="sourceCode" id="cb63"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb63-1"><a href="tuesday-october-12-2022.html#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(I1)</span></code></pre></div>
<pre><code>## I1
##  2  4  6  7  9 10 13 14 15 
##  2  2  1  3  1  2  1  1  2</code></pre>
<p>To get a bootstrap sample you use these integers as indices in the vectors of <code>HR</code> and <code>Age</code>.</p>
<div class="sourceCode" id="cb65"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb65-1"><a href="tuesday-october-12-2022.html#cb65-1" aria-hidden="true" tabindex="-1"></a>bsHR <span class="ot">&lt;-</span> heart.df<span class="sc">$</span>HR[I1]</span>
<span id="cb65-2"><a href="tuesday-october-12-2022.html#cb65-2" aria-hidden="true" tabindex="-1"></a>bsAge <span class="ot">&lt;-</span> heart.df<span class="sc">$</span>Age[I1]</span>
<span id="cb65-3"><a href="tuesday-october-12-2022.html#cb65-3" aria-hidden="true" tabindex="-1"></a>bsHR; bsAge</span></code></pre></div>
<pre><code>##  [1] 174 199 174 178 180 180 153 198 199 174 178 183 186 169 186</code></pre>
<pre><code>##  [1] 34 19 34 37 35 35 72 18 19 34 37 39 23 54 23</code></pre>
<p>You fit the regression model using the bootstrap sample as an index to select the individuals to include.</p>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb68-1"><a href="tuesday-october-12-2022.html#cb68-1" aria-hidden="true" tabindex="-1"></a>modelBS1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(bsHR <span class="sc">~</span> bsAge)</span>
<span id="cb68-2"><a href="tuesday-october-12-2022.html#cb68-2" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(modelBS1)</span></code></pre></div>
<pre><code>## (Intercept)       bsAge 
## 207.6843417  -0.7880412</code></pre>
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb70-1"><a href="tuesday-october-12-2022.html#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(modelBS1)[<span class="dv">2</span>]</span></code></pre></div>
<pre><code>##      bsAge 
## -0.7880412</code></pre>
<p>The slope value is different.</p>
<p>You repeat this entire procedure (repeadedly selecting integers and corresponding values of the variables) 1000 times and create a histogram of the slope values.</p>
<div class="sourceCode" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb72-1"><a href="tuesday-october-12-2022.html#cb72-1" aria-hidden="true" tabindex="-1"></a>slope <span class="ot">&lt;-</span> <span class="fu">numeric</span>()</span>
<span id="cb72-2"><a href="tuesday-october-12-2022.html#cb72-2" aria-hidden="true" tabindex="-1"></a>int <span class="ot">&lt;-</span> <span class="fu">numeric</span>()</span>
<span id="cb72-3"><a href="tuesday-october-12-2022.html#cb72-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">100</span>){</span>
<span id="cb72-4"><a href="tuesday-october-12-2022.html#cb72-4" aria-hidden="true" tabindex="-1"></a>  I <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">15</span>, <span class="at">size =</span> <span class="dv">15</span>, <span class="at">replace =</span> <span class="cn">TRUE</span>)</span>
<span id="cb72-5"><a href="tuesday-october-12-2022.html#cb72-5" aria-hidden="true" tabindex="-1"></a>  models <span class="ot">&lt;-</span> <span class="fu">lm</span>(HR <span class="sc">~</span> Age, <span class="at">data =</span> heart.df[I, ])</span>
<span id="cb72-6"><a href="tuesday-october-12-2022.html#cb72-6" aria-hidden="true" tabindex="-1"></a>  slope[i] <span class="ot">&lt;-</span> <span class="fu">coef</span>(models)[<span class="dv">2</span>]</span>
<span id="cb72-7"><a href="tuesday-october-12-2022.html#cb72-7" aria-hidden="true" tabindex="-1"></a>  int[i] <span class="ot">&lt;-</span> <span class="fu">coef</span>(models)[<span class="dv">1</span>]</span>
<span id="cb72-8"><a href="tuesday-october-12-2022.html#cb72-8" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb72-9"><a href="tuesday-october-12-2022.html#cb72-9" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> <span class="fu">as.data.frame</span>(slope), </span>
<span id="cb72-10"><a href="tuesday-october-12-2022.html#cb72-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">mapping =</span> <span class="fu">aes</span>(slope)) <span class="sc">+</span></span>
<span id="cb72-11"><a href="tuesday-october-12-2022.html#cb72-11" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">25</span>)</span></code></pre></div>
<p><img src="QG-2022_files/figure-html/unnamed-chunk-35-1.png" width="672" /></p>
<div class="sourceCode" id="cb73"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb73-1"><a href="tuesday-october-12-2022.html#cb73-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(int, slope, <span class="at">bs =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">100</span>)</span>
<span id="cb73-2"><a href="tuesday-october-12-2022.html#cb73-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> heart.df, </span>
<span id="cb73-3"><a href="tuesday-october-12-2022.html#cb73-3" aria-hidden="true" tabindex="-1"></a>       <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> Age, <span class="at">y =</span> HR)) <span class="sc">+</span> </span>
<span id="cb73-4"><a href="tuesday-october-12-2022.html#cb73-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb73-5"><a href="tuesday-october-12-2022.html#cb73-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">intercept =</span> int, <span class="at">slope  =</span> slope, <span class="at">group =</span> bs), </span>
<span id="cb73-6"><a href="tuesday-october-12-2022.html#cb73-6" aria-hidden="true" tabindex="-1"></a>              <span class="at">data =</span> df) <span class="sc">+</span></span>
<span id="cb73-7"><a href="tuesday-october-12-2022.html#cb73-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> lm)</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<p><img src="QG-2022_files/figure-html/unnamed-chunk-35-2.png" width="672" /></p>
<p>The standard deviation of all the slopes will be close to the standard error estimated (from statistical theory) on the original data.</p>
<div class="sourceCode" id="cb75"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb75-1"><a href="tuesday-october-12-2022.html#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(slope)</span></code></pre></div>
<pre><code>## [1] 0.08801409</code></pre>
<p>Uncertainty bounds are estimated from a single sample without reference to statistical theory.</p>
</div>
<div id="predictive-uncertainty" class="section level2 unnumbered">
<h2>Predictive uncertainty</h2>
<p>The <code>predict()</code> function (method) is used to make a prediction. You specify the model object and value(s) of the explanatory variable as a data frame.</p>
<div class="sourceCode" id="cb77"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb77-1"><a href="tuesday-october-12-2022.html#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(model, </span>
<span id="cb77-2"><a href="tuesday-october-12-2022.html#cb77-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">newdata =</span> <span class="fu">data.frame</span>(<span class="at">Age =</span> <span class="fu">c</span>(<span class="dv">50</span>, <span class="dv">60</span>)))</span></code></pre></div>
<pre><code>##        1        2 
## 170.1621 162.1849</code></pre>
<p>To get the uncertainty intervals on the predicted values: Use the <code>level =</code> and <code>interval = "confidence"</code> arguments.</p>
<div class="sourceCode" id="cb79"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb79-1"><a href="tuesday-october-12-2022.html#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(model, </span>
<span id="cb79-2"><a href="tuesday-october-12-2022.html#cb79-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">newdata =</span> <span class="fu">data.frame</span>(<span class="at">Age =</span> <span class="fu">c</span>(<span class="dv">50</span>, <span class="dv">60</span>)), </span>
<span id="cb79-3"><a href="tuesday-october-12-2022.html#cb79-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">level =</span> .<span class="dv">95</span>, <span class="at">interval =</span> <span class="st">&quot;confidence&quot;</span>)</span></code></pre></div>
<pre><code>##        fit      lwr      upr
## 1 170.1621 166.9706 173.3537
## 2 162.1849 157.9120 166.4578</code></pre>
<div class="sourceCode" id="cb81"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb81-1"><a href="tuesday-october-12-2022.html#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> heart.df, </span>
<span id="cb81-2"><a href="tuesday-october-12-2022.html#cb81-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> Age, <span class="at">y =</span> HR)) <span class="sc">+</span></span>
<span id="cb81-3"><a href="tuesday-october-12-2022.html#cb81-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb81-4"><a href="tuesday-october-12-2022.html#cb81-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> lm)</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<p><img src="QG-2022_files/figure-html/unnamed-chunk-38-1.png" width="672" /></p>
<p>The lower (<code>lwr</code>) and upper (<code>upr</code>) bounds represent the 95% uncertainty interval about the location of the line for the particular value of the explanatory variable <code>Age</code>.</p>
<p>You state that the best prediction for average maximum heart rate for people at age 50 is 170 bpm with a 95% uncertainty interval between 167 and 173 bpm.</p>
<p>Thus if you repeat the sampling 100 times and make the same prediction, our CI on the prediction will cover the true predicted value 95 times.</p>
<p>Note: repeated sampling is not the same as bootstrap re-sampling. Repeated sampling refers to the theoretical ideal of a true model, while bootstrap re-sampling is a procedure that you implement on your data.</p>
<p>With <code>interval = "prediction"</code> you get a 95% <em>prediction</em> interval. That interval is wider than the confidence interval as it represents two sources of uncertainty.</p>
<p>The uncertainty associated with the mean value GIVEN the person’s age AND the uncertainty associated with a particular maximum heart rate GIVEN the conditional mean.</p>
<div class="sourceCode" id="cb83"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb83-1"><a href="tuesday-october-12-2022.html#cb83-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(model, <span class="fu">data.frame</span>(<span class="at">Age =</span> <span class="fu">c</span>(<span class="dv">50</span>, <span class="dv">60</span>)), </span>
<span id="cb83-2"><a href="tuesday-october-12-2022.html#cb83-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">level =</span> .<span class="dv">95</span>, <span class="at">interval =</span> <span class="st">&quot;prediction&quot;</span>)</span></code></pre></div>
<pre><code>##        fit      lwr      upr
## 1 170.1621 159.7702 180.5541
## 2 162.1849 151.4115 172.9582</code></pre>
<p>This is an example of compound uncertainty that we discussed in the context of Bayesian data analysis. The difference between the posterior distribution on the parameter of interest and the posterior distribution on the prediction of a specific value.</p>
<p>If you are 90% certain that your spouse is faithful and 90% certain he is not a cross-dresser, then you must be less than 90% certain he is a faithful, non-cross dresser.</p>
<p>To plot the confidence band type</p>
<div class="sourceCode" id="cb85"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb85-1"><a href="tuesday-october-12-2022.html#cb85-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> heart.df, </span>
<span id="cb85-2"><a href="tuesday-october-12-2022.html#cb85-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> Age, <span class="at">y =</span> HR)) <span class="sc">+</span> </span>
<span id="cb85-3"><a href="tuesday-october-12-2022.html#cb85-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb85-4"><a href="tuesday-october-12-2022.html#cb85-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> lm)</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<p><img src="QG-2022_files/figure-html/unnamed-chunk-40-1.png" width="672" /></p>
<p>By default <code>level = .95</code> in the <code>geom_smooth()</code> function.</p>
<p>To plot the prediction band, first add the prediction intervals to the original data frame.</p>
<div class="sourceCode" id="cb87"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb87-1"><a href="tuesday-october-12-2022.html#cb87-1" aria-hidden="true" tabindex="-1"></a>heart2 <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(heart.df, <span class="fu">predict</span>(model, <span class="at">interval =</span> <span class="st">&quot;prediction&quot;</span>))</span></code></pre></div>
<pre><code>## Warning in predict.lm(model, interval = &quot;prediction&quot;): predictions on current data refer to _future_ responses</code></pre>
<div class="sourceCode" id="cb89"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb89-1"><a href="tuesday-october-12-2022.html#cb89-1" aria-hidden="true" tabindex="-1"></a>heart2 <span class="ot">&lt;-</span> heart2[<span class="fu">order</span>(heart2<span class="sc">$</span>Age), ]</span></code></pre></div>
<p>Then</p>
<div class="sourceCode" id="cb90"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb90-1"><a href="tuesday-october-12-2022.html#cb90-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(heart2, <span class="fu">aes</span>(<span class="at">x =</span> Age, <span class="at">y =</span> HR)) <span class="sc">+</span> </span>
<span id="cb90-2"><a href="tuesday-october-12-2022.html#cb90-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb90-3"><a href="tuesday-october-12-2022.html#cb90-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> lm) <span class="sc">+</span> </span>
<span id="cb90-4"><a href="tuesday-october-12-2022.html#cb90-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_ribbon</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> lwr, <span class="at">ymax =</span> upr), <span class="at">alpha =</span> .<span class="dv">2</span>)</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<p><img src="QG-2022_files/figure-html/unnamed-chunk-42-1.png" width="672" /></p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="thursday-october-5-2022.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
