<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Tuesday, November 8, 2022 | GEO5156: Quantitative Geography</title>
  <meta name="description" content="Tuesday, November 8, 2022 | GEO5156: Quantitative Geography" />
  <meta name="generator" content="bookdown 0.24 and GitBook 2.6.7" />

  <meta property="og:title" content="Tuesday, November 8, 2022 | GEO5156: Quantitative Geography" />
  <meta property="og:type" content="book" />
  
  
  
  <meta name="github-repo" content="jelsner/QG-2022" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Tuesday, November 8, 2022 | GEO5156: Quantitative Geography" />
  
  
  

<meta name="author" content="James B. Elsner" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="thursday-november-3-2022.html"/>

<script src="libs/header-attrs-2.11/header-attrs.js"></script>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Quantitative Geography</a></li>

<li class="divider"></li>
<li><a href="index.html#section"></a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html"><i class="fa fa-check"></i>Syllabus</a>
<ul>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#geo5165c-quantitative-geography"><i class="fa fa-check"></i>GEO5165C: Quantitative Geography</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#contact-information"><i class="fa fa-check"></i>Contact information</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#course-description"><i class="fa fa-check"></i>Course description</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#expected-learning-outcomes"><i class="fa fa-check"></i>Expected learning outcomes</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#materials"><i class="fa fa-check"></i>Materials</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#class-meetings"><i class="fa fa-check"></i>Class meetings</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#grades"><i class="fa fa-check"></i>Grades</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#academic-honor-code"><i class="fa fa-check"></i>Academic honor code</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#students-with-disabilities-act"><i class="fa fa-check"></i>Students With Disabilities Act</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#inclusiveness"><i class="fa fa-check"></i>Inclusiveness</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#more-about-your-instructor"><i class="fa fa-check"></i>More about your instructor</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#syllabus-change-policy"><i class="fa fa-check"></i>Syllabus change policy</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#schedule-subject-to-change-with-notice"><i class="fa fa-check"></i>Schedule (subject to change with notice)</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#other-materials-to-check-out"><i class="fa fa-check"></i>Other materials to check out</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#julia-programming-language"><i class="fa fa-check"></i>Julia programming language</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html"><i class="fa fa-check"></i>Tuesday, August 23, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#today"><i class="fa fa-check"></i>Today</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#what-is-this-course"><i class="fa fa-check"></i>What is this course?</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#where-are-the-materials-for-this-course"><i class="fa fa-check"></i>Where are the materials for this course?</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#join-rstudio-cloud"><i class="fa fa-check"></i>Join RStudio Cloud</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#examples"><i class="fa fa-check"></i>Examples</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#course-syllabus"><i class="fa fa-check"></i>Course Syllabus</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#tallahassee-daily-temperatures"><i class="fa fa-check"></i>Tallahassee daily temperatures</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html"><i class="fa fa-check"></i>Thursday, August 25, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#today-1"><i class="fa fa-check"></i>Today</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#data-analysis"><i class="fa fa-check"></i>Data Analysis</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#reproducibility"><i class="fa fa-check"></i>Reproducibility</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#communication"><i class="fa fa-check"></i>Communication</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#automation"><i class="fa fa-check"></i>Automation</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#the-r-programming-language"><i class="fa fa-check"></i>The R programming language</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#overview-of-this-course"><i class="fa fa-check"></i>Overview of this course</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#work-in-plain-text-using-r-markdown"><i class="fa fa-check"></i>Work in plain text, using R Markdown</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#visualizing-data"><i class="fa fa-check"></i>Visualizing data</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#a-code-template"><i class="fa fa-check"></i>A code template</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#the-code"><i class="fa fa-check"></i>The code</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#a-graphing-workflow"><i class="fa fa-check"></i>A graphing workflow</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#a-graphing-template"><i class="fa fa-check"></i>A graphing template</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#common-problems"><i class="fa fa-check"></i>Common problems</a></li>
<li><a href="thursday-august-25-2022.html#location-of-the-sign">location of the <code>+</code> sign</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#help"><i class="fa fa-check"></i>help</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#things-to-know"><i class="fa fa-check"></i>Things to know</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#everything-has-a-name"><i class="fa fa-check"></i>Everything has a name</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#everything-is-an-object"><i class="fa fa-check"></i>Everything is an object</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#you-do-things-using-functions"><i class="fa fa-check"></i>You do things using functions</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#functions-come-in-packages-libraries"><i class="fa fa-check"></i>Functions come in packages (libraries)</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#your-turn"><i class="fa fa-check"></i>Your turn</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html"><i class="fa fa-check"></i>Tuesday, August 30, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html#today-2"><i class="fa fa-check"></i>Today</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html#scatter-plots"><i class="fa fa-check"></i>Scatter plots</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html#facets"><i class="fa fa-check"></i>Facets</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html#calculations"><i class="fa fa-check"></i>Calculations</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html#functions"><i class="fa fa-check"></i>Functions</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html#syntax-is-important"><i class="fa fa-check"></i>Syntax is important</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html#saving-an-object"><i class="fa fa-check"></i>Saving an object</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html#object-names"><i class="fa fa-check"></i>Object names</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html#entering-data"><i class="fa fa-check"></i>Entering data</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html#applying-a-function"><i class="fa fa-check"></i>Applying a function</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html#averge"><i class="fa fa-check"></i>Averge</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html#data-vectors"><i class="fa fa-check"></i>Data vectors</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html#variance"><i class="fa fa-check"></i>Variance</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html#data-vectors-have-a-type"><i class="fa fa-check"></i>Data vectors have a type</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html#working-smarter"><i class="fa fa-check"></i>Working smarter</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-september-1-2022.html"><a href="thursday-september-1-2022.html"><i class="fa fa-check"></i>Thursday, September 1, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-september-1-2022.html"><a href="thursday-september-1-2022.html#today-3"><i class="fa fa-check"></i>Today</a></li>
<li class="chapter" data-level="" data-path="thursday-september-1-2022.html"><a href="thursday-september-1-2022.html#data-as-vectors"><i class="fa fa-check"></i>Data as vectors</a></li>
<li class="chapter" data-level="" data-path="thursday-september-1-2022.html"><a href="thursday-september-1-2022.html#mean"><i class="fa fa-check"></i>Mean</a></li>
<li class="chapter" data-level="" data-path="thursday-september-1-2022.html"><a href="thursday-september-1-2022.html#variance-1"><i class="fa fa-check"></i>Variance</a></li>
<li class="chapter" data-level="" data-path="thursday-september-1-2022.html"><a href="thursday-september-1-2022.html#median"><i class="fa fa-check"></i>Median</a></li>
<li class="chapter" data-level="" data-path="thursday-september-1-2022.html"><a href="thursday-september-1-2022.html#spread"><i class="fa fa-check"></i>Spread</a></li>
<li class="chapter" data-level="" data-path="thursday-september-1-2022.html"><a href="thursday-september-1-2022.html#vector-types"><i class="fa fa-check"></i>Vector types</a></li>
<li class="chapter" data-level="" data-path="thursday-september-1-2022.html"><a href="thursday-september-1-2022.html#structured-data"><i class="fa fa-check"></i>Structured data</a></li>
<li class="chapter" data-level="" data-path="thursday-september-1-2022.html"><a href="thursday-september-1-2022.html#asking-questions"><i class="fa fa-check"></i>Asking questions</a></li>
<li class="chapter" data-level="" data-path="thursday-september-1-2022.html"><a href="thursday-september-1-2022.html#tables-and-summaries"><i class="fa fa-check"></i>Tables and summaries</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-september-6-2022.html"><a href="tuesday-september-6-2022.html"><i class="fa fa-check"></i>Tuesday, September 6, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-september-6-2022.html"><a href="tuesday-september-6-2022.html#today-4"><i class="fa fa-check"></i>Today</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-6-2022.html"><a href="tuesday-september-6-2022.html#getting-your-data-into-r"><i class="fa fa-check"></i>Getting your data into R</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-6-2022.html"><a href="tuesday-september-6-2022.html#creating-structured-data-files"><i class="fa fa-check"></i>Creating structured data files</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-6-2022.html"><a href="tuesday-september-6-2022.html#data-frames"><i class="fa fa-check"></i>Data frames</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-6-2022.html"><a href="tuesday-september-6-2022.html#quantiles"><i class="fa fa-check"></i>Quantiles</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-6-2022.html"><a href="tuesday-september-6-2022.html#creating-a-data-frame"><i class="fa fa-check"></i>Creating a data frame</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-6-2022.html"><a href="tuesday-september-6-2022.html#pipes"><i class="fa fa-check"></i>Pipes</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-6-2022.html"><a href="tuesday-september-6-2022.html#your-turn-1"><i class="fa fa-check"></i>Your turn</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-september-8-2022.html"><a href="thursday-september-8-2022.html"><i class="fa fa-check"></i>Thursday, September 8, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-september-8-2022.html"><a href="thursday-september-8-2022.html#today-5"><i class="fa fa-check"></i>Today</a></li>
<li class="chapter" data-level="" data-path="thursday-september-8-2022.html"><a href="thursday-september-8-2022.html#pipe-operator"><i class="fa fa-check"></i>Pipe operator</a></li>
<li class="chapter" data-level="" data-path="thursday-september-8-2022.html"><a href="thursday-september-8-2022.html#wrangling-data-frames"><i class="fa fa-check"></i>Wrangling data frames</a></li>
<li class="chapter" data-level="" data-path="thursday-september-8-2022.html"><a href="thursday-september-8-2022.html#selecting-and-filtering"><i class="fa fa-check"></i>Selecting and filtering</a></li>
<li class="chapter" data-level="" data-path="thursday-september-8-2022.html"><a href="thursday-september-8-2022.html#example-palmer-penguins"><i class="fa fa-check"></i>Example: Palmer penguins</a></li>
<li class="chapter" data-level="" data-path="thursday-september-8-2022.html"><a href="thursday-september-8-2022.html#stringing-functions-together"><i class="fa fa-check"></i>Stringing functions together</a></li>
<li class="chapter" data-level="" data-path="thursday-september-8-2022.html"><a href="thursday-september-8-2022.html#summarize"><i class="fa fa-check"></i>Summarize</a></li>
<li class="chapter" data-level="" data-path="thursday-september-8-2022.html"><a href="thursday-september-8-2022.html#grouping"><i class="fa fa-check"></i>Grouping</a></li>
<li class="chapter" data-level="" data-path="thursday-september-8-2022.html"><a href="thursday-september-8-2022.html#your-turn-2"><i class="fa fa-check"></i>Your turn</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-september-12-2022.html"><a href="tuesday-september-12-2022.html"><i class="fa fa-check"></i>Tuesday, September 12, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-september-12-2022.html"><a href="tuesday-september-12-2022.html#today-6"><i class="fa fa-check"></i>Today</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-12-2022.html"><a href="tuesday-september-12-2022.html#example-1-new-york-city-flight-data"><i class="fa fa-check"></i>Example 1: New York City flight data</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-12-2022.html"><a href="tuesday-september-12-2022.html#example-2-daily-weather-data-from-tallahassee"><i class="fa fa-check"></i>Example 2: Daily weather data from Tallahassee</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-12-2022.html"><a href="tuesday-september-12-2022.html#putting-everything-together"><i class="fa fa-check"></i>Putting everything together</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-12-2022.html"><a href="tuesday-september-12-2022.html#example-3-food-consumption-and-co2-emissions"><i class="fa fa-check"></i>Example 3: Food consumption and CO2 emissions</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-12-2022.html"><a href="tuesday-september-12-2022.html#summary"><i class="fa fa-check"></i>Summary</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-september-14-2022.html"><a href="thursday-september-14-2022.html"><i class="fa fa-check"></i>Thursday, September 14, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-september-14-2022.html"><a href="thursday-september-14-2022.html#today-7"><i class="fa fa-check"></i>Today</a></li>
<li class="chapter" data-level="" data-path="thursday-september-14-2022.html"><a href="thursday-september-14-2022.html#bar-chart"><i class="fa fa-check"></i>Bar chart</a></li>
<li class="chapter" data-level="" data-path="thursday-september-14-2022.html"><a href="thursday-september-14-2022.html#pie-preference"><i class="fa fa-check"></i>Pie preference</a></li>
<li class="chapter" data-level="" data-path="thursday-september-14-2022.html"><a href="thursday-september-14-2022.html#histogram"><i class="fa fa-check"></i>Histogram</a></li>
<li class="chapter" data-level="" data-path="thursday-september-14-2022.html"><a href="thursday-september-14-2022.html#density-plot"><i class="fa fa-check"></i>Density plot</a></li>
<li class="chapter" data-level="" data-path="thursday-september-14-2022.html"><a href="thursday-september-14-2022.html#box-plot"><i class="fa fa-check"></i>Box plot</a></li>
<li class="chapter" data-level="" data-path="thursday-september-14-2022.html"><a href="thursday-september-14-2022.html#side-by-side-box-plots"><i class="fa fa-check"></i>Side-by-side box plots</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-september-19-2022.html"><a href="tuesday-september-19-2022.html"><i class="fa fa-check"></i>Tuesday, September 19, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-september-19-2022.html"><a href="tuesday-september-19-2022.html#today-8"><i class="fa fa-check"></i>Today</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-19-2022.html"><a href="tuesday-september-19-2022.html#comparing-distributions"><i class="fa fa-check"></i>Comparing distributions</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-19-2022.html"><a href="tuesday-september-19-2022.html#box-plots"><i class="fa fa-check"></i>Box plots</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-19-2022.html"><a href="tuesday-september-19-2022.html#long-data-frames"><i class="fa fa-check"></i>Long data frames</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-19-2022.html"><a href="tuesday-september-19-2022.html#scatter-plots-1"><i class="fa fa-check"></i>Scatter plots</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-19-2022.html"><a href="tuesday-september-19-2022.html#facets-1"><i class="fa fa-check"></i>Facets</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-19-2022.html"><a href="tuesday-september-19-2022.html#example-palmer-penguins-1"><i class="fa fa-check"></i>Example: Palmer penguins</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-19-2022.html"><a href="tuesday-september-19-2022.html#an-expository-graph"><i class="fa fa-check"></i>An expository graph</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-19-2022.html"><a href="tuesday-september-19-2022.html#exporting-your-graph"><i class="fa fa-check"></i>Exporting your graph</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-september-21-2022.html"><a href="thursday-september-21-2022.html"><i class="fa fa-check"></i>Thursday, September 21, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-september-21-2022.html"><a href="thursday-september-21-2022.html#today-9"><i class="fa fa-check"></i>Today</a></li>
<li class="chapter" data-level="" data-path="thursday-september-21-2022.html"><a href="thursday-september-21-2022.html#simple-feature-data-frames"><i class="fa fa-check"></i>Simple feature data frames</a></li>
<li class="chapter" data-level="" data-path="thursday-september-21-2022.html"><a href="thursday-september-21-2022.html#making-a-boundary-map"><i class="fa fa-check"></i>Making a boundary map</a></li>
<li class="chapter" data-level="" data-path="thursday-september-21-2022.html"><a href="thursday-september-21-2022.html#fills"><i class="fa fa-check"></i>Fills</a></li>
<li class="chapter" data-level="" data-path="thursday-september-21-2022.html"><a href="thursday-september-21-2022.html#adding-data"><i class="fa fa-check"></i>Adding data</a></li>
<li class="chapter" data-level="" data-path="thursday-september-21-2022.html"><a href="thursday-september-21-2022.html#inset-maps"><i class="fa fa-check"></i>Inset maps</a></li>
<li class="chapter" data-level="" data-path="thursday-september-21-2022.html"><a href="thursday-september-21-2022.html#map-projections"><i class="fa fa-check"></i>Map projections</a></li>
<li class="chapter" data-level="" data-path="thursday-september-21-2022.html"><a href="thursday-september-21-2022.html#bivariate-maps"><i class="fa fa-check"></i>Bivariate maps</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-september-21-2022-1.html"><a href="thursday-september-21-2022-1.html"><i class="fa fa-check"></i>Thursday, September 21, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-september-21-2022-1.html"><a href="thursday-september-21-2022-1.html#today-10"><i class="fa fa-check"></i>Today</a></li>
<li class="chapter" data-level="" data-path="thursday-september-21-2022-1.html"><a href="thursday-september-21-2022-1.html#making-maps-using-functions-from-the-tmap-package"><i class="fa fa-check"></i>Making maps using functions from the {tmap} package</a></li>
<li class="chapter" data-level="" data-path="thursday-september-21-2022-1.html"><a href="thursday-september-21-2022-1.html#example-mapping-tornadoes"><i class="fa fa-check"></i>Example: Mapping tornadoes</a></li>
<li class="chapter" data-level="" data-path="thursday-september-21-2022-1.html"><a href="thursday-september-21-2022-1.html#example-mapping-the-frequency-of-tornadoes-by-state"><i class="fa fa-check"></i>Example: Mapping the frequency of tornadoes by state</a></li>
<li class="chapter" data-level="" data-path="thursday-september-21-2022-1.html"><a href="thursday-september-21-2022-1.html#calculations-using-the-geometry-simple-feature-column"><i class="fa fa-check"></i>Calculations using the geometry simple feature column</a></li>
<li class="chapter" data-level="" data-path="thursday-september-21-2022-1.html"><a href="thursday-september-21-2022-1.html#making-raster-maps"><i class="fa fa-check"></i>Making raster maps</a></li>
<li class="chapter" data-level="" data-path="thursday-september-21-2022-1.html"><a href="thursday-september-21-2022-1.html#get-map-images-using-functions-from-the-ggmap-package"><i class="fa fa-check"></i>Get map images using functions from the {ggmap} package</a></li>
<li class="chapter" data-level="" data-path="thursday-september-21-2022-1.html"><a href="thursday-september-21-2022-1.html#add-data-to-the-raster-map"><i class="fa fa-check"></i>Add data to the raster map</a></li>
<li class="chapter" data-level="" data-path="thursday-september-21-2022-1.html"><a href="thursday-september-21-2022-1.html#spatial-density-maps-extra-material"><i class="fa fa-check"></i>Spatial density maps (extra material)</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-september-26-2022.html"><a href="tuesday-september-26-2022.html"><i class="fa fa-check"></i>Tuesday, September 26, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-september-26-2022.html"><a href="tuesday-september-26-2022.html#today-11"><i class="fa fa-check"></i>Today</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-26-2022.html"><a href="tuesday-september-26-2022.html#one-sample-test-of-the-population-mean"><i class="fa fa-check"></i>One-sample test of the population mean</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-26-2022.html"><a href="tuesday-september-26-2022.html#about-p-values"><i class="fa fa-check"></i>About p-values</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-26-2022.html"><a href="tuesday-september-26-2022.html#example-strongest-atlantic-hurricanes"><i class="fa fa-check"></i>Example: Strongest Atlantic hurricanes</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-26-2022.html"><a href="tuesday-september-26-2022.html#graphical-inference"><i class="fa fa-check"></i>Graphical inference</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-26-2022.html"><a href="tuesday-september-26-2022.html#two-sample-test-of-the-difference-in-population-means"><i class="fa fa-check"></i>Two-sample test of the difference in population means</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-26-2022.html"><a href="tuesday-september-26-2022.html#example-hurricanes-in-the-north-atlantic-and-the-eastern-north-pacific"><i class="fa fa-check"></i>Example: hurricanes in the North Atlantic and the eastern North Pacific</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-26-2022.html"><a href="tuesday-september-26-2022.html#example-palmer-penguins-2"><i class="fa fa-check"></i>Example: Palmer penguins</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-26-2022.html"><a href="tuesday-september-26-2022.html#your-turn-3"><i class="fa fa-check"></i>Your turn</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-26-2022.html"><a href="tuesday-september-26-2022.html#test-of-equal-variance"><i class="fa fa-check"></i>Test of equal variance</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-26-2022.html"><a href="tuesday-september-26-2022.html#wilcoxon-mann-whitney-u-non-parameteric-test-of-difference-in-means"><i class="fa fa-check"></i>Wilcoxon (Mann-Whitney U) non-parameteric test of difference in means</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-september-28-2022.html"><a href="thursday-september-28-2022.html"><i class="fa fa-check"></i>Thursday, September 28, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-september-28-2022.html"><a href="thursday-september-28-2022.html#today-12"><i class="fa fa-check"></i>Today</a></li>
<li class="chapter" data-level="" data-path="thursday-september-28-2022.html"><a href="thursday-september-28-2022.html#review"><i class="fa fa-check"></i>Review</a></li>
<li class="chapter" data-level="" data-path="thursday-september-28-2022.html"><a href="thursday-september-28-2022.html#paired-observations"><i class="fa fa-check"></i>Paired observations</a></li>
<li class="chapter" data-level="" data-path="thursday-september-28-2022.html"><a href="thursday-september-28-2022.html#example-reaction-time-while-driving"><i class="fa fa-check"></i>Example: Reaction time while driving</a></li>
<li class="chapter" data-level="" data-path="thursday-september-28-2022.html"><a href="thursday-september-28-2022.html#chi-squared-test-for-independence"><i class="fa fa-check"></i>Chi-squared test for independence</a></li>
<li class="chapter" data-level="" data-path="thursday-september-28-2022.html"><a href="thursday-september-28-2022.html#example-smoking-and-exercise"><i class="fa fa-check"></i>Example: Smoking and exercise</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-october-3-2022.html"><a href="tuesday-october-3-2022.html"><i class="fa fa-check"></i>Tuesday, October 3, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-october-3-2022.html"><a href="tuesday-october-3-2022.html#today-13"><i class="fa fa-check"></i>Today</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-3-2022.html"><a href="tuesday-october-3-2022.html#distributions"><i class="fa fa-check"></i>Distributions</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-3-2022.html"><a href="tuesday-october-3-2022.html#normal-distribution"><i class="fa fa-check"></i>Normal distribution</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-3-2022.html"><a href="tuesday-october-3-2022.html#uniform-distribution"><i class="fa fa-check"></i>Uniform distribution</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-3-2022.html"><a href="tuesday-october-3-2022.html#how-many-blue-marbles"><i class="fa fa-check"></i>How many blue marbles?</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-3-2022.html"><a href="tuesday-october-3-2022.html#what-percentage-of-the-globe-is-covered-by-water"><i class="fa fa-check"></i>What percentage of the globe is covered by water?</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-3-2022.html"><a href="tuesday-october-3-2022.html#how-many-fish-are-in-the-lake"><i class="fa fa-check"></i>How many fish are in the lake?</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-october-5-2022.html"><a href="thursday-october-5-2022.html"><i class="fa fa-check"></i>Thursday, October 5, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-october-5-2022.html"><a href="thursday-october-5-2022.html#today-14"><i class="fa fa-check"></i>Today</a></li>
<li class="chapter" data-level="" data-path="thursday-october-5-2022.html"><a href="thursday-october-5-2022.html#how-many-fish-are-in-the-lake-1"><i class="fa fa-check"></i>How many fish are in the lake?</a></li>
<li class="chapter" data-level="" data-path="thursday-october-5-2022.html"><a href="thursday-october-5-2022.html#percentage-of-survey-signups"><i class="fa fa-check"></i>Percentage of survey signups</a></li>
<li class="chapter" data-level="" data-path="thursday-october-5-2022.html"><a href="thursday-october-5-2022.html#a-generative-model-for-people-agreeing-to-take-your-survey"><i class="fa fa-check"></i>A generative model for people agreeing to take your survey</a></li>
<li class="chapter" data-level="" data-path="thursday-october-5-2022.html"><a href="thursday-october-5-2022.html#prior-for-the-response-rate"><i class="fa fa-check"></i>Prior for the response rate</a></li>
<li class="chapter" data-level="" data-path="thursday-october-5-2022.html"><a href="thursday-october-5-2022.html#define-the-generative-model-and-simulate-the-data"><i class="fa fa-check"></i>Define the generative model and simulate the data</a></li>
<li class="chapter" data-level="" data-path="thursday-october-5-2022.html"><a href="thursday-october-5-2022.html#prediction"><i class="fa fa-check"></i>Prediction</a></li>
<li class="chapter" data-level="" data-path="thursday-october-5-2022.html"><a href="thursday-october-5-2022.html#approximate-bayesian-computation"><i class="fa fa-check"></i>Approximate Bayesian computation</a></li>
<li class="chapter" data-level="" data-path="thursday-october-5-2022.html"><a href="thursday-october-5-2022.html#what-bayesian-data-analysis-is-not"><i class="fa fa-check"></i>What Bayesian data analysis is not</a></li>
<li class="chapter" data-level="" data-path="thursday-october-5-2022.html"><a href="thursday-october-5-2022.html#comparing-two-hypotheses"><i class="fa fa-check"></i>Comparing two hypotheses</a></li>
<li class="chapter" data-level="" data-path="thursday-october-5-2022.html"><a href="thursday-october-5-2022.html#reaction-times-while-driving"><i class="fa fa-check"></i>Reaction times while driving</a></li>
<li class="chapter" data-level="" data-path="thursday-october-5-2022.html"><a href="thursday-october-5-2022.html#repeat-the-survey-example"><i class="fa fa-check"></i>Repeat the survey example</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-october-12-2022.html"><a href="tuesday-october-12-2022.html"><i class="fa fa-check"></i>Tuesday, October 12, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-october-12-2022.html"><a href="tuesday-october-12-2022.html#today-15"><i class="fa fa-check"></i>Today</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-12-2022.html"><a href="tuesday-october-12-2022.html#linear-regression-a-t-test-by-another-name"><i class="fa fa-check"></i>Linear regression: A t test by another name</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-12-2022.html"><a href="tuesday-october-12-2022.html#motivating-regression"><i class="fa fa-check"></i>Motivating regression</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-12-2022.html"><a href="tuesday-october-12-2022.html#eyeballing-the-regression"><i class="fa fa-check"></i>Eyeballing the regression</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-12-2022.html"><a href="tuesday-october-12-2022.html#example-increasing-heart-rates-with-age"><i class="fa fa-check"></i>Example: Increasing heart rates with age</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-12-2022.html"><a href="tuesday-october-12-2022.html#making-predictions-with-regression"><i class="fa fa-check"></i>Making predictions with regression</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-12-2022.html"><a href="tuesday-october-12-2022.html#uncertainty-about-the-regression-coefficients"><i class="fa fa-check"></i>Uncertainty about the regression coefficients</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-12-2022.html"><a href="tuesday-october-12-2022.html#bootstrapping-the-uncertainty"><i class="fa fa-check"></i>Bootstrapping the uncertainty</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-12-2022.html"><a href="tuesday-october-12-2022.html#predictive-uncertainty"><i class="fa fa-check"></i>Predictive uncertainty</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-october-14-2022.html"><a href="thursday-october-14-2022.html"><i class="fa fa-check"></i>Thursday, October 14, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-october-14-2022.html"><a href="thursday-october-14-2022.html#today-16"><i class="fa fa-check"></i>Today</a></li>
<li class="chapter" data-level="" data-path="thursday-october-14-2022.html"><a href="thursday-october-14-2022.html#uncertainty-about-a-particular-predicted-value"><i class="fa fa-check"></i>Uncertainty about a particular predicted value</a></li>
<li class="chapter" data-level="" data-path="thursday-october-14-2022.html"><a href="thursday-october-14-2022.html#example-predicting-body-mass-from-fipper-length"><i class="fa fa-check"></i>Example: Predicting body mass from fipper length</a></li>
<li class="chapter" data-level="" data-path="thursday-october-14-2022.html"><a href="thursday-october-14-2022.html#model-adequacy"><i class="fa fa-check"></i>Model Adequacy</a></li>
<li class="chapter" data-level="" data-path="thursday-october-14-2022.html"><a href="thursday-october-14-2022.html#transforming-the-response-variable"><i class="fa fa-check"></i>Transforming the response variable</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-october-19-2022.html"><a href="tuesday-october-19-2022.html"><i class="fa fa-check"></i>Tuesday, October 19, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-october-19-2022.html"><a href="tuesday-october-19-2022.html#today-17"><i class="fa fa-check"></i>Today</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-19-2022.html"><a href="tuesday-october-19-2022.html#example-average-income-vs-percent-college-graduates-at-the-state-level"><i class="fa fa-check"></i>Example: Average income vs percent college graduates at the state level</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-19-2022.html"><a href="tuesday-october-19-2022.html#outliers"><i class="fa fa-check"></i>Outliers</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-19-2022.html"><a href="tuesday-october-19-2022.html#summarizing"><i class="fa fa-check"></i>Summarizing</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-19-2022.html"><a href="tuesday-october-19-2022.html#example-a-regression-model-for-trend"><i class="fa fa-check"></i>Example: A regression model for trend</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-19-2022.html"><a href="tuesday-october-19-2022.html#simpsons-paradox"><i class="fa fa-check"></i>Simpson’s paradox</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-october-21-2022.html"><a href="thursday-october-21-2022.html"><i class="fa fa-check"></i>Thursday, October 21, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-october-21-2022.html"><a href="thursday-october-21-2022.html#today-18"><i class="fa fa-check"></i>Today</a></li>
<li class="chapter" data-level="" data-path="thursday-october-21-2022.html"><a href="thursday-october-21-2022.html#multiple-variable-linear-regression"><i class="fa fa-check"></i>Multiple variable linear regression</a></li>
<li class="chapter" data-level="" data-path="thursday-october-21-2022.html"><a href="thursday-october-21-2022.html#a-grid-of-scatter-plots"><i class="fa fa-check"></i>A grid of scatter plots</a></li>
<li class="chapter" data-level="" data-path="thursday-october-21-2022.html"><a href="thursday-october-21-2022.html#fit-a-multiple-variable-regression-model"><i class="fa fa-check"></i>Fit a multiple variable regression model</a></li>
<li class="chapter" data-level="" data-path="thursday-october-21-2022.html"><a href="thursday-october-21-2022.html#should-you-remove-a-variable-from-the-model"><i class="fa fa-check"></i>Should you remove a variable from the model?</a></li>
<li class="chapter" data-level="" data-path="thursday-october-21-2022.html"><a href="thursday-october-21-2022.html#checking-on-the-model-assumptions"><i class="fa fa-check"></i>Checking on the model assumptions</a></li>
<li class="chapter" data-level="" data-path="thursday-october-21-2022.html"><a href="thursday-october-21-2022.html#checking-predictions"><i class="fa fa-check"></i>Checking predictions</a></li>
<li class="chapter" data-level="" data-path="thursday-october-21-2022.html"><a href="thursday-october-21-2022.html#example-predicting-house-prices"><i class="fa fa-check"></i>Example: Predicting house prices</a></li>
<li class="chapter" data-level="" data-path="thursday-october-21-2022.html"><a href="thursday-october-21-2022.html#collinearity"><i class="fa fa-check"></i>Collinearity</a></li>
<li class="chapter" data-level="" data-path="thursday-october-21-2022.html"><a href="thursday-october-21-2022.html#interactions"><i class="fa fa-check"></i>Interactions</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-october-28-2022.html"><a href="tuesday-october-28-2022.html"><i class="fa fa-check"></i>Tuesday, October 28, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-october-28-2022.html"><a href="tuesday-october-28-2022.html#today-19"><i class="fa fa-check"></i>Today</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-28-2022.html"><a href="tuesday-october-28-2022.html#removing-variables-from-a-model"><i class="fa fa-check"></i>Removing variables from a model</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-28-2022.html"><a href="tuesday-october-28-2022.html#the-stepwise-regression-procedure"><i class="fa fa-check"></i>The stepwise regression procedure</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-28-2022.html"><a href="tuesday-october-28-2022.html#transforming-a-response-variable"><i class="fa fa-check"></i>Transforming a response variable</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-28-2022.html"><a href="tuesday-october-28-2022.html#regression-trees"><i class="fa fa-check"></i>Regression trees</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-october-30-2022.html"><a href="thursday-october-30-2022.html"><i class="fa fa-check"></i>Thursday, October 30, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-october-30-2022.html"><a href="thursday-october-30-2022.html#today-20"><i class="fa fa-check"></i>Today</a></li>
<li class="chapter" data-level="" data-path="thursday-october-30-2022.html"><a href="thursday-october-30-2022.html#regression-tree-example"><i class="fa fa-check"></i>Regression tree example</a></li>
<li class="chapter" data-level="" data-path="thursday-october-30-2022.html"><a href="thursday-october-30-2022.html#predictive-uncertainty-1"><i class="fa fa-check"></i>Predictive uncertainty</a></li>
<li class="chapter" data-level="" data-path="thursday-october-30-2022.html"><a href="thursday-october-30-2022.html#random-forest-algorithm"><i class="fa fa-check"></i>Random forest algorithm</a></li>
<li class="chapter" data-level="" data-path="thursday-october-30-2022.html"><a href="thursday-october-30-2022.html#cross-validation"><i class="fa fa-check"></i>Cross validation</a></li>
<li class="chapter" data-level="" data-path="thursday-october-30-2022.html"><a href="thursday-october-30-2022.html#classification-trees"><i class="fa fa-check"></i>Classification trees</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-november-1-2022.html"><a href="tuesday-november-1-2022.html"><i class="fa fa-check"></i>Tuesday, November 1, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-november-1-2022.html"><a href="tuesday-november-1-2022.html#today-21"><i class="fa fa-check"></i>Today</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-1-2022.html"><a href="tuesday-november-1-2022.html#binary-outcomes-and-probabilities"><i class="fa fa-check"></i>Binary outcomes and probabilities</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-1-2022.html"><a href="tuesday-november-1-2022.html#logistic-regression"><i class="fa fa-check"></i>Logistic regression</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-1-2022.html"><a href="tuesday-november-1-2022.html#example-who-survives-in-the-donner-party"><i class="fa fa-check"></i>Example: Who survives in the Donner Party?</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-1-2022.html"><a href="tuesday-november-1-2022.html#example-probability-of-rocket-damage-on-liftoff"><i class="fa fa-check"></i>Example: Probability of rocket damage on liftoff</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-november-3-2022.html"><a href="thursday-november-3-2022.html"><i class="fa fa-check"></i>Thursday, November 3, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-november-3-2022.html"><a href="thursday-november-3-2022.html#today-22"><i class="fa fa-check"></i>Today</a></li>
<li class="chapter" data-level="" data-path="thursday-november-3-2022.html"><a href="thursday-november-3-2022.html#quantifying-autocorrelation-in-spatial-data"><i class="fa fa-check"></i>Quantifying autocorrelation in spatial data</a></li>
<li class="chapter" data-level="" data-path="thursday-november-3-2022.html"><a href="thursday-november-3-2022.html#spatial-data-as-polygons"><i class="fa fa-check"></i>Spatial data as polygons</a></li>
<li class="chapter" data-level="" data-path="thursday-november-3-2022.html"><a href="thursday-november-3-2022.html#list-of-neighbors"><i class="fa fa-check"></i>List of neighbors</a></li>
<li class="chapter" data-level="" data-path="thursday-november-3-2022.html"><a href="thursday-november-3-2022.html#spatial-weights-matrix"><i class="fa fa-check"></i>Spatial weights matrix</a></li>
<li class="chapter" data-level="" data-path="thursday-november-3-2022.html"><a href="thursday-november-3-2022.html#morans-i"><i class="fa fa-check"></i>Moran’s I</a></li>
<li class="chapter" data-level="" data-path="thursday-november-3-2022.html"><a href="thursday-november-3-2022.html#spatial-lag-variable"><i class="fa fa-check"></i>Spatial lag variable</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-november-8-2022.html"><a href="tuesday-november-8-2022.html"><i class="fa fa-check"></i>Tuesday, November 8, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-november-8-2022.html"><a href="tuesday-november-8-2022.html#today-23"><i class="fa fa-check"></i>Today</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-8-2022.html"><a href="tuesday-november-8-2022.html#statistical-significance-of-spatial-autocorrelation"><i class="fa fa-check"></i>Statistical significance of spatial autocorrelation</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-8-2022.html"><a href="tuesday-november-8-2022.html#a-monte-carlo-approach-to-inference-about-spatial-autocorrelation"><i class="fa fa-check"></i>A Monte Carlo approach to inference about spatial autocorrelation</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-8-2022.html"><a href="tuesday-november-8-2022.html#spatial-autocorrelation-in-model-residuals"><i class="fa fa-check"></i>Spatial autocorrelation in model residuals</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-8-2022.html"><a href="tuesday-november-8-2022.html#example-percentage-of-folks-identifying-as-white-in-mississippi-counties"><i class="fa fa-check"></i>Example: Percentage of folks identifying as white in Mississippi counties</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">GEO5156: Quantitative Geography</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="tuesday-november-8-2022" class="section level1 unnumbered">
<h1>Tuesday, November 8, 2022</h1>
<div id="today-23" class="section level2 unnumbered">
<h2>Today</h2>
<ul>
<li>Statistical significance of spatial autocorrelation</li>
<li>The Monte Carlo approach to inference</li>
<li>Spatial autocorrelation in model residuals</li>
</ul>
<p>As a review let us consider another data set where we start by compute spatial autocorrelation. The data are sudden infant deaths (SIDS) rates in the 100 counties of North Carolina for the period July 1, 1979 to June 30, 1984. Download and unzip the data in your working directory.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="tuesday-november-8-2022.html#cb1-1" aria-hidden="true" tabindex="-1"></a>url <span class="ot">&lt;-</span> <span class="st">&quot;http://myweb.fsu.edu/jelsner/temp/data/sids2.zip&quot;</span></span>
<span id="cb1-2"><a href="tuesday-november-8-2022.html#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">download.file</span>(url,</span>
<span id="cb1-3"><a href="tuesday-november-8-2022.html#cb1-3" aria-hidden="true" tabindex="-1"></a>              <span class="at">destfile =</span> here<span class="sc">::</span><span class="fu">here</span>(<span class="st">&quot;data&quot;</span>, <span class="st">&quot;sids2.zip&quot;</span>))</span>
<span id="cb1-4"><a href="tuesday-november-8-2022.html#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">unzip</span>(<span class="at">zipfile =</span> here<span class="sc">::</span><span class="fu">here</span>(<span class="st">&quot;data&quot;</span>, <span class="st">&quot;sids2.zip&quot;</span>),</span>
<span id="cb1-5"><a href="tuesday-november-8-2022.html#cb1-5" aria-hidden="true" tabindex="-1"></a>      <span class="at">exdir =</span> here<span class="sc">::</span><span class="fu">here</span>(<span class="st">&quot;data&quot;</span>))</span></code></pre></div>
<p>Then import the data with the <code>read_sf()</code> function from the {sf} package. Set the coordinate reference system to WGS 1984 with latitude/longitude coordinates using the ESPG code of 4326.</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="tuesday-november-8-2022.html#cb2-1" aria-hidden="true" tabindex="-1"></a>SIDS.sf <span class="ot">&lt;-</span> sf<span class="sc">::</span><span class="fu">read_sf</span>(<span class="at">dsn =</span> here<span class="sc">::</span><span class="fu">here</span>(<span class="st">&quot;data&quot;</span>, <span class="st">&quot;sids2&quot;</span>))</span>
<span id="cb2-2"><a href="tuesday-november-8-2022.html#cb2-2" aria-hidden="true" tabindex="-1"></a>sf<span class="sc">::</span><span class="fu">st_crs</span>(SIDS.sf) <span class="ot">&lt;-</span> <span class="dv">4326</span></span>
<span id="cb2-3"><a href="tuesday-november-8-2022.html#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="tuesday-november-8-2022.html#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(SIDS.sf)</span></code></pre></div>
<pre><code>## Simple feature collection with 6 features and 18 fields
## Geometry type: MULTIPOLYGON
## Dimension:     XY
## Bounding box:  xmin: -81.74107 ymin: 36.07282 xmax: -75.77316 ymax: 36.58965
## Geodetic CRS:  WGS 84
## # A tibble: 6 × 19
##    AREA PERIMETER CNTY_ CNTY_ID NAME   FIPS  FIPSNO CRESS_ID BIR74 SID74 NWBIR74
##   &lt;dbl&gt;     &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt; &lt;chr&gt;  &lt;chr&gt;  &lt;dbl&gt;    &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;
## 1 0.114      1.44  1825    1825 Ashe   37009  37009        5  1091     1      10
## 2 0.061      1.23  1827    1827 Alleg… 37005  37005        3   487     0      10
## 3 0.143      1.63  1828    1828 Surry  37171  37171       86  3188     5     208
## 4 0.07       2.97  1831    1831 Curri… 37053  37053       27   508     1     123
## 5 0.153      2.21  1832    1832 North… 37131  37131       66  1421     9    1066
## 6 0.097      1.67  1833    1833 Hertf… 37091  37091       46  1452     7     954
## # … with 8 more variables: BIR79 &lt;dbl&gt;, SID79 &lt;dbl&gt;, NWBIR79 &lt;dbl&gt;,
## #   SIDR74 &lt;dbl&gt;, SIDR79 &lt;dbl&gt;, NWR74 &lt;dbl&gt;, NWR79 &lt;dbl&gt;,
## #   geometry &lt;MULTIPOLYGON [°]&gt;</code></pre>
<p>The column <code>SIDR79</code> contains the death rate per 1000 live births (1979-84) from sudden infant death syndrome. Create a choropleth map of the SIDS rates.</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="tuesday-november-8-2022.html#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tmap)</span>
<span id="cb4-2"><a href="tuesday-november-8-2022.html#cb4-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-3"><a href="tuesday-november-8-2022.html#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(SIDS.sf) <span class="sc">+</span></span>
<span id="cb4-4"><a href="tuesday-november-8-2022.html#cb4-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="st">&quot;SIDR79&quot;</span>, <span class="at">title =</span> <span class="st">&quot;&quot;</span>) <span class="sc">+</span></span>
<span id="cb4-5"><a href="tuesday-november-8-2022.html#cb4-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">col =</span> <span class="st">&quot;gray70&quot;</span>) <span class="sc">+</span></span>
<span id="cb4-6"><a href="tuesday-november-8-2022.html#cb4-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">title =</span> <span class="st">&quot;SIDS Rates 1979-84 [per 1000]&quot;</span>,</span>
<span id="cb4-7"><a href="tuesday-november-8-2022.html#cb4-7" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.outside =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<p><img src="QG-2022_files/figure-html/unnamed-chunk-3-1.png" width="672" /></p>
<p>Counties with the highest rates are noted in the southern and western parts of the state. There appears to be some clustering. Counties with high rates tend to be surrounded by counties also with high rates and counties with low rates tend to be surrounded by counties also with low rates.</p>
<p>To quantify the amount of clustering you first create a neighborhood list (<code>nb</code>) and a <code>listw</code> object (<code>wts</code>). To visualize the connectivity you graph the neighborhood network.</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="tuesday-november-8-2022.html#cb5-1" aria-hidden="true" tabindex="-1"></a>nbs <span class="ot">&lt;-</span> spdep<span class="sc">::</span><span class="fu">poly2nb</span>(SIDS.sf)</span>
<span id="cb5-2"><a href="tuesday-november-8-2022.html#cb5-2" aria-hidden="true" tabindex="-1"></a>wts <span class="ot">&lt;-</span> spdep<span class="sc">::</span><span class="fu">nb2listw</span>(nbs)</span>
<span id="cb5-3"><a href="tuesday-november-8-2022.html#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(nbs, sf<span class="sc">::</span><span class="fu">st_centroid</span>(SIDS.sf)<span class="sc">$</span>geometry)</span></code></pre></div>
<pre><code>## Warning in st_centroid.sf(SIDS.sf): st_centroid assumes attributes are constant
## over geometries of x</code></pre>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="tuesday-november-8-2022.html#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(SIDS.sf<span class="sc">$</span>geometry, <span class="at">add =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<p><img src="QG-2022_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<p>Next you compute Moran’s I with the <code>moran()</code> function from the {spdep} package.</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="tuesday-november-8-2022.html#cb8-1" aria-hidden="true" tabindex="-1"></a>m <span class="ot">&lt;-</span> <span class="fu">length</span>(SIDS.sf<span class="sc">$</span>SIDR79)</span>
<span id="cb8-2"><a href="tuesday-november-8-2022.html#cb8-2" aria-hidden="true" tabindex="-1"></a>s <span class="ot">&lt;-</span> spdep<span class="sc">::</span><span class="fu">Szero</span>(wts)</span>
<span id="cb8-3"><a href="tuesday-november-8-2022.html#cb8-3" aria-hidden="true" tabindex="-1"></a>spdep<span class="sc">::</span><span class="fu">moran</span>(SIDS.sf<span class="sc">$</span>SIDR79, </span>
<span id="cb8-4"><a href="tuesday-november-8-2022.html#cb8-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">listw =</span> wts, </span>
<span id="cb8-5"><a href="tuesday-november-8-2022.html#cb8-5" aria-hidden="true" tabindex="-1"></a>             <span class="at">n =</span> m, </span>
<span id="cb8-6"><a href="tuesday-november-8-2022.html#cb8-6" aria-hidden="true" tabindex="-1"></a>             <span class="at">S0 =</span> s)</span></code></pre></div>
<pre><code>## $I
## [1] 0.1427504
## 
## $K
## [1] 4.44434</code></pre>
<p>I is .14 and K is 4.4. A normal distribution has a kurtosis of 3. Values less than about 2 or greater than about 4 indicate that inferences about autocorrelation based on the assumption of normality are suspect.</p>
<p>Weights are specified using the <code>style =</code> argument in the <code>nb2listw()</code> function. The default “W” is row standardized (sum of the weights over all links equals the number of polygons).</p>
<p>“B” is binary (each neighbor gets a weight of one). “S” is a variance stabilizing scheme.</p>
<p>Each style gives a slightly different value for I.</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="tuesday-november-8-2022.html#cb10-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> SIDS.sf<span class="sc">$</span>SIDR79</span>
<span id="cb10-2"><a href="tuesday-november-8-2022.html#cb10-2" aria-hidden="true" tabindex="-1"></a>spdep<span class="sc">::</span><span class="fu">moran.test</span>(x, spdep<span class="sc">::</span><span class="fu">nb2listw</span>(nbs, <span class="at">style =</span> <span class="st">&quot;W&quot;</span>))<span class="sc">$</span>estimate[<span class="dv">1</span>]</span></code></pre></div>
<pre><code>## Moran I statistic 
##         0.1427504</code></pre>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="tuesday-november-8-2022.html#cb12-1" aria-hidden="true" tabindex="-1"></a>spdep<span class="sc">::</span><span class="fu">moran.test</span>(x, spdep<span class="sc">::</span><span class="fu">nb2listw</span>(nbs, <span class="at">style =</span> <span class="st">&quot;B&quot;</span>))<span class="sc">$</span>estimate[<span class="dv">1</span>]  <span class="co"># binary</span></span></code></pre></div>
<pre><code>## Moran I statistic 
##         0.1105207</code></pre>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="tuesday-november-8-2022.html#cb14-1" aria-hidden="true" tabindex="-1"></a>spdep<span class="sc">::</span><span class="fu">moran.test</span>(x, spdep<span class="sc">::</span><span class="fu">nb2listw</span>(nbs, <span class="at">style =</span> <span class="st">&quot;S&quot;</span>))<span class="sc">$</span>estimate[<span class="dv">1</span>]  <span class="co"># variance-stabilizing</span></span></code></pre></div>
<pre><code>## Moran I statistic 
##         0.1260686</code></pre>
<p>Thus when reporting Moran’s I you need to indicate what weighting scheme you used.</p>
<p>Moran’s I is the slope of a regression of the spatial lag variable onto the variable itself.</p>
<p>The spatial lag variable consists of the average of the neighboring values. To compute the spatial lag variable you use the <code>lag.listw()</code> function from the {spdep} package.</p>
<p>Let <code>sids</code> be the SIDS rate in each county then the first argument in the <code>lab.listw()</code> function is the <code>listw</code> object and the second is the vector of sids values.</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="tuesday-november-8-2022.html#cb16-1" aria-hidden="true" tabindex="-1"></a>sids <span class="ot">&lt;-</span> SIDS.sf<span class="sc">$</span>SIDR79</span>
<span id="cb16-2"><a href="tuesday-november-8-2022.html#cb16-2" aria-hidden="true" tabindex="-1"></a>Wsids <span class="ot">&lt;-</span> spdep<span class="sc">::</span><span class="fu">lag.listw</span>(wts, </span>
<span id="cb16-3"><a href="tuesday-november-8-2022.html#cb16-3" aria-hidden="true" tabindex="-1"></a>                          <span class="at">var =</span> sids)</span></code></pre></div>
<p>For each value in the vector <code>sids</code> there is a corresponding value in the object <code>Wsids</code> representing the neighborhood average SIDS rate.</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="tuesday-november-8-2022.html#cb17-1" aria-hidden="true" tabindex="-1"></a>Wsids[<span class="dv">1</span>]</span></code></pre></div>
<pre><code>## [1] 2.65921</code></pre>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="tuesday-november-8-2022.html#cb19-1" aria-hidden="true" tabindex="-1"></a>j <span class="ot">&lt;-</span> wts<span class="sc">$</span>neighbours[[<span class="dv">1</span>]]</span>
<span id="cb19-2"><a href="tuesday-november-8-2022.html#cb19-2" aria-hidden="true" tabindex="-1"></a>j</span></code></pre></div>
<pre><code>## [1]  2 18 19</code></pre>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="tuesday-november-8-2022.html#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(SIDS.sf<span class="sc">$</span>SIDR79[j])<span class="sc">/</span><span class="fu">length</span>(j)</span></code></pre></div>
<pre><code>## [1] 2.65921</code></pre>
<p>The weight for county one is <code>Wsids[1]</code> = 2.659. The neighbor indexes for this county are in the vector <code>wts$neighbours[[1]]</code> of length 3. Add the SIDS rates from those counties and divide by the length.</p>
<p>A scatter plot of the neighborhood average SIDS rate versus the actual SIDS rate in each region.</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="tuesday-november-8-2022.html#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb23-2"><a href="tuesday-november-8-2022.html#cb23-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-3"><a href="tuesday-november-8-2022.html#cb23-3" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>(sids, Wsids) <span class="sc">|&gt;</span></span>
<span id="cb23-4"><a href="tuesday-november-8-2022.html#cb23-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> sids, <span class="at">y =</span> Wsids)) <span class="sc">+</span> </span>
<span id="cb23-5"><a href="tuesday-november-8-2022.html#cb23-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb23-6"><a href="tuesday-november-8-2022.html#cb23-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> lm) <span class="sc">+</span></span>
<span id="cb23-7"><a href="tuesday-november-8-2022.html#cb23-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;SIDS&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;Spatial Lag of SIDS&quot;</span>) <span class="sc">+</span></span>
<span id="cb23-8"><a href="tuesday-november-8-2022.html#cb23-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<p><img src="QG-2022_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<p>The slope of the regression line is upward indicating positive autocorrelation. The value of the slope is I. To check this type</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="tuesday-november-8-2022.html#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(Wsids <span class="sc">~</span> sids)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Wsids ~ sids)
## 
## Coefficients:
## (Intercept)         sids  
##      1.7622       0.1428</code></pre>
</div>
<div id="statistical-significance-of-spatial-autocorrelation" class="section level2 unnumbered">
<h2>Statistical significance of spatial autocorrelation</h2>
<p>Even if the county SIDS rates are randomly distributed across the state, the value of Moran’s I will not necessarily be close to zero (-1/(n-1)). If we want to use I to establish statistically significant clustering, you need a way to guard against this randomness.</p>
<p>Said another way: Is the value of Moran’s I significant with respect to the null hypothesis of no spatial autocorrelation?</p>
<p>One way to answer this question is to draw an uncertainty band on the regression line and see if a horizontal line can be placed within the band. If not, then I is statistically different than what you would expect if the null hypothesis of no spatial autocorrelation were true.</p>
<p>More formally the question is answered by comparing the standard deviate (<span class="math inline">\(z\)</span> value) of the I statistic with a standard normal deviate. This is done using the <code>moran.test()</code> function, where the <span class="math inline">\(z\)</span> value is the difference between I and the expected value of I divided by the square root of the variance of I.</p>
<p>The function takes a variable name or numeric vector and a spatial weights list object in that order. The argument <code>randomisation = FALSE</code> means the variance of I is computed under the assumption of normally distributed SIDS rates.</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="tuesday-november-8-2022.html#cb27-1" aria-hidden="true" tabindex="-1"></a>( mt <span class="ot">&lt;-</span> spdep<span class="sc">::</span><span class="fu">moran.test</span>(sids, </span>
<span id="cb27-2"><a href="tuesday-november-8-2022.html#cb27-2" aria-hidden="true" tabindex="-1"></a>                          <span class="at">listw =</span> wts,</span>
<span id="cb27-3"><a href="tuesday-november-8-2022.html#cb27-3" aria-hidden="true" tabindex="-1"></a>                          <span class="at">randomisation =</span> <span class="cn">FALSE</span>) )</span></code></pre></div>
<pre><code>## 
##  Moran I test under normality
## 
## data:  sids  
## weights: wts    
## 
## Moran I statistic standard deviate = 2.3438, p-value = 0.009544
## alternative hypothesis: greater
## sample estimates:
## Moran I statistic       Expectation          Variance 
##       0.142750392      -0.010101010       0.004252954</code></pre>
<p>I is .143 with a variance of .0043. The <span class="math inline">\(z\)</span> value for the I statistic is 2.3438 giving a <span class="math inline">\(p\)</span> value slightly less than .01 under the null hypothesis of no spatial autocorrelation.</p>
<p>Thus we reject the null hypothesis and conclude there is weak (I is small) but significant spatial autocorrelation in SIDS rates across North Carolina at the county level.</p>
<p>Look at the output in the object <code>mt</code> with the <code>str()</code> function.</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="tuesday-november-8-2022.html#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(mt)</span></code></pre></div>
<pre><code>## List of 6
##  $ statistic  : Named num 2.34
##   ..- attr(*, &quot;names&quot;)= chr &quot;Moran I statistic standard deviate&quot;
##  $ p.value    : num 0.00954
##  $ estimate   : Named num [1:3] 0.14275 -0.0101 0.00425
##   ..- attr(*, &quot;names&quot;)= chr [1:3] &quot;Moran I statistic&quot; &quot;Expectation&quot; &quot;Variance&quot;
##  $ alternative: chr &quot;greater&quot;
##  $ method     : chr &quot;Moran I test under normality&quot;
##  $ data.name  : chr &quot;sids  \nweights: wts    \n&quot;
##  - attr(*, &quot;class&quot;)= chr &quot;htest&quot;</code></pre>
<p>The element called <code>estimate</code> is a vector of length three containing Moran’s I statistic, the expected value of Moran’s I under the assumption of uncorrelated normally distributed SIDS rates, and the variance of Moran’s I.</p>
<p>The <span class="math inline">\(z\)</span> value is the difference between the statistic and it’s expected value divided by the square root of the variance.</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="tuesday-november-8-2022.html#cb31-1" aria-hidden="true" tabindex="-1"></a>( mt<span class="sc">$</span>estimate[<span class="dv">1</span>] <span class="sc">-</span> mt<span class="sc">$</span>estimate[<span class="dv">2</span>] ) <span class="sc">/</span> <span class="fu">sqrt</span>(mt<span class="sc">$</span>estimate[<span class="dv">3</span>])</span></code></pre></div>
<pre><code>## Moran I statistic 
##          2.343819</code></pre>
<p>The <span class="math inline">\(p\)</span> value is the area under a standard normal distribution curve to the right (<code>lower.tail = FALSE</code>) of 2.3438 (<code>mt$statistic</code>).</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="tuesday-november-8-2022.html#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pnorm</span>(mt<span class="sc">$</span>statistic, </span>
<span id="cb33-2"><a href="tuesday-november-8-2022.html#cb33-2" aria-hidden="true" tabindex="-1"></a>      <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## Moran I statistic standard deviate 
##                        0.009543713</code></pre>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="tuesday-november-8-2022.html#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">curve</span>(<span class="fu">dnorm</span>(x), <span class="at">from =</span> <span class="sc">-</span><span class="dv">4</span>, <span class="at">to =</span> <span class="dv">4</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb35-2"><a href="tuesday-november-8-2022.html#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> mt<span class="sc">$</span>statistic, <span class="at">col =</span> <span class="st">&#39;red&#39;</span>)</span></code></pre></div>
<p><img src="QG-2022_files/figure-html/unnamed-chunk-14-1.png" width="672" /></p>
<p>So slightly less than 1% (<span class="math inline">\(p\)</span> value of .0095) of the area lies to the right of the red line.</p>
<p>Recall the <span class="math inline">\(p\)</span> value summarizes the evidence in support of the null hypothesis. The smaller the <span class="math inline">\(p\)</span> value, the less evidence there is to support the null hypothesis.</p>
<p>In this case it is the probability that the county SIDS rates could have been arranged at random across the state. The small <span class="math inline">\(p\)</span> value tells us that the spatial arrangement of our data is unusual with respect to the null hypothesis.</p>
<p>The interpretation of the <span class="math inline">\(p\)</span> value is stated as evidence AGAINST the null hypothesis. This is because your interest lies in the null hypothesis being unsupported.</p>
<table>
<thead>
<tr class="header">
<th><span class="math inline">\(p\)</span> value</th>
<th>Statement of evidence against the null</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>less than .01</td>
<td>convincing</td>
</tr>
<tr class="even">
<td>.01 - .05</td>
<td>moderate</td>
</tr>
<tr class="odd">
<td>.05 - .15</td>
<td>suggestive, but inconclusive</td>
</tr>
<tr class="even">
<td>greater than .15</td>
<td>no</td>
</tr>
</tbody>
</table>
<p>Under the assumption of normal distributed and uncorrelated data, the expected value for Moran’s I is -1/(n-1) where n is the number of counties.</p>
<p>A check on the distribution of SIDS rates indicates that normality is suspect. Recall a good way to check the normality assumption is to use the <code>sm.density()</code> function from the {sm} package.</p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="tuesday-november-8-2022.html#cb36-1" aria-hidden="true" tabindex="-1"></a>sm<span class="sc">::</span><span class="fu">sm.density</span>(sids, </span>
<span id="cb36-2"><a href="tuesday-november-8-2022.html#cb36-2" aria-hidden="true" tabindex="-1"></a>               <span class="at">model =</span> <span class="st">&quot;Normal&quot;</span>,</span>
<span id="cb36-3"><a href="tuesday-november-8-2022.html#cb36-3" aria-hidden="true" tabindex="-1"></a>               <span class="at">xlab =</span> <span class="st">&quot;SIDS Rates 1979-84 [per 1000]&quot;</span>)</span></code></pre></div>
<p><img src="QG-2022_files/figure-html/unnamed-chunk-15-1.png" width="672" /></p>
<p>The SIDS rates are more “peaked” (higher kurtosis) than a normal distribution. In this case it is better to use the default <code>randomisation = TRUE</code> argument.</p>
<p>Further, the assumptions underlying the test are sensitive to the form of the graph of neighbor relationships and other factors so results should be checked against a test that involves permutations.</p>
</div>
<div id="a-monte-carlo-approach-to-inference-about-spatial-autocorrelation" class="section level2 unnumbered">
<h2>A Monte Carlo approach to inference about spatial autocorrelation</h2>
<p>A permutation test to examine the statistical significance of spatial autocorrelation is performed with the <code>moran.mc()</code> function. MC stands for Monte Carlo which refers to the city of Monte Carlo in Monaco famous for its gambling casinos. The MC procedure refers to random sampling.</p>
<p>The name of the data vector and the weights list object (<code>listw</code>) are required arguments as is the number of permutations (<code>nsim</code>). Each permutation is a rearrangement of the SIDS rates across the counties. This rearrangement removes the spatial autocorrelation but keeps the non-spatial distribution of the SIDS rates. The neighbor topology and weights remain the same.</p>
<p>For each permutation (shuffle or simulation), I is computed and saved. The <span class="math inline">\(p\)</span> value is obtained as the ratio of the number of permuted I values greater or exceeding the observed I over the number of permutation plus one. In the case where there are 5 permuted I values greater or equal to the observed value based on 99 simulations, the <span class="math inline">\(p\)</span> value is 5/(99 + 1) = .05.</p>
<p>For example, if you want draw inference on your value for I using 99 simulations you type</p>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="tuesday-november-8-2022.html#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">4102</span>)</span>
<span id="cb37-2"><a href="tuesday-november-8-2022.html#cb37-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-3"><a href="tuesday-november-8-2022.html#cb37-3" aria-hidden="true" tabindex="-1"></a>( mP <span class="ot">&lt;-</span> spdep<span class="sc">::</span><span class="fu">moran.mc</span>(sids, </span>
<span id="cb37-4"><a href="tuesday-november-8-2022.html#cb37-4" aria-hidden="true" tabindex="-1"></a>                        <span class="at">listw =</span> wts,</span>
<span id="cb37-5"><a href="tuesday-november-8-2022.html#cb37-5" aria-hidden="true" tabindex="-1"></a>                        <span class="at">nsim =</span> <span class="dv">99</span>) )</span></code></pre></div>
<pre><code>## 
##  Monte-Carlo simulation of Moran I
## 
## data:  sids 
## weights: wts  
## number of simulations + 1: 100 
## 
## statistic = 0.14275, observed rank = 96, p-value = 0.04
## alternative hypothesis: greater</code></pre>
<p>You see that only two of the 99 simulations give a Moran’s I value exceeding .1428.
Thus the <span class="math inline">\(p\)</span> value, as evidence in support of the null hypothesis, (the true value for is close to zero) is .02.</p>
<p>Note: here you initiate the random number generator with a seed value (4102) with the <code>set.seed()</code> function so that the set of random permutations of the values across the domain will be the same each time you run the simulations. This is not needed but it is important for reproducibility. The default random number generator seed value is determined from the current time (internal clock) and so no two sets of permutations will be identical.</p>
<p>The values of I computed for each permutation are saved in the vector <code>mP$res</code>.</p>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="tuesday-november-8-2022.html#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(mP<span class="sc">$</span>res)</span></code></pre></div>
<pre><code>## [1]  0.072218451  0.011785265 -0.032330997  0.046546755  0.008730068
## [6]  0.080639514</code></pre>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="tuesday-november-8-2022.html#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tail</span>(mP<span class="sc">$</span>res)</span></code></pre></div>
<pre><code>## [1]  0.03479774 -0.01222684  0.03392046 -0.03833658 -0.03410486  0.14275039</code></pre>
<p>The last value in the vector is I computed using the data in the correct counties. So the <span class="math inline">\(p\)</span> value as evidence in support of the null hypothesis that I is close to zero is given as</p>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="tuesday-november-8-2022.html#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(mP<span class="sc">$</span>res <span class="sc">&gt;</span> mP<span class="sc">$</span>res[<span class="dv">100</span>])<span class="sc">/</span><span class="dv">99</span></span></code></pre></div>
<pre><code>## [1] 0.04040404</code></pre>
<p>A density graph shows the distribution of permuted I values. To see this create 999 simulations and then plot a density curve adding a vertical line at the value of Moran’s I computed from the data at the correct counties.</p>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="tuesday-november-8-2022.html#cb45-1" aria-hidden="true" tabindex="-1"></a>mP <span class="ot">&lt;-</span> spdep<span class="sc">::</span><span class="fu">moran.mc</span>(sids, </span>
<span id="cb45-2"><a href="tuesday-november-8-2022.html#cb45-2" aria-hidden="true" tabindex="-1"></a>                      <span class="at">listw =</span> wts, </span>
<span id="cb45-3"><a href="tuesday-november-8-2022.html#cb45-3" aria-hidden="true" tabindex="-1"></a>                      <span class="at">nsim =</span> <span class="dv">999</span>)</span>
<span id="cb45-4"><a href="tuesday-november-8-2022.html#cb45-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-5"><a href="tuesday-november-8-2022.html#cb45-5" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">mp =</span> mP<span class="sc">$</span>res[<span class="sc">-</span><span class="dv">1000</span>])</span>
<span id="cb45-6"><a href="tuesday-november-8-2022.html#cb45-6" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> df, </span>
<span id="cb45-7"><a href="tuesday-november-8-2022.html#cb45-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">mapping =</span> <span class="fu">aes</span>(mp)) <span class="sc">+</span> </span>
<span id="cb45-8"><a href="tuesday-november-8-2022.html#cb45-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>() <span class="sc">+</span> </span>
<span id="cb45-9"><a href="tuesday-november-8-2022.html#cb45-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_rug</span>() <span class="sc">+</span> </span>
<span id="cb45-10"><a href="tuesday-november-8-2022.html#cb45-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> mP<span class="sc">$</span>res[<span class="dv">1000</span>], </span>
<span id="cb45-11"><a href="tuesday-november-8-2022.html#cb45-11" aria-hidden="true" tabindex="-1"></a>             <span class="at">color =</span> <span class="st">&quot;red&quot;</span>, <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb45-12"><a href="tuesday-november-8-2022.html#cb45-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="QG-2022_files/figure-html/unnamed-chunk-19-1.png" width="672" /></p>
<p>Only a handful simulations give a Moran’s I value exceeding .143 (tic marks to the right of the red vertical line). The density curve is centered just to the left of zero which is consistent with the true mean being slightly less than zero (-.01).</p>
<p>Note that the right tail of the distribution is fatter than the left tail. This is due to the skewness of the rates used in the calculation of I.</p>
<p>What do you do with the knowledge that the SIDS rates have significant spatial autocorrelation? By itself not much, but it can be a warning that something is going on a larger scale (larger than the scale of the counties).</p>
<p>More typically the knowledge is useful after other known factors are considered in the analysis. In the language of statistics, knowledge of significant spatial autocorrelation in the residuals from a model can help you better specify the relationships defined by the model.</p>
</div>
<div id="spatial-autocorrelation-in-model-residuals" class="section level2 unnumbered">
<h2>Spatial autocorrelation in model residuals</h2>
<p>A spatial regression model might be needed when the residuals resulting from an aspatial (non-spatial) regression model exhibit significant spatial autocorrelation.</p>
<p>A common way to proceed is to regress the response variable onto the explanatory variables and check for spatial autocorrelation in the residuals.</p>
<p>If the residuals are spatially uncorrelated then a spatial regression model is not needed.</p>
<p>Let’s return to the Columbus crime data and fit a linear regression model with <code>CRIME</code> as the response variable and <code>INC</code> and <code>HOVAL</code> as the explanatory variables.</p>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="tuesday-november-8-2022.html#cb46-1" aria-hidden="true" tabindex="-1"></a>CC.sf <span class="ot">&lt;-</span> sf<span class="sc">::</span><span class="fu">read_sf</span>(<span class="at">dsn =</span> here<span class="sc">::</span><span class="fu">here</span>(<span class="st">&quot;data&quot;</span>, <span class="st">&quot;columbus&quot;</span>), </span>
<span id="cb46-2"><a href="tuesday-november-8-2022.html#cb46-2" aria-hidden="true" tabindex="-1"></a>                     <span class="at">layer =</span> <span class="st">&quot;columbus&quot;</span>)</span></code></pre></div>
<p>Start with a choropleth map displaying the crime rates across the city at the tract level.</p>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="tuesday-november-8-2022.html#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(CC.sf) <span class="sc">+</span></span>
<span id="cb47-2"><a href="tuesday-november-8-2022.html#cb47-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="st">&quot;CRIME&quot;</span>,</span>
<span id="cb47-3"><a href="tuesday-november-8-2022.html#cb47-3" aria-hidden="true" tabindex="-1"></a>          <span class="at">title =</span> <span class="st">&quot;&quot;</span>) <span class="sc">+</span></span>
<span id="cb47-4"><a href="tuesday-november-8-2022.html#cb47-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">col =</span> <span class="st">&quot;gray70&quot;</span>) <span class="sc">+</span></span>
<span id="cb47-5"><a href="tuesday-november-8-2022.html#cb47-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">title =</span> <span class="st">&quot;Burglary &amp; Vehicle Thefts</span><span class="sc">\n</span><span class="st">/1000 Households&quot;</span>,</span>
<span id="cb47-6"><a href="tuesday-november-8-2022.html#cb47-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.outside =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## Warning: Currect projection of shape CC.sf unknown. Long-lat (WGS84) is assumed.</code></pre>
<p><img src="QG-2022_files/figure-html/unnamed-chunk-21-1.png" width="672" /></p>
<p>Next compute Moran’s I on the <code>CRIME</code> variable using row-standardized weights (default option in the <code>nb2listw()</code> function).</p>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb49-1"><a href="tuesday-november-8-2022.html#cb49-1" aria-hidden="true" tabindex="-1"></a>nbs <span class="ot">&lt;-</span> spdep<span class="sc">::</span><span class="fu">poly2nb</span>(CC.sf)</span>
<span id="cb49-2"><a href="tuesday-november-8-2022.html#cb49-2" aria-hidden="true" tabindex="-1"></a>wts <span class="ot">&lt;-</span> spdep<span class="sc">::</span><span class="fu">nb2listw</span>(nbs)</span>
<span id="cb49-3"><a href="tuesday-november-8-2022.html#cb49-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-4"><a href="tuesday-november-8-2022.html#cb49-4" aria-hidden="true" tabindex="-1"></a>spdep<span class="sc">::</span><span class="fu">moran</span>(CC.sf<span class="sc">$</span>CRIME,</span>
<span id="cb49-5"><a href="tuesday-november-8-2022.html#cb49-5" aria-hidden="true" tabindex="-1"></a>             <span class="at">listw =</span> wts,</span>
<span id="cb49-6"><a href="tuesday-november-8-2022.html#cb49-6" aria-hidden="true" tabindex="-1"></a>             <span class="at">n =</span> <span class="fu">length</span>(nbs),</span>
<span id="cb49-7"><a href="tuesday-november-8-2022.html#cb49-7" aria-hidden="true" tabindex="-1"></a>             <span class="at">S0 =</span> spdep<span class="sc">::</span><span class="fu">Szero</span>(wts))</span></code></pre></div>
<pre><code>## $I
## [1] 0.5001886
## 
## $K
## [1] 2.225946</code></pre>
<p>Is the spatial autocorrelation you detect due to a clustering of income and housing values across the city? Said another way, after accounting for income and housing values, do crime rates still cluster?</p>
<p>This is answered by fitting a regression model to the crime rates with income and housing values as explanatory variables.</p>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb51-1"><a href="tuesday-november-8-2022.html#cb51-1" aria-hidden="true" tabindex="-1"></a>model.lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(CRIME <span class="sc">~</span> INC <span class="sc">+</span> HOVAL, </span>
<span id="cb51-2"><a href="tuesday-november-8-2022.html#cb51-2" aria-hidden="true" tabindex="-1"></a>               <span class="at">data =</span> CC.sf)</span>
<span id="cb51-3"><a href="tuesday-november-8-2022.html#cb51-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model.lm)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = CRIME ~ INC + HOVAL, data = CC.sf)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -34.418  -6.388  -1.580   9.052  28.649 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  68.6190     4.7355  14.490  &lt; 2e-16 ***
## INC          -1.5973     0.3341  -4.780 1.83e-05 ***
## HOVAL        -0.2739     0.1032  -2.654   0.0109 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 11.43 on 46 degrees of freedom
## Multiple R-squared:  0.5524, Adjusted R-squared:  0.5329 
## F-statistic: 28.39 on 2 and 46 DF,  p-value: 9.341e-09</code></pre>
<p>Income and housing values vary indirectly with values of crime. Higher income tracts and tracts with higher housing values have less crime. The model statistically explains 55% of the variation in crime.</p>
<p>You use the <code>residuals()</code> method to extract the vector of residuals from the model.</p>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="tuesday-november-8-2022.html#cb53-1" aria-hidden="true" tabindex="-1"></a>res <span class="ot">&lt;-</span> <span class="fu">residuals</span>(model.lm)</span></code></pre></div>
<p>There are 49 residuals, one residual for every tract. A residual is defined as the difference between the observed value and the model predicted value. A tract with a residual that is greater than zero indicates that there is more crime than the model predicts for that location.</p>
<p>You next check on the distribution of the residuals relative to a normal distribution.</p>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb54-1"><a href="tuesday-november-8-2022.html#cb54-1" aria-hidden="true" tabindex="-1"></a>sm<span class="sc">::</span><span class="fu">sm.density</span>(res, </span>
<span id="cb54-2"><a href="tuesday-november-8-2022.html#cb54-2" aria-hidden="true" tabindex="-1"></a>               <span class="at">model =</span> <span class="st">&quot;Normal&quot;</span>)</span></code></pre></div>
<p><img src="QG-2022_files/figure-html/unnamed-chunk-25-1.png" width="672" /></p>
<p>Since the black lines falls completely within the blue envelope (defined by a normal distribution) you find no evidence to reject the assumption of normally distributed model residuals.</p>
<p>Next you plot a choropleth map of the model residuals. Are there clusters of high and low residuals? First add the vector of residuals as a column in the simple feature data frame. Call this new column <code>residuals</code> then use functions from the {tmap} package.</p>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb55-1"><a href="tuesday-november-8-2022.html#cb55-1" aria-hidden="true" tabindex="-1"></a>CC.sf<span class="sc">$</span>residuals <span class="ot">&lt;-</span> res</span>
<span id="cb55-2"><a href="tuesday-november-8-2022.html#cb55-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-3"><a href="tuesday-november-8-2022.html#cb55-3" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(CC.sf) <span class="sc">+</span></span>
<span id="cb55-4"><a href="tuesday-november-8-2022.html#cb55-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="st">&quot;residuals&quot;</span>) <span class="sc">+</span></span>
<span id="cb55-5"><a href="tuesday-november-8-2022.html#cb55-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">col =</span> <span class="st">&quot;gray70&quot;</span>) <span class="sc">+</span></span>
<span id="cb55-6"><a href="tuesday-november-8-2022.html#cb55-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">title =</span> <span class="st">&quot;Regression Residuals&quot;</span>)</span></code></pre></div>
<pre><code>## Warning: Currect projection of shape CC.sf unknown. Long-lat (WGS84) is assumed.</code></pre>
<pre><code>## Variable(s) &quot;residuals&quot; contains positive and negative values, so midpoint is set to 0. Set midpoint = NA to show the full spectrum of the color palette.</code></pre>
<p><img src="QG-2022_files/figure-html/unnamed-chunk-26-1.png" width="672" /></p>
<p>There appears to be distinct regions where the model over predicts crime (yellow to green tracts) conditional on household income and housing values and where it under predicts crime (yellow to red tracts).</p>
<p>The amount of clustering appears to be is less than the crime rates themselves. That is, after accounting for regional factors related to crime the spatial autocorrelation is reduced.</p>
<p>To determine how much less clustering you compute I on the residuals with the <code>lm.morantest()</code> function. You need to include the model object and the spatial weights object.</p>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb58-1"><a href="tuesday-november-8-2022.html#cb58-1" aria-hidden="true" tabindex="-1"></a>spdep<span class="sc">::</span><span class="fu">lm.morantest</span>(<span class="at">model =</span> model.lm, </span>
<span id="cb58-2"><a href="tuesday-november-8-2022.html#cb58-2" aria-hidden="true" tabindex="-1"></a>                    <span class="at">listw =</span> wts)</span></code></pre></div>
<pre><code>## 
##  Global Moran I for regression residuals
## 
## data:  
## model: lm(formula = CRIME ~ INC + HOVAL, data = CC.sf)
## weights: wts
## 
## Moran I statistic standard deviate = 2.8393, p-value = 0.00226
## alternative hypothesis: greater
## sample estimates:
## Observed Moran I      Expectation         Variance 
##      0.222109407     -0.033418335      0.008099305</code></pre>
<p>Moran’s I on the model residuals is .222. This compares with the value of .5 on crime alone. Part of the spatial autocorrelation is absorbed by the explanatory factors.</p>
<p>The output gives a <span class="math inline">\(p\)</span> value on I of .002, thus you reject the null hypothesis of no spatial autocorrelation in the residuals and conclude that a spatial regression model would improve the model.</p>
<p>The <span class="math inline">\(z\)</span>-value takes into account the fact that these are residuals so the variance is adjusted accordingly.</p>
<p>The next step is to choose the type of spatial regression model. Before that, let’s look at one more example.</p>
</div>
<div id="example-percentage-of-folks-identifying-as-white-in-mississippi-counties" class="section level2 unnumbered">
<h2>Example: Percentage of folks identifying as white in Mississippi counties</h2>
<p>Download the county-level police data. Import the data as a simple feature data frame and assign the geometry a geographic CRS. The file <em>police.zip</em> contains shapefiles in a folder on my website.</p>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb60-1"><a href="tuesday-november-8-2022.html#cb60-1" aria-hidden="true" tabindex="-1"></a>url <span class="ot">&lt;-</span> <span class="st">&quot;http://myweb.fsu.edu/jelsner/temp/data/police.zip&quot;</span></span>
<span id="cb60-2"><a href="tuesday-november-8-2022.html#cb60-2" aria-hidden="true" tabindex="-1"></a><span class="fu">download.file</span>(url,</span>
<span id="cb60-3"><a href="tuesday-november-8-2022.html#cb60-3" aria-hidden="true" tabindex="-1"></a>              <span class="at">destfile =</span> here<span class="sc">::</span><span class="fu">here</span>(<span class="st">&quot;data&quot;</span>, <span class="st">&quot;police.zip&quot;</span>))</span>
<span id="cb60-4"><a href="tuesday-november-8-2022.html#cb60-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-5"><a href="tuesday-november-8-2022.html#cb60-5" aria-hidden="true" tabindex="-1"></a><span class="fu">unzip</span>(<span class="at">zipfile =</span> here<span class="sc">::</span><span class="fu">here</span>(<span class="st">&quot;data&quot;</span>, <span class="st">&quot;police.zip&quot;</span>),</span>
<span id="cb60-6"><a href="tuesday-november-8-2022.html#cb60-6" aria-hidden="true" tabindex="-1"></a>      <span class="at">exdir =</span> here<span class="sc">::</span><span class="fu">here</span>(<span class="st">&quot;data&quot;</span>))</span>
<span id="cb60-7"><a href="tuesday-november-8-2022.html#cb60-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-8"><a href="tuesday-november-8-2022.html#cb60-8" aria-hidden="true" tabindex="-1"></a>PE.sf <span class="ot">&lt;-</span> sf<span class="sc">::</span><span class="fu">read_sf</span>(<span class="at">dsn =</span> here<span class="sc">::</span><span class="fu">here</span>(<span class="st">&quot;data&quot;</span>, <span class="st">&quot;police&quot;</span>), </span>
<span id="cb60-9"><a href="tuesday-november-8-2022.html#cb60-9" aria-hidden="true" tabindex="-1"></a>                 <span class="at">layer =</span> <span class="st">&quot;police&quot;</span>)</span>
<span id="cb60-10"><a href="tuesday-november-8-2022.html#cb60-10" aria-hidden="true" tabindex="-1"></a>sf<span class="sc">::</span><span class="fu">st_crs</span>(PE.sf) <span class="ot">&lt;-</span> <span class="dv">4326</span></span>
<span id="cb60-11"><a href="tuesday-november-8-2022.html#cb60-11" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(PE.sf)</span></code></pre></div>
<pre><code>##  [1] &quot;AREA&quot;       &quot;PERIMETER&quot;  &quot;CNTY_&quot;      &quot;CNTY_ID&quot;    &quot;NAME&quot;      
##  [6] &quot;STATE_NAME&quot; &quot;STATE_FIPS&quot; &quot;CNTY_FIPS&quot;  &quot;FIPS&quot;       &quot;FIPSNO&quot;    
## [11] &quot;POLICE&quot;     &quot;POP&quot;        &quot;TAX&quot;        &quot;TRANSFER&quot;   &quot;INC&quot;       
## [16] &quot;CRIME&quot;      &quot;UNEMP&quot;      &quot;OWN&quot;        &quot;COLLEGE&quot;    &quot;WHITE&quot;     
## [21] &quot;COMMUTE&quot;    &quot;geometry&quot;</code></pre>
<p>Variables include police expenditures (<code>POLICE</code>), crime (<code>CRIME</code>), income (<code>INC</code>), unemployment (<code>UNEMP</code>) and other socio-economic characteristics across Mississippi at the county level. The police expenditures are per capita 1982 (dollars per person). The personal income per county resident, 1982 (dollars per person). The crime is the number of serious crimes per 100,000 residents, 1981. Unemployment is percent unemployed in 1980.</p>
<p>The geometries are polygons defining the county borders.</p>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb62-1"><a href="tuesday-november-8-2022.html#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(PE.sf<span class="sc">$</span>geometry)</span></code></pre></div>
<p><img src="QG-2022_files/figure-html/unnamed-chunk-29-1.png" width="672" /></p>
<p>Again, you need to assign the neighborhoods and the associated weights between the each region and each neighbor of that region.</p>
<div class="sourceCode" id="cb63"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb63-1"><a href="tuesday-november-8-2022.html#cb63-1" aria-hidden="true" tabindex="-1"></a>nbs <span class="ot">&lt;-</span> spdep<span class="sc">::</span><span class="fu">poly2nb</span>(PE.sf)</span>
<span id="cb63-2"><a href="tuesday-november-8-2022.html#cb63-2" aria-hidden="true" tabindex="-1"></a>wts <span class="ot">&lt;-</span> spdep<span class="sc">::</span><span class="fu">nb2listw</span>(nbs)</span></code></pre></div>
<p>Another way to do this is to specify the number of neighbors and define who the neighbors are based on distance. You do this with the <code>knearneigh()</code> function. First extract the coordinates of the polygon centroids.</p>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb64-1"><a href="tuesday-november-8-2022.html#cb64-1" aria-hidden="true" tabindex="-1"></a>coords <span class="ot">&lt;-</span> PE.sf <span class="sc">|&gt;</span></span>
<span id="cb64-2"><a href="tuesday-november-8-2022.html#cb64-2" aria-hidden="true" tabindex="-1"></a>  sf<span class="sc">::</span><span class="fu">st_geometry</span>() <span class="sc">|&gt;</span></span>
<span id="cb64-3"><a href="tuesday-november-8-2022.html#cb64-3" aria-hidden="true" tabindex="-1"></a>  sf<span class="sc">::</span><span class="fu">st_centroid</span>() <span class="sc">|&gt;</span></span>
<span id="cb64-4"><a href="tuesday-november-8-2022.html#cb64-4" aria-hidden="true" tabindex="-1"></a>  sf<span class="sc">::</span><span class="fu">st_coordinates</span>()</span>
<span id="cb64-5"><a href="tuesday-november-8-2022.html#cb64-5" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(coords)</span></code></pre></div>
<pre><code>##           X        Y
## 1 -88.56938 34.88746
## 2 -88.23073 34.74665
## 3 -88.89928 34.77600
## 4 -89.17942 34.82323
## 5 -89.98973 34.88099
## 6 -89.49699 34.76984</code></pre>
<p>You can specify that each county for example has six neighbors where the neighbors are based on proximity. Since the CRS is geographic we include the <code>longlat = TRUE</code> argument so the distances are based on great circles.</p>
<div class="sourceCode" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb66-1"><a href="tuesday-november-8-2022.html#cb66-1" aria-hidden="true" tabindex="-1"></a>knn <span class="ot">&lt;-</span> spdep<span class="sc">::</span><span class="fu">knearneigh</span>(coords, </span>
<span id="cb66-2"><a href="tuesday-november-8-2022.html#cb66-2" aria-hidden="true" tabindex="-1"></a>                         <span class="at">k =</span> <span class="dv">6</span>, </span>
<span id="cb66-3"><a href="tuesday-november-8-2022.html#cb66-3" aria-hidden="true" tabindex="-1"></a>                         <span class="at">longlat =</span> <span class="cn">TRUE</span>)</span>
<span id="cb66-4"><a href="tuesday-november-8-2022.html#cb66-4" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(knn<span class="sc">$</span>nn)</span></code></pre></div>
<pre><code>##      [,1] [,2] [,3] [,4] [,5] [,6]
## [1,]    9    3    2    4   10   14
## [2,]    9    1   16    3   14   10
## [3,]    4   10    1    9    6   14
## [4,]    3    6   10    1   11    9
## [5,]    8    7    6   12   11    4
## [6,]    4    8   11    5    3   10</code></pre>
<p>The output is a list of five elements with the first being a matrix of dimension number of counties by the number of neighbors. You see here that the neighborhoods are non-symmetric. County 3 is a neighbor of county 2, but county 2 is not a neighbor of county 3. This is important since some spatial regression models require symmetric neighborhood definitions.</p>
<p>You turn this list into a neighborhood object (class <code>nb</code>) with the <code>knn2nb()</code> function.</p>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb68-1"><a href="tuesday-november-8-2022.html#cb68-1" aria-hidden="true" tabindex="-1"></a>nbs2 <span class="ot">&lt;-</span> spdep<span class="sc">::</span><span class="fu">knn2nb</span>(knn)</span>
<span id="cb68-2"><a href="tuesday-november-8-2022.html#cb68-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(nbs2)</span></code></pre></div>
<pre><code>## Neighbour list object:
## Number of regions: 82 
## Number of nonzero links: 492 
## Percentage nonzero weights: 7.317073 
## Average number of links: 6 
## Non-symmetric neighbours list
## Link number distribution:
## 
##  6 
## 82 
## 82 least connected regions:
## 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 with 6 links
## 82 most connected regions:
## 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 with 6 links</code></pre>
<p>The argument <code>sym = TRUE</code> forces the output neighbors list to be symmetric. Create another neighborhood object.</p>
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb70-1"><a href="tuesday-november-8-2022.html#cb70-1" aria-hidden="true" tabindex="-1"></a>nbs3 <span class="ot">&lt;-</span> spdep<span class="sc">::</span><span class="fu">knn2nb</span>(knn,</span>
<span id="cb70-2"><a href="tuesday-november-8-2022.html#cb70-2" aria-hidden="true" tabindex="-1"></a>                      <span class="at">sym =</span> <span class="cn">TRUE</span>)</span>
<span id="cb70-3"><a href="tuesday-november-8-2022.html#cb70-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(nbs3)</span></code></pre></div>
<pre><code>## Neighbour list object:
## Number of regions: 82 
## Number of nonzero links: 568 
## Percentage nonzero weights: 8.447353 
## Average number of links: 6.926829 
## Link number distribution:
## 
##  6  7  8  9 10 
## 37 25 13  3  4 
## 37 least connected regions:
## 1 2 5 6 7 8 13 16 18 21 22 28 31 33 34 40 42 44 45 46 48 49 50 54 57 59 62 63 65 73 74 76 77 78 80 81 82 with 6 links
## 4 most connected regions:
## 10 19 66 70 with 10 links</code></pre>
<p>Compare the neighborhood topologies.</p>
<div class="sourceCode" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb72-1"><a href="tuesday-november-8-2022.html#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>))</span>
<span id="cb72-2"><a href="tuesday-november-8-2022.html#cb72-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-3"><a href="tuesday-november-8-2022.html#cb72-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(sf<span class="sc">::</span><span class="fu">st_geometry</span>(PE.sf), <span class="at">border =</span> <span class="st">&quot;grey&quot;</span>)</span>
<span id="cb72-4"><a href="tuesday-november-8-2022.html#cb72-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(nbs, coords, <span class="at">add =</span> <span class="cn">TRUE</span>)</span>
<span id="cb72-5"><a href="tuesday-november-8-2022.html#cb72-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-6"><a href="tuesday-november-8-2022.html#cb72-6" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(sf<span class="sc">::</span><span class="fu">st_geometry</span>(PE.sf), <span class="at">border =</span> <span class="st">&quot;grey&quot;</span>)</span>
<span id="cb72-7"><a href="tuesday-november-8-2022.html#cb72-7" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(nbs2, coords, <span class="at">add =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<p>Create weight matrices for these alternative neighborhood definitions using the same <code>nb2listw()</code> function.</p>
<div class="sourceCode" id="cb73"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb73-1"><a href="tuesday-november-8-2022.html#cb73-1" aria-hidden="true" tabindex="-1"></a>wts2 <span class="ot">&lt;-</span> spdep<span class="sc">::</span><span class="fu">nb2listw</span>(nbs2)</span>
<span id="cb73-2"><a href="tuesday-november-8-2022.html#cb73-2" aria-hidden="true" tabindex="-1"></a>wts3 <span class="ot">&lt;-</span> spdep<span class="sc">::</span><span class="fu">nb2listw</span>(nbs3)</span></code></pre></div>
<p>You then compute Moran I for the variable percentage white (<code>WHITE</code>) with the <code>moran()</code> function. And you do it separately for the three different weight matrices.</p>
<div class="sourceCode" id="cb74"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb74-1"><a href="tuesday-november-8-2022.html#cb74-1" aria-hidden="true" tabindex="-1"></a>spdep<span class="sc">::</span><span class="fu">moran</span>(PE.sf<span class="sc">$</span>WHITE,</span>
<span id="cb74-2"><a href="tuesday-november-8-2022.html#cb74-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">listw =</span> wts,</span>
<span id="cb74-3"><a href="tuesday-november-8-2022.html#cb74-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">n =</span> <span class="fu">length</span>(nbs),</span>
<span id="cb74-4"><a href="tuesday-november-8-2022.html#cb74-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">S0 =</span> spdep<span class="sc">::</span><span class="fu">Szero</span>(wts))</span></code></pre></div>
<pre><code>## $I
## [1] 0.5634778
## 
## $K
## [1] 2.300738</code></pre>
<div class="sourceCode" id="cb76"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb76-1"><a href="tuesday-november-8-2022.html#cb76-1" aria-hidden="true" tabindex="-1"></a>spdep<span class="sc">::</span><span class="fu">moran</span>(PE.sf<span class="sc">$</span>WHITE,</span>
<span id="cb76-2"><a href="tuesday-november-8-2022.html#cb76-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">listw =</span> wts2,</span>
<span id="cb76-3"><a href="tuesday-november-8-2022.html#cb76-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">n =</span> <span class="fu">length</span>(nbs2),</span>
<span id="cb76-4"><a href="tuesday-november-8-2022.html#cb76-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">S0 =</span> spdep<span class="sc">::</span><span class="fu">Szero</span>(wts2))</span></code></pre></div>
<pre><code>## $I
## [1] 0.5506132
## 
## $K
## [1] 2.300738</code></pre>
<div class="sourceCode" id="cb78"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb78-1"><a href="tuesday-november-8-2022.html#cb78-1" aria-hidden="true" tabindex="-1"></a>spdep<span class="sc">::</span><span class="fu">moran</span>(PE.sf<span class="sc">$</span>WHITE,</span>
<span id="cb78-2"><a href="tuesday-november-8-2022.html#cb78-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">listw =</span> wts3,</span>
<span id="cb78-3"><a href="tuesday-november-8-2022.html#cb78-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">n =</span> <span class="fu">length</span>(nbs3),</span>
<span id="cb78-4"><a href="tuesday-november-8-2022.html#cb78-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">S0 =</span> spdep<span class="sc">::</span><span class="fu">Szero</span>(wts3))</span></code></pre></div>
<pre><code>## $I
## [1] 0.5592557
## 
## $K
## [1] 2.300738</code></pre>
<p>Values of Moran I are constrained between -1 and +1. In this case the neighborhood definition has little impact on inferences made about spatial autocorrelation. The kurtosis is between 2 and 4 consistent with a set of values from a normal distribution.</p>
<p>In a similar way you compute Geary’s c statistic.</p>
<div class="sourceCode" id="cb80"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb80-1"><a href="tuesday-november-8-2022.html#cb80-1" aria-hidden="true" tabindex="-1"></a>spdep<span class="sc">::</span><span class="fu">geary</span>(PE.sf<span class="sc">$</span>WHITE, </span>
<span id="cb80-2"><a href="tuesday-november-8-2022.html#cb80-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">listw =</span> wts,</span>
<span id="cb80-3"><a href="tuesday-november-8-2022.html#cb80-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">n =</span> <span class="fu">length</span>(nbs), </span>
<span id="cb80-4"><a href="tuesday-november-8-2022.html#cb80-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">S0 =</span> spdep<span class="sc">::</span><span class="fu">Szero</span>(wts), </span>
<span id="cb80-5"><a href="tuesday-november-8-2022.html#cb80-5" aria-hidden="true" tabindex="-1"></a>             <span class="at">n1 =</span> <span class="fu">length</span>(nbs) <span class="sc">-</span> <span class="dv">1</span>)</span></code></pre></div>
<pre><code>## $C
## [1] 0.4123818
## 
## $K
## [1] 2.300738</code></pre>
<p>Values of Geary’s c are between 0 and 2 with values less than one indicating positive autocorrelation. If the interpretation on the amount of spatial autocorrelation based on Geary’s c is different than the interpretation on the amount of autocorrelation based on Moran I then it is a good idea to examine local variations in autocorrelation.</p>
<p>Finally, recall that to create a Moran scatter plot. You first assign to <code>white</code> the percentage of whites in each county (variable <code>WHITE</code>) and to <code>Wwhite</code> the spatial lagged value of percentage of whites. You then use <code>ggplot()</code> as follows.</p>
<div class="sourceCode" id="cb82"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb82-1"><a href="tuesday-november-8-2022.html#cb82-1" aria-hidden="true" tabindex="-1"></a>white <span class="ot">&lt;-</span> PE.sf<span class="sc">$</span>WHITE</span>
<span id="cb82-2"><a href="tuesday-november-8-2022.html#cb82-2" aria-hidden="true" tabindex="-1"></a>Wwhite <span class="ot">&lt;-</span> spdep<span class="sc">::</span><span class="fu">lag.listw</span>(wts, </span>
<span id="cb82-3"><a href="tuesday-november-8-2022.html#cb82-3" aria-hidden="true" tabindex="-1"></a>                           white)</span>
<span id="cb82-4"><a href="tuesday-november-8-2022.html#cb82-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb82-5"><a href="tuesday-november-8-2022.html#cb82-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb82-6"><a href="tuesday-november-8-2022.html#cb82-6" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>(white, Wwhite) <span class="sc">|&gt;</span></span>
<span id="cb82-7"><a href="tuesday-november-8-2022.html#cb82-7" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> white, <span class="at">y =</span> Wwhite)) <span class="sc">+</span> </span>
<span id="cb82-8"><a href="tuesday-november-8-2022.html#cb82-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb82-9"><a href="tuesday-november-8-2022.html#cb82-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> lm) <span class="sc">+</span></span>
<span id="cb82-10"><a href="tuesday-november-8-2022.html#cb82-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">100</span>)) <span class="sc">+</span></span>
<span id="cb82-11"><a href="tuesday-november-8-2022.html#cb82-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">100</span>)) <span class="sc">+</span></span>
<span id="cb82-12"><a href="tuesday-november-8-2022.html#cb82-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;% White&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;Avg of % White in the Neighborhood</span><span class="sc">\n</span><span class="st">(Spatial Lag)&quot;</span>) <span class="sc">+</span></span>
<span id="cb82-13"><a href="tuesday-november-8-2022.html#cb82-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<p><img src="QG-2022_files/figure-html/unnamed-chunk-39-1.png" width="672" /></p>
<p>The line is the best-fit linear regression of <code>Wwhite</code> onto <code>white</code> and it’s slope is equal to the value of Moran I. This is true regardless of the neighborhood definition.</p>
<div class="sourceCode" id="cb84"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb84-1"><a href="tuesday-november-8-2022.html#cb84-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(Wwhite <span class="sc">~</span> white)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Wwhite ~ white)
## 
## Coefficients:
## (Intercept)        white  
##     27.2333       0.5635</code></pre>
<p>You test for significant spatial autocorrelation with the <code>moran.test()</code> function.</p>
<div class="sourceCode" id="cb86"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb86-1"><a href="tuesday-november-8-2022.html#cb86-1" aria-hidden="true" tabindex="-1"></a>spdep<span class="sc">::</span><span class="fu">moran.test</span>(white, </span>
<span id="cb86-2"><a href="tuesday-november-8-2022.html#cb86-2" aria-hidden="true" tabindex="-1"></a>                  <span class="at">listw =</span> wts)</span></code></pre></div>
<pre><code>## 
##  Moran I test under randomisation
## 
## data:  white  
## weights: wts    
## 
## Moran I statistic standard deviate = 8.5089, p-value &lt; 2.2e-16
## alternative hypothesis: greater
## sample estimates:
## Moran I statistic       Expectation          Variance 
##       0.563477779      -0.012345679       0.004579648</code></pre>
<p>You see that the value of .56 is much larger than the expected value under the null hypothesis of no autocorrelation (-.012 = -1/(n-1)).</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="thursday-november-3-2022.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
