<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Tuesday, November 1, 2022 | GEO5156: Quantitative Geography</title>
  <meta name="description" content="Tuesday, November 1, 2022 | GEO5156: Quantitative Geography" />
  <meta name="generator" content="bookdown 0.24 and GitBook 2.6.7" />

  <meta property="og:title" content="Tuesday, November 1, 2022 | GEO5156: Quantitative Geography" />
  <meta property="og:type" content="book" />
  
  
  
  <meta name="github-repo" content="jelsner/QG-2022" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Tuesday, November 1, 2022 | GEO5156: Quantitative Geography" />
  
  
  

<meta name="author" content="James B. Elsner" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="thursday-october-30-2022.html"/>

<script src="libs/header-attrs-2.11/header-attrs.js"></script>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Quantitative Geography</a></li>

<li class="divider"></li>
<li><a href="index.html#section"></a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html"><i class="fa fa-check"></i>Syllabus</a>
<ul>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#geo5165c-quantitative-geography"><i class="fa fa-check"></i>GEO5165C: Quantitative Geography</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#contact-information"><i class="fa fa-check"></i>Contact information</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#course-description"><i class="fa fa-check"></i>Course description</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#expected-learning-outcomes"><i class="fa fa-check"></i>Expected learning outcomes</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#materials"><i class="fa fa-check"></i>Materials</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#class-meetings"><i class="fa fa-check"></i>Class meetings</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#grades"><i class="fa fa-check"></i>Grades</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#academic-honor-code"><i class="fa fa-check"></i>Academic honor code</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#students-with-disabilities-act"><i class="fa fa-check"></i>Students With Disabilities Act</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#inclusiveness"><i class="fa fa-check"></i>Inclusiveness</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#more-about-your-instructor"><i class="fa fa-check"></i>More about your instructor</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#syllabus-change-policy"><i class="fa fa-check"></i>Syllabus change policy</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#schedule-subject-to-change-with-notice"><i class="fa fa-check"></i>Schedule (subject to change with notice)</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#other-materials-to-check-out"><i class="fa fa-check"></i>Other materials to check out</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#julia-programming-language"><i class="fa fa-check"></i>Julia programming language</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html"><i class="fa fa-check"></i>Tuesday, August 23, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#today"><i class="fa fa-check"></i>Today</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#what-is-this-course"><i class="fa fa-check"></i>What is this course?</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#where-are-the-materials-for-this-course"><i class="fa fa-check"></i>Where are the materials for this course?</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#join-rstudio-cloud"><i class="fa fa-check"></i>Join RStudio Cloud</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#examples"><i class="fa fa-check"></i>Examples</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#course-syllabus"><i class="fa fa-check"></i>Course Syllabus</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#tallahassee-daily-temperatures"><i class="fa fa-check"></i>Tallahassee daily temperatures</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html"><i class="fa fa-check"></i>Thursday, August 25, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#today-1"><i class="fa fa-check"></i>Today</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#data-analysis"><i class="fa fa-check"></i>Data Analysis</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#reproducibility"><i class="fa fa-check"></i>Reproducibility</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#communication"><i class="fa fa-check"></i>Communication</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#automation"><i class="fa fa-check"></i>Automation</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#the-r-programming-language"><i class="fa fa-check"></i>The R programming language</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#overview-of-this-course"><i class="fa fa-check"></i>Overview of this course</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#work-in-plain-text-using-r-markdown"><i class="fa fa-check"></i>Work in plain text, using R Markdown</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#visualizing-data"><i class="fa fa-check"></i>Visualizing data</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#a-code-template"><i class="fa fa-check"></i>A code template</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#the-code"><i class="fa fa-check"></i>The code</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#a-graphing-workflow"><i class="fa fa-check"></i>A graphing workflow</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#a-graphing-template"><i class="fa fa-check"></i>A graphing template</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#common-problems"><i class="fa fa-check"></i>Common problems</a></li>
<li><a href="thursday-august-25-2022.html#location-of-the-sign">location of the <code>+</code> sign</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#help"><i class="fa fa-check"></i>help</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#things-to-know"><i class="fa fa-check"></i>Things to know</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#everything-has-a-name"><i class="fa fa-check"></i>Everything has a name</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#everything-is-an-object"><i class="fa fa-check"></i>Everything is an object</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#you-do-things-using-functions"><i class="fa fa-check"></i>You do things using functions</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#functions-come-in-packages-libraries"><i class="fa fa-check"></i>Functions come in packages (libraries)</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#your-turn"><i class="fa fa-check"></i>Your turn</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html"><i class="fa fa-check"></i>Tuesday, August 30, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html#today-2"><i class="fa fa-check"></i>Today</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html#scatter-plots"><i class="fa fa-check"></i>Scatter plots</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html#facets"><i class="fa fa-check"></i>Facets</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html#calculations"><i class="fa fa-check"></i>Calculations</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html#functions"><i class="fa fa-check"></i>Functions</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html#syntax-is-important"><i class="fa fa-check"></i>Syntax is important</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html#saving-an-object"><i class="fa fa-check"></i>Saving an object</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html#object-names"><i class="fa fa-check"></i>Object names</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html#entering-data"><i class="fa fa-check"></i>Entering data</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html#applying-a-function"><i class="fa fa-check"></i>Applying a function</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html#averge"><i class="fa fa-check"></i>Averge</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html#data-vectors"><i class="fa fa-check"></i>Data vectors</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html#variance"><i class="fa fa-check"></i>Variance</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html#data-vectors-have-a-type"><i class="fa fa-check"></i>Data vectors have a type</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html#working-smarter"><i class="fa fa-check"></i>Working smarter</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-september-1-2022.html"><a href="thursday-september-1-2022.html"><i class="fa fa-check"></i>Thursday, September 1, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-september-1-2022.html"><a href="thursday-september-1-2022.html#today-3"><i class="fa fa-check"></i>Today</a></li>
<li class="chapter" data-level="" data-path="thursday-september-1-2022.html"><a href="thursday-september-1-2022.html#data-as-vectors"><i class="fa fa-check"></i>Data as vectors</a></li>
<li class="chapter" data-level="" data-path="thursday-september-1-2022.html"><a href="thursday-september-1-2022.html#mean"><i class="fa fa-check"></i>Mean</a></li>
<li class="chapter" data-level="" data-path="thursday-september-1-2022.html"><a href="thursday-september-1-2022.html#variance-1"><i class="fa fa-check"></i>Variance</a></li>
<li class="chapter" data-level="" data-path="thursday-september-1-2022.html"><a href="thursday-september-1-2022.html#median"><i class="fa fa-check"></i>Median</a></li>
<li class="chapter" data-level="" data-path="thursday-september-1-2022.html"><a href="thursday-september-1-2022.html#spread"><i class="fa fa-check"></i>Spread</a></li>
<li class="chapter" data-level="" data-path="thursday-september-1-2022.html"><a href="thursday-september-1-2022.html#vector-types"><i class="fa fa-check"></i>Vector types</a></li>
<li class="chapter" data-level="" data-path="thursday-september-1-2022.html"><a href="thursday-september-1-2022.html#structured-data"><i class="fa fa-check"></i>Structured data</a></li>
<li class="chapter" data-level="" data-path="thursday-september-1-2022.html"><a href="thursday-september-1-2022.html#asking-questions"><i class="fa fa-check"></i>Asking questions</a></li>
<li class="chapter" data-level="" data-path="thursday-september-1-2022.html"><a href="thursday-september-1-2022.html#tables-and-summaries"><i class="fa fa-check"></i>Tables and summaries</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-september-6-2022.html"><a href="tuesday-september-6-2022.html"><i class="fa fa-check"></i>Tuesday, September 6, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-september-6-2022.html"><a href="tuesday-september-6-2022.html#today-4"><i class="fa fa-check"></i>Today</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-6-2022.html"><a href="tuesday-september-6-2022.html#getting-your-data-into-r"><i class="fa fa-check"></i>Getting your data into R</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-6-2022.html"><a href="tuesday-september-6-2022.html#creating-structured-data-files"><i class="fa fa-check"></i>Creating structured data files</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-6-2022.html"><a href="tuesday-september-6-2022.html#data-frames"><i class="fa fa-check"></i>Data frames</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-6-2022.html"><a href="tuesday-september-6-2022.html#quantiles"><i class="fa fa-check"></i>Quantiles</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-6-2022.html"><a href="tuesday-september-6-2022.html#creating-a-data-frame"><i class="fa fa-check"></i>Creating a data frame</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-6-2022.html"><a href="tuesday-september-6-2022.html#pipes"><i class="fa fa-check"></i>Pipes</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-6-2022.html"><a href="tuesday-september-6-2022.html#your-turn-1"><i class="fa fa-check"></i>Your turn</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-september-8-2022.html"><a href="thursday-september-8-2022.html"><i class="fa fa-check"></i>Thursday, September 8, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-september-8-2022.html"><a href="thursday-september-8-2022.html#today-5"><i class="fa fa-check"></i>Today</a></li>
<li class="chapter" data-level="" data-path="thursday-september-8-2022.html"><a href="thursday-september-8-2022.html#pipe-operator"><i class="fa fa-check"></i>Pipe operator</a></li>
<li class="chapter" data-level="" data-path="thursday-september-8-2022.html"><a href="thursday-september-8-2022.html#wrangling-data-frames"><i class="fa fa-check"></i>Wrangling data frames</a></li>
<li class="chapter" data-level="" data-path="thursday-september-8-2022.html"><a href="thursday-september-8-2022.html#selecting-and-filtering"><i class="fa fa-check"></i>Selecting and filtering</a></li>
<li class="chapter" data-level="" data-path="thursday-september-8-2022.html"><a href="thursday-september-8-2022.html#example-palmer-penguins"><i class="fa fa-check"></i>Example: Palmer penguins</a></li>
<li class="chapter" data-level="" data-path="thursday-september-8-2022.html"><a href="thursday-september-8-2022.html#stringing-functions-together"><i class="fa fa-check"></i>Stringing functions together</a></li>
<li class="chapter" data-level="" data-path="thursday-september-8-2022.html"><a href="thursday-september-8-2022.html#summarize"><i class="fa fa-check"></i>Summarize</a></li>
<li class="chapter" data-level="" data-path="thursday-september-8-2022.html"><a href="thursday-september-8-2022.html#grouping"><i class="fa fa-check"></i>Grouping</a></li>
<li class="chapter" data-level="" data-path="thursday-september-8-2022.html"><a href="thursday-september-8-2022.html#your-turn-2"><i class="fa fa-check"></i>Your turn</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-september-12-2022.html"><a href="tuesday-september-12-2022.html"><i class="fa fa-check"></i>Tuesday, September 12, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-september-12-2022.html"><a href="tuesday-september-12-2022.html#today-6"><i class="fa fa-check"></i>Today</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-12-2022.html"><a href="tuesday-september-12-2022.html#example-1-new-york-city-flight-data"><i class="fa fa-check"></i>Example 1: New York City flight data</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-12-2022.html"><a href="tuesday-september-12-2022.html#example-2-daily-weather-data-from-tallahassee"><i class="fa fa-check"></i>Example 2: Daily weather data from Tallahassee</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-12-2022.html"><a href="tuesday-september-12-2022.html#putting-everything-together"><i class="fa fa-check"></i>Putting everything together</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-12-2022.html"><a href="tuesday-september-12-2022.html#example-3-food-consumption-and-co2-emissions"><i class="fa fa-check"></i>Example 3: Food consumption and CO2 emissions</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-12-2022.html"><a href="tuesday-september-12-2022.html#summary"><i class="fa fa-check"></i>Summary</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-september-14-2022.html"><a href="thursday-september-14-2022.html"><i class="fa fa-check"></i>Thursday, September 14, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-september-14-2022.html"><a href="thursday-september-14-2022.html#today-7"><i class="fa fa-check"></i>Today</a></li>
<li class="chapter" data-level="" data-path="thursday-september-14-2022.html"><a href="thursday-september-14-2022.html#bar-chart"><i class="fa fa-check"></i>Bar chart</a></li>
<li class="chapter" data-level="" data-path="thursday-september-14-2022.html"><a href="thursday-september-14-2022.html#pie-preference"><i class="fa fa-check"></i>Pie preference</a></li>
<li class="chapter" data-level="" data-path="thursday-september-14-2022.html"><a href="thursday-september-14-2022.html#histogram"><i class="fa fa-check"></i>Histogram</a></li>
<li class="chapter" data-level="" data-path="thursday-september-14-2022.html"><a href="thursday-september-14-2022.html#density-plot"><i class="fa fa-check"></i>Density plot</a></li>
<li class="chapter" data-level="" data-path="thursday-september-14-2022.html"><a href="thursday-september-14-2022.html#box-plot"><i class="fa fa-check"></i>Box plot</a></li>
<li class="chapter" data-level="" data-path="thursday-september-14-2022.html"><a href="thursday-september-14-2022.html#side-by-side-box-plots"><i class="fa fa-check"></i>Side-by-side box plots</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-september-19-2022.html"><a href="tuesday-september-19-2022.html"><i class="fa fa-check"></i>Tuesday, September 19, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-september-19-2022.html"><a href="tuesday-september-19-2022.html#today-8"><i class="fa fa-check"></i>Today</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-19-2022.html"><a href="tuesday-september-19-2022.html#comparing-distributions"><i class="fa fa-check"></i>Comparing distributions</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-19-2022.html"><a href="tuesday-september-19-2022.html#box-plots"><i class="fa fa-check"></i>Box plots</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-19-2022.html"><a href="tuesday-september-19-2022.html#long-data-frames"><i class="fa fa-check"></i>Long data frames</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-19-2022.html"><a href="tuesday-september-19-2022.html#scatter-plots-1"><i class="fa fa-check"></i>Scatter plots</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-19-2022.html"><a href="tuesday-september-19-2022.html#facets-1"><i class="fa fa-check"></i>Facets</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-19-2022.html"><a href="tuesday-september-19-2022.html#example-palmer-penguins-1"><i class="fa fa-check"></i>Example: Palmer penguins</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-19-2022.html"><a href="tuesday-september-19-2022.html#an-expository-graph"><i class="fa fa-check"></i>An expository graph</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-19-2022.html"><a href="tuesday-september-19-2022.html#exporting-your-graph"><i class="fa fa-check"></i>Exporting your graph</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-september-21-2022.html"><a href="thursday-september-21-2022.html"><i class="fa fa-check"></i>Thursday, September 21, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-september-21-2022.html"><a href="thursday-september-21-2022.html#today-9"><i class="fa fa-check"></i>Today</a></li>
<li class="chapter" data-level="" data-path="thursday-september-21-2022.html"><a href="thursday-september-21-2022.html#simple-feature-data-frames"><i class="fa fa-check"></i>Simple feature data frames</a></li>
<li class="chapter" data-level="" data-path="thursday-september-21-2022.html"><a href="thursday-september-21-2022.html#making-a-boundary-map"><i class="fa fa-check"></i>Making a boundary map</a></li>
<li class="chapter" data-level="" data-path="thursday-september-21-2022.html"><a href="thursday-september-21-2022.html#fills"><i class="fa fa-check"></i>Fills</a></li>
<li class="chapter" data-level="" data-path="thursday-september-21-2022.html"><a href="thursday-september-21-2022.html#adding-data"><i class="fa fa-check"></i>Adding data</a></li>
<li class="chapter" data-level="" data-path="thursday-september-21-2022.html"><a href="thursday-september-21-2022.html#inset-maps"><i class="fa fa-check"></i>Inset maps</a></li>
<li class="chapter" data-level="" data-path="thursday-september-21-2022.html"><a href="thursday-september-21-2022.html#map-projections"><i class="fa fa-check"></i>Map projections</a></li>
<li class="chapter" data-level="" data-path="thursday-september-21-2022.html"><a href="thursday-september-21-2022.html#bivariate-maps"><i class="fa fa-check"></i>Bivariate maps</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-september-21-2022-1.html"><a href="thursday-september-21-2022-1.html"><i class="fa fa-check"></i>Thursday, September 21, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-september-21-2022-1.html"><a href="thursday-september-21-2022-1.html#today-10"><i class="fa fa-check"></i>Today</a></li>
<li class="chapter" data-level="" data-path="thursday-september-21-2022-1.html"><a href="thursday-september-21-2022-1.html#making-maps-using-functions-from-the-tmap-package"><i class="fa fa-check"></i>Making maps using functions from the {tmap} package</a></li>
<li class="chapter" data-level="" data-path="thursday-september-21-2022-1.html"><a href="thursday-september-21-2022-1.html#example-mapping-tornadoes"><i class="fa fa-check"></i>Example: Mapping tornadoes</a></li>
<li class="chapter" data-level="" data-path="thursday-september-21-2022-1.html"><a href="thursday-september-21-2022-1.html#example-mapping-the-frequency-of-tornadoes-by-state"><i class="fa fa-check"></i>Example: Mapping the frequency of tornadoes by state</a></li>
<li class="chapter" data-level="" data-path="thursday-september-21-2022-1.html"><a href="thursday-september-21-2022-1.html#calculations-using-the-geometry-simple-feature-column"><i class="fa fa-check"></i>Calculations using the geometry simple feature column</a></li>
<li class="chapter" data-level="" data-path="thursday-september-21-2022-1.html"><a href="thursday-september-21-2022-1.html#making-raster-maps"><i class="fa fa-check"></i>Making raster maps</a></li>
<li class="chapter" data-level="" data-path="thursday-september-21-2022-1.html"><a href="thursday-september-21-2022-1.html#get-map-images-using-functions-from-the-ggmap-package"><i class="fa fa-check"></i>Get map images using functions from the {ggmap} package</a></li>
<li class="chapter" data-level="" data-path="thursday-september-21-2022-1.html"><a href="thursday-september-21-2022-1.html#add-data-to-the-raster-map"><i class="fa fa-check"></i>Add data to the raster map</a></li>
<li class="chapter" data-level="" data-path="thursday-september-21-2022-1.html"><a href="thursday-september-21-2022-1.html#spatial-density-maps-extra-material"><i class="fa fa-check"></i>Spatial density maps (extra material)</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-september-26-2022.html"><a href="tuesday-september-26-2022.html"><i class="fa fa-check"></i>Tuesday, September 26, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-september-26-2022.html"><a href="tuesday-september-26-2022.html#today-11"><i class="fa fa-check"></i>Today</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-26-2022.html"><a href="tuesday-september-26-2022.html#one-sample-test-of-the-population-mean"><i class="fa fa-check"></i>One-sample test of the population mean</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-26-2022.html"><a href="tuesday-september-26-2022.html#about-p-values"><i class="fa fa-check"></i>About p-values</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-26-2022.html"><a href="tuesday-september-26-2022.html#example-strongest-atlantic-hurricanes"><i class="fa fa-check"></i>Example: Strongest Atlantic hurricanes</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-26-2022.html"><a href="tuesday-september-26-2022.html#graphical-inference"><i class="fa fa-check"></i>Graphical inference</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-26-2022.html"><a href="tuesday-september-26-2022.html#two-sample-test-of-the-difference-in-population-means"><i class="fa fa-check"></i>Two-sample test of the difference in population means</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-26-2022.html"><a href="tuesday-september-26-2022.html#example-hurricanes-in-the-north-atlantic-and-the-eastern-north-pacific"><i class="fa fa-check"></i>Example: hurricanes in the North Atlantic and the eastern North Pacific</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-26-2022.html"><a href="tuesday-september-26-2022.html#example-palmer-penguins-2"><i class="fa fa-check"></i>Example: Palmer penguins</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-26-2022.html"><a href="tuesday-september-26-2022.html#your-turn-3"><i class="fa fa-check"></i>Your turn</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-26-2022.html"><a href="tuesday-september-26-2022.html#test-of-equal-variance"><i class="fa fa-check"></i>Test of equal variance</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-26-2022.html"><a href="tuesday-september-26-2022.html#wilcoxon-mann-whitney-u-non-parameteric-test-of-difference-in-means"><i class="fa fa-check"></i>Wilcoxon (Mann-Whitney U) non-parameteric test of difference in means</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-september-28-2022.html"><a href="thursday-september-28-2022.html"><i class="fa fa-check"></i>Thursday, September 28, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-september-28-2022.html"><a href="thursday-september-28-2022.html#today-12"><i class="fa fa-check"></i>Today</a></li>
<li class="chapter" data-level="" data-path="thursday-september-28-2022.html"><a href="thursday-september-28-2022.html#review"><i class="fa fa-check"></i>Review</a></li>
<li class="chapter" data-level="" data-path="thursday-september-28-2022.html"><a href="thursday-september-28-2022.html#paired-observations"><i class="fa fa-check"></i>Paired observations</a></li>
<li class="chapter" data-level="" data-path="thursday-september-28-2022.html"><a href="thursday-september-28-2022.html#example-reaction-time-while-driving"><i class="fa fa-check"></i>Example: Reaction time while driving</a></li>
<li class="chapter" data-level="" data-path="thursday-september-28-2022.html"><a href="thursday-september-28-2022.html#chi-squared-test-for-independence"><i class="fa fa-check"></i>Chi-squared test for independence</a></li>
<li class="chapter" data-level="" data-path="thursday-september-28-2022.html"><a href="thursday-september-28-2022.html#example-smoking-and-exercise"><i class="fa fa-check"></i>Example: Smoking and exercise</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-october-3-2022.html"><a href="tuesday-october-3-2022.html"><i class="fa fa-check"></i>Tuesday, October 3, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-october-3-2022.html"><a href="tuesday-october-3-2022.html#today-13"><i class="fa fa-check"></i>Today</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-3-2022.html"><a href="tuesday-october-3-2022.html#distributions"><i class="fa fa-check"></i>Distributions</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-3-2022.html"><a href="tuesday-october-3-2022.html#normal-distribution"><i class="fa fa-check"></i>Normal distribution</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-3-2022.html"><a href="tuesday-october-3-2022.html#uniform-distribution"><i class="fa fa-check"></i>Uniform distribution</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-3-2022.html"><a href="tuesday-october-3-2022.html#how-many-blue-marbles"><i class="fa fa-check"></i>How many blue marbles?</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-3-2022.html"><a href="tuesday-october-3-2022.html#what-percentage-of-the-globe-is-covered-by-water"><i class="fa fa-check"></i>What percentage of the globe is covered by water?</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-3-2022.html"><a href="tuesday-october-3-2022.html#how-many-fish-are-in-the-lake"><i class="fa fa-check"></i>How many fish are in the lake?</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-october-5-2022.html"><a href="thursday-october-5-2022.html"><i class="fa fa-check"></i>Thursday, October 5, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-october-5-2022.html"><a href="thursday-october-5-2022.html#today-14"><i class="fa fa-check"></i>Today</a></li>
<li class="chapter" data-level="" data-path="thursday-october-5-2022.html"><a href="thursday-october-5-2022.html#how-many-fish-are-in-the-lake-1"><i class="fa fa-check"></i>How many fish are in the lake?</a></li>
<li class="chapter" data-level="" data-path="thursday-october-5-2022.html"><a href="thursday-october-5-2022.html#percentage-of-survey-signups"><i class="fa fa-check"></i>Percentage of survey signups</a></li>
<li class="chapter" data-level="" data-path="thursday-october-5-2022.html"><a href="thursday-october-5-2022.html#a-generative-model-for-people-agreeing-to-take-your-survey"><i class="fa fa-check"></i>A generative model for people agreeing to take your survey</a></li>
<li class="chapter" data-level="" data-path="thursday-october-5-2022.html"><a href="thursday-october-5-2022.html#prior-for-the-response-rate"><i class="fa fa-check"></i>Prior for the response rate</a></li>
<li class="chapter" data-level="" data-path="thursday-october-5-2022.html"><a href="thursday-october-5-2022.html#define-the-generative-model-and-simulate-the-data"><i class="fa fa-check"></i>Define the generative model and simulate the data</a></li>
<li class="chapter" data-level="" data-path="thursday-october-5-2022.html"><a href="thursday-october-5-2022.html#prediction"><i class="fa fa-check"></i>Prediction</a></li>
<li class="chapter" data-level="" data-path="thursday-october-5-2022.html"><a href="thursday-october-5-2022.html#approximate-bayesian-computation"><i class="fa fa-check"></i>Approximate Bayesian computation</a></li>
<li class="chapter" data-level="" data-path="thursday-october-5-2022.html"><a href="thursday-october-5-2022.html#what-bayesian-data-analysis-is-not"><i class="fa fa-check"></i>What Bayesian data analysis is not</a></li>
<li class="chapter" data-level="" data-path="thursday-october-5-2022.html"><a href="thursday-october-5-2022.html#comparing-two-hypotheses"><i class="fa fa-check"></i>Comparing two hypotheses</a></li>
<li class="chapter" data-level="" data-path="thursday-october-5-2022.html"><a href="thursday-october-5-2022.html#reaction-times-while-driving"><i class="fa fa-check"></i>Reaction times while driving</a></li>
<li class="chapter" data-level="" data-path="thursday-october-5-2022.html"><a href="thursday-october-5-2022.html#repeat-the-survey-example"><i class="fa fa-check"></i>Repeat the survey example</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-october-12-2022.html"><a href="tuesday-october-12-2022.html"><i class="fa fa-check"></i>Tuesday, October 12, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-october-12-2022.html"><a href="tuesday-october-12-2022.html#today-15"><i class="fa fa-check"></i>Today</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-12-2022.html"><a href="tuesday-october-12-2022.html#linear-regression-a-t-test-by-another-name"><i class="fa fa-check"></i>Linear regression: A t test by another name</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-12-2022.html"><a href="tuesday-october-12-2022.html#motivating-regression"><i class="fa fa-check"></i>Motivating regression</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-12-2022.html"><a href="tuesday-october-12-2022.html#eyeballing-the-regression"><i class="fa fa-check"></i>Eyeballing the regression</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-12-2022.html"><a href="tuesday-october-12-2022.html#example-increasing-heart-rates-with-age"><i class="fa fa-check"></i>Example: Increasing heart rates with age</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-12-2022.html"><a href="tuesday-october-12-2022.html#making-predictions-with-regression"><i class="fa fa-check"></i>Making predictions with regression</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-12-2022.html"><a href="tuesday-october-12-2022.html#uncertainty-about-the-regression-coefficients"><i class="fa fa-check"></i>Uncertainty about the regression coefficients</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-12-2022.html"><a href="tuesday-october-12-2022.html#bootstrapping-the-uncertainty"><i class="fa fa-check"></i>Bootstrapping the uncertainty</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-12-2022.html"><a href="tuesday-october-12-2022.html#predictive-uncertainty"><i class="fa fa-check"></i>Predictive uncertainty</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-october-14-2022.html"><a href="thursday-october-14-2022.html"><i class="fa fa-check"></i>Thursday, October 14, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-october-14-2022.html"><a href="thursday-october-14-2022.html#today-16"><i class="fa fa-check"></i>Today</a></li>
<li class="chapter" data-level="" data-path="thursday-october-14-2022.html"><a href="thursday-october-14-2022.html#uncertainty-about-a-particular-predicted-value"><i class="fa fa-check"></i>Uncertainty about a particular predicted value</a></li>
<li class="chapter" data-level="" data-path="thursday-october-14-2022.html"><a href="thursday-october-14-2022.html#example-predicting-body-mass-from-fipper-length"><i class="fa fa-check"></i>Example: Predicting body mass from fipper length</a></li>
<li class="chapter" data-level="" data-path="thursday-october-14-2022.html"><a href="thursday-october-14-2022.html#model-adequacy"><i class="fa fa-check"></i>Model Adequacy</a></li>
<li class="chapter" data-level="" data-path="thursday-october-14-2022.html"><a href="thursday-october-14-2022.html#transforming-the-response-variable"><i class="fa fa-check"></i>Transforming the response variable</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-october-19-2022.html"><a href="tuesday-october-19-2022.html"><i class="fa fa-check"></i>Tuesday, October 19, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-october-19-2022.html"><a href="tuesday-october-19-2022.html#today-17"><i class="fa fa-check"></i>Today</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-19-2022.html"><a href="tuesday-october-19-2022.html#example-average-income-vs-percent-college-graduates-at-the-state-level"><i class="fa fa-check"></i>Example: Average income vs percent college graduates at the state level</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-19-2022.html"><a href="tuesday-october-19-2022.html#outliers"><i class="fa fa-check"></i>Outliers</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-19-2022.html"><a href="tuesday-october-19-2022.html#summarizing"><i class="fa fa-check"></i>Summarizing</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-19-2022.html"><a href="tuesday-october-19-2022.html#example-a-regression-model-for-trend"><i class="fa fa-check"></i>Example: A regression model for trend</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-19-2022.html"><a href="tuesday-october-19-2022.html#simpsons-paradox"><i class="fa fa-check"></i>Simpson’s paradox</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-october-21-2022.html"><a href="thursday-october-21-2022.html"><i class="fa fa-check"></i>Thursday, October 21, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-october-21-2022.html"><a href="thursday-october-21-2022.html#today-18"><i class="fa fa-check"></i>Today</a></li>
<li class="chapter" data-level="" data-path="thursday-october-21-2022.html"><a href="thursday-october-21-2022.html#multiple-variable-linear-regression"><i class="fa fa-check"></i>Multiple variable linear regression</a></li>
<li class="chapter" data-level="" data-path="thursday-october-21-2022.html"><a href="thursday-october-21-2022.html#a-grid-of-scatter-plots"><i class="fa fa-check"></i>A grid of scatter plots</a></li>
<li class="chapter" data-level="" data-path="thursday-october-21-2022.html"><a href="thursday-october-21-2022.html#fit-a-multiple-variable-regression-model"><i class="fa fa-check"></i>Fit a multiple variable regression model</a></li>
<li class="chapter" data-level="" data-path="thursday-october-21-2022.html"><a href="thursday-october-21-2022.html#should-you-remove-a-variable-from-the-model"><i class="fa fa-check"></i>Should you remove a variable from the model?</a></li>
<li class="chapter" data-level="" data-path="thursday-october-21-2022.html"><a href="thursday-october-21-2022.html#checking-on-the-model-assumptions"><i class="fa fa-check"></i>Checking on the model assumptions</a></li>
<li class="chapter" data-level="" data-path="thursday-october-21-2022.html"><a href="thursday-october-21-2022.html#example-predicting-house-prices"><i class="fa fa-check"></i>Example: Predicting house prices</a></li>
<li class="chapter" data-level="" data-path="thursday-october-21-2022.html"><a href="thursday-october-21-2022.html#collinearity"><i class="fa fa-check"></i>Collinearity</a></li>
<li class="chapter" data-level="" data-path="thursday-october-21-2022.html"><a href="thursday-october-21-2022.html#interactions"><i class="fa fa-check"></i>Interactions</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-october-28-2022.html"><a href="tuesday-october-28-2022.html"><i class="fa fa-check"></i>Tuesday, October 28, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-october-28-2022.html"><a href="tuesday-october-28-2022.html#today-19"><i class="fa fa-check"></i>Today</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-28-2022.html"><a href="tuesday-october-28-2022.html#removing-variables-from-a-model"><i class="fa fa-check"></i>Removing variables from a model</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-28-2022.html"><a href="tuesday-october-28-2022.html#the-stepwise-regression-procedure"><i class="fa fa-check"></i>The stepwise regression procedure</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-28-2022.html"><a href="tuesday-october-28-2022.html#transforming-a-response-variable"><i class="fa fa-check"></i>Transforming a response variable</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-28-2022.html"><a href="tuesday-october-28-2022.html#regression-trees"><i class="fa fa-check"></i>Regression trees</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-october-30-2022.html"><a href="thursday-october-30-2022.html"><i class="fa fa-check"></i>Thursday, October 30, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-october-30-2022.html"><a href="thursday-october-30-2022.html#today-20"><i class="fa fa-check"></i>Today</a></li>
<li class="chapter" data-level="" data-path="thursday-october-30-2022.html"><a href="thursday-october-30-2022.html#regression-tree-example"><i class="fa fa-check"></i>Regression tree example</a></li>
<li class="chapter" data-level="" data-path="thursday-october-30-2022.html"><a href="thursday-october-30-2022.html#predictive-uncertainty-1"><i class="fa fa-check"></i>Predictive uncertainty</a></li>
<li class="chapter" data-level="" data-path="thursday-october-30-2022.html"><a href="thursday-october-30-2022.html#random-forest-algorithm"><i class="fa fa-check"></i>Random forest algorithm</a></li>
<li class="chapter" data-level="" data-path="thursday-october-30-2022.html"><a href="thursday-october-30-2022.html#cross-validation"><i class="fa fa-check"></i>Cross validation</a></li>
<li class="chapter" data-level="" data-path="thursday-october-30-2022.html"><a href="thursday-october-30-2022.html#classification-trees"><i class="fa fa-check"></i>Classification trees</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-november-1-2022.html"><a href="tuesday-november-1-2022.html"><i class="fa fa-check"></i>Tuesday, November 1, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-november-1-2022.html"><a href="tuesday-november-1-2022.html#today-21"><i class="fa fa-check"></i>Today</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-1-2022.html"><a href="tuesday-november-1-2022.html#binary-outcomes-and-probabilities"><i class="fa fa-check"></i>Binary outcomes and probabilities</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-1-2022.html"><a href="tuesday-november-1-2022.html#logistic-regression"><i class="fa fa-check"></i>Logistic regression</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-1-2022.html"><a href="tuesday-november-1-2022.html#example-who-survives-in-the-donner-party"><i class="fa fa-check"></i>Example: Who survives in the Donner Party?</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-1-2022.html"><a href="tuesday-november-1-2022.html#example-probability-of-rocket-damage-on-liftoff"><i class="fa fa-check"></i>Example: Probability of rocket damage on liftoff</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">GEO5156: Quantitative Geography</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="tuesday-november-1-2022" class="section level1 unnumbered">
<h1>Tuesday, November 1, 2022</h1>
<div id="today-21" class="section level2 unnumbered">
<h2>Today</h2>
<ul>
<li>logistic regression</li>
</ul>
<p>Linear regression is one of the most powerful tool in data science. But it’s utility is limited to response variables that can be approximated with a normal distribution.</p>
<p>When the response variable is binary (only two outcomes) a linear regression model should not be used.</p>
<p>Many scientific research questions involve binary outcomes, and there is often a need to predict the probability that something will happen. The probability you will get a virus.</p>
<p>Fortunately, with only a small modification to the linear regression model you can get a <em>logistic regression</em> model that describes how a binary response variable is related to a set of explanatory variables.</p>
<p>The mechanics of fitting a logistic regression model are the same as with fitting a linear regression. The model coefficients are determined using the <em>method of maximum likelihood</em>.</p>
<p>The method of maximum likelihood answers the question, what is the probability of our data given the model. A model that assigns the highest probability to our data is the model that is chosen.</p>
</div>
<div id="binary-outcomes-and-probabilities" class="section level2 unnumbered">
<h2>Binary outcomes and probabilities</h2>
<p>A key understanding here is that the <em>average value</em> over a set of binary responses is a number between 0 and 1. To see this, here we generate a set of random binary responses using the <code>rbinom()</code> function. <code>r</code> for random and <code>binom</code> for binomial distribution with a long-run probability of .2.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="tuesday-november-1-2022.html#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rbinom</span>(<span class="at">n =</span> <span class="dv">100</span>, </span>
<span id="cb1-2"><a href="tuesday-november-1-2022.html#cb1-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">size =</span> <span class="dv">1</span>, </span>
<span id="cb1-3"><a href="tuesday-november-1-2022.html#cb1-3" aria-hidden="true" tabindex="-1"></a>       <span class="at">prob =</span> .<span class="dv">2</span>)</span></code></pre></div>
<pre><code>##   [1] 0 0 0 1 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0
##  [38] 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0
##  [75] 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0 1 0 1 0 0</code></pre>
<p>The <code>n = 100</code> is the number of binary responses to generate, <code>size = 1</code> indicates two choices (<code>0</code> or <code>1</code>), and <code>prob = .2</code> is the long-run probability of getting a <code>1</code>.</p>
<p>If we say that an outcome of <code>1</code> is a success and that an outcome of <code>0</code> is a failure, then the average taken over all outcomes is the sample probability of success.</p>
<p>Here we compute averages over a samples of binary outcomes where the probability of a <code>1</code> (success) is .2, .5, and .9.</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="tuesday-november-1-2022.html#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(<span class="fu">rbinom</span>(<span class="at">n =</span> <span class="dv">100</span>, <span class="at">size =</span> <span class="dv">1</span>, <span class="at">prob =</span> .<span class="dv">2</span>))</span></code></pre></div>
<pre><code>## [1] 0.17</code></pre>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="tuesday-november-1-2022.html#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(<span class="fu">rbinom</span>(<span class="at">n =</span> <span class="dv">100</span>, <span class="at">size =</span> <span class="dv">1</span>, <span class="at">prob =</span> .<span class="dv">5</span>))</span></code></pre></div>
<pre><code>## [1] 0.48</code></pre>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="tuesday-november-1-2022.html#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(<span class="fu">rbinom</span>(<span class="at">n =</span> <span class="dv">100</span>, <span class="at">size =</span> <span class="dv">1</span>, <span class="at">prob =</span> .<span class="dv">9</span>))</span></code></pre></div>
<pre><code>## [1] 0.86</code></pre>
<p>Repeat. We see that the sample means are close to the long-run probabilities.</p>
<p>Recall that a regression model predicts the conditional mean values of the response variable. When the response variable is binary, the mean values are probabilities, so a logistic regression predicts the conditional probability of something happening. For example, the probability of getting COVID-19 given your social distancing and mask-wearing habits.</p>
<p>Probabilities are bounded between 0 and 1, but the linear regression line is not.</p>
<p>Example: Consider data collected from the recovered solid booster rockets of the 23 previous shuttle flights (before the Challenger Space Shuttle disaster in 1986). The temperature in F at launch time and whether there was (<code>1</code>) or was not (<code>0</code>) damage to the O-rings on the booster.</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="tuesday-november-1-2022.html#cb9-1" aria-hidden="true" tabindex="-1"></a>Temperature <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">66</span>, <span class="dv">70</span>, <span class="dv">69</span>, <span class="dv">68</span>, <span class="dv">67</span>, <span class="dv">72</span>, <span class="dv">73</span>, <span class="dv">70</span>, <span class="dv">57</span>, <span class="dv">63</span>, <span class="dv">70</span>, <span class="dv">78</span>, <span class="dv">67</span>, <span class="dv">53</span>, <span class="dv">67</span>, <span class="dv">75</span>, <span class="dv">70</span>, <span class="dv">81</span>, <span class="dv">76</span>, <span class="dv">79</span>, <span class="dv">75</span>, <span class="dv">76</span>, <span class="dv">58</span>)</span>
<span id="cb9-2"><a href="tuesday-november-1-2022.html#cb9-2" aria-hidden="true" tabindex="-1"></a>Damage <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">1</span>)</span></code></pre></div>
<p>The variable <code>Damage</code> is the response variable and <code>Temperature</code> is the explanatory variable.</p>
<p>We start with a scatter plot of these two variables along with the linear regression line.</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="tuesday-november-1-2022.html#cb10-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(Damage, Temperature)</span>
<span id="cb10-2"><a href="tuesday-november-1-2022.html#cb10-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-3"><a href="tuesday-november-1-2022.html#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb10-4"><a href="tuesday-november-1-2022.html#cb10-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-5"><a href="tuesday-november-1-2022.html#cb10-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> df, </span>
<span id="cb10-6"><a href="tuesday-november-1-2022.html#cb10-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> Temperature, <span class="at">y =</span> Damage)) <span class="sc">+</span></span>
<span id="cb10-7"><a href="tuesday-november-1-2022.html#cb10-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb10-8"><a href="tuesday-november-1-2022.html#cb10-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> lm, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb10-9"><a href="tuesday-november-1-2022.html#cb10-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>))</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<pre><code>## Warning: Removed 10 rows containing missing values (geom_smooth).</code></pre>
<p><img src="QG-2022_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<p>The plot shows more points at a value of 1 (at least some damage to the O-rings) when temperatures are lower and more more points at a value of 0 (no damage) when the temperatures are higher.</p>
<p>The linear regression line indicates this inverse relationship. The line slopes from upper left to lower right. We conclude that there is less chance of O-ring damage when temperatures are higher. But we note that the straight line does not capture this relationship very well.</p>
<p>We fit a linear regression model to these data.</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="tuesday-november-1-2022.html#cb13-1" aria-hidden="true" tabindex="-1"></a>lrm <span class="ot">&lt;-</span> <span class="fu">lm</span>(Damage <span class="sc">~</span> Temperature, </span>
<span id="cb13-2"><a href="tuesday-november-1-2022.html#cb13-2" aria-hidden="true" tabindex="-1"></a>          <span class="at">data =</span> df)</span>
<span id="cb13-3"><a href="tuesday-november-1-2022.html#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lrm)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Damage ~ Temperature, data = df)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.43762 -0.30679 -0.06381  0.17452  0.89881 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)   
## (Intercept)  2.90476    0.84208   3.450  0.00240 **
## Temperature -0.03738    0.01205  -3.103  0.00538 **
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.3987 on 21 degrees of freedom
## Multiple R-squared:  0.3144, Adjusted R-squared:  0.2818 
## F-statistic:  9.63 on 1 and 21 DF,  p-value: 0.005383</code></pre>
<p>The model diagnostics indicate temperature is significant in explaining O-ring damage.</p>
<p>Looking at the slope coefficient we can state that for every one degree F <em>decrease</em> in temperature the chance of damage increases by 3.7 percentage points.</p>
<p>We interpret the predicted damage as the probability of damage for a given temperature (conditional mean).</p>
<p>We use the <code>predict()</code> method to predict the probability of damage when the launch temperatures are 77 F, 65 F, and 51 F. We multiply the predicted mean values by 100 so that the probabilities are in percentages.</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="tuesday-november-1-2022.html#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(lrm, </span>
<span id="cb15-2"><a href="tuesday-november-1-2022.html#cb15-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">newdata =</span> <span class="fu">data.frame</span>(<span class="at">Temperature =</span> <span class="fu">c</span>(<span class="dv">77</span>, <span class="dv">65</span>, <span class="dv">51</span>))) <span class="sc">*</span> <span class="dv">100</span></span></code></pre></div>
<pre><code>##         1         2         3 
##  2.642857 47.500000 99.833333</code></pre>
<p>Predictions make sense. When the launch temperature is 77 F, the chance of O-ring damage is quite small (2.6%) but when the launch temperature is 51 F, the change of O-ring damage is quite large (99.8%).</p>
<p>Although this appears to be a reasonable prediction equation, it leads to nonsensical forecasts. For example, what does the linear regression model predict when the temperature is 85 F and when it is 45 F?</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="tuesday-november-1-2022.html#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(lrm, </span>
<span id="cb17-2"><a href="tuesday-november-1-2022.html#cb17-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">newdata =</span> <span class="fu">data.frame</span>(<span class="at">Temperature =</span> <span class="fu">c</span>(<span class="dv">85</span>, <span class="dv">45</span>))) <span class="sc">*</span> <span class="dv">100</span></span></code></pre></div>
<pre><code>##        1        2 
## -27.2619 122.2619</code></pre>
<p>These values do not make sense since probabilities are constrained to be between 0 and 100 (0 and 1).</p>
<p>Key point: Linear regression can not capture the bounded nature of probabilities.</p>
</div>
<div id="logistic-regression" class="section level2 unnumbered">
<h2>Logistic regression</h2>
<p>A regression model has a response function and a regression structure. The response function is specified on the left side of the regression equation and the regression structure on the right side of the equation.</p>
<p>With linear regression, the response function is the identity function. That is, for any value of <span class="math inline">\(y\)</span> the function returns the value of <span class="math inline">\(y\)</span>. We write it as
<span class="math display">\[
f(y) = y
\]</span></p>
<p>With logistic regression, the response function is the <em>logit</em> function. Said another way, logistic regression is a generalization of the linear regression model where the response function is the <em>logit</em> function.</p>
<p>We write the <em>logit</em> function as
<span class="math display">\[
f(y) = \hbox{logit}(y)
\]</span></p>
<p>The logit is the logarithm of the odds ratio. The odds ratio is the probability of a thing happening to the probability it won’t happen. Using math
<span class="math display">\[
\hbox{logit}(\pi) = \log\left(\frac{\pi}{1 - \pi}\right).
\]</span></p>
<p>We write odds as <em>for:against</em>. If there is a 2:1 odds of something happening, then the probability it will happen is 2/(1 + 2) or 2/3 (67%).</p>
<p>The inverse of the logit function is the logistic function. With logit(<span class="math inline">\(\pi\)</span>) = <span class="math inline">\(z\)</span>, we have
<span class="math display">\[
\pi = \frac{\exp(z)}{1 + \exp(z)} = \frac{1}{1 + \exp(-z)}.
\]</span></p>
<p>To make a graph of the logistic function we use the <code>curve()</code> function.</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="tuesday-november-1-2022.html#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">curve</span>(<span class="dv">1</span><span class="sc">/</span>(<span class="dv">1</span> <span class="sc">+</span> <span class="fu">exp</span>(<span class="sc">-</span>x)), </span>
<span id="cb19-2"><a href="tuesday-november-1-2022.html#cb19-2" aria-hidden="true" tabindex="-1"></a>      <span class="at">from =</span> <span class="sc">-</span><span class="dv">6</span>, <span class="at">to =</span> <span class="dv">6</span>, </span>
<span id="cb19-3"><a href="tuesday-november-1-2022.html#cb19-3" aria-hidden="true" tabindex="-1"></a>      <span class="at">col =</span> <span class="st">&quot;red&quot;</span>, <span class="at">ylab =</span> <span class="st">&quot;logistic function of z&quot;</span>, <span class="at">xlab =</span> <span class="st">&quot;z&quot;</span>)</span>
<span id="cb19-4"><a href="tuesday-november-1-2022.html#cb19-4" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> <span class="dv">1</span>, <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb19-5"><a href="tuesday-november-1-2022.html#cb19-5" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> <span class="dv">0</span>, <span class="at">lty =</span> <span class="dv">2</span>)</span></code></pre></div>
<p><img src="QG-2022_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<p>The logistic function takes as input any value from negative infinity to positive infinity and returns a value between 0 and 1.</p>
<p>The variable <span class="math inline">\(z\)</span> can be thought of as the exposure to some set of risk factors, while the logistic function represents the chance of a particular outcome given the exposure.</p>
<p>The variable <span class="math inline">\(z\)</span> is a measure of the total contribution (weighted sum) of all the risk factors (explanatory variables). It is defined as
<span class="math display">\[
z = \beta_0 + \beta_1  x_1 + \beta_2  x_2 + \ldots + \beta_p x_p
\]</span>
where the regression coefficients are <span class="math inline">\(\beta_0\)</span>,…, <span class="math inline">\(\beta_p\)</span> and the risk factors are <span class="math inline">\(x_1\)</span>,…, <span class="math inline">\(x_p\)</span>. The intercept <span class="math inline">\(\beta_0\)</span> is the value of <span class="math inline">\(z\)</span> when there is no risk (base rate).</p>
<p>The regression coefficient quantifies the amount of contribution the associated variable makes to the overall risk. For example, the magnitude of <span class="math inline">\(\beta_1\)</span> quantifies the amount of contribution variable <span class="math inline">\(x_1\)</span> makes to the overall risk.</p>
<p>A positive regression coefficient means the variable increases the probability of the outcome. If the outcome is getting COVID-19, then the variable indicating that you don’t wear a mask in public, increases the probability of that outcome.</p>
<p>A negative regression coefficient means the variable decreases the probability of that outcome.</p>
<p>A large regression coefficient means the variable strongly influences the probability of that outcome; while a near-zero regression coefficient means the variable has little influence on the probability of that outcome.</p>
</div>
<div id="example-who-survives-in-the-donner-party" class="section level2 unnumbered">
<h2>Example: Who survives in the Donner Party?</h2>
<p>The Donner and Reed families from Springfield, Illinois headed to California in 1846. The group, which became know as the ‘Donner Party,’ was stranded in the Sierra Nevada mountains by heavy late October snows. By the time the last survivor was rescued in April 1847, 40 of the 87 members had died from famine and exposure to the cold.</p>
<p>The data file <code>DonnerParty.txt</code> contains a list of individuals in the Donner Party along with their age, sex, and whether or not they survived.</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="tuesday-november-1-2022.html#cb20-1" aria-hidden="true" tabindex="-1"></a>DP.df <span class="ot">&lt;-</span> readr<span class="sc">::</span><span class="fu">read_table</span>(<span class="at">file =</span> <span class="st">&quot;http://myweb.fsu.edu/jelsner/temp/data/DonnerParty.txt&quot;</span>) <span class="sc">|&gt;</span></span>
<span id="cb20-2"><a href="tuesday-november-1-2022.html#cb20-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">Survival =</span> <span class="fu">as.factor</span>(Survival))</span></code></pre></div>
<pre><code>## 
## ── Column specification ────────────────────────────────────────────────────────
## cols(
##   Last = col_character(),
##   First = col_character(),
##   Sex = col_character(),
##   Age = col_double(),
##   Survival = col_character()
## )</code></pre>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="tuesday-november-1-2022.html#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(DP.df)</span></code></pre></div>
<pre><code>## tibble [45 × 5] (S3: tbl_df/tbl/data.frame)
##  $ Last    : chr [1:45] &quot;Antoine&quot; &quot;Breen&quot; &quot;Breen&quot; &quot;Burger&quot; ...
##  $ First   : chr [1:45] &quot;A&quot; &quot;Mary&quot; &quot;Patrick&quot; &quot;Charles&quot; ...
##  $ Sex     : chr [1:45] &quot;male&quot; &quot;female&quot; &quot;male&quot; &quot;male&quot; ...
##  $ Age     : num [1:45] 23 40 40 30 28 40 45 62 65 45 ...
##  $ Survival: Factor w/ 2 levels &quot;no&quot;,&quot;yes&quot;: 1 2 2 1 1 1 1 1 1 1 ...</code></pre>
<p>The data frame contains the <code>Name</code>, <code>Sex</code>, <code>Age</code>, and <code>Survival</code> status of all individuals that were at least 15 years old.</p>
<p>How many individuals are coded as <code>female</code> and how many are coded as <code>male</code>?</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="tuesday-november-1-2022.html#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(DP.df<span class="sc">$</span>Sex)</span></code></pre></div>
<pre><code>## 
## female   male 
##     15     30</code></pre>
<p>How many survived?</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="tuesday-november-1-2022.html#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(DP.df<span class="sc">$</span>Survival)</span></code></pre></div>
<pre><code>## 
##  no yes 
##  25  20</code></pre>
<p>What was the average age in the party?</p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="tuesday-november-1-2022.html#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(DP.df<span class="sc">$</span>Age)</span></code></pre></div>
<pre><code>## [1] 31.8</code></pre>
<p>What is the relationship between an individual’s age and whether or not they survived?</p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="tuesday-november-1-2022.html#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> DP.df, </span>
<span id="cb30-2"><a href="tuesday-november-1-2022.html#cb30-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> Survival, <span class="at">y =</span> Age)) <span class="sc">+</span> </span>
<span id="cb30-3"><a href="tuesday-november-1-2022.html#cb30-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>()</span></code></pre></div>
<p><img src="QG-2022_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
<p>Age appears to be a factor in explaining whether or not someone survived. Younger members of the party appear to have had a better chance of survival.</p>
<p>What about sex as an explanatory variable?</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="tuesday-november-1-2022.html#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(DP.df<span class="sc">$</span>Sex, DP.df<span class="sc">$</span>Survival)</span></code></pre></div>
<pre><code>##         
##          no yes
##   female  5  10
##   male   20  10</code></pre>
<p>The table shows that of the 15 women, 5 perished and 10 survived. This compares with 20 deaths and 10 survivors among the men. It appears that sex is also important. Relatively more women survived than men.</p>
<p>Logistic regression quantifies these risk factors (sex and age) in terms of survival probability.</p>
<p>The variable <code>Survival</code> is our dependent (response) variable coded as <code>no</code> and <code>yes</code>. The two risk factors are <code>Sex</code> coded as <code>male</code> and <code>female</code> and <code>Age</code> in years.</p>
<p>So you fit a logistic model to these data with <code>Survival</code> as your response variable. You use the <code>glm()</code> function (generalized linear model) and specify <code>family = binomial</code>.</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="tuesday-november-1-2022.html#cb33-1" aria-hidden="true" tabindex="-1"></a>logrm <span class="ot">&lt;-</span> <span class="fu">glm</span>(<span class="fu">factor</span>(Survival) <span class="sc">~</span> Age <span class="sc">+</span> Sex, </span>
<span id="cb33-2"><a href="tuesday-november-1-2022.html#cb33-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">data =</span> DP.df, </span>
<span id="cb33-3"><a href="tuesday-november-1-2022.html#cb33-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">family =</span> binomial)</span>
<span id="cb33-4"><a href="tuesday-november-1-2022.html#cb33-4" aria-hidden="true" tabindex="-1"></a>logrm</span></code></pre></div>
<pre><code>## 
## Call:  glm(formula = factor(Survival) ~ Age + Sex, family = binomial, 
##     data = DP.df)
## 
## Coefficients:
## (Intercept)          Age      Sexmale  
##      3.2304      -0.0782      -1.5973  
## 
## Degrees of Freedom: 44 Total (i.e. Null);  42 Residual
## Null Deviance:       61.83 
## Residual Deviance: 51.26     AIC: 57.26</code></pre>
<p>You write the model, where <span class="math inline">\(\pi\)</span> represents survival probability, as
<span class="math display">\[
\hbox{logit}(\pi) = 3.23 - .0782 \times \hbox{Age} - 1.597 \times \hbox{Sex}
\]</span></p>
<p>You interpret the value of 3.23 as the base rate when <code>Age</code> is zero and <code>Sex</code> is zero. Although <code>Sex</code> is coded as a factor variable <code>female</code> comes before <code>male</code> alphabetically so <code>female</code> is zero.</p>
<p>You take the value of 3.23 as input to the logistic function and get</p>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="tuesday-november-1-2022.html#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fl">3.23</span>)<span class="sc">/</span>(<span class="dv">1</span> <span class="sc">+</span> <span class="fu">exp</span>(<span class="fl">3.23</span>))</span></code></pre></div>
<pre><code>## [1] 0.9619478</code></pre>
<p>The resulting value tells you that a newborn (<code>Age</code> = 0) girl would have a 96% chance of survival.</p>
<p>You get this answer directly with the <code>predict()</code> method by typing</p>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="tuesday-november-1-2022.html#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(logrm, </span>
<span id="cb37-2"><a href="tuesday-november-1-2022.html#cb37-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">newdata =</span> <span class="fu">data.frame</span>(<span class="at">Age =</span> <span class="dv">0</span>, <span class="at">Sex =</span> <span class="st">&quot;female&quot;</span>),</span>
<span id="cb37-3"><a href="tuesday-november-1-2022.html#cb37-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">type =</span> <span class="st">&quot;response&quot;</span>)</span></code></pre></div>
<pre><code>##         1 
## 0.9619629</code></pre>
<p>Without the <code>type =</code> argument you get the logit value of 3.23.</p>
<p>You can also interpret the model in terms of the odds ratio. For example, the model tells you that the odds ratio of a 20-year old surviving relative to a 50-year old is
<span class="math display">\[
\exp(-.0782 \times (20 - 50))
\]</span></p>
<p>With code</p>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="tuesday-november-1-2022.html#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="sc">-</span>.<span class="dv">0782</span> <span class="sc">*</span> (<span class="dv">20</span> <span class="sc">-</span> <span class="dv">50</span>))</span></code></pre></div>
<pre><code>## [1] 10.44371</code></pre>
<p>The odds of a 20-year old surviving is more than 10 times the odds of a 50-year old surviving regardless of whether the person is a man or woman.</p>
<p>If an explanatory variable increases by one unit while the other explanatory variables remain constant, the odds will change by a <em>multiplicative</em> amount given by the exponent of the coefficient.</p>
<p>The odds of a woman (<code>Sex = 0</code>) surviving relative to the odds of a man (<code>Sex = 1</code>) of the same age is</p>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="tuesday-november-1-2022.html#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="sc">-</span><span class="fl">1.597</span> <span class="sc">*</span> (<span class="dv">0</span> <span class="sc">-</span> <span class="dv">1</span>))</span></code></pre></div>
<pre><code>## [1] 4.938196</code></pre>
<p>Thus, the survival odds of a women are about 5 times the survival odds of a man both at the same age.</p>
<p>You get uncertainty intervals on the coefficients using an extractor function.</p>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="tuesday-november-1-2022.html#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(logrm)</span></code></pre></div>
<pre><code>## Waiting for profiling to be done...</code></pre>
<pre><code>##                  2.5 %      97.5 %
## (Intercept)  0.8514190  6.42669512
## Age         -0.1624377 -0.01406576
## Sexmale     -3.2286705 -0.19510198</code></pre>
<p>You see that the 95% uncertainty intervals for both factors do not include the value of zero. This indicates that <code>Age</code> and <code>Sex</code> are significant in statistically explaining survivability.</p>
<p>You can also check the importance of the variables with the <code>summary()</code> method on the model object.</p>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="tuesday-november-1-2022.html#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(logrm)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = factor(Survival) ~ Age + Sex, family = binomial, 
##     data = DP.df)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -1.7445  -1.0441  -0.3029   0.8877   2.0472  
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)  
## (Intercept)  3.23041    1.38686   2.329   0.0198 *
## Age         -0.07820    0.03728  -2.097   0.0359 *
## Sexmale     -1.59729    0.75547  -2.114   0.0345 *
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 61.827  on 44  degrees of freedom
## Residual deviance: 51.256  on 42  degrees of freedom
## AIC: 57.256
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<p>You see that <code>Age</code> and <code>Sex</code> are significant variables in explaining the probability of survival (<span class="math inline">\(p\)</span> values less than .05).</p>
<p>The smaller the residual deviance, the better the logistic model fits. Output shows a null deviance of 61.827 on 44 degrees of freedom. The null deviance is the deviance of a model with a constant (no explanatory variables) survival probability (44%; 20 out of 45 survived).</p>
<p>The residual deviance for the model with <code>Age</code> and <code>Sex</code> as explanatory variables is 51.256 on 42 degrees of freedom. The difference in deviance between the null and the full model is: 61.827 - 51.256 = 10.571. The difference in degrees of freedom is 44 - 42 = 2.</p>
<p>You compare this drop in deviance to a value from the chi-squared distribution with 2 degrees of freedom.</p>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="tuesday-november-1-2022.html#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pchisq</span>(<span class="fl">10.571</span>, </span>
<span id="cb48-2"><a href="tuesday-november-1-2022.html#cb48-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">df =</span> <span class="dv">2</span>, </span>
<span id="cb48-3"><a href="tuesday-november-1-2022.html#cb48-3" aria-hidden="true" tabindex="-1"></a>       <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## [1] 0.005064499</code></pre>
<p>This is the <span class="math inline">\(p\)</span> value for the model as a whole. Since it is less than .01 you state that there is convincing evidence that the model helps statistically explain survivability given these data.</p>
<p>Here you predict the survival probability of a 50-year old man.</p>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="tuesday-november-1-2022.html#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(logrm, </span>
<span id="cb50-2"><a href="tuesday-november-1-2022.html#cb50-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">newdata =</span> <span class="fu">data.frame</span>(<span class="at">Age =</span> <span class="dv">50</span>, </span>
<span id="cb50-3"><a href="tuesday-november-1-2022.html#cb50-3" aria-hidden="true" tabindex="-1"></a>                             <span class="at">Sex =</span> <span class="st">&quot;male&quot;</span>))</span></code></pre></div>
<pre><code>##         1 
## -2.277083</code></pre>
<p>By default the predicted value is the logarithm of the odds. To convert this to a probability we use the logistic function or we use the <code>type = "response"</code> argument in the <code>predict()</code> method.</p>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb52-1"><a href="tuesday-november-1-2022.html#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="sc">-</span><span class="fl">2.277</span>)<span class="sc">/</span>(<span class="dv">1</span> <span class="sc">+</span> <span class="fu">exp</span>(<span class="sc">-</span><span class="fl">2.277</span>))</span></code></pre></div>
<pre><code>## [1] 0.09304581</code></pre>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb54-1"><a href="tuesday-november-1-2022.html#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(logrm, </span>
<span id="cb54-2"><a href="tuesday-november-1-2022.html#cb54-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">newdata =</span> <span class="fu">data.frame</span>(<span class="at">Age =</span> <span class="dv">50</span>, </span>
<span id="cb54-3"><a href="tuesday-november-1-2022.html#cb54-3" aria-hidden="true" tabindex="-1"></a>                             <span class="at">Sex =</span> <span class="st">&quot;male&quot;</span>),</span>
<span id="cb54-4"><a href="tuesday-november-1-2022.html#cb54-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">type =</span> <span class="st">&quot;response&quot;</span>)</span></code></pre></div>
<pre><code>##          1 
## 0.09303878</code></pre>
<p>You see that, based on the data and the model, you would predict a survival probability of 9.3% for a 50-year old man.</p>
<p>What is the survival probability for a 50-year old woman? A 25-year old woman?</p>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb56-1"><a href="tuesday-november-1-2022.html#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(logrm, </span>
<span id="cb56-2"><a href="tuesday-november-1-2022.html#cb56-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">newdata =</span> <span class="fu">data.frame</span>(<span class="at">Age =</span> <span class="fu">c</span>(<span class="dv">50</span>, <span class="dv">25</span>), </span>
<span id="cb56-3"><a href="tuesday-november-1-2022.html#cb56-3" aria-hidden="true" tabindex="-1"></a>                             <span class="at">Sex =</span> <span class="st">&quot;female&quot;</span>),</span>
<span id="cb56-4"><a href="tuesday-november-1-2022.html#cb56-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">type =</span> <span class="st">&quot;response&quot;</span>,</span>
<span id="cb56-5"><a href="tuesday-november-1-2022.html#cb56-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">se.fit =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## $fit
##         1         2 
## 0.3363082 0.7816507 
## 
## $se.fit
##         1         2 
## 0.1904773 0.1153756 
## 
## $residual.scale
## [1] 1</code></pre>
<p>You include the argument <code>se.fit = TRUE</code> to get a standard error on the predicted survival probability.</p>
<p>Assessing the adequacy of a linear regression model involves plots of the residuals. Similar diagnostics are available for assessing the adequacy of logistic regression, but they are often more difficult to interpret. For instance how do you examine the linearity assumption when the linearity is on the log of the odds?</p>
<p>Residual deviance: Returning to the output from <code>summary(logrm)</code>, you find that the residual deviance is 51.256 on 42 degrees of freedom. A <span class="math inline">\(p\)</span> value from a <span class="math inline">\(\chi^2\)</span> distribution with a quantile value of 51.256 with this many degrees of freedom provides evidence against the null hypothesis. The null hypothesis is that the model is adequate.</p>
<p>Thus a small <span class="math inline">\(p\)</span> value in this case is evidence <em>against</em> the null hypothesis, which is that the model is adequate.</p>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb58-1"><a href="tuesday-november-1-2022.html#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pchisq</span>(<span class="at">q =</span> <span class="fl">51.256</span>, </span>
<span id="cb58-2"><a href="tuesday-november-1-2022.html#cb58-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">df =</span> <span class="dv">42</span>, </span>
<span id="cb58-3"><a href="tuesday-november-1-2022.html#cb58-3" aria-hidden="true" tabindex="-1"></a>       <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## [1] 0.1549141</code></pre>
<p>Since the <span class="math inline">\(p\)</span> value exceeds .05 you fail to reject the null hypothesis that the model is adequate and report that there is no compelling evidence that the model needs to be improved.</p>
</div>
<div id="example-probability-of-rocket-damage-on-liftoff" class="section level2 unnumbered">
<h2>Example: Probability of rocket damage on liftoff</h2>
<p>Returning to the data on the Space Shuttle O-ring damage and launch time temperature. The recovered booster rockets were checked for damage to the rings. A damaged rocket booster is coded as <code>1</code>.</p>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb60-1"><a href="tuesday-november-1-2022.html#cb60-1" aria-hidden="true" tabindex="-1"></a>Temperature <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">66</span>, <span class="dv">70</span>, <span class="dv">69</span>, <span class="dv">68</span>, <span class="dv">67</span>, <span class="dv">72</span>, <span class="dv">73</span>, <span class="dv">70</span>, <span class="dv">57</span>, <span class="dv">63</span>, <span class="dv">70</span>, <span class="dv">78</span>, <span class="dv">67</span>, <span class="dv">53</span>, <span class="dv">67</span>, <span class="dv">75</span>, <span class="dv">70</span>, <span class="dv">81</span>, <span class="dv">76</span>, <span class="dv">79</span>, <span class="dv">75</span>, <span class="dv">76</span>, <span class="dv">58</span>)</span>
<span id="cb60-2"><a href="tuesday-november-1-2022.html#cb60-2" aria-hidden="true" tabindex="-1"></a>Damage <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">1</span>)</span>
<span id="cb60-3"><a href="tuesday-november-1-2022.html#cb60-3" aria-hidden="true" tabindex="-1"></a>ORings.df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(Temperature, Damage)</span></code></pre></div>
<p>A logistic regression model is used to predict the probability of damage given the temperature.</p>
<p>Fit a logistic regression model to the data.</p>
<div class="sourceCode" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb61-1"><a href="tuesday-november-1-2022.html#cb61-1" aria-hidden="true" tabindex="-1"></a>logrm <span class="ot">&lt;-</span> <span class="fu">glm</span>(Damage <span class="sc">~</span> Temperature, </span>
<span id="cb61-2"><a href="tuesday-november-1-2022.html#cb61-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">data =</span> ORings.df,</span>
<span id="cb61-3"><a href="tuesday-november-1-2022.html#cb61-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">family =</span> binomial)</span>
<span id="cb61-4"><a href="tuesday-november-1-2022.html#cb61-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(logrm)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = Damage ~ Temperature, family = binomial, data = ORings.df)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -1.0611  -0.7613  -0.3783   0.4524   2.2175  
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)  
## (Intercept)  15.0429     7.3786   2.039   0.0415 *
## Temperature  -0.2322     0.1082  -2.145   0.0320 *
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 28.267  on 22  degrees of freedom
## Residual deviance: 20.315  on 21  degrees of freedom
## AIC: 24.315
## 
## Number of Fisher Scoring iterations: 5</code></pre>
<p>The negative sign on the <code>Temperature</code> coefficient indicates that the chance of O-ring damages decreases with increasing temperature.</p>
<p>You interpret the magnitude of the coefficient by first applying the exponentiation function (<code>exp()</code>).</p>
<div class="sourceCode" id="cb63"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb63-1"><a href="tuesday-november-1-2022.html#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="sc">-</span>.<span class="dv">2322</span>)</span></code></pre></div>
<pre><code>## [1] 0.7927875</code></pre>
<p>The value of .79 tells you that for every 1 degree increase in temperature the chance of O-ring damage is only 79% of it’s previous value (given the model).</p>
<p>For example, to determine how much more likely there is to be damage when the temperature is 65 F compared to when the temperature is 69 F you use</p>
<div class="sourceCode" id="cb65"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb65-1"><a href="tuesday-november-1-2022.html#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">exp</span>(<span class="sc">-</span>.<span class="dv">2322</span> <span class="sc">*</span> (<span class="dv">65</span> <span class="sc">-</span> <span class="dv">69</span>)), <span class="dv">1</span>)</span></code></pre></div>
<pre><code>## [1] 2.5</code></pre>
<p>Thus, on average, there is a 2.5 times increase in the chance of O-ring damage when launch temperatures are 65 F compared to when they are 69 F.</p>
<div class="sourceCode" id="cb67"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb67-1"><a href="tuesday-november-1-2022.html#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(logrm,</span>
<span id="cb67-2"><a href="tuesday-november-1-2022.html#cb67-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">newdata =</span> <span class="fu">data.frame</span>(<span class="at">Temperature =</span> <span class="fu">c</span>(<span class="dv">45</span>, <span class="dv">95</span>)),</span>
<span id="cb67-3"><a href="tuesday-november-1-2022.html#cb67-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">type =</span> <span class="st">&quot;response&quot;</span>)</span></code></pre></div>
<pre><code>##           1           2 
## 0.990004536 0.000899691</code></pre>
<p>With generalized linear models, model adequacy is determined by the residual deviance. No plots are needed.</p>
<p>The residual deviance is 20.315 on 21 degrees of freedom. A <span class="math inline">\(p\)</span> value from a <span class="math inline">\(\chi^2\)</span> distribution with this quantile value and this many degrees of freedom is evidence in favor of the null hypothesis that the model is adequate.</p>
<div class="sourceCode" id="cb69"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb69-1"><a href="tuesday-november-1-2022.html#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pchisq</span>(<span class="at">q =</span> <span class="fl">20.315</span>, </span>
<span id="cb69-2"><a href="tuesday-november-1-2022.html#cb69-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">df =</span> <span class="dv">21</span>,</span>
<span id="cb69-3"><a href="tuesday-november-1-2022.html#cb69-3" aria-hidden="true" tabindex="-1"></a>       <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## [1] 0.5013948</code></pre>
<p>The large <span class="math inline">\(p\)</span> value gives you no reason to question the adequacy of the model.</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="thursday-october-30-2022.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
