<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Tuesday November 29, 2022 | GEO5156: Quantitative Geography</title>
  <meta name="description" content="Tuesday November 29, 2022 | GEO5156: Quantitative Geography" />
  <meta name="generator" content="bookdown 0.27 and GitBook 2.6.7" />

  <meta property="og:title" content="Tuesday November 29, 2022 | GEO5156: Quantitative Geography" />
  <meta property="og:type" content="book" />
  
  
  <meta name="github-repo" content="jelsner/QG-2022" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Tuesday November 29, 2022 | GEO5156: Quantitative Geography" />
  
  
  

<meta name="author" content="James B. Elsner" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="tuesday-november-22-2022.html"/>
<link rel="next" href="thursday-december-1-2022.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Quantitative Geography</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html"><i class="fa fa-check"></i>Syllabus</a>
<ul>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#geo5165c-quantitative-geography"><i class="fa fa-check"></i>GEO5165C: Quantitative Geography</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#contact-information"><i class="fa fa-check"></i>Contact information</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#course-description-and-expected-learning-outcomes"><i class="fa fa-check"></i>Course description and expected learning outcomes</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#grades-and-ethics"><i class="fa fa-check"></i>Grades and ethics</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#schedule-subject-to-change-with-notice"><i class="fa fa-check"></i>Schedule (subject to change with notice)</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#deeper-dives"><i class="fa fa-check"></i>Deeper dives</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html"><i class="fa fa-check"></i>Tuesday, August 23, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#what-is-this-course"><i class="fa fa-check"></i>What is this course?</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#where-are-the-materials-for-this-course"><i class="fa fa-check"></i>Where are the materials for this course?</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#get-the-syllabus"><i class="fa fa-check"></i>Get the syllabus</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#getting-setup"><i class="fa fa-check"></i>Getting setup</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-23-2022.html"><a href="tuesday-august-23-2022.html#getting-to-know-rstudios-integrated-development-environment-ide"><i class="fa fa-check"></i>Getting to know RStudio’s integrated development environment (IDE)</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html"><i class="fa fa-check"></i>Thursday, August 25, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#data-science"><i class="fa fa-check"></i>Data science</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#structure-of-markdown-files"><i class="fa fa-check"></i>Structure of markdown files</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#how-to-make-a-plot"><i class="fa fa-check"></i>How to make a plot</a></li>
<li class="chapter" data-level="" data-path="thursday-august-25-2022.html"><a href="thursday-august-25-2022.html#getting-started-using-r"><i class="fa fa-check"></i>Getting started using R</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html"><i class="fa fa-check"></i>Tuesday, August 30, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html#graphing-examples"><i class="fa fa-check"></i>Graphing examples</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html#introduction-to-working-with-base-r"><i class="fa fa-check"></i>Introduction to working with base R</a></li>
<li class="chapter" data-level="" data-path="tuesday-august-30-2022.html"><a href="tuesday-august-30-2022.html#data-as-vectors"><i class="fa fa-check"></i>Data as vectors</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-september-1-2022.html"><a href="thursday-september-1-2022.html"><i class="fa fa-check"></i>Thursday, September 1, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-september-1-2022.html"><a href="thursday-september-1-2022.html#statistical-summaries-of-data"><i class="fa fa-check"></i>Statistical summaries of data</a></li>
<li class="chapter" data-level="" data-path="thursday-september-1-2022.html"><a href="thursday-september-1-2022.html#structured-data"><i class="fa fa-check"></i>Structured data</a></li>
<li class="chapter" data-level="" data-path="thursday-september-1-2022.html"><a href="thursday-september-1-2022.html#tables"><i class="fa fa-check"></i>Tables</a></li>
<li class="chapter" data-level="" data-path="thursday-september-1-2022.html"><a href="thursday-september-1-2022.html#assignment-1"><i class="fa fa-check"></i>Assignment #1</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-september-6-2022.html"><a href="tuesday-september-6-2022.html"><i class="fa fa-check"></i>Tuesday, September 6, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-september-6-2022.html"><a href="tuesday-september-6-2022.html#getting-data-into-r"><i class="fa fa-check"></i>Getting data into R</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-6-2022.html"><a href="tuesday-september-6-2022.html#data-frames"><i class="fa fa-check"></i>Data frames</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-6-2022.html"><a href="tuesday-september-6-2022.html#piping-your-commands"><i class="fa fa-check"></i>Piping your commands</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-september-8-2022.html"><a href="thursday-september-8-2022.html"><i class="fa fa-check"></i>Thursday, September 8, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-september-8-2022.html"><a href="thursday-september-8-2022.html#data-transformation-with-dplyr"><i class="fa fa-check"></i>Data transformation with {dplyr}</a></li>
<li class="chapter" data-level="" data-path="thursday-september-8-2022.html"><a href="thursday-september-8-2022.html#from-data-import-to-final-plot"><i class="fa fa-check"></i>From data import to final plot</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-september-13-2022.html"><a href="tuesday-september-13-2022.html"><i class="fa fa-check"></i>Tuesday, September 13, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-september-13-2022.html"><a href="tuesday-september-13-2022.html#data-visualization"><i class="fa fa-check"></i>Data visualization</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-september-20-2022.html"><a href="tuesday-september-20-2022.html"><i class="fa fa-check"></i>Tuesday, September 20, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-september-20-2022.html"><a href="tuesday-september-20-2022.html#comparing-distributions"><i class="fa fa-check"></i>Comparing distributions</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-20-2022.html"><a href="tuesday-september-20-2022.html#visualizing-uncertainty"><i class="fa fa-check"></i>Visualizing uncertainty</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-20-2022.html"><a href="tuesday-september-20-2022.html#simple-feature-data-frames"><i class="fa fa-check"></i>Simple feature data frames</a></li>
<li class="chapter" data-level="" data-path="tuesday-september-20-2022.html"><a href="tuesday-september-20-2022.html#making-a-boundary-map"><i class="fa fa-check"></i>Making a boundary map</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-september-22-2022.html"><a href="thursday-september-22-2022.html"><i class="fa fa-check"></i>Thursday, September 22, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-september-22-2022.html"><a href="thursday-september-22-2022.html#adding-data-to-boundary-maps"><i class="fa fa-check"></i>Adding data to boundary maps</a></li>
<li class="chapter" data-level="" data-path="thursday-september-22-2022.html"><a href="thursday-september-22-2022.html#changing-projections"><i class="fa fa-check"></i>Changing projections</a></li>
<li class="chapter" data-level="" data-path="thursday-september-22-2022.html"><a href="thursday-september-22-2022.html#mapping-using-functions-from-tmap"><i class="fa fa-check"></i>Mapping using functions from tmap</a></li>
<li class="chapter" data-level="" data-path="thursday-september-22-2022.html"><a href="thursday-september-22-2022.html#making-an-interactive-map"><i class="fa fa-check"></i>Making an interactive map</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-october-4-2022.html"><a href="tuesday-october-4-2022.html"><i class="fa fa-check"></i>Tuesday, October 4, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-october-4-2022.html"><a href="tuesday-october-4-2022.html#extended-mapping-example-tornado-frequency"><i class="fa fa-check"></i>Extended mapping example: tornado frequency</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-4-2022.html"><a href="tuesday-october-4-2022.html#geo-computation-on-simple-feature-data-frames"><i class="fa fa-check"></i>Geo-computation on simple feature data frames</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-4-2022.html"><a href="tuesday-october-4-2022.html#making-raster-maps"><i class="fa fa-check"></i>Making raster maps</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-4-2022.html"><a href="tuesday-october-4-2022.html#spatial-density-maps"><i class="fa fa-check"></i>Spatial density maps</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-4-2022.html"><a href="tuesday-october-4-2022.html#assignment-3"><i class="fa fa-check"></i>Assignment #3</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-september-29-2022.html"><a href="thursday-september-29-2022.html"><i class="fa fa-check"></i>Thursday, September 29, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-september-29-2022.html"><a href="thursday-september-29-2022.html#one-sample-test-for-the-value-of-the-population-mean"><i class="fa fa-check"></i>One-sample test for the value of the population mean</a></li>
<li class="chapter" data-level="" data-path="thursday-september-29-2022.html"><a href="thursday-september-29-2022.html#graphical-inference"><i class="fa fa-check"></i>Graphical inference</a></li>
<li class="chapter" data-level="" data-path="thursday-september-29-2022.html"><a href="thursday-september-29-2022.html#two-sample-test-for-a-difference-in-population-means"><i class="fa fa-check"></i>Two-sample test for a difference in population means</a></li>
<li class="chapter" data-level="" data-path="thursday-september-29-2022.html"><a href="thursday-september-29-2022.html#a-non-parameteric-test-for-difference-in-population-means"><i class="fa fa-check"></i>A non-parameteric test for difference in population means</a></li>
<li class="chapter" data-level="" data-path="thursday-september-29-2022.html"><a href="thursday-september-29-2022.html#paired-observations"><i class="fa fa-check"></i>Paired observations</a></li>
<li class="chapter" data-level="" data-path="thursday-september-29-2022.html"><a href="thursday-september-29-2022.html#chi-squared-test-for-independence"><i class="fa fa-check"></i>Chi-squared test for independence</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-october-11-2022.html"><a href="tuesday-october-11-2022.html"><i class="fa fa-check"></i>Tuesday, October 11, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-october-11-2022.html"><a href="tuesday-october-11-2022.html#distributions-as-lego-bricks"><i class="fa fa-check"></i>Distributions as Lego bricks</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-11-2022.html"><a href="tuesday-october-11-2022.html#bayesian-computation"><i class="fa fa-check"></i>Bayesian computation</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-11-2022.html"><a href="tuesday-october-11-2022.html#real-world-example"><i class="fa fa-check"></i>Real world example</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-11-2022.html"><a href="tuesday-october-11-2022.html#why-use-bayesian-models"><i class="fa fa-check"></i>Why use Bayesian models?</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-october-13-2022.html"><a href="thursday-october-13-2022.html"><i class="fa fa-check"></i>Thursday, October 13, 2022</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-18-2022.html"><a href="tuesday-october-18-2022.html"><i class="fa fa-check"></i>Tuesday, October 18, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-october-18-2022.html"><a href="tuesday-october-18-2022.html#linear-regression-a-t-test-by-another-name"><i class="fa fa-check"></i>Linear regression: A t test by another name</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-18-2022.html"><a href="tuesday-october-18-2022.html#motivation-for-the-regression-model"><i class="fa fa-check"></i>Motivation for the regression model</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-18-2022.html"><a href="tuesday-october-18-2022.html#making-predictions-with-the-regression-model"><i class="fa fa-check"></i>Making predictions with the regression model</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-18-2022.html"><a href="tuesday-october-18-2022.html#uncertainty-about-the-regression-model-coefficients"><i class="fa fa-check"></i>Uncertainty about the regression model coefficients</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-18-2022.html"><a href="tuesday-october-18-2022.html#bootstrapping-the-uncertainty"><i class="fa fa-check"></i>Bootstrapping the uncertainty</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-october-20-2022.html"><a href="thursday-october-20-2022.html"><i class="fa fa-check"></i>Thursday, October 20, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-october-20-2022.html"><a href="thursday-october-20-2022.html#predictive-uncertainty"><i class="fa fa-check"></i>Predictive uncertainty</a></li>
<li class="chapter" data-level="" data-path="thursday-october-20-2022.html"><a href="thursday-october-20-2022.html#model-adequacy"><i class="fa fa-check"></i>Model adequacy</a></li>
<li class="chapter" data-level="" data-path="thursday-october-20-2022.html"><a href="thursday-october-20-2022.html#regression-examples"><i class="fa fa-check"></i>Regression examples</a></li>
<li class="chapter" data-level="" data-path="thursday-october-20-2022.html"><a href="thursday-october-20-2022.html#outliers"><i class="fa fa-check"></i>Outliers</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-october-25-2022.html"><a href="tuesday-october-25-2022.html"><i class="fa fa-check"></i>Tuesday, October 25, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-october-25-2022.html"><a href="tuesday-october-25-2022.html#simpsons-paradox"><i class="fa fa-check"></i>Simpson’s paradox</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-25-2022.html"><a href="tuesday-october-25-2022.html#multiple-variable-regression"><i class="fa fa-check"></i>Multiple variable regression</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-25-2022.html"><a href="tuesday-october-25-2022.html#fitting-a-multiple-variable-regression-model"><i class="fa fa-check"></i>Fitting a multiple variable regression model</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-25-2022.html"><a href="tuesday-october-25-2022.html#should-you-remove-a-variable-from-your-model"><i class="fa fa-check"></i>Should you remove a variable from your model?</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-25-2022.html"><a href="tuesday-october-25-2022.html#checking-the-model-assumptions"><i class="fa fa-check"></i>Checking the model assumptions</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-25-2022.html"><a href="tuesday-october-25-2022.html#using-the-model-to-make-predictions"><i class="fa fa-check"></i>Using the model to make predictions</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-25-2022.html"><a href="tuesday-october-25-2022.html#collinearity-and-what-to-do-about-it"><i class="fa fa-check"></i>Collinearity and what to do about it</a></li>
<li class="chapter" data-level="" data-path="tuesday-october-25-2022.html"><a href="tuesday-october-25-2022.html#how-to-include-and-interpret-interactions-terms"><i class="fa fa-check"></i>How to include and interpret interactions terms</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-november-1-2022.html"><a href="tuesday-november-1-2022.html"><i class="fa fa-check"></i>Tuesday, November 1, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-november-1-2022.html"><a href="tuesday-november-1-2022.html#removing-variables-from-a-regression-model"><i class="fa fa-check"></i>Removing variables from a regression model</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-1-2022.html"><a href="tuesday-november-1-2022.html#automatic-selection-of-variables"><i class="fa fa-check"></i>Automatic selection of variables</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-1-2022.html"><a href="tuesday-november-1-2022.html#transforming-the-response-variable"><i class="fa fa-check"></i>Transforming the response variable</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-1-2022.html"><a href="tuesday-november-1-2022.html#fitting-a-regression-tree-model"><i class="fa fa-check"></i>Fitting a regression tree model</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-november-8-2022.html"><a href="tuesday-november-8-2022.html"><i class="fa fa-check"></i>Tuesday, November 8, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-november-8-2022.html"><a href="tuesday-november-8-2022.html#predictive-uncertainty-with-regression-trees"><i class="fa fa-check"></i>Predictive uncertainty with regression trees</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-8-2022.html"><a href="tuesday-november-8-2022.html#the-random-forest-algorithm"><i class="fa fa-check"></i>The random forest algorithm</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-8-2022.html"><a href="tuesday-november-8-2022.html#cross-validation"><i class="fa fa-check"></i>Cross validation</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-8-2022.html"><a href="tuesday-november-8-2022.html#classification-trees"><i class="fa fa-check"></i>Classification trees</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-november-15-2022.html"><a href="tuesday-november-15-2022.html"><i class="fa fa-check"></i>Tuesday, November 15, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-november-15-2022.html"><a href="tuesday-november-15-2022.html#binary-outcomes-and-probabilities"><i class="fa fa-check"></i>Binary outcomes and probabilities</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-15-2022.html"><a href="tuesday-november-15-2022.html#logistic-regression"><i class="fa fa-check"></i>Logistic regression</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-november-17-2022.html"><a href="thursday-november-17-2022.html"><i class="fa fa-check"></i>Thursday November 17, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-november-17-2022.html"><a href="thursday-november-17-2022.html#defining-spatial-neighborhoods-and-spatial-weights"><i class="fa fa-check"></i>Defining spatial neighborhoods and spatial weights</a></li>
<li class="chapter" data-level="" data-path="thursday-november-17-2022.html"><a href="thursday-november-17-2022.html#computing-autocorrelation"><i class="fa fa-check"></i>Computing autocorrelation</a></li>
<li class="chapter" data-level="" data-path="thursday-november-17-2022.html"><a href="thursday-november-17-2022.html#spatial-lag-and-its-relation-to-autocorrelation"><i class="fa fa-check"></i>Spatial lag and its relation to autocorrelation</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-november-22-2022.html"><a href="tuesday-november-22-2022.html"><i class="fa fa-check"></i>Tuesday November 22, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-november-22-2022.html"><a href="tuesday-november-22-2022.html#other-neighborhood-definitions"><i class="fa fa-check"></i>Other neighborhood definitions</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-22-2022.html"><a href="tuesday-november-22-2022.html#assessing-the-statistical-significance-of-autocorrelation"><i class="fa fa-check"></i>Assessing the statistical significance of autocorrelation</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-22-2022.html"><a href="tuesday-november-22-2022.html#bivariate-spatial-autocorrelation"><i class="fa fa-check"></i>Bivariate spatial autocorrelation</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-22-2022.html"><a href="tuesday-november-22-2022.html#local-indicators-of-spatial-autocorrelation"><i class="fa fa-check"></i>Local indicators of spatial autocorrelation</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tuesday-november-29-2022.html"><a href="tuesday-november-29-2022.html"><i class="fa fa-check"></i>Tuesday November 29, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="tuesday-november-29-2022.html"><a href="tuesday-november-29-2022.html#estimating-spatial-autocorrelation-in-model-residuals"><i class="fa fa-check"></i>Estimating spatial autocorrelation in model residuals</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-29-2022.html"><a href="tuesday-november-29-2022.html#choosing-a-spatial-regression-model"><i class="fa fa-check"></i>Choosing a spatial regression model</a></li>
<li class="chapter" data-level="" data-path="tuesday-november-29-2022.html"><a href="tuesday-november-29-2022.html#fitting-and-interpreting-spatial-regression-models"><i class="fa fa-check"></i>Fitting and interpreting spatial regression models</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="thursday-december-1-2022.html"><a href="thursday-december-1-2022.html"><i class="fa fa-check"></i>Thursday December 1, 2022</a>
<ul>
<li class="chapter" data-level="" data-path="thursday-december-1-2022.html"><a href="thursday-december-1-2022.html#fitting-and-interpreting-geographic-regression"><i class="fa fa-check"></i>Fitting and interpreting geographic regression</a></li>
<li class="chapter" data-level="" data-path="thursday-december-1-2022.html"><a href="thursday-december-1-2022.html#mapping-incidence-and-risk-with-a-spatial-regression-model"><i class="fa fa-check"></i>Mapping incidence and risk with a spatial regression model</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">GEO5156: Quantitative Geography</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="tuesday-november-29-2022" class="section level1 unnumbered hasAnchor">
<h1>Tuesday November 29, 2022<a href="tuesday-november-29-2022.html#tuesday-november-29-2022" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<ul>
<li>Estimating spatial autocorrelation in model residuals</li>
<li>Choosing a spatial regression model</li>
<li>Fitting and interpreting spatial regression models</li>
</ul>
<div id="estimating-spatial-autocorrelation-in-model-residuals" class="section level2 unnumbered hasAnchor">
<h2>Estimating spatial autocorrelation in model residuals<a href="tuesday-november-29-2022.html#estimating-spatial-autocorrelation-in-model-residuals" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Previous focus has been on estimating the amount of spatial autocorrelation in a variable aggregated at some areal-unit level. You saw examples of crime rates and police expenditures aggregated at the county level. This is important for hot-spot analysis or spatial sampling.</p>
<p>However, if you want a model for a response variable as a function of explanatory variables across a set of areal units then focus shifts to estimating the spatial autocorrelation in the model residuals.</p>
<p>The model of first choice is a linear regression, but when the residuals from a linear regression model exhibit significant spatial autocorrelation then you should consider a <em>spatial</em> regression model.</p>
<p>So the workflow starts by fitting an OLS regression model where you regress the response variable onto the explanatory variables. You then check for spatial autocorrelation in the residuals.</p>
<p>Consider again the crime data at the tract level in the city of Columbus, Ohio.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="tuesday-november-29-2022.html#cb1-1" aria-hidden="true" tabindex="-1"></a>CC.sf <span class="ot">&lt;-</span> sf<span class="sc">::</span><span class="fu">st_read</span>(<span class="at">dsn =</span> here<span class="sc">::</span><span class="fu">here</span>(<span class="st">&quot;data&quot;</span>, <span class="st">&quot;columbus&quot;</span>),</span>
<span id="cb1-2"><a href="tuesday-november-29-2022.html#cb1-2" aria-hidden="true" tabindex="-1"></a>                     <span class="at">layer =</span> <span class="st">&quot;columbus&quot;</span>)</span></code></pre></div>
<pre><code>## Reading layer `columbus&#39; from data source 
##   `/Users/jelsner/Desktop/ClassNotes/QG-2022/data/columbus&#39; using driver `ESRI Shapefile&#39;
## Simple feature collection with 49 features and 20 fields
## Geometry type: POLYGON
## Dimension:     XY
## Bounding box:  xmin: 5.874907 ymin: 10.78863 xmax: 11.28742 ymax: 14.74245
## CRS:           NA</code></pre>
<p><code>CRIME</code> is the response variable and <code>INC</code> and <code>HOVAL</code> are the explanatory variables. The data are aggregated to census tracts. How well do these two explanatory variables statistically explain the amount of crime at the tract level?</p>
<p>An answer to this question is obtained by regressing crime onto income and housing values. Here you use the <code>lm()</code> function and save the results to the object <code>model.lm</code>.</p>
<p>Set the formula assigning it to the object <code>f</code>, then use the formula as the first argument in the <code>lm()</code> function. Summarize the results with the <code>summary()</code> method.</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="tuesday-november-29-2022.html#cb3-1" aria-hidden="true" tabindex="-1"></a>f <span class="ot">&lt;-</span> CRIME <span class="sc">~</span> INC <span class="sc">+</span> HOVAL</span>
<span id="cb3-2"><a href="tuesday-november-29-2022.html#cb3-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-3"><a href="tuesday-november-29-2022.html#cb3-3" aria-hidden="true" tabindex="-1"></a>model.lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(f, </span>
<span id="cb3-4"><a href="tuesday-november-29-2022.html#cb3-4" aria-hidden="true" tabindex="-1"></a>                <span class="at">data =</span> CC.sf)</span>
<span id="cb3-5"><a href="tuesday-november-29-2022.html#cb3-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-6"><a href="tuesday-november-29-2022.html#cb3-6" aria-hidden="true" tabindex="-1"></a>model.lm <span class="sc">|&gt;</span></span>
<span id="cb3-7"><a href="tuesday-november-29-2022.html#cb3-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summary</span>()</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = f, data = CC.sf)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -34.418  -6.388  -1.580   9.052  28.649 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  68.6190     4.7355  14.490  &lt; 2e-16 ***
## INC          -1.5973     0.3341  -4.780 1.83e-05 ***
## HOVAL        -0.2739     0.1032  -2.654   0.0109 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 11.43 on 46 degrees of freedom
## Multiple R-squared:  0.5524, Adjusted R-squared:  0.5329 
## F-statistic: 28.39 on 2 and 46 DF,  p-value: 9.341e-09</code></pre>
<p>The output shows that the linear regression model statistically explains 55% of the variation in crime.(multiple R-squared).</p>
<p>Looking at the coefficients (values under the <code>Estimate</code> column), you see that <em>higher</em> incomes are associated with <em>lower</em> values of crime (negative coefficient) and <em>higher</em> housing values are associated with <em>lower</em> crime. The marginal effect of income on crime is -1.6 and the marginal effect of housing value on crime is -.27.</p>
<p>The extractor function <code>residuals()</code> is used to get the model residuals as a vector object.</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="tuesday-november-29-2022.html#cb5-1" aria-hidden="true" tabindex="-1"></a>( res <span class="ot">&lt;-</span> model.lm <span class="sc">|&gt;</span></span>
<span id="cb5-2"><a href="tuesday-november-29-2022.html#cb5-2" aria-hidden="true" tabindex="-1"></a>   <span class="fu">residuals</span>() )</span></code></pre></div>
<pre><code>##           1           2           3           4           5           6 
##   0.3465419  -3.6947990  -5.2873940 -19.9855151   6.4475490  -9.0734793 
##           7           8           9          10          11          12 
## -34.4177224  -1.9146840   4.3960594  13.5091017  10.9800573   9.5877236 
##          13          14          15          16          17          18 
##   4.7728320  16.1128397   0.6675424   3.5491565  -4.6630963  12.8399569 
##          19          20          21          22          23          24 
##  12.8428644   3.4948724  -6.0537589  -7.8697868  -1.7037730   6.9913819 
##          25          26          27          28          29          30 
##  11.0984343  -9.1741523  10.8026296   7.1086321  14.9005133  28.6487456 
##          31          32          33          34          35          36 
## -15.1722792  -8.1776706  -4.3438864 -12.9749799  -1.5798172 -14.4376850 
##          37          38          39          40          41          42 
##  12.8687861   9.0515532  -9.1569014  12.2449674  -2.7098171   1.3443547 
##          43          44          45          46          47          48 
##  -3.5432909  -6.3880045  -9.4155428  -1.9731210   1.1150296 -15.7632989 
##          49 
##  -6.2476690</code></pre>
<p>There are 49 residuals, one for each tract. The residuals are the difference between the observed crime rates and the predicted crime rates (observed - predicted). A residual that has a value greater than 0 indicates that the model <em>under</em> predicts the observed crime rate in that tract and a residual that has a value less than 0 indicates that the model <em>over</em> predicts the observed crime rate.</p>
<p>Inferences made about the relationships between the response and explanatory variables are valid under the assumption that the residuals can be adequately described by a normal distribution. You check this with the <code>sm::sm.density()</code> function with the first argument the vector of residuals (<code>res</code>) and the argument <code>model = "Normal"</code>.</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="tuesday-november-29-2022.html#cb7-1" aria-hidden="true" tabindex="-1"></a>res <span class="sc">|&gt;</span></span>
<span id="cb7-2"><a href="tuesday-november-29-2022.html#cb7-2" aria-hidden="true" tabindex="-1"></a>  sm<span class="sc">::</span><span class="fu">sm.density</span>(<span class="at">model =</span> <span class="st">&quot;Normal&quot;</span>)</span></code></pre></div>
<p><img src="QG-2022_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<p>The density curve of the residuals (black line) fits within the blue ribbon that defines a normal distribution, so there is no evidence against normally distributed residuals.</p>
<p>Next create a map of the model residuals. Do the residuals show any pattern of clustering?</p>
<p><em>Key point</em>: The values in the vector of residuals <code>res</code> are arranged in the same order as the rows in the simple feature data frame.</p>
<p>So you create a new column in the simple feature data frame using the <code>$</code> syntax calling the new column <code>res</code>. Now the residuals are aligned with the corresponding simple feature geometry defining the tract boundary.</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="tuesday-november-29-2022.html#cb8-1" aria-hidden="true" tabindex="-1"></a>CC.sf<span class="sc">$</span>res <span class="ot">&lt;-</span> res</span>
<span id="cb8-2"><a href="tuesday-november-29-2022.html#cb8-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-3"><a href="tuesday-november-29-2022.html#cb8-3" aria-hidden="true" tabindex="-1"></a>CC.sf <span class="sc">|&gt;</span></span>
<span id="cb8-4"><a href="tuesday-november-29-2022.html#cb8-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>()</span></code></pre></div>
<pre><code>## Simple feature collection with 6 features and 21 fields
## Geometry type: POLYGON
## Dimension:     XY
## Bounding box:  xmin: 7.950089 ymin: 12.86109 xmax: 10.1806 ymax: 14.74245
## CRS:           NA
##       AREA PERIMETER COLUMBUS_ COLUMBUS_I POLYID NEIG  HOVAL    INC    CRIME
## 1 0.309441  2.440629         2          5      1    5 80.467 19.531 15.72598
## 2 0.259329  2.236939         3          1      2    1 44.567 21.232 18.80175
## 3 0.192468  2.187547         4          6      3    6 26.350 15.956 30.62678
## 4 0.083841  1.427635         5          2      4    2 33.200  4.477 32.38776
## 5 0.488888  2.997133         6          7      5    7 23.225 11.252 50.73151
## 6 0.283079  2.335634         7          8      6    8 28.750 16.029 26.06666
##       OPEN    PLUMB DISCBD     X     Y NSA NSB EW CP THOUS NEIGNO
## 1 2.850747 0.217155   5.03 38.80 44.07   1   1  1  0  1000   1005
## 2 5.296720 0.320581   4.27 35.62 42.38   1   1  0  0  1000   1001
## 3 4.534649 0.374404   3.89 39.82 41.18   1   1  1  0  1000   1006
## 4 0.394427 1.186944   3.70 36.50 40.52   1   1  0  0  1000   1002
## 5 0.405664 0.624596   2.83 40.01 38.00   1   1  1  0  1000   1007
## 6 0.563075 0.254130   3.78 43.75 39.28   1   1  1  0  1000   1008
##                         geometry         res
## 1 POLYGON ((8.624129 14.23698...   0.3465419
## 2 POLYGON ((8.25279 14.23694,...  -3.6947990
## 3 POLYGON ((8.653305 14.00809...  -5.2873940
## 4 POLYGON ((8.459499 13.82035... -19.9855151
## 5 POLYGON ((8.685274 13.63952...   6.4475490
## 6 POLYGON ((9.401384 13.5504,...  -9.0734793</code></pre>
<p>Now you make two maps using the functions from the {tmap} package, one showing the crime rates and the other showing the residuals from the linear model of crime.</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="tuesday-november-29-2022.html#cb10-1" aria-hidden="true" tabindex="-1"></a>tmap<span class="sc">::</span><span class="fu">tm_shape</span>(CC.sf) <span class="sc">+</span></span>
<span id="cb10-2"><a href="tuesday-november-29-2022.html#cb10-2" aria-hidden="true" tabindex="-1"></a>  tmap<span class="sc">::</span><span class="fu">tm_fill</span>(<span class="at">col =</span> <span class="fu">c</span>(<span class="st">&quot;CRIME&quot;</span>, <span class="st">&quot;res&quot;</span>), <span class="at">title =</span> <span class="st">&quot;&quot;</span>) <span class="sc">+</span></span>
<span id="cb10-3"><a href="tuesday-november-29-2022.html#cb10-3" aria-hidden="true" tabindex="-1"></a>  tmap<span class="sc">::</span><span class="fu">tm_borders</span>(<span class="at">col =</span> <span class="st">&quot;gray70&quot;</span>) <span class="sc">+</span></span>
<span id="cb10-4"><a href="tuesday-november-29-2022.html#cb10-4" aria-hidden="true" tabindex="-1"></a>  tmap<span class="sc">::</span><span class="fu">tm_layout</span>(<span class="at">title =</span> <span class="fu">c</span>(<span class="st">&quot;Crime rate&quot;</span>, </span>
<span id="cb10-5"><a href="tuesday-november-29-2022.html#cb10-5" aria-hidden="true" tabindex="-1"></a>                            <span class="st">&quot;Linear model residuals&quot;</span>))</span></code></pre></div>
<pre><code>## Warning: Currect projection of shape CC.sf unknown. Long-lat (WGS84) is assumed.</code></pre>
<pre><code>## Variable(s) &quot;res&quot; contains positive and negative values, so midpoint is set to 0. Set midpoint = NA to show the full spectrum of the color palette.</code></pre>
<p><img src="QG-2022_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<p>As you saw last time, crime rates tend to cluster. Residuals from a model of crime also show some clustering. Tracts with negative residuals are noted across the southwestern and southern part of the city and a group of tracts with positive residuals toward the center.</p>
<p>Clustering in the residuals appears to be less than with the crime values themselves. That is, after accounting for regional factors related to crime, the autocorrelation is reduced.</p>
<p>To determine the amount of spatial autocorrelation in crime use the <code>spdep::moran.test()</code> function after specifying the neighborhood topology and the weights. Here you use the default queen contiguity and row standardized weights.</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="tuesday-november-29-2022.html#cb13-1" aria-hidden="true" tabindex="-1"></a>nbs <span class="ot">&lt;-</span> CC.sf <span class="sc">|&gt;</span></span>
<span id="cb13-2"><a href="tuesday-november-29-2022.html#cb13-2" aria-hidden="true" tabindex="-1"></a>  spdep<span class="sc">::</span><span class="fu">poly2nb</span>()</span>
<span id="cb13-3"><a href="tuesday-november-29-2022.html#cb13-3" aria-hidden="true" tabindex="-1"></a>wts <span class="ot">&lt;-</span> nbs <span class="sc">|&gt;</span></span>
<span id="cb13-4"><a href="tuesday-november-29-2022.html#cb13-4" aria-hidden="true" tabindex="-1"></a>  spdep<span class="sc">::</span><span class="fu">nb2listw</span>()</span>
<span id="cb13-5"><a href="tuesday-november-29-2022.html#cb13-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-6"><a href="tuesday-november-29-2022.html#cb13-6" aria-hidden="true" tabindex="-1"></a>CC.sf<span class="sc">$</span>CRIME <span class="sc">|&gt;</span></span>
<span id="cb13-7"><a href="tuesday-november-29-2022.html#cb13-7" aria-hidden="true" tabindex="-1"></a>  spdep<span class="sc">::</span><span class="fu">moran.test</span>(<span class="at">listw =</span> wts)</span></code></pre></div>
<pre><code>## 
##  Moran I test under randomisation
## 
## data:  CC.sf$CRIME  
## weights: wts    
## 
## Moran I statistic standard deviate = 5.5894, p-value = 1.139e-08
## alternative hypothesis: greater
## sample estimates:
## Moran I statistic       Expectation          Variance 
##       0.500188557      -0.020833333       0.008689289</code></pre>
<p>To determine the amount of autocorrelation in the model residuals use the <code>spdep::lm.morantest()</code> function, passing the regression model object and the weights object to it.</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="tuesday-november-29-2022.html#cb15-1" aria-hidden="true" tabindex="-1"></a>model.lm <span class="sc">|&gt;</span></span>
<span id="cb15-2"><a href="tuesday-november-29-2022.html#cb15-2" aria-hidden="true" tabindex="-1"></a>  spdep<span class="sc">::</span><span class="fu">lm.morantest</span>(<span class="at">listw =</span> wts)</span></code></pre></div>
<pre><code>## 
##  Global Moran I for regression residuals
## 
## data:  
## model: lm(formula = f, data = CC.sf)
## weights: wts
## 
## Moran I statistic standard deviate = 2.8393, p-value = 0.00226
## alternative hypothesis: greater
## sample estimates:
## Observed Moran I      Expectation         Variance 
##      0.222109407     -0.033418335      0.008099305</code></pre>
<p>Moran’s I on the model residuals is .22. This compares with the value of .5 on the value of crime alone. This is what you might have expected given the maps of crime and the residuals.</p>
<p>Part of the autocorrelation in the crime rates is statistically ‘absorbed’ by the explanatory factors.</p>
<p>The <span class="math inline">\(p\)</span>-value on I of .002, thus you reject the null hypothesis of no spatial autocorrelation in the model residuals and conclude that a spatial regression model would be an improvement over the non-spatial OLS model. The <span class="math inline">\(z\)</span>-value (as the basis for the <span class="math inline">\(p\)</span>-value) takes into account the fact that these are residuals from a model so the variance is adjusted accordingly.</p>
<p>Given significant spatial autocorrelation in the model residuals, the next step is to choose the type of spatial regression model.</p>
</div>
<div id="choosing-a-spatial-regression-model" class="section level2 unnumbered hasAnchor">
<h2>Choosing a spatial regression model<a href="tuesday-november-29-2022.html#choosing-a-spatial-regression-model" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Linear regression models fit to spatial data can lead to improper inference because observations are not independent. This might lead to poor policy decisions. If the residuals from a linear model are strongly correlated the model is not specified properly.</p>
<p>You can try to improve the model by adding variables. If that’s not possible (no additional data, or no clue as to what variable to include), you can try a spatial regression model. Spatial regression models are widely used in econometrics and epidemiology.</p>
<p>The equation for a regression model in vector notation is</p>
<p><span class="math display">\[
y = X \beta + \varepsilon
\]</span></p>
<p>where <span class="math inline">\(y\)</span> is a <span class="math inline">\(n\)</span> by 1 vector of response variable values, <span class="math inline">\(X\)</span> is a <span class="math inline">\(n\)</span> by <span class="math inline">\(p+1\)</span> matrix containing the explanatory variables and augmented by a column of ones for the intercept term, <span class="math inline">\(\beta\)</span> is a <span class="math inline">\(p+1\)</span> <span class="math inline">\(\times\)</span> 1 vector of model coefficients and <span class="math inline">\(\varepsilon\)</span> is a <span class="math inline">\(n\)</span> by 1 vector of residuals (iid: independent and identically distributed).</p>
<p>A couple options exist if the elements of the vector <span class="math inline">\(\varepsilon\)</span> are correlated. One is to include a spatial lag term so the model becomes</p>
<p><span class="math display">\[
y = \rho W y + X \beta + \varepsilon
\]</span></p>
<p>where <span class="math inline">\(Wy\)</span> is the weighted average of the neighborhood response values with <span class="math inline">\(W\)</span> the spatial weights matrix, and <span class="math inline">\(\rho\)</span> is the autoregression coefficient. This is called a spatial autoregressive (SAR) model.</p>
<p><em>Note</em>: <span class="math inline">\(Wy\)</span> is the spatial lag variable you compute with the <code>spdep::lag.listw()</code> function and <span class="math inline">\(\rho\)</span> is Moran’s I. Thus the model is also called a spatial lag model (SLM).</p>
<p>Justification for the spatial lag model comes from domain specific but is motivated by a ‘diffusion’ process. The response variable <span class="math inline">\(y_i\)</span> is influenced by the explanatory variables at location <span class="math inline">\(i\)</span> and by explanatory variables at locations <span class="math inline">\(j\)</span>.</p>
<p><span class="math inline">\(\rho Wy\)</span> is called the <em>spatial signal</em> term and <span class="math inline">\(\beta X\)</span> is called the <em>trend</em> term.</p>
<p>Another option is to include a spatial error term so the model becomes</p>
<p><span class="math display">\[
y = X\beta + \lambda W \epsilon + u
\]</span></p>
<p>where <span class="math inline">\(\lambda\)</span> is the autoregression coefficient, <span class="math inline">\(W\epsilon\)</span> is the spatial error term representing the weighted average of the neighborhood residuals, and <span class="math inline">\(u\)</span> are the overall residuals assumed to be iid. This is called a spatial error model (SEM).</p>
<p>Here the lag term is computed using the residuals rather the response variable.</p>
<p>Application of the spatial error model is motivated by the omitted (unobserved) variable bias. Examples of unobservable (latent) variables include local culture, social capital, neighborhood readiness.</p>
<p>Importantly you would expect the latent variable to be spatially correlated (e.g., culture will be similar across neighborhoods). Another motivation for considering a spatial error model is heterogeneity.</p>
<p>In the absence of domain-specific knowledge of the process that might be responsible for the spatially autocorrelated residuals, you can run statistical tests on the linear model.</p>
<p>The tests are performed with the <code>spdep::lm.LMtests()</code> function. The <code>LM</code> stands for ‘Lagrange multiplier’ indicating that the technique simultaneously determines the coefficients on the explanatory variables AND the coefficient on the spatial lag variable.</p>
<p>The test type is specified as a character string. The tests should be considered in a sequence starting with the standard versions and moving to the ‘robust’ versions if the choice is ambiguous based on the standard versions.</p>
<p>To perform LM tests you specify the model object, the weights matrix, and the two model types using the <code>test =</code> argument. The model types are specified as character strings <code>"LMerr"</code> and <code>"LMlag"</code> for the spatial error and lag models, respectively.</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="tuesday-november-29-2022.html#cb17-1" aria-hidden="true" tabindex="-1"></a>model.lm <span class="sc">|&gt;</span></span>
<span id="cb17-2"><a href="tuesday-november-29-2022.html#cb17-2" aria-hidden="true" tabindex="-1"></a>  spdep<span class="sc">::</span><span class="fu">lm.LMtests</span>(<span class="at">listw =</span> wts, </span>
<span id="cb17-3"><a href="tuesday-november-29-2022.html#cb17-3" aria-hidden="true" tabindex="-1"></a>                    <span class="at">test =</span> <span class="fu">c</span>(<span class="st">&quot;LMerr&quot;</span>, <span class="st">&quot;LMlag&quot;</span>))</span></code></pre></div>
<pre><code>## 
##  Lagrange multiplier diagnostics for spatial dependence
## 
## data:  
## model: lm(formula = f, data = CC.sf)
## weights: wts
## 
## LMerr = 5.2062, df = 1, p-value = 0.02251
## 
## 
##  Lagrange multiplier diagnostics for spatial dependence
## 
## data:  
## model: lm(formula = f, data = CC.sf)
## weights: wts
## 
## LMlag = 8.898, df = 1, p-value = 0.002855</code></pre>
<p>The output shows that both the spatial error and spatial lag models are significant (<span class="math inline">\(p\)</span>-value &lt; .15). Ideally one model is significant and the other is not, and you choose the model that is significant.</p>
<p>Since both are significant, you test again. This time you use the robust forms of the statistics with character strings <code>"RLMerr"</code> and <code>"RLMlag"</code> in the <code>test =</code> argument.</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="tuesday-november-29-2022.html#cb19-1" aria-hidden="true" tabindex="-1"></a>model.lm <span class="sc">|&gt;</span></span>
<span id="cb19-2"><a href="tuesday-november-29-2022.html#cb19-2" aria-hidden="true" tabindex="-1"></a>  spdep<span class="sc">::</span><span class="fu">lm.LMtests</span>(<span class="at">listw =</span> wts, </span>
<span id="cb19-3"><a href="tuesday-november-29-2022.html#cb19-3" aria-hidden="true" tabindex="-1"></a>                    <span class="at">test =</span> <span class="fu">c</span>(<span class="st">&quot;RLMerr&quot;</span>, <span class="st">&quot;RLMlag&quot;</span>))</span></code></pre></div>
<pre><code>## 
##  Lagrange multiplier diagnostics for spatial dependence
## 
## data:  
## model: lm(formula = f, data = CC.sf)
## weights: wts
## 
## RLMerr = 0.043906, df = 1, p-value = 0.834
## 
## 
##  Lagrange multiplier diagnostics for spatial dependence
## 
## data:  
## model: lm(formula = f, data = CC.sf)
## weights: wts
## 
## RLMlag = 3.7357, df = 1, p-value = 0.05326</code></pre>
<p>Here the error model has a large <span class="math inline">\(p\)</span>-value and the lag model has a <span class="math inline">\(p\)</span>-value that is less than .15 so you choose the lag model for your spatial regression.</p>
<p>A decision tree (from Luc Anselin) shows the sequence of tests for making a choice about which type of spatial model to use <a href="http://myweb.fsu.edu/jelsner/temp/SpatialRegressionDecisionTree.png">Decision Tree</a></p>
<p>If both tests show significant models, then you should fit both models and check which one gives the lowest information criteria (AIC). Another options is to include both a spatial lag term and a spatial error term into a single model.</p>
</div>
<div id="fitting-and-interpreting-spatial-regression-models" class="section level2 unnumbered hasAnchor">
<h2>Fitting and interpreting spatial regression models<a href="tuesday-november-29-2022.html#fitting-and-interpreting-spatial-regression-models" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Recall that the marginal effect of income on crime is -1.6 and the marginal effect of housing value on crime is -.27.</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="tuesday-november-29-2022.html#cb21-1" aria-hidden="true" tabindex="-1"></a>model.lm</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = f, data = CC.sf)
## 
## Coefficients:
## (Intercept)          INC        HOVAL  
##     68.6190      -1.5973      -0.2739</code></pre>
<p>A nice way to visualize the relative significance of the explanatory variables is to make a plot. Here you use the <code>broom::tidy()</code> method and then <code>ggplot()</code> as follows.</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="tuesday-november-29-2022.html#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span>(<span class="sc">!</span><span class="fu">require</span>(broom)) <span class="fu">install.packages</span>(<span class="at">pkgs =</span> <span class="st">&quot;broom&quot;</span>, <span class="at">repos =</span> <span class="st">&quot;http://cran.us.r-project.org&quot;</span>)</span></code></pre></div>
<pre><code>## Loading required package: broom</code></pre>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="tuesday-november-29-2022.html#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb25-2"><a href="tuesday-november-29-2022.html#cb25-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-3"><a href="tuesday-november-29-2022.html#cb25-3" aria-hidden="true" tabindex="-1"></a>( d <span class="ot">&lt;-</span> broom<span class="sc">::</span><span class="fu">tidy</span>(model.lm, </span>
<span id="cb25-4"><a href="tuesday-november-29-2022.html#cb25-4" aria-hidden="true" tabindex="-1"></a>                   <span class="at">conf.int =</span> <span class="cn">TRUE</span>) )</span></code></pre></div>
<pre><code>## # A tibble: 3 × 7
##   term        estimate std.error statistic  p.value conf.low conf.high
##   &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
## 1 (Intercept)   68.6       4.74      14.5  9.21e-19   59.1     78.2   
## 2 INC           -1.60      0.334     -4.78 1.83e- 5   -2.27    -0.925 
## 3 HOVAL         -0.274     0.103     -2.65 1.09e- 2   -0.482   -0.0662</code></pre>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="tuesday-november-29-2022.html#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb27-2"><a href="tuesday-november-29-2022.html#cb27-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-3"><a href="tuesday-november-29-2022.html#cb27-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(d[<span class="sc">-</span><span class="dv">1</span>,], <span class="fu">aes</span>(<span class="at">x =</span> estimate,  <span class="co"># do not plot the intercept term</span></span>
<span id="cb27-4"><a href="tuesday-november-29-2022.html#cb27-4" aria-hidden="true" tabindex="-1"></a>                   <span class="at">y =</span> term, </span>
<span id="cb27-5"><a href="tuesday-november-29-2022.html#cb27-5" aria-hidden="true" tabindex="-1"></a>                   <span class="at">xmin =</span> conf.low, </span>
<span id="cb27-6"><a href="tuesday-november-29-2022.html#cb27-6" aria-hidden="true" tabindex="-1"></a>                   <span class="at">xmax =</span> conf.high, </span>
<span id="cb27-7"><a href="tuesday-november-29-2022.html#cb27-7" aria-hidden="true" tabindex="-1"></a>                   <span class="at">height =</span> <span class="dv">0</span>)) <span class="sc">+</span></span>
<span id="cb27-8"><a href="tuesday-november-29-2022.html#cb27-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb27-9"><a href="tuesday-november-29-2022.html#cb27-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">0</span>, <span class="at">lty =</span> <span class="dv">4</span>) <span class="sc">+</span></span>
<span id="cb27-10"><a href="tuesday-november-29-2022.html#cb27-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_errorbarh</span>()</span></code></pre></div>
<p><img src="QG-2022_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
<p>The two explanatory variables are plotted on the vertical axis. The marginal effect estimate is shown as a point and the confidence interval around the estimate is shown as a horizontal error bar. The default confidence level is 95% (<code>conf.level = .95</code>). The effects are statistically significant as the confidence intervals do not intersect the zero line (dashed-dotted vertical line).</p>
<p>But you’ve shown above that the model residuals have significant spatial autocorrelation so reporting the marginal effects with this regression model is incorrect.</p>
<p>Instead, you fit a spatially-lagged Y model using the <code>lagsarlm()</code> function from the {spatialreg} package. The model is</p>
<p><span class="math display">\[
y = \rho W y + X \beta + \varepsilon
\]</span></p>
<p>where <span class="math inline">\(Wy\)</span> is the weighted average of the neighborhood response values (spatial lag variable) with <span class="math inline">\(W\)</span> the spatial weights matrix, and <span class="math inline">\(\rho\)</span> is the autoregression coefficient.</p>
<p>The <code>spatialreg::lagsarlm()</code> function first determines a value for <span class="math inline">\(\rho\)</span> ( with the internal <code>optimize()</code> function) and then the <span class="math inline">\(\beta\)</span>’s are obtained using generalized least squares (GLS). The model formula <code>f</code> is the same as what you used to fit the linear regression model above. You save the model object as <code>model.slym</code>.</p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="tuesday-november-29-2022.html#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span>(<span class="sc">!</span><span class="fu">require</span>(spatialreg)) <span class="fu">install.packages</span>(<span class="at">pkgs =</span> <span class="st">&quot;spatialreg&quot;</span>, <span class="at">repos =</span> <span class="st">&quot;http://cran.us.r-project.org&quot;</span>)</span></code></pre></div>
<pre><code>## Loading required package: spatialreg</code></pre>
<pre><code>## Loading required package: spData</code></pre>
<pre><code>## Loading required package: Matrix</code></pre>
<pre><code>## Loading required package: sf</code></pre>
<pre><code>## Linking to GEOS 3.10.2, GDAL 3.4.2, PROJ 8.2.1; sf_use_s2() is TRUE</code></pre>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="tuesday-november-29-2022.html#cb34-1" aria-hidden="true" tabindex="-1"></a>model.slym <span class="ot">&lt;-</span> spatialreg<span class="sc">::</span><span class="fu">lagsarlm</span>(<span class="at">formula =</span> f, </span>
<span id="cb34-2"><a href="tuesday-november-29-2022.html#cb34-2" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">data =</span> CC.sf, </span>
<span id="cb34-3"><a href="tuesday-november-29-2022.html#cb34-3" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">listw =</span> wts)</span>
<span id="cb34-4"><a href="tuesday-november-29-2022.html#cb34-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-5"><a href="tuesday-november-29-2022.html#cb34-5" aria-hidden="true" tabindex="-1"></a>model.slym <span class="sc">|&gt;</span></span>
<span id="cb34-6"><a href="tuesday-november-29-2022.html#cb34-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summary</span>()</span></code></pre></div>
<pre><code>## 
## Call:spatialreg::lagsarlm(formula = f, data = CC.sf, listw = wts)
## 
## Residuals:
##        Min         1Q     Median         3Q        Max 
## -37.652017  -5.334611   0.071473   6.107196  23.302618 
## 
## Type: lag 
## Coefficients: (asymptotic standard errors) 
##              Estimate Std. Error z value  Pr(&gt;|z|)
## (Intercept) 45.603250   7.257404  6.2837 3.306e-10
## INC         -1.048728   0.307406 -3.4115  0.000646
## HOVAL       -0.266335   0.089096 -2.9893  0.002796
## 
## Rho: 0.42333, LR test value: 9.4065, p-value: 0.0021621
## Asymptotic standard error: 0.11951
##     z-value: 3.5422, p-value: 0.00039686
## Wald statistic: 12.547, p-value: 0.00039686
## 
## Log likelihood: -182.674 for lag model
## ML residual variance (sigma squared): 96.857, (sigma: 9.8416)
## Number of observations: 49 
## Number of parameters estimated: 5 
## AIC: 375.35, (AIC for lm: 382.75)
## LM test for residual autocorrelation
## test value: 0.24703, p-value: 0.61917</code></pre>
<p>The first batch of output concerns the model residuals and the coefficients on the explanatory variables. Again, the model residuals are the observed crime rates minus the predicted crime rates.</p>
<p>The coefficients on income and housing have the same sign (negative) and they remain statistically significant (-1.05 for income and -.27 for housing value). But you can’t interpret these coefficients as marginal effects.</p>
<p>The next set of output is about the coefficient of spatial autocorrelation (<span class="math inline">\(\rho\)</span>). The value is .423 and a likelihood ratio test gives a value of 9.41 which translates to a <span class="math inline">\(p\)</span>-value of .002. The null hypothesis is the autocorrelation is zero, so you confidently reject it. This is consistent with the significant Moran’s I value that you found in the linear model residuals.</p>
<p>Two other tests are performed on the value of <span class="math inline">\(\rho\)</span> including a z-test (t-test) using the asymptotic standard error. Both tests confirm that the lag term should be included in the model for crime.</p>
<p>In spatial models that contain a lagged response term, the coefficients are not marginal effects. The spatial lag model allows for ‘spillover’. That is a change in an explanatory variable anywhere in the study domain will affect the value of the response variable <em>everywhere</em>. Spillover occurs even when the neighborhood weights matrix represents local contiguity. The spillover makes interpreting the coefficients more complicated.</p>
<p>With a spatially-lagged Y model a change in the value of an explanatory variable results in both <em>direct</em> and <em>indirect</em> effects on the response variable. For example, the direct effect gives the impact a change in income has on crime averaged over all tracts. It takes into account the effects that occur from a change in the <span class="math inline">\(i\)</span>th tract’s income on crime across neighboring tracts.</p>
<p>The indirect effect gives the impact of a change in income has on crime averaged over all <em>other</em> tracts. The indirect effect represent spillovers. The influences on the dependent variable <span class="math inline">\(y\)</span> in a region rendered by change in <span class="math inline">\(x\)</span> in some <em>other</em> region. For example, if all tracts <span class="math inline">\(i \ne j\)</span> (i not equal to j) increase their income, what will be the impact on crime in region <span class="math inline">\(i\)</span>?</p>
<p>The total effect (TE) is the sum of the direct and indirect effects. It measures the total cumulative impact on crime arising from one tract <span class="math inline">\(j\)</span> increasing its income over all other tracts (on average). It is given by</p>
<p><span class="math display">\[
\hbox{TE} = \left(\frac{\beta_k}{1-\rho^2}\right)\left(1 + \rho\right)
\]</span></p>
<p>where <span class="math inline">\(\beta_k\)</span> is the effect of variable <span class="math inline">\(k\)</span> and <span class="math inline">\(\rho\)</span> is the spatial autocorrelation coefficient. With <span class="math inline">\(\rho = 0\)</span> TE is <span class="math inline">\(\beta_k\)</span>.</p>
<p>Here <span class="math inline">\(\beta_{INC}\)</span> is -1.0487 and <span class="math inline">\(\rho\)</span> is .4233, so the total effect is</p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="tuesday-november-29-2022.html#cb36-1" aria-hidden="true" tabindex="-1"></a>( TE_INC <span class="ot">&lt;-</span> <span class="sc">-</span><span class="fl">1.0487</span> <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">-</span> .<span class="dv">4233</span><span class="sc">^</span><span class="dv">2</span>) <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">+</span> .<span class="dv">4233</span>) )</span></code></pre></div>
<pre><code>## [1] -1.81845</code></pre>
<p>The direct, indirect, and total effects are shown using the <code>spatialreg::impacts()</code> function.</p>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="tuesday-november-29-2022.html#cb38-1" aria-hidden="true" tabindex="-1"></a>model.slym <span class="sc">|&gt;</span> </span>
<span id="cb38-2"><a href="tuesday-november-29-2022.html#cb38-2" aria-hidden="true" tabindex="-1"></a>  spatialreg<span class="sc">::</span><span class="fu">impacts</span>(<span class="at">listw =</span> wts)</span></code></pre></div>
<pre><code>## Impact measures (lag, exact):
##           Direct   Indirect      Total
## INC   -1.1008955 -0.7176833 -1.8185788
## HOVAL -0.2795832 -0.1822627 -0.4618459</code></pre>
<p>The direct effects are the changes in the response variable of a particular region arising from a one unit increase in an explanatory variable in that region.</p>
<p>The indirect effects are the changes in the response variable of a particular region arising from a one unit increase in an explanatory variable in another region. For example, due to spatial autocorrelation, a one-unit change in the income variable in region 1 affects the crime rate in regions 2 and 3.</p>
<p>The next set of output concerns the overall model fit. It includes the log likelihood value and the AIC (Akaike Information Criterion). The AIC value for the linear model is included. Here it is clear that the spatial lag model is an improvement (smaller AIC) over the aspatial model.</p>
<p>The larger the likelihood, the better the model and two times the difference in log likelihoods from two competing models divided by the number of observations gives a scale for how much improvement.</p>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="tuesday-november-29-2022.html#cb40-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="dv">2</span> <span class="sc">*</span> (<span class="fu">logLik</span>(model.slym) <span class="sc">-</span> <span class="fu">logLik</span>(model.lm))<span class="sc">/</span><span class="dv">49</span></span>
<span id="cb40-2"><a href="tuesday-november-29-2022.html#cb40-2" aria-hidden="true" tabindex="-1"></a>x[<span class="dv">1</span>]</span></code></pre></div>
<pre><code>## [1] 0.1919701</code></pre>
<p>Improvement table</p>
<table>
<thead>
<tr class="header">
<th>Likelihood difference</th>
<th>Qualitative improvement</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>huge</td>
</tr>
<tr class="even">
<td>.1</td>
<td>large</td>
</tr>
<tr class="odd">
<td>.01</td>
<td>good</td>
</tr>
<tr class="even">
<td>.001</td>
<td>okay</td>
</tr>
</tbody>
</table>
<p>The final bit of output is a Lagrange multiplier test for remaining autocorrelation. The null hypothesis is there is no remaining autocorrelation since we have a lag term in the model. The result is a high <span class="math inline">\(p\)</span>-value so you are satisfied that the lag term takes care of the autocorrelation.</p>
<p>Compare the spatial lag model to a spatial error model. Here you use the <code>spatialreg::errorsarlm()</code> function.</p>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="tuesday-november-29-2022.html#cb42-1" aria-hidden="true" tabindex="-1"></a>model.sem <span class="ot">&lt;-</span> spatialreg<span class="sc">::</span><span class="fu">errorsarlm</span>(<span class="at">formula =</span> f, </span>
<span id="cb42-2"><a href="tuesday-november-29-2022.html#cb42-2" aria-hidden="true" tabindex="-1"></a>                                    <span class="at">data =</span> CC.sf, </span>
<span id="cb42-3"><a href="tuesday-november-29-2022.html#cb42-3" aria-hidden="true" tabindex="-1"></a>                                    <span class="at">listw =</span> wts)</span>
<span id="cb42-4"><a href="tuesday-november-29-2022.html#cb42-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model.sem)</span></code></pre></div>
<pre><code>## 
## Call:spatialreg::errorsarlm(formula = f, data = CC.sf, listw = wts)
## 
## Residuals:
##       Min        1Q    Median        3Q       Max 
## -34.65998  -6.16943  -0.70623   7.75392  23.43878 
## 
## Type: error 
## Coefficients: (asymptotic standard errors) 
##              Estimate Std. Error z value  Pr(&gt;|z|)
## (Intercept) 60.279469   5.365594 11.2344 &lt; 2.2e-16
## INC         -0.957305   0.334231 -2.8642 0.0041806
## HOVAL       -0.304559   0.092047 -3.3087 0.0009372
## 
## Lambda: 0.54675, LR test value: 7.2556, p-value: 0.0070679
## Asymptotic standard error: 0.13805
##     z-value: 3.9605, p-value: 7.4786e-05
## Wald statistic: 15.686, p-value: 7.4786e-05
## 
## Log likelihood: -183.7494 for error model
## ML residual variance (sigma squared): 97.674, (sigma: 9.883)
## Number of observations: 49 
## Number of parameters estimated: 5 
## AIC: 377.5, (AIC for lm: 382.75)</code></pre>
<p>You find the coefficient of spatial autocorrelation (<span class="math inline">\(\lambda\)</span>) is significant, but the log likelihood value from the model is smaller (-183.7) and the AIC value is larger (377.5) compared with corresponding values from the lag model. This is consistent with the Lagrange multiplier (LM) tests indicating the spatial lag model is more appropriate.</p>
<p>Also you can compare the log likelihoods from the two spatial regression models that you fit.</p>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="tuesday-november-29-2022.html#cb44-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="dv">2</span> <span class="sc">*</span> (<span class="fu">logLik</span>(model.slym) <span class="sc">-</span> <span class="fu">logLik</span>(model.sem))<span class="sc">/</span><span class="dv">49</span></span>
<span id="cb44-2"><a href="tuesday-november-29-2022.html#cb44-2" aria-hidden="true" tabindex="-1"></a>x[<span class="dv">1</span>]</span></code></pre></div>
<pre><code>## [1] 0.04389617</code></pre>
<p>With a value of .04 you conclude that there is good improvement of the lag model over the error model. Again, this is consistent with your decision above to use the lag model.</p>
<p>With the spatial error model the coefficients can be interpreted as marginal effects like with the linear model.</p>
<p>If there are large differences (e.g., different signs) between the coefficient estimate from SEM and the linear model, this suggests that neither model is yielding parameters estimates matching the underlying parameters of the data generating process.</p>
<p>You test whether there is a significant difference in coefficient estimates with the Hausman test under the hypothesis of no difference.</p>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="tuesday-november-29-2022.html#cb46-1" aria-hidden="true" tabindex="-1"></a>model.sem <span class="sc">|&gt;</span></span>
<span id="cb46-2"><a href="tuesday-november-29-2022.html#cb46-2" aria-hidden="true" tabindex="-1"></a>  spatialreg<span class="sc">::</span><span class="fu">Hausman.test</span>()</span></code></pre></div>
<pre><code>## 
##  Spatial Hausman test (asymptotic)
## 
## data:  NULL
## Hausman test = 5.6132, df = 3, p-value = 0.132</code></pre>
<p>The <span class="math inline">\(p\)</span>-value gives inconclusive evidence that the coefficients are different and that maybe the SEM is not the right way to proceed with these data.</p>
<p>The <code>predict()</code> method implements the <code>predict.sarlm()</code> function to calculate predictions from the spatial regression model. The prediction on a spatial lag Y model is decomposed into a “trend” term (explanatory variable effect) and a “signal” term (spatial smoother). The predicted fit is the sum of the trend and the signal terms when using the spatial lag model.</p>
<p>You make predictions with the <code>predict()</code> method under the assumption that the mean response is known. You examine the structure of the corresponding predict object.</p>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="tuesday-november-29-2022.html#cb48-1" aria-hidden="true" tabindex="-1"></a>( predictedValues <span class="ot">&lt;-</span> <span class="fu">predict</span>(model.slym) )</span></code></pre></div>
<pre><code>## This method assumes the response is known - see manual page</code></pre>
<pre><code>##          fit     trend    signal
## 1  14.151553  3.689376 10.462177
## 2  22.577864 11.466910 11.110954
## 3  34.302562 21.851821 12.450741
## 4  46.732511 32.065778 14.666733
## 5  44.747335 27.617335 17.130001
## 6  38.333111 21.136061 17.197049
## 7  37.830286 16.778971 21.051314
## 8  41.393775 23.826139 17.567636
## 9  28.792040 13.151106 15.640934
## 10 16.390116  5.667968 10.722148
## 11 53.631524 32.525601 21.105923
## 12 48.074429 29.765567 18.308862
## 13 40.608933 24.482783 16.126150
## 14 41.856029 23.729007 18.127021
## 15 51.665885 30.455130 21.210754
## 16 54.767238 32.599604 22.167634
## 17 31.866732 24.208333  7.658399
## 18 37.461969 15.795681 21.666289
## 19 44.929428 25.269281 19.660147
## 20  5.110404 -8.624965 13.735369
## 21 47.617356 29.109014 18.508343
## 22 40.412907 25.213797 15.199111
## 23 18.640125 10.704444  7.935681
## 24 39.747460 16.504544 23.242917
## 25 53.116667 31.962568 21.154099
## 26 52.303708 31.717686 20.586022
## 27 39.228078 25.171897 14.056180
## 28 51.354572 31.278691 20.075881
## 29 49.767662 27.843360 21.924302
## 30 45.589426 25.027103 20.562323
## 31 27.465214 19.368347  8.096867
## 32 20.869990 15.004949  5.865041
## 33 44.697299 28.916463 15.780837
## 34 31.720868 22.349636  9.371232
## 35 38.985264 24.973807 14.011457
## 36 24.222607 16.283179  7.939428
## 37 37.811893 16.224746 21.587148
## 38 46.388525 27.909226 18.479299
## 39 22.524680 15.679043  6.845638
## 40  6.730001 -2.182900  8.912900
## 41 20.020878 11.101447  8.919431
## 42 14.764446  6.662086  8.102360
## 43 40.034408 24.726462 15.307946
## 44 34.026283 18.893555 15.132728
## 45 36.970894 23.393214 13.577680
## 46 13.189170  6.118277  7.070893
## 47 21.849812 14.410621  7.439191
## 48 38.162353 26.076852 12.085501
## 49 27.876102 16.356569 11.519533</code></pre>
<p>The predicted values are in the column labeled <code>fit</code>. The predicted values are a sum of the trend term (<span class="math inline">\(X\beta\)</span>) and the signal term (<span class="math inline">\(\rho W y\)</span>). The signal term is called the spatial smoother.</p>
<p>As a first-order check to see if things are what you think they should be, compare the first five predicted values with the corresponding observed values.</p>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb51-1"><a href="tuesday-november-29-2022.html#cb51-1" aria-hidden="true" tabindex="-1"></a>predictedValues[<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>]</span></code></pre></div>
<pre><code>##        1        2        3        4        5 
## 14.15155 22.57786 34.30256 46.73251 44.74734</code></pre>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="tuesday-november-29-2022.html#cb53-1" aria-hidden="true" tabindex="-1"></a>CC.sf<span class="sc">$</span>CRIME[<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>]</span></code></pre></div>
<pre><code>## [1] 15.72598 18.80175 30.62678 32.38776 50.73151</code></pre>
<p>Some predicted values are lower than the corresponding observed values and some are higher.</p>
<p>The predicted values along with the values for the trend and signal are appended to the simple features data frame using the <code>$</code> notation.</p>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb55-1"><a href="tuesday-november-29-2022.html#cb55-1" aria-hidden="true" tabindex="-1"></a>CC.sf<span class="sc">$</span>fit <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(predictedValues)</span>
<span id="cb55-2"><a href="tuesday-november-29-2022.html#cb55-2" aria-hidden="true" tabindex="-1"></a>CC.sf<span class="sc">$</span>trend <span class="ot">&lt;-</span> <span class="fu">attr</span>(predictedValues, <span class="st">&quot;trend&quot;</span>)</span>
<span id="cb55-3"><a href="tuesday-november-29-2022.html#cb55-3" aria-hidden="true" tabindex="-1"></a>CC.sf<span class="sc">$</span>signal <span class="ot">&lt;-</span> <span class="fu">attr</span>(predictedValues, <span class="st">&quot;signal&quot;</span>)</span></code></pre></div>
<p>You plot the observed versus the predicted as a scatter plot with a y = x line and a best-fit regression line.</p>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb56-1"><a href="tuesday-november-29-2022.html#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> CC.sf,</span>
<span id="cb56-2"><a href="tuesday-november-29-2022.html#cb56-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> CRIME, <span class="at">y =</span> fit)) <span class="sc">+</span></span>
<span id="cb56-3"><a href="tuesday-november-29-2022.html#cb56-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb56-4"><a href="tuesday-november-29-2022.html#cb56-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> lm, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">color =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span></span>
<span id="cb56-5"><a href="tuesday-november-29-2022.html#cb56-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>() <span class="sc">+</span></span>
<span id="cb56-6"><a href="tuesday-november-29-2022.html#cb56-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">70</span>)) <span class="sc">+</span></span>
<span id="cb56-7"><a href="tuesday-november-29-2022.html#cb56-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">70</span>)) <span class="sc">+</span></span>
<span id="cb56-8"><a href="tuesday-november-29-2022.html#cb56-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Observed Crime&quot;</span>) <span class="sc">+</span></span>
<span id="cb56-9"><a href="tuesday-november-29-2022.html#cb56-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Predicted Crime&quot;</span>)</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<p><img src="QG-2022_files/figure-html/unnamed-chunk-23-1.png" width="672" /></p>
<p>The components of the predictions are mapped and placed on the same plot.</p>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb58-1"><a href="tuesday-november-29-2022.html#cb58-1" aria-hidden="true" tabindex="-1"></a>( g1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb58-2"><a href="tuesday-november-29-2022.html#cb58-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_sf</span>(<span class="at">data =</span> CC.sf, <span class="fu">aes</span>(<span class="at">fill =</span> fit)) <span class="sc">+</span></span>
<span id="cb58-3"><a href="tuesday-november-29-2022.html#cb58-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">scale_fill_viridis_c</span>() <span class="sc">+</span></span>
<span id="cb58-4"><a href="tuesday-november-29-2022.html#cb58-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ggtitle</span>(<span class="st">&quot;Predicted Crime&quot;</span>) )</span></code></pre></div>
<p><img src="QG-2022_files/figure-html/unnamed-chunk-24-1.png" width="672" /></p>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb59-1"><a href="tuesday-november-29-2022.html#cb59-1" aria-hidden="true" tabindex="-1"></a>( g2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb59-2"><a href="tuesday-november-29-2022.html#cb59-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_sf</span>(<span class="at">data =</span> CC.sf, <span class="fu">aes</span>(<span class="at">fill =</span> trend)) <span class="sc">+</span></span>
<span id="cb59-3"><a href="tuesday-november-29-2022.html#cb59-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">scale_fill_viridis_c</span>() <span class="sc">+</span></span>
<span id="cb59-4"><a href="tuesday-november-29-2022.html#cb59-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ggtitle</span>(<span class="st">&quot;Trend (Explanatory Variables)&quot;</span>) )</span></code></pre></div>
<p><img src="QG-2022_files/figure-html/unnamed-chunk-24-2.png" width="672" /></p>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb60-1"><a href="tuesday-november-29-2022.html#cb60-1" aria-hidden="true" tabindex="-1"></a>( g3 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb60-2"><a href="tuesday-november-29-2022.html#cb60-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_sf</span>(<span class="at">data =</span> CC.sf, <span class="fu">aes</span>(<span class="at">fill =</span> signal)) <span class="sc">+</span></span>
<span id="cb60-3"><a href="tuesday-november-29-2022.html#cb60-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">scale_fill_viridis_c</span>() <span class="sc">+</span></span>
<span id="cb60-4"><a href="tuesday-november-29-2022.html#cb60-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ggtitle</span>(<span class="st">&quot;Signal&quot;</span>) )</span></code></pre></div>
<p><img src="QG-2022_files/figure-html/unnamed-chunk-24-3.png" width="672" /></p>
<div class="sourceCode" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb61-1"><a href="tuesday-november-29-2022.html#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(patchwork)</span>
<span id="cb61-2"><a href="tuesday-november-29-2022.html#cb61-2" aria-hidden="true" tabindex="-1"></a>g1 <span class="sc">+</span> g2 <span class="sc">+</span> g3</span></code></pre></div>
<p><img src="QG-2022_files/figure-html/unnamed-chunk-24-4.png" width="672" /></p>
<p>The trend term and the spatial smoother have similar ranges indicating nearly equal contributions to the predictions. The largest difference between the two terms occurs in the city’s east side.</p>
<p>A map of the difference makes this clear.</p>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb62-1"><a href="tuesday-november-29-2022.html#cb62-1" aria-hidden="true" tabindex="-1"></a>CC.sf <span class="ot">&lt;-</span> CC.sf <span class="sc">|&gt;</span></span>
<span id="cb62-2"><a href="tuesday-november-29-2022.html#cb62-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">CovMinusSmooth =</span> trend <span class="sc">-</span> signal)</span>
<span id="cb62-3"><a href="tuesday-november-29-2022.html#cb62-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-4"><a href="tuesday-november-29-2022.html#cb62-4" aria-hidden="true" tabindex="-1"></a>tmap<span class="sc">::</span><span class="fu">tm_shape</span>(CC.sf) <span class="sc">+</span></span>
<span id="cb62-5"><a href="tuesday-november-29-2022.html#cb62-5" aria-hidden="true" tabindex="-1"></a>  tmap<span class="sc">::</span><span class="fu">tm_fill</span>(<span class="at">col =</span> <span class="st">&quot;CovMinusSmooth&quot;</span>)</span></code></pre></div>
<pre><code>## Warning: Currect projection of shape CC.sf unknown. Long-lat (WGS84) is assumed.</code></pre>
<pre><code>## Variable(s) &quot;CovMinusSmooth&quot; contains positive and negative values, so midpoint is set to 0. Set midpoint = NA to show the full spectrum of the color palette.</code></pre>
<p><img src="QG-2022_files/figure-html/unnamed-chunk-25-1.png" width="672" /></p>
<p>How many tracts have a smaller residual with the lag model versus the OLS model?</p>
<div class="sourceCode" id="cb65"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb65-1"><a href="tuesday-november-29-2022.html#cb65-1" aria-hidden="true" tabindex="-1"></a>CC.sf <span class="sc">|&gt;</span></span>
<span id="cb65-2"><a href="tuesday-november-29-2022.html#cb65-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">residualsL =</span> CRIME <span class="sc">-</span> fit,</span>
<span id="cb65-3"><a href="tuesday-november-29-2022.html#cb65-3" aria-hidden="true" tabindex="-1"></a>                <span class="at">lagWins =</span> <span class="fu">abs</span>(<span class="fu">residuals</span>(model.lm)) <span class="sc">&gt;</span> <span class="fu">abs</span>(residualsL),</span>
<span id="cb65-4"><a href="tuesday-november-29-2022.html#cb65-4" aria-hidden="true" tabindex="-1"></a>                <span class="at">CovMinusSmooth =</span> trend <span class="sc">-</span> signal) <span class="sc">|&gt;</span></span>
<span id="cb65-5"><a href="tuesday-november-29-2022.html#cb65-5" aria-hidden="true" tabindex="-1"></a>  sf<span class="sc">::</span><span class="fu">st_drop_geometry</span>() <span class="sc">|&gt;</span></span>
<span id="cb65-6"><a href="tuesday-november-29-2022.html#cb65-6" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">summarize</span>(<span class="at">N =</span> <span class="fu">sum</span>(lagWins))</span></code></pre></div>
<pre><code>##    N
## 1 32</code></pre>
<p>In 32 out of the 49 tracts the residuals from the spatial model are smaller than the residuals from the OLS model.</p>
<p>Another spatial regression option is to modify the linear model to include spatially-lagged explanatory variables. This is called the spatially-lagged X model.</p>
<p><span class="math display">\[
y = X \beta + XW \theta + \varepsilon
\]</span></p>
<p>In this case the weights matrix is (post) multiplied by the matrix of X variables where <span class="math inline">\(W\)</span> is again the weights matrix and <span class="math inline">\(\theta\)</span> is a vector of coefficients for each lagged explanatory variable.</p>
<p>Here you fit the spatially-lagged X model using the <code>spatialreg::lmSLX()</code> function and save the model object as <code>model.slxm</code>.</p>
<div class="sourceCode" id="cb67"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb67-1"><a href="tuesday-november-29-2022.html#cb67-1" aria-hidden="true" tabindex="-1"></a>( model.slxm <span class="ot">&lt;-</span> spatialreg<span class="sc">::</span><span class="fu">lmSLX</span>(<span class="at">formula =</span> f, </span>
<span id="cb67-2"><a href="tuesday-november-29-2022.html#cb67-2" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">data =</span> CC.sf, </span>
<span id="cb67-3"><a href="tuesday-november-29-2022.html#cb67-3" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">listw =</span> wts) )</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = formula(paste(&quot;y ~ &quot;, paste(colnames(x)[-1], collapse = &quot;+&quot;))), 
##     data = as.data.frame(x), weights = weights)
## 
## Coefficients:
## (Intercept)          INC        HOVAL      lag.INC    lag.HOVAL  
##     74.5534      -1.0974      -0.2944      -1.3987       0.2148</code></pre>
<p>With this model, beside the direct marginal effects of income and housing value on crime, you also have the spatially-lagged indirect effects.</p>
<p>The total effect of income on crime is the sum of the direct effect and indirect effect. And again, using the <code>spatialreg::impacts()</code> function you see this.</p>
<div class="sourceCode" id="cb69"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb69-1"><a href="tuesday-november-29-2022.html#cb69-1" aria-hidden="true" tabindex="-1"></a>model.slxm <span class="sc">|&gt;</span></span>
<span id="cb69-2"><a href="tuesday-november-29-2022.html#cb69-2" aria-hidden="true" tabindex="-1"></a>  spatialreg<span class="sc">::</span><span class="fu">impacts</span>(<span class="at">listw =</span> wts)</span></code></pre></div>
<pre><code>## Impact measures (SlX, estimable):
##           Direct  Indirect       Total
## INC   -1.0973898 -1.398746 -2.49613551
## HOVAL -0.2943898  0.214841 -0.07954881</code></pre>
<p>You get the impact measures and their standard errors, z-values and <span class="math inline">\(p\)</span>-values with the <code>summary()</code> method applied to the output of the <code>impacts()</code> function.</p>
<div class="sourceCode" id="cb71"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb71-1"><a href="tuesday-november-29-2022.html#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(spatialreg<span class="sc">::</span><span class="fu">impacts</span>(model.slxm, <span class="at">listw =</span> wts))</span></code></pre></div>
<pre><code>## Impact measures (SlX, estimable, n-k):
##           Direct  Indirect       Total
## INC   -1.0973898 -1.398746 -2.49613551
## HOVAL -0.2943898  0.214841 -0.07954881
## ========================================================
## Standard errors:
##          Direct  Indirect     Total
## INC   0.3738313 0.5601247 0.4929713
## HOVAL 0.1016586 0.2079212 0.2074767
## ========================================================
## Z-values:
##          Direct  Indirect      Total
## INC   -2.935522 -2.497204 -5.0634496
## HOVAL -2.895867  1.033281 -0.3834108
## 
## p-values:
##       Direct    Indirect Total     
## INC   0.0033299 0.012518 4.1174e-07
## HOVAL 0.0037811 0.301473 0.70142</code></pre>
<p>Results show that income has a significant direct <em>and</em> indirect effect on crime rates, but housing values only show a significant direct effect and not a significant indirect effect.</p>
<p>Again you visualize the relative significance of the effects.</p>
<div class="sourceCode" id="cb73"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb73-1"><a href="tuesday-november-29-2022.html#cb73-1" aria-hidden="true" tabindex="-1"></a>model.slxm <span class="sc">|&gt;</span></span>
<span id="cb73-2"><a href="tuesday-november-29-2022.html#cb73-2" aria-hidden="true" tabindex="-1"></a>  broom<span class="sc">::</span><span class="fu">tidy</span>(<span class="at">conf.int =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span></span>
<span id="cb73-3"><a href="tuesday-november-29-2022.html#cb73-3" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">slice</span>(<span class="sc">-</span><span class="dv">1</span>) <span class="sc">|&gt;</span></span>
<span id="cb73-4"><a href="tuesday-november-29-2022.html#cb73-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> estimate,</span>
<span id="cb73-5"><a href="tuesday-november-29-2022.html#cb73-5" aria-hidden="true" tabindex="-1"></a>                   <span class="at">y =</span> term, </span>
<span id="cb73-6"><a href="tuesday-november-29-2022.html#cb73-6" aria-hidden="true" tabindex="-1"></a>                   <span class="at">xmin =</span> conf.low, </span>
<span id="cb73-7"><a href="tuesday-november-29-2022.html#cb73-7" aria-hidden="true" tabindex="-1"></a>                   <span class="at">xmax =</span> conf.high, </span>
<span id="cb73-8"><a href="tuesday-november-29-2022.html#cb73-8" aria-hidden="true" tabindex="-1"></a>                   <span class="at">height =</span> <span class="dv">0</span>)) <span class="sc">+</span></span>
<span id="cb73-9"><a href="tuesday-november-29-2022.html#cb73-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb73-10"><a href="tuesday-november-29-2022.html#cb73-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">0</span>, <span class="at">lty =</span> <span class="dv">4</span>) <span class="sc">+</span></span>
<span id="cb73-11"><a href="tuesday-november-29-2022.html#cb73-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_errorbarh</span>()</span></code></pre></div>
<pre><code>## Warning: The `tidy()` method for objects of class `SlX` is not maintained by the broom team, and is only supported through the `lm` tidier method. Please be cautious in interpreting and reporting broom output.
## 
## This warning is displayed once per session.</code></pre>
<p><img src="QG-2022_files/figure-html/unnamed-chunk-30-1.png" width="672" /></p>
<p>Compare R squared values between the linear model and the spatially-lagged X model.</p>
<div class="sourceCode" id="cb75"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb75-1"><a href="tuesday-november-29-2022.html#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model.lm)<span class="sc">$</span>r.squared</span></code></pre></div>
<pre><code>## [1] 0.552404</code></pre>
<div class="sourceCode" id="cb77"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb77-1"><a href="tuesday-november-29-2022.html#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model.slxm)<span class="sc">$</span>r.squared</span></code></pre></div>
<pre><code>## [1] 0.6105076</code></pre>
<p>The spatially lagged model has an R squared value that is higher than the R squared value from the linear regression.</p>
<p>Another way to find the correct spatial model is to consider both the spatial Durbin error model and the spatial Durbin model. The spatial Durban error model (SDEM) is a spatial error model with a spatially-lagged X term added.</p>
<p>More information:
- <a href="https://youtu.be/b3HtV2Mhmvk" class="uri">https://youtu.be/b3HtV2Mhmvk</a> Video explaining the types of spatial regression models and how to implement them in R
- <a href="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=2420725" class="uri">https://papers.ssrn.com/sol3/papers.cfm?abstract_id=2420725</a> What Regional Scientists Need to Know About Spatial Econometrics</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="tuesday-november-22-2022.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="thursday-december-1-2022.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
